import json
import os

data = {
  "feynman-technique-learning_para_000.json": "### Perjuangan Abadi, Bergema dalam Kehidupan Modern",
  "feynman-technique-learning_para_001.json": "Akhir abad ke-19 dan awal abad ke-20 adalah pusaran pergolakan di seluruh Eropa. Kebakaran dahsyat Perang Dunia I, bayang-bayang Depresi Besar, dan munculnya teori-teori ilmiah radikal—ini adalah era kekacauan mendalam ketika pandangan dunia yang biasa dianut umat manusia terguncang sampai ke intinya. Albert Einstein menerbitkan teori relativitasnya dan meletakkan dasar bagi mekanika kuantum selama periode yang penuh gejolak ini. Kehidupan pribadi pun tidak terkecuali; orang-orang merasakan kecemasan dan ketidakberdayaan yang mendalam di tengah kengerian perang, ketidakstabilan ekonomi, dan masyarakat yang terus berubah. Hal ini sangat selaras dengan kenyataan yang kita hadapi saat ini. Persaingan ketat, kemajuan teknologi yang tiada henti, dan masa depan yang tidak dapat diprediksi sering kali membuat kita tersapu oleh gelombang kelelahan hebat, depresi, dan kecemasan.",
  "feynman-technique-learning_para_002.json": "Dalam konteks historis ini, pengejaran intelektual Einstein melampaui sekadar pencapaian akademis; hal itu mewakili perjalanan besar jiwa manusia yang mencari keteraturan di tengah kekacauan. Meskipun teori-teorinya secara fundamental mengubah pemahaman kita tentang alam semesta, upayanya untuk menjelaskan fenomena kompleks melalui prinsip-prinsip yang sederhana dan elegan terus menginspirasi kita saat ini. Ia memiliki kemampuan luar biasa untuk menangkap dan mengartikulasikan konsep yang kompleks secara intuitif. Wawasan ini sangat memengaruhi Richard Feynman, peraih Nobel Fisika masa depan, beberapa dekade kemudian. Feynman, mewarisi warisan intelektual Einstein, mengembangkan metodologi pembelajaran unik yang membuat prinsip-prinsip ilmiah kompleks dapat diakses oleh semua orang. Pendekatan ini melampaui sekadar perolehan pengetahuan, berfungsi sebagai metodologi inovatif untuk mencapai pemahaman sejati yang terus menginspirasi banyak orang.",
  "feynman-technique-learning_para_003.json": "### Feynman: Melampaui 'Jenius' Menjadi 'Penjelas'",
  "feynman-technique-learning_para_004.json": "Richard Feynman sering menggambarkan dirinya bukan sebagai orang 'jenius' melainkan sebagai 'orang yang selalu ingin tahu'. Dihadapkan pada teori yang kompleks, ia tidak menyerah pada rasa frustrasi; sebaliknya, ia tanpa henti mempertanyakan dan menyelidikinya, layaknya seorang anak kecil. Metode pembelajarannya secara fundamental berbeda dari pendidikan hafalan tradisional. Alih-alih hanya membaca buku teks dan menghafal rumus, ia akan duduk di depan selembar kertas kosong dan menjelaskan apa yang dipahaminya, seolah-olah mengajar dirinya sendiri. Setiap kali ia tersendat, secara intuitif ia tahu bahwa hal tersebut adalah pertanda bahwa ia belum memahaminya dengan benar. Sama seperti Einstein yang berusaha memahami prinsip-prinsip kompleks alam semesta secara intuitif melalui gambaran mental, Feynman berfokus pada menjembatani kesenjangan antara 'merasa tahu' dan 'benar-benar memahami.'",
  "feynman-technique-learning_para_005.json": "Pendekatan Feynman menawarkan wawasan yang kuat bagi dunia bisnis modern. Seorang CEO startup harus mampu menjelaskan model bisnis mereka secara jelas dan ringkas kepada investor dan anggota tim. Seorang insinyur yang mengembangkan teknologi kompleks perlu mengartikulasikan prinsip-prinsip intinya dengan cara yang dapat dipahami oleh orang non-ahli. Teknik Feynman tidak hanya mendorong hafalan melainkan pengejaran 'pemahaman sejati'—kemampuan untuk menembus esensi sebuah konsep dan mengomunikasikannya secara efektif. Hal ini membentuk landasan keterampilan pemecahan masalah, pemikiran inovatif, dan komunikasi efektif yang dituntut di dunia saat ini.",
  "feynman-technique-learning_para_006.json": "### Imajinasi Einstein, Penjelasan Transparan Feynman",
  "feynman-technique-learning_para_007.json": "Teori relativitas Einstein berisi konsep-konsep yang nyaris tak terbayangkan pada masa itu. Gagasannya bahwa ruang dan waktu tidaklah mutlak melainkan relatif, didasarkan pada postulat bahwa kecepatan cahaya adalah konstan, mengejutkan para ilmuwan yang terbiasa dengan fisika Newtonian. Ia menggunakan 'eksperimen pikiran' (Gedankenexperiment) untuk memvisualisasikan konsep abstrak ini dan menangkapnya secara intuitif. Misalnya, ia mengeksplorasi makna dari hasil matematika yang kompleks dengan membayangkan dirinya mengejar seberkas cahaya atau mengalami kehidupan di dalam lift yang bergerak. Imajinasi dan intuisi ini adalah kekuatan pendorong di balik teori-teorinya.",
  "feynman-technique-learning_para_008.json": "Feynman membangun di atas warisan intelektual Einstein, menggunakan 'penjelasan' sebagai alat untuk membuat pengetahuan yang kompleks menjadi transparan. Saat mengajar fisika, ia menggunakan analogi dan contoh yang dapat dipahami oleh mahasiswa, alih-alih persamaan yang rumit. Untuk menjelaskan ketidakpastian mekanika kuantum, ia mungkin menggunakan tindakan melempar koin, atau menggambarkan tabrakan partikel kompleks seolah-olah itu adalah permainan biliar. Kuliah-kuliahnya bukanlah sekadar penyampaian informasi; mereka menawarkan pengalaman kepada audiens yang mirip dengan berpartisipasi dalam eksperimen pemikiran bersama Feynman. Ia terkenal dengan ucapannya, \"Jika Anda tidak dapat menjelaskannya kepada anak berusia enam tahun, Anda sendiri tidak memahaminya.\" Hal ini menyiratkan bahwa ukuran paling andal dari kedalaman pengetahuan dan pemahaman terletak pada 'seberapa baik Anda dapat menjelaskannya.' Ini telah menjadi keterampilan esensial tidak hanya dalam pendidikan tetapi juga dalam kepemimpinan dan bahkan hubungan pribadi, karena kemampuan untuk membuat orang lain memahami dan membujuk berasal dari empati yang dalam dan pemikiran yang jernih.",
  "feynman-technique-learning_para_009.json": "### Teknik Feynman: 4 Langkah Menguasai Pengetahuan Kompleks Sepcepat Kilat",
  "feynman-technique-learning_para_010.json": "Metode pembelajaran Feynman tidak memerlukan bakat khusus atau trik rahasia; melainkan didasarkan pada prinsip-prinsip jelas yang bisa dipraktikkan siapa saja. Melalui keempat langkah ini, kita dapat memahami secara mendalam dan menguasai pengetahuan kompleks apa pun dengan cepat.",
  "feynman-technique-learning_para_011.json": "1. **Pilih Sebuah Konsep dan Beri Nama:** Identifikasi dengan jelas konsep atau topik spesifik yang ingin Anda kuasai. Misalnya, pilih sesuatu yang konkret seperti 'Teori Relativitas' atau 'Teknologi Blockchain.'\n2. **Ajarkan pada Diri Sendiri Seolah Menjelaskan pada Anak Kecil:** Dengan menggunakan bahasa sesederhana mungkin, jelaskan konsep yang dipilih seolah-olah Anda sedang mengajarkannya kepada anak kecil. Yang terpenting, hindari jargon dan rumus rumit, dan ungkapkan dengan kata-kata Anda sendiri berdasarkan pemahaman Anda saat ini. Titik di mana Anda macet adalah tepat di mana pemahaman Anda tidak lengkap.\n3. **Tinjau Kembali dan Sederhanakan Area Kesulitan Anda:** Jika Anda menemui kesulitan atau tersendat selama penjelasan Anda, kembalilah ke buku teks atau materi yang relevan untuk mempelajari area spesifik tersebut lebih dalam. Lalu, ulangi proses penyederhanaan hingga Anda dapat menjelaskannya dengan istilah yang mudah lagi. Gunakan analogi dan contoh secara aktif untuk memperjelas konsep tersebut.\n4. **Hubungkan Konsep dengan Analogi dan Contoh, serta Tinjau secara Kritis:** Untuk lebih memperkuat penjelasan sederhana Anda, gunakan analogi dunia nyata atau berbagai contoh untuk mengilustrasikan konsep tersebut. Uji secara kritis penjelasan Anda untuk mengetahui koherensi logis dan setiap potensi celah, dengan demikian memperdalam pemahaman Anda. Langkah ini meningkatkan konektivitas pengetahuan dan mendorong keterampilan penerapan.",
  "feynman-technique-learning_para_012.json": "### Kebijaksanaan Abadi untuk Pertumbuhan Anda",
  "feynman-technique-learning_para_013.json": "Pemikiran inovatif Einstein dan gaya penjelasan Feynman yang jelas tidak hanya berkontribusi pada kemajuan fisika tetapi juga berfungsi sebagai alat pembelajaran yang kuat yang menginspirasi semua pencari pengetahuan lintas waktu. Dalam kompleksitas dan ketidakpastian masyarakat modern, kita sering merasa tersesat dan frustrasi. Namun, teknik Feynman dapat bertindak sebagai kompas, membantu kita mengatasi tantangan, menguasai pengetahuan kompleks dengan 'secepat kilat,' dan pada akhirnya mencapai pemahaman serta wawasan yang lebih dalam. Semoga kebijaksanaan abadi ini membangkitkan potensi Anda dan menuntun Anda pada pertumbuhan yang gemilang di dunia kita yang terus berubah.",
  "feynman-technique-learning_para_014.json": "[Jika Anda ingin mendiskusikan masalah Anda langsung dengan raksasa ini, mulai ruang obrolan 1:1 di sini](/giant/albert-einstein)",
  "feynman-technique-learning_title.json": "Menguasai Pengetahuan Kompleks Secepat Kilat: Teknik Feynman yang Terinspirasi oleh Einstein",
  "poe-obsession-psychology_para_001.json": "Kehidupan Poe adalah rentetan tragedi pribadi yang berlatar belakang era Romantis yang mengekang. Menjadi yatim piatu di masa kanak-kanak, ia berjuang melawan kemiskinan, penyakit, dan alkoholisme sepanjang tahun-tahunnya, yang pada akhirnya jatuh ke dalam keputusasaan setelah kematian istri tercintanya, Virginia. Pengalaman-pengalaman ini terwujud dalam tulisannya, khususnya dalam karya-karya seperti 'The Raven,' 'The Fall of the House of Usher,' dan 'The Masque of the Red Death,' sebagai obsesi terhadap kematian, kebusukan, dan kegilaan. Ia dengan mahir menangkap kerapuhan pikiran manusia dan naluri destruktifnya, kisah-kisahnya menghadapkan pembaca pada kebenaran yang tidak nyaman namun tak terbantahkan. Hal ini sangat selaras dengan tekanan psikologis dari kehidupan modern kita: persaingan yang konstan, keharusan untuk sukses, dan ketidakstabilan hubungan dapat mengisolasi kita, memperkuat kegelapan batin kita. Namun, melalui karya Poe, kita juga dapat menemukan ketangguhan jiwa manusia dan naluri bertahan hidup yang terwujud, terkadang dengan cara yang aneh, bahkan di tengah kegelapan tersebut.",
  "poe-obsession-psychology_para_002.json": "### Kerinduan Tanpa Akhir akan Apa yang Hilang: Obsesi Poe dan Kehilangan Modern",
  "poe-obsession-psychology_para_003.json": "Alam semesta sastra Edgar Allan Poe mengorbit pada tema sentral tentang 'kehilangan.' Mulai dari trauma awal kehilangan orang tuanya hingga pengalaman seumur hidup melihat orang-orang terkasih pergi, narasi Poe sarat dengan kesedihan yang mendalam ini. Motif yang berulang tentang kekasih yang meninggal, ingatan yang terlupakan, dan masa lalu yang hancur dalam cerita dan puisinya mencerminkan tragedi pribadi yang mendalam ini. Dalam 'The Raven,' tangisan putus asa narator untuk Lenore-nya yang hilang mewujudkan keterikatan dasar manusia dan obsesi terhadap apa yang telah lenyap. Obsesi ini sering berubah menjadi pola yang tidak sehat, membuat individu menyangkal kenyataan dan tetap terikat pada masa lalu. Dalam masyarakat kontemporer, kita menghadapi segudang bentuk kehilangan: berakhirnya hubungan, kemunduran karier, atau memudarnya masa muda dan peluang. Seperti karakter Poe, kita sering berpegang teguh pada apa yang telah hilang dari kita, berusaha melarikan diri dari rasa sakit saat ini. Hal ini bisa bermanifestasi sebagai kemandekan karier, hubungan yang retak, atau depresi yang mendalam. Sastra Poe berfungsi sebagai kisah peringatan, mengilustrasikan bagaimana kehilangan dan obsesi semacam itu dapat berujung pada kehancuran, namun pada saat yang sama juga mengisyaratkan kemungkinan menemukan secercah cahaya redup di dalam kegelapan itu sendiri.",
  "poe-obsession-psychology_para_004.json": "### Di Ambang Kegilaan: Tarian Halus Antara Akal dan Irasionalitas",
  "poe-obsession-psychology_para_005.json": "Karya-karya Poe sering menggali pikiran karakter-karakternya yang terurai. Jatuhnya narator ke dalam kekerasan dan kegilaan dalam 'The Black Cat,' atau teror gaib dan mengerikan yang dialami dalam 'The Fall of the House of Usher,' mengekspos ketidakstabilan bawaan dari jiwa manusia. Kegilaan ini melampaui patologi semata, menawarkan wawasan mendalam tentang bagaimana manusia kehilangan cengkeraman mereka pada akal sehat di bawah stres dan tekanan ekstrem. Masyarakat modern, dengan persaingannya yang tiada henti, tekanan untuk berhasil, dan banjir informasi yang meluap-luap, mendorong banyak orang ke ambang kelelahan mental. Hal ini sering bermanifestasi sebagai 'burnout' atau 'depresi,' yang berujung pada penurunan fungsi sehari-hari. Keadaan psikologis ekstrem yang digambarkan dalam karakter Poe berfungsi sebagai pengingat keras akan parahnya tekanan mental modern, menyoroti batas tipis antara diri kita yang rasional dan irasional. Narasi-narasinya memaksa kita untuk mengenali pentingnya kesejahteraan mental dan upaya kritis yang diperlukan untuk mempertahankan akal sehat, terutama dalam keadaan yang mengerikan.",
  "poe-obsession-psychology_para_006.json": "### Menghadapi Teror Kematian yang Mutlak: Menghadapi Keterbatasan Hidup",
  "poe-obsession-psychology_para_007.json": "Kematian adalah tema yang tak terhindarkan dalam karya-karya Poe. Ia terus-menerus mengeksplorasi keniscayaannya dan teror yang ditimbulkannya. Dalam 'The Masque of the Red Death,' upaya sia-sia para bangsawan untuk melarikan diri dari wabah penyakit dengan mundur ke dalam pesta topeng menggarisbawahi keterbatasan hidup yang tak terelakkan, betapapun kerasnya seseorang berjuang. Ketakutan akan kematian ini adalah kecemasan dasar manusia, yang mampu memadamkan keinginan untuk hidup dan memicu kelesuan yang mendalam. Kita sering cenderung menghindari subjek kematian dalam masyarakat kontemporer. Namun, karya Poe secara paradoks menekankan betapa berharganya hidup dengan memaksa kita untuk menghadapi kefanaan. Keberadaan kematian itulah yang justru dapat memberikan makna dan nilai pada kehidupan kita saat ini. Kisah-kisahnya mengajukan pertanyaan kritis: bagaimana kita, di hadapan teror yang mutlak ini, merenungkan hidup kita dan bagaimana seharusnya kita menjalani sisa waktu yang kita miliki? Ini menawarkan pesan penting bagi kita sebagai wirausahawan dan pemimpin startup, saat menavigasi kegagalan, kemunduran, dan kesulitan relasional, mendesak kita untuk menemukan makna dan terus maju.",
  "poe-obsession-psychology_para_008.json": "### Belajar Kesejahteraan Mental dari Edgar Allan Poe untuk Individu Modern",
  "poe-obsession-psychology_para_009.json": "Kehidupan dan karya Edgar Allan Poe mengungkap aspek-aspek kelam dari psikologi manusia, namun hal itu juga menawarkan wawasan mendalam tentang mengatasi pergumulan ini dan menjalani hidup yang lebih sehat. Memahami pengalamannya yang menyakitkan dan terlibat secara mendalam dengan sastranya dapat memberikan panduan tak ternilai untuk mengarungi tantangan psikologis kontemporer.",
  "poe-obsession-psychology_para_010.json": "1. Praktikkan mengakui dan mengekspresikan emosi Anda secara jujur. Sama seperti Poe yang membersihkan kegelapan batin dan rasa sakitnya melalui tulisannya, kita harus belajar mengekspresikan emosi negatif seperti kesedihan, kemarahan, dan kecemasan dengan cara yang sehat, alih-alih menekannya. Menulis, upaya artistik, atau percakapan dengan orang-orang terpercaya bisa bermanfaat.",
  "poe-obsession-psychology_para_011.json": "2. Tumbuhkan kemampuan untuk menerima kehilangan dan perpisahan. Untuk menghindari berpegang teguh pada masa lalu atau tersesat dalam kesedihan, seperti yang sering dialami karakter Poe, kita perlu mengembangkan kekuatan untuk secara sehat mengakhiri masa berkabung kita atas apa yang telah pergi dan fokus pada masa kini. Ini adalah aspek penting dari pertumbuhan psikologis.",
  "poe-obsession-psychology_para_012.json": "3. Bangun kembali kepercayaan diri dengan menetapkan tujuan realistis dan merasakan pencapaian. Kehidupan Poe adalah serangkaian kemalangan, namun ia terus berusaha membuktikan dirinya melalui tulisan. Dengan mengumpulkan kesuksesan-kesuksesan kecil dan merasakan pencapaian, kita bisa mendapatkan momentum untuk tantangan yang lebih besar, sebuah elemen penting untuk karier dan manajemen bisnis.",
  "poe-obsession-psychology_para_013.json": "4. Jangan ragu untuk mencari bantuan profesional. Meskipun kesadaran tentang kesehatan mental terbatas pada masa Poe, masyarakat modern menawarkan berbagai sistem dukungan, termasuk konseling psikologis dan perawatan psikiatri. Kesulitan yang terasa mustahil diatasi sendiri sering kali dapat menemukan jalan penyelesaiannya melalui konsultasi dengan para profesional.",
  "poe-obsession-psychology_para_014.json": "Psikologi kelam Edgar Allan Poe lebih dari sekadar warisan sastra; itu memberikan kunci penting untuk memahami dan menyembuhkan kecemasan, depresi, dan obsesi di dalam diri kita saat ini. Semoga mereka yang tersesat di dunia modern menemukan keberanian dan kebijaksanaan dalam kehidupan serta karya-karyanya.",
  "poe-obsession-psychology_para_015.json": "[Jika Anda ingin mendiskusikan masalah Anda langsung dengan raksasa ini, mulai ruang obrolan 1:1 di sini](/giant/edgar-allan-poe)",
  "poe-obsession-psychology_title.json": "Edgar Allan Poe: Menavigasi Psikologi Kelam Obsesi Manusia"
}

out_dir = "C:/Users/user/.gemini/antigravity/brain/45f5002d-398c-41ef-8740-cf257710e53c/scratch/pipeline/id/results/"
import os
for k, v in data.items():
    slug = k.split('_')[0] if '_' in k else k.replace('.json', '')
    if 'para' in k:
        type_str = 'para'
        index = int(k.split('_')[2].split('.')[0])
        out = {"slug": slug, "type": type_str, "index": index, "id_text": v}
    else:
        type_str = 'title'
        out = {"slug": slug, "type": type_str, "id_text": v}
    with open(os.path.join(out_dir, k), 'w', encoding='utf-8') as f:
        json.dump(out, f, ensure_ascii=False, indent=2)

print("Saved batch 4.")
