import json

data = {
  "rockefeller-monopoly-guide_para_000.json": "Akhir abad ke-19 adalah pusaran pergolakan industri di Amerika. Minyak, urat nadi peradaban modern, adalah wilayah baru, dan kendali atas sumber daya yang berkembang pesat ini menentukan masa depan bangsa. Di tengah era yang penuh gejolak ini, muncullah sosok yang akan mendefinisikan ulang industri: John D. Rockefeller. Ia lebih dari sekadar pengusaha; ia adalah personifikasi dari prinsip-prinsip yang dingin dan penuh perhitungan yang dibutuhkan untuk bertahan dan berkembang di lanskap yang brutal. Di masa kita sendiri, saat bergulat dengan persaingan sengit, tekanan tanpa henti, dan kecemasan tentang masa depan, kisah hidup Rockefeller melampaui sejarah semata, menjadi cermin yang memantulkan perjuangan kita sendiri. Kesuksesannya tidak lahir dari keberuntungan atau kejeniusan belaka, tetapi dari perencanaan yang cermat, ketegasan tanpa ampun, dan wawasan yang tajam ke dalam arus pasar. Narasi Rockefeller menawarkan tidak hanya daya tarik kemenangan, tetapi juga konfrontasi nyata dengan harga pahit dan kenyataan pantang menyerah yang dibawanya.",
  "rockefeller-monopoly-guide_para_001.json": "Era Rockefeller adalah wilayah perbatasan yang liar dan belum terjamah di mana peluang dan bahaya menari beriringan. Sebagai \"Raja Minyak,\" bersama para raja kereta api dan baja, ia mengejar efisiensi dan keuntungan dengan intensitas yang nyaris tidak manusiawi untuk menghancurkan pesaing dan merebut kendali pasar. Metode-metodenya mengundang kontroversi, namun kebenaran yang tak terbantahkan adalah bahwa Standard Oil miliknya tumbuh menjadi salah satu perusahaan paling kolosal yang pernah ada di dunia. Kisah ini melampaui sekadar akumulasi kekayaan; ia mengajukan pertanyaan mendasar tentang bagaimana membangun, mempertahankan, dan menavigasi sistem yang luas di tengah persaingan sengit. Bagi para pendiri perusahaan rintisan modern, profesional korporat yang berambisi, atau siapa pun yang sedang merintis jalan di pasar kehidupan yang megah, strategi Rockefeller menawarkan wawasan abadi tentang kekuatan efisiensi, fokus, dan, terkadang, kekejaman yang nyata.",
  "rockefeller-monopoly-guide_para_002.json": "### Strategi Rockefeller untuk Dominasi Pasar: Efisiensi dan Konsolidasi",
  "rockefeller-monopoly-guide_para_003.json": "Kebangkitan Rockefeller yang sesungguhnya dimulai dengan pendirian Standard Oil Company. Ia berfokus pada konsolidasi lanskap penyulingan independen yang terfragmentasi. Strategi intinya adalah integrasi vertikal: mengendalikan setiap aspek industri minyak, dari ekstraksi dan transportasi hingga penyulingan dan distribusi. Hal ini memungkinkannya untuk memangkas biaya produksi dan membangun jaringan distribusi eksklusif yang tak tertembus oleh pesaing. Rockefeller tidak sekadar mengakuisisi pesaing; ia menyerap teknologi dan aset mereka, memperkuat keunggulan kompetitif Standard Oil. Meskipun ia mungkin berbicara tentang \"kerja sama,\" versinya sering kali berarti memaksa pesaing untuk tunduk pada kehendaknya. Ia dengan kejam menghilangkan pemborosan, mendorong efisiensi, dan mempelopori inovasi seperti jaringan pipa untuk memotong biaya transportasi secara drastis. Ini bukan semata-mata tentang meningkatkan keuntungan; ini adalah senjata ampuh yang membentuk kembali pasar itu sendiri. Ketika kita membahas \"skala ekonomi\" dan \"sinergi\" dalam bisnis modern, integrasi vertikal Rockefeller berfungsi sebagai cetak biru fundamental.",
  "rockefeller-monopoly-guide_para_004.json": "### Realisme Kejam yang Menghancurkan Persaingan",
  "rockefeller-monopoly-guide_para_005.json": "Rockefeller tidak kenal ampun dalam metodenya untuk menyingkirkan pesaing. Ia membanjiri pasar dengan minyak pada harga rendah yang tidak berkelanjutan, memaksa pesaing bangkrut, atau mengakuisisi mereka dengan harga murah. Ia tidak segan-segan secara aktif mengganggu operasi mereka. Ia tampak beroperasi di bawah prinsip bahwa \"Ketika Anda bertemu bajingan, Anda harus menjadi bajingan yang lebih besar.\" Ia menggunakan taktik untuk secara sistematis membuat pesaing kelaparan, mengeksploitasi kelemahan mereka sampai mereka layu. Kolusi terkenalnya dengan perusahaan kereta api, memungut biaya pengiriman yang selangit pada pesaing sambil mengamankan rabat dramatis untuk Standard Oil, memberikan contoh pendekatan berdarah dinginnya. Walaupun secara etika meragukan, Rockefeller kemungkinan memandang tindakan-tindakan ini sebagai kejahatan yang perlu untuk mengamankan dominasi pasar absolut. Taktik ini, meskipun kontroversial, bergema dalam strategi agresif yang digunakan di dunia bisnis yang kejam saat ini, terus-menerus memunculkan pertanyaan tentang batasan etika.",
  "rockefeller-monopoly-guide_para_006.json": "### Filosofi Manajemen Rockefeller: Fokus dan Kontrol",
  "rockefeller-monopoly-guide_para_007.json": "Rockefeller dengan terkenal menganjurkan: \"Berkonsentrasilah pada tujuan Anda dan curahkan semua energi Anda ke dalamnya.\" Ia mendedikasikan seluruh fokusnya pada bisnis minyak, dengan sengaja menghindari diversifikasi. Satu-satunya perhatiannya adalah efisiensi dan dominasi industri perminyakan. Ia menyederhanakan struktur perusahaan yang kompleks dan memegang kendali besar dari puncak. Dewan Standard Oil sebagian besar berfungsi untuk melaksanakan arahannya. Ia mengelola perusahaan dengan analisis data yang cermat dan kontrol biaya yang ketat, meneliti pengeluaran sekecil apa pun dan mengevaluasi kinerja setiap divisi secara ketat. Kontrol yang tak tergoyahkan dan fokus setajam laser ini adalah mesin yang mendorong transformasi Standard Oil menjadi kerajaan kolosal. Prinsip-prinsip \"berfokus pada kompetensi inti\" dan membangun \"struktur pengambilan keputusan yang efisien\" tetap menjadi prinsip vital dari manajemen modern.",
  "rockefeller-monopoly-guide_para_008.json": "### Panduan Bertahan dan Tumbuh Rockefeller untuk Individu Modern",
  "rockefeller-monopoly-guide_para_009.json": "Prinsip-prinsip keras dan pantang menyerah Rockefeller menawarkan pelajaran berharga bahkan hingga hari ini. Dari kehidupannya, kita bisa memetik hal-hal berikut:",
  "rockefeller-monopoly-guide_para_010.json": "1. **Fokus pada Inti Anda:** Seperti Rockefeller, dedikasikan energi penuh Anda ke area di mana Anda unggul atau memiliki potensi terbesar. Upaya yang tersebar menghasilkan hasil yang terfragmentasi.\n2. **Maksimalkan Efisiensi:** Hilangkan pemborosan tanpa henti, perbaiki proses, dan manfaatkan teknologi untuk memangkas biaya dan meningkatkan produktivitas. Peningkatan kecil terakumulasi menjadi keuntungan yang signifikan.\n3. **Pahami dan Manfaatkan Lanskap Kompetitif Anda:** Identifikasi kerentanan pesaing dan pahami dinamika pasar. Keputusan dan strategi berani terkadang diperlukan, tetapi selalu dengan memperhatikan batas-batas etika.\n4. **Integrasikan dengan Visi Jangka Panjang:** Lihat melampaui keuntungan jangka pendek. Konsolidasikan sumber daya dan kemampuan di bidang terkait untuk menciptakan sinergi yang kuat dan memperkuat dominasi pasar. Ini berlaku untuk bisnis serta pengembangan keterampilan pribadi.",
  "rockefeller-monopoly-guide_para_011.json": "Kehidupan John D. Rockefeller adalah narasi dramatis tentang kesuksesan, ambisi, dan pragmatisme mengerikan yang mendasarinya. Meskipun metodenya mungkin tidak selalu dianggap benar, prinsip-prinsip yang digunakannya untuk mendominasi pasar memiliki nilai strategis yang abadi. Kisahnya menawarkan lebih dari sekadar jalan menuju kekayaan; ini memberikan wawasan mendalam tentang bagaimana bertahan dan berkembang di arena dunia yang luas dan kompetitif.",
  "rockefeller-monopoly-guide_para_012.json": "[Jika Anda ingin mendiskusikan masalah Anda langsung dengan raksasa ini, mulai ruang obrolan 1:1 di sini](/giant/john-d-rockefeller)",
  "rockefeller-monopoly-guide_title.json": "Rahasia Monopoli John D. Rockefeller: Prinsip Kejam yang Mendominasi Pasar",
  "carnegie-gospel-wealth_para_000.json": "Pada akhir abad ke-19 yang penuh gejolak, di tengah arus industrialisasi yang menderu, banyak individu yang terjun bebas ke lautan perubahan besar. Andrew Carnegie adalah salah satu tokoh tersebut. Berawal dari seorang anak imigran miskin asal Skotlandia hingga menjadi raksasa industri, kisah hidupnya sangat selaras dengan perjuangan individu modern yang menavigasi dunia startup yang kejam atau menghadapi tekanan tanpa henti untuk peningkatan diri. Era itu juga dibayangi oleh ketimpangan kekayaan yang tajam dan tenaga kerja yang eksploitatif, memaksa individu ke dalam pertempuran putus asa untuk bertahan hidup dan sukses. Narasi Carnegie melampaui kisah sukses sederhana; ini menerangi bagaimana keputusasaan dan harapan pada zamannya terhubung langsung dengan kecemasan, tekanan, dan aspirasi akan pencapaian yang kita hadapi saat ini. Kehidupannya mengajukan pertanyaan mendalam kepada kita: Untuk apa, sejujurnya, kita berjuang begitu keras? Dan di akhir semua upaya ini, bagaimana kita ingin dikenang?",
  "carnegie-gospel-wealth_para_001.json": "Carnegie tidak seharusnya dikenang hanya sebagai pria yang mengumpulkan kekayaan luar biasa. Melalui konsepnya tentang 'Injil Kekayaan', ia dengan kuat mengadvokasi pentingnya mengembalikan kekayaan tersebut kepada masyarakat. Ini lebih dari sekadar amal; itu adalah filosofi yang menekankan bahwa mengakumulasi kekayaan membawa tanggung jawab sosial yang mendalam. Eranya melihat kekayaan besar terkonsentrasi di tangan segelintir orang, namun juga membuka kemungkinan untuk menggunakan kekayaan itu guna mengangkat martabat masyarakat. Saat ini, kita bergulat dengan ketimpangan ekonomi, hilangnya pekerjaan akibat kemajuan teknologi, dan krisis kesehatan mental. 'Injil Kekayaan' Carnegie menawarkan refleksi mendalam tentang bagaimana kita mengumpulkan dan memanfaatkan kekayaan di tengah dilema modern ini. Kehidupannya memberikan pelajaran penting tidak hanya tentang memperoleh kekayaan dan ketenaran, tetapi yang lebih penting, tentang bagaimana menggunakan kekayaan tersebut untuk memperbaiki dunia dan, pada akhirnya, meninggalkannya dengan cara yang paling terhormat.",
  "carnegie-gospel-wealth_para_002.json": "### Dari 'Raja Baja' Menjadi 'Filantropis': Transformasi Sang Raksasa",
  "carnegie-gospel-wealth_para_003.json": "Kehidupan Carnegie dapat dipahami melalui dua fase yang berbeda. Yang pertama adalah pesonanya sebagai pengusaha, yang membangun kerajaan industri melalui ketekunan dan tekad bulat. Yang kedua adalah perannya sebagai filantropis, yang berusaha membagikan secara dermawan kekayaan yang dihasilkan oleh kerajaan tersebut. Ia memegang keyakinan teguh: \"Bukan pengumpulan kekayaan, melainkan penggunaannya, yang sangat penting.\" Praktik bisnisnya, meskipun efisien tanpa ampun, terkadang mengorbankan kesejahteraan pekerja. Namun, ia secara bertahap menyadari tanggung jawab berat yang datang bersama kekayaan besar, mendedikasikan lebih dari 90% kekayaannya untuk kepentingan masyarakat. Kontribusinya pada perpustakaan, lembaga pendidikan, dan dana perdamaian tidak dapat diukur. Ini bukan sekadar sumbangan; ini adalah manifestasi dari filosofi mendalam yang bertujuan untuk memberikan kesempatan bagi semua anggota masyarakat untuk menjalani kehidupan yang lebih baik. Ia mengakui bahwa kesuksesannya tidak semata-mata karena kemampuannya sendiri tetapi juga struktur masyarakat dan upaya rekan-rekannya, dan ia memilih untuk membayar utang itu.",
  "carnegie-gospel-wealth_para_004.json": "### Injil Kekayaan: Sebuah Filosofi Akumulasi dan Distribusi",
  "carnegie-gospel-wealth_para_005.json": "‘Injil Kekayaan’ Carnegie menawarkan wawasan yang tetap sangat relevan hingga hari ini. Ia memandang kekayaan sebagai sumber daya berharga yang “seharusnya dikelola oleh orang kaya, sebagai agen dan wali tunggal dalam pelepasannya, baik selama hidupnya atau untuk masa depan yang tidak diketahui, demi kebaikan sesamanya, lebih memilih pelayanan-pelayanan yang mengangkat derajat umat manusia.” Hal ini menyiratkan bukan sekadar menjadi kaya melainkan merencanakan secara cermat bagaimana menggunakan kekayaan tersebut secara efektif untuk berkontribusi pada kemajuan masyarakat. Carnegie menekankan bahwa kemampuan untuk mengumpulkan kekayaan dan kemampuan untuk mendistribusikannya secara bijaksana adalah dua hal yang berbeda, di mana yang terakhir jauh lebih menantang dan krusial. Filosofinya dapat dilihat sebagai pendahulu inisiatif Tanggung Jawab Sosial Perusahaan (CSR) dan ESG modern. Ia percaya bahwa mereka yang memiliki kekayaan bertindak sebagai pengurus masyarakat, berinvestasi dalam pendidikan, budaya, dan kemajuan ilmu pengetahuan untuk generasi mendatang. Hal ini menghadirkan model kehidupan yang melampaui kepuasan pribadi, melainkan berkontribusi pada kemajuan umat manusia secara keseluruhan.",
  "carnegie-gospel-wealth_para_006.json": "### Kebijaksanaan Carnegie untuk Individu Modern",
  "carnegie-gospel-wealth_para_007.json": "Kehidupan Carnegie menawarkan beberapa pelajaran penting. Pertama, kesuksesan adalah maraton, bukan lari cepat. Ia mengatasi banyak kegagalan dan 역경 (rintangan), secara konsisten menunjukkan komitmen untuk belajar dan berkembang. Kedua, nilai sejati dari kekayaan terletak pada membagikannya. Dengan mendistribusikan kekayaannya, ia mencapai warisan yang melampaui kehormatan pribadi, memberikan dampak jangka panjang pada sejarah umat manusia. Ketiga, refleksi diri yang berkelanjutan dan rasa tanggung jawab sosial sangatlah esensial. Menyadari bahwa kesuksesan seseorang bukan murni hasil jerih payah sendiri, sangat penting untuk menjalani kehidupan yang berkontribusi pada masyarakat.",
  "carnegie-gospel-wealth_para_008.json": "### Panduan Praktis untuk Memperoleh Kekayaan dan Rasa Hormat",
  "carnegie-gospel-wealth_para_009.json": "Menerapkan filosofi kehidupan Carnegie dalam konteks modern, berikut ini adalah panduan praktis untuk mencapai kekayaan dan rasa hormat:",
  "carnegie-gospel-wealth_para_010.json": "1. **Tetapkan Tujuan yang Jelas dan Eksekusi Secara Konsisten:** Seperti Carnegie, tetapkan tujuan yang jelas dan miliki keuletan untuk mengejarnya tanpa henti, tanpa menyerah saat menghadapi kemunduran. Bangun kepercayaan diri melalui kemenangan kecil dan bergerak menuju visi jangka panjang Anda.\n2. **Rangkul Pembelajaran dan Pengembangan Berkelanjutan:** Terus ikuti perubahan sosial dengan terus belajar, memperoleh keterampilan baru, dan meningkatkan kemampuan Anda. Carnegie mendidik dirinya sendiri melalui membaca; kita memiliki akses ke beragam sumber belajar saat ini.\n3. **Praktikkan Nilai Memberi:** Sama pentingnya, atau bahkan lebih penting dari, mengumpulkan kekayaan adalah memikirkan cara-cara untuk membagikan apa yang Anda miliki dengan masyarakat. Berdonasi secara konsisten, bahkan dalam jumlah kecil, atau berkontribusi melalui layanan pro bono untuk memberikan dampak sosial yang positif.\n4. **Kembangkan Tanggung Jawab Sosial:** Jangan pernah lupa bahwa kesuksesan Anda juga berutang budi pada sistem masyarakat dan bantuan orang lain. Tumbuhkan pola pikir yang berkontribusi pada kemajuan masyarakat. Menciptakan lapangan kerja melalui bisnis atau mempraktikkan manajemen yang etis adalah cara terbaik untuk melakukan ini.",
  "carnegie-gospel-wealth_para_011.json": "Kehidupan Carnegie memaksa kita untuk memikirkan kembali makna sebenarnya dari kekayaan dan kesuksesan. Ia melakukan lebih dari sekadar mengumpulkan harta; ia menggunakan kekayaannya untuk memperbaiki dunia dan pada akhirnya menjalani kehidupan yang dikenang dengan penghormatan tertinggi. Kebijaksanaannya melampaui waktu, menawarkan inspirasi mendalam bagi kita semua saat ini.",
  "carnegie-gospel-wealth_para_012.json": "[Jika Anda ingin mendiskusikan masalah Anda langsung dengan raksasa ini, mulai ruang obrolan 1:1 di sini](/giant/andrew-carnegie)",
  "carnegie-gospel-wealth_title.json": "Injil Kekayaan Andrew Carnegie: Cara Meninggalkan Dunia Paling Dihormati"
}

out_dir = "C:/Users/user/.gemini/antigravity/brain/45f5002d-398c-41ef-8740-cf257710e53c/scratch/pipeline/id/results/"
import os
os.makedirs(out_dir, exist_ok=True)

for k, v in data.items():
    slug = k.split('_')[0] if '_' in k else k.replace('.json', '')
    if 'para' in k:
        type_str = 'para'
        index = int(k.split('_')[2].split('.')[0])
        out = {"slug": slug, "type": type_str, "index": index, "id_text": v}
    else:
        type_str = 'title'
        out = {"slug": slug, "type": type_str, "id_text": v}
    with open(os.path.join(out_dir, k), 'w', encoding='utf-8') as f:
        json.dump(out, f, ensure_ascii=False, indent=2)

print("Saved rockefeller and carnegie.")
