import json
import os

data = {
  "oppenheimer-genius-regret_para_000.json": "Pada bulan Agustus 1945, saat bom atom dijatuhkan di Hiroshima dan Nagasaki, umat manusia memperoleh kekuatan untuk memusnahkan dirinya sendiri. Di jantung pencapaian yang monumental dan mengerikan ini berdirilah J. Robert Oppenheimer, yang sering dipuji sebagai 'bapak bom atom.' Terdorong oleh rasa ingin tahu ilmiah dan rasa kewajiban patriotik, ia memimpin Proyek Manhattan menuju kesimpulan yang sukses, meskipun membawa malapetaka. Namun, di hadapan kekuatan penghancur yang ia bantu lepaskan, Oppenheimer dilanda penyesalan mendalam dan pergolakan batin. Kisahnya melampaui biografi seorang ilmuwan tunggal; ini menyelidiki dilema moral yang ditimbulkan oleh kemajuan ilmiah selama salah satu era paling penuh gejolak dalam sejarah, mempertanyakan beban tanggung jawab individu. Saat ini, kita mengarungi dunia dengan teknologi yang berkembang pesat, persaingan yang kejam, dan banjir informasi yang tiada henti, masing-masing membawa beban kita sendiri. Rasa tanggung jawab dan konflik etika luar biasa yang dirasakan Oppenheimer sangat selaras dengan kecemasan, depresi, dan tekanan psikologis yang dihadapi oleh pengusaha modern, pemimpin startup, maupun individu. Narasinya menawarkan wawasan tak ternilai, melampaui catatan sejarah untuk menerangi perjuangan internal yang kita hadapi dan jalan menuju jalan keluarnya.",
  "oppenheimer-genius-regret_para_001.json": "Kehidupan Oppenheimer adalah interaksi dramatis antara cahaya dan bayangan. Sebagai bintang baru di komunitas fisika di masa mudanya, kecerdasan luar biasa dan karismanya memikat rekan-rekannya. Di tengah urgensi keputusasaan Perang Dunia II, ia memelopori pengembangan senjata nuklir, sebuah keharusan nasional, yang membuatnya mendapat penghargaan sebagai pahlawan. Namun, pada saat ia menyaksikan awan jamur dari uji coba Trinity, retakan mendalam muncul di dalam dirinya. Kutipannya yang terkenal, merujuk pada Bhagavad Gita – \"Sekarang aku menjadi Maut, penghancur dunia\" – dengan tajam menangkap penderitaan manusia yang dirasakan saat menghadapi kenyataan destruktif yang tersembunyi di balik kemenangan ilmiah. Bahkan setelah perang, ia bergulat dengan kecemasan tentang proliferasi nuklir dan Perang Dingin yang memanas dengan Uni Soviet. Hubungan masa lalunya dengan simpatisan komunis menjadi dalih untuk penganiayaan politik, yang pada akhirnya mengarah pada akhir tragis karier publiknya. Seluruh cobaan ini berfungsi sebagai bukti beban psikologis berat yang harus ditanggung seorang jenius atas konsekuensi pencapaian intelektualnya. Ini bukan semata-mata tragedi pribadi melainkan pesan universal yang menuntut refleksi mendalam tentang tanggung jawab etis dari kemajuan ilmu pengetahuan dan teknologi serta sifat dasar kemanusiaan itu sendiri.",
  "oppenheimer-genius-regret_para_002.json": "### Salib Etika Ilmu Pengetahuan",
  "oppenheimer-genius-regret_para_003.json": "Proyek Manhattan mewakili puncak pencapaian ilmiah Oppenheimer, namun itu juga menandai awal siksaan etis yang menggerogoti jiwanya. Ia memegang pedang bermata dua, yang mampu menyelamatkan sekaligus menghancurkan umat manusia. Ia terus-menerus terombang-ambing antara penyelidikan ilmiah murni sebagai seorang peneliti dan kewajiban untuk berkontribusi pada bangsanya di saat krisis eksistensial. Setelah keberhasilan proyek tersebut, ia mengadvokasi pengendalian dan pelucutan senjata nuklir, berjuang demi perdamaian global. Namun, benih kehancuran yang ia tabur sudah menyebar tak terkendali. Hal ini mencerminkan dilema yang dihadapi para pendiri startup modern dan pengembang yang menciptakan teknologi inovatif. Menyeimbangkan kesuksesan pasar dengan tanggung jawab sosial, dan potensi manfaat kemajuan teknologi terhadap risiko inherennya, bukanlah tugas yang mudah. Pengalaman Oppenheimer mengajarkan kita bahwa kemajuan teknologi tidak dapat hadir dalam ruang hampa; hal itu harus disertai dengan pertimbangan mendalam tentang implikasi sosial dan etisnya. Penyesalannya memaksa kita untuk mengevaluasi kembali definisi 'kesuksesan' kita dan mengakui beban tanggung jawab yang menyertainya.",
  "oppenheimer-genius-regret_para_004.json": "### Kesepian dan Tekanan Psikologis Sang Jenius",
  "oppenheimer-genius-regret_para_005.json": "Oppenheimer bukan hanya sosok dengan pikiran brilian melainkan juga figur dengan kehidupan batin yang kompleks. Meskipun dihormati oleh rekan-rekannya, volatilitas emosional dan hubungan pribadinya sering kali menciptakan ketegangan. Kengerian perang dan rasa bersalah yang terkait dengan penggunaan senjata atom, khususnya, memakan korban parah pada kejiwaannya. Ia sering menarik diri ke dalam kesendirian, tersiksa oleh introspeksi. Isolasi mendalam dan tekanan psikologis ini sering terlihat pada para pemimpin dan orang berprestasi tinggi saat ini. Tuntutan kinerja yang tiada henti, obsesi terhadap kesuksesan, dan ketakutan akan kegagalan dapat sangat mengancam kesejahteraan mental seseorang. Kasus Oppenheimer menawarkan wawasan mendalam tentang bagaimana mengelola beban psikologis ini dan menemukan keseimbangan sehat antara pencapaian seseorang dan tekanan yang ditimbulkannya. Menjaga kedamaian batin saat menavigasi pujian dan kritik eksternal adalah tantangan yang tak lekang oleh waktu.",
  "oppenheimer-genius-regret_para_006.json": "### Kaum Intelektual sebagai Kambing Hitam Politik",
  "oppenheimer-genius-regret_para_007.json": "Di pusaran Perang Dingin, Oppenheimer menjadi kambing hitam politik. Hubungan masa lalunya dan aktivisme anti-nuklirnya menjadikannya target kaum garis keras dalam pemerintah AS. Pada akhirnya, izin keamanannya dicabut, dan ia disingkirkan dari pelayanan publik. Peristiwa tragis ini menyoroti benturan antara hati nurani ilmiah dan tekanan politik. Realitas dicap sebagai 'risiko keamanan' setelah sebelumnya menjadi pahlawan nasional menunjukkan penderitaan mendalam yang dapat timbul dari keterputusan antara keyakinan individu dan norma-norma masyarakat. Dalam masyarakat kontemporer, kita juga sering menghadapi situasi di mana kita harus mempertahankan keyakinan kita dengan pengorbanan pribadi atau mengorbankan hati nurani demi kemanfaatan. Pengalaman Oppenheimer mengharuskan adanya pemahaman mendalam tentang kesulitan yang dihadapi kaum intelektual dan pemimpin yang mengejar kebenaran, serta rasa sakit psikologis yang diderita dalam prosesnya. Kehidupannya menunjukkan bahwa keberanian untuk mengejar kebenaran dan keadilan terkadang bisa memakan harga yang mahal.",
  "oppenheimer-genius-regret_para_008.json": "### Mempelajari Manajemen Psikologis dari Oppenheimer untuk Kehidupan Modern",
  "oppenheimer-genius-regret_para_009.json": "Kehidupan J. Robert Oppenheimer menawarkan pelajaran penting untuk mengarungi tekanan psikologis masyarakat modern. Melalui penyesalan dan kekacauannya, kita dapat memperoleh refleksi dan strategi praktis berikut:",
  "oppenheimer-genius-regret_para_010.json": "1. **Menyeimbangkan Tanggung Jawab dan Etika:** Seperti Oppenheimer, kita harus merenungkan secara mendalam dampak tindakan dan keputusan kita pada orang lain dan masyarakat. Khususnya saat mengejar teknologi atau bisnis inovatif, mengenali potensi risiko dan memikul tanggung jawab etis adalah hal yang terpenting. Hal ini membentuk fondasi bagi kepercayaan dan keberlanjutan jangka panjang, melampaui kesuksesan jangka pendek.\n2. **Mendengarkan Suara Hati Anda:** Daripada menyerah pada ekspektasi atau tekanan eksternal, berusahalah untuk bertindak sesuai dengan hati nurani dan keyakinan Anda. Sama seperti Oppenheimer yang terus-menerus merenungkan proliferasi nuklir, introspeksi yang tulus tentang nilai-nilai Anda membantu Anda menjaga pusat diri di tengah situasi yang kacau.\n3. **Memanfaatkan Kesendirian untuk Refleksi:** Meskipun kesendirian Oppenheimer adalah sumber penderitaan, hal itu juga memberikan peluang untuk refleksi diri yang mendalam. Dalam kehidupan kita yang serba cepat, meluangkan waktu untuk berhenti sejenak, melihat ke dalam diri, dan mempraktikkan pemrosesan emosi yang sehat sangatlah esensial.\n4. **Membangun dan Memanfaatkan Sistem Dukungan:** Terlepas dari kecerdasannya, Oppenheimer harus menghadapi serangan politik dan pengawasan eksternal sendirian. Dalam masyarakat modern, sangat penting untuk mendapatkan dukungan psikologis melalui hubungan dengan kolega, mentor, atau profesional terpercaya. Jangan mencoba menanggung semua beban sendirian; milikilah keberanian untuk meminta bantuan saat dibutuhkan.",
  "oppenheimer-genius-regret_para_011.json": "Kehidupan Oppenheimer adalah bukti beban psikologis berat yang ditanggung oleh kejeniusan. Perjuangan dan penyesalannya mendorong kita untuk merenungkan secara mendalam tanggung jawab atas kemajuan ilmiah, hati nurani individu, dan kompleksitas eksistensi manusia. Kisahnya bukan sekadar kenangan sejarah melainkan kompas berharga untuk memahami dan mengatasi kecemasan dan tekanan yang kita hadapi saat ini.",
  "oppenheimer-genius-regret_para_012.json": "[Jika Anda ingin mendiskusikan masalah Anda langsung dengan raksasa ini, mulai ruang obrolan 1:1 di sini](/giant/robert-oppenheimer)",
  "oppenheimer-genius-regret_title.json": "Penyesalan Oppenheimer: Beban Psikologis Berat Para Jenius",
  "lincoln-leadership-depression_para_000.json": "Di masa pertengahan abad ke-19 yang penuh gejolak, Amerika Serikat berdiri di tepi jurang. Terpecah belah karena isu perbudakan, negara itu terhuyung-huyung di ambang kehancuran, dan akhirnya terjun ke dalam kancah brutal Perang Saudara. Pada titik kritis ini, Abraham Lincoln, Presiden ke-16, memikul beban yang lebih berat dari yang dapat dipahami kebanyakan orang. Sambil memproyeksikan citra tekad yang tak tergoyahkan, Lincoln secara pribadi bergumul dengan pergolakan internal yang mendalam melawan melankolia, depresi yang dalam dan terus-menerus yang membayangi hidupnya. Tragedi pribadi dan ujian politiknya sangat selaras dengan kecemasan, tekanan, dan perjuangan mencari makna yang dihadapi individu saat ini. Kisah Lincoln melampaui sekadar catatan sejarah; kisah ini menawarkan wawasan mendalam dalam menavigasi iblis pribadi dan menghadapi tantangan masyarakat lintas abad.",
  "lincoln-leadership-depression_para_001.json": "Kehidupan kita sendiri sering kali diterjang badai. Ketidakpastian bisnis, tekanan kemajuan karier, kompleksitas hubungan, dan beban tanpa henti dari ekspektasi masyarakat dapat membuat kita merasa tersesat dan kewalahan. Sama seperti Lincoln yang bergulat dengan negara yang terpecah, kita bisa mendapati diri kita lumpuh oleh masalah-masalah rumit. Namun, kehidupan Lincoln menunjukkan bahwa bahkan di tengah kegelapan terdalam, adalah mungkin untuk menyalakan percikan harapan dan mengubah penderitaan pribadi menjadi katalisator bagi penyembuhan dan persatuan kolektif. Kerentanan dan perjuangan manusianya yang mendalam menawarkan penghiburan dan inspirasi, membangkitkan potensi terpendam kita sendiri.",
  "lincoln-leadership-depression_para_002.json": "### Pergolakan Batin Lincoln: Pertempuran Melawan Melankolis",
  "lincoln-leadership-depression_para_003.json": "Melankolia adalah teman setia Lincoln. Kehilangan di awal kehidupannya, termasuk kematian ibunya dan seorang anak yang masih kecil, ditambah dengan kegagalan bisnis dan kemunduran politik, menjerumuskannya ke dalam keputusasaan yang mendalam. Ia terkenal dengan deskripsinya yang merasa \"tertekan, benar-benar hancur,\" dan bercerita kepada teman-temannya tentang pikiran untuk bunuh diri. Surat-menyurat dan tulisan pribadinya mengungkap kedalaman pergumulan ini. Namun, Lincoln menolak untuk menyerah pada kegelapan. Daripada menghindari rasa sakitnya, ia menghadapinya, berusaha memahami garis besarnya. Ia mengakui kerentanannya, bukan sebagai kelemahan, melainkan sebagai bagian dari kemanusiaannya, dan memupuk ketangguhan batin. Hal ini mencerminkan pengusaha modern yang, saat menghadapi kenyataan pahit akan potensi kegagalan, berusaha mengidentifikasi peluang di dalam risiko tersebut. Kemampuan Lincoln untuk mengintegrasikan 'sisi gelapnya' menempa karakter yang lebih kuat.",
  "lincoln-leadership-depression_para_004.json": "### Sebuah Bangsa yang Terbelah, Sebuah Perjalanan Menuju Persatuan",
  "lincoln-leadership-depression_para_005.json": "Setelah menjabat, Lincoln mewarisi negara yang sudah terhuyung-huyung di ambang perpecahan. Negara-negara bagian Selatan telah mendeklarasikan pemisahan diri, dan pelantikannya diadakan di bawah pengamanan yang belum pernah terjadi sebelumnya, dibayangi oleh ancaman kekerasan. Sepanjang konflik berdarah Perang Saudara, Lincoln tidak pernah goyah dari tujuan akhirnya: pelestarian dan penyatuan kembali bangsa. Pidato-pidatonya, terutama Pidato Gettysburg, dengan kuat mengartikulasikan cita-cita \"pemerintahan dari rakyat, oleh rakyat, untuk rakyat,\" yang menggalang masyarakat yang terpecah. Kepemimpinannya melampaui kemenangan militer; itu adalah bukti perjuangan abadi untuk menegakkan martabat dan kebebasan manusia di tengah kengerian perang. Hal ini sejalan dengan peran seorang pemimpin di masa krisis, yang harus mendefinisikan kembali visi dan nilai-nilai inti organisasi, serta memberikan energi baru kepada tim menuju tujuan bersama. Lincoln, meskipun putus asa, secara konsisten memproyeksikan harapan dan memupuk persatuan.",
  "lincoln-leadership-depression_para_006.json": "### Kebijaksanaan Lincoln untuk Mengatasi Kesulitan",
  "lincoln-leadership-depression_para_007.json": "Kehidupan Lincoln menawarkan kekayaan kebijaksanaan yang dipetik dari kesulitan mendalam. Ia tidak semata-mata menanggung kemurungannya; ia mengintegrasikannya, memungkinkannya untuk memperdalam pemahamannya tentang kondisi manusia. Ia sering menggunakan humor untuk meredakan ketegangan dan terhubung dengan orang lain melalui kerentanan bersama. Kisahnya mengilustrasikan kekuatan mengakui, daripada menyembunyikan, perjuangan seseorang. Kegagalan dan kemunduran bukanlah titik akhir melainkan tanah subur untuk pertumbuhan. Lincoln mengasah dirinya melalui pemahaman ini, hingga pada akhirnya muncul sebagai pemimpin transformatif. Proses ini mirip dengan individu yang mengatasi trauma atau kemunduran pribadi, yang muncul dengan lebih tangguh dan sadar diri.",
  "lincoln-leadership-depression_para_008.json": "### Pelajaran dari Lincoln untuk Kehidupan Modern",
  "lincoln-leadership-depression_para_009.json": "Kehidupan Lincoln memberikan panduan praktis yang tak lekang oleh waktu untuk menavigasi tantangan kontemporer. Pengalaman-pengalamannya menawarkan pelajaran berharga dalam menghadapi perjuangan kesehatan mental dan tekanan masyarakat:",
  "lincoln-leadership-depression_para_010.json": "1. **Hadapi Kegelapan Anda**: Seperti Lincoln, akui dan terimalah rasa sakit serta kerentanan Anda. Perubahan sejati dimulai dengan penilaian diri yang jujur dan memahami emosi Anda.\n2. **Salurkan Kesulitan menjadi Pertumbuhan**: Ujian dan kegagalan pribadi pada dasarnya tidak merusak; mereka adalah peluang untuk membangun kekuatan dan kedalaman. Belajarlah dan kembangkan diri dari kemunduran.\n3. **Pertahankan Visi Anda**: Dalam menghadapi keadaan yang luar biasa, berpegang teguhlah pada nilai-nilai inti dan tujuan akhir Anda. Sama seperti Lincoln yang memimpikan negara yang bersatu, perjelas apa yang benar-benar penting dalam hidup Anda.\n4. **Praktikkan Empati dan Kasih Sayang**: Berhubungan dengan penderitaan orang lain dan menyebarkan kebaikan kepada diri sendiri serta orang-orang di sekitar Anda adalah kekuatan yang kuat untuk mengatasi krisis dan memperkuat komunitas. Sisi kemanusiaan Lincoln menyoroti prinsip vital ini.",
  "lincoln-leadership-depression_para_011.json": "Perjalanan Lincoln melewati pertempuran internal dan krisis nasional yang tanpa henti berdiri sebagai kesaksian kuat untuk menjaga harapan dan meraih persatuan melawan kekuatan perpecahan. Perjuangan dan kemenangannya terus bergema mendalam di dalam kehidupan kita masing-masing.",
  "lincoln-leadership-depression_para_012.json": "[Jika Anda ingin mendiskusikan masalah Anda langsung dengan raksasa ini, mulai ruang obrolan 1:1 di sini](/giant/abraham-lincoln)",
  "lincoln-leadership-depression_title.json": "Perang Rahasia Lincoln: Bagaimana Ia Menyelamatkan Negara yang Terpecah Saat Berjuang Melawan Depresi"
}

out_dir = "C:/Users/user/.gemini/antigravity/brain/45f5002d-398c-41ef-8740-cf257710e53c/scratch/pipeline/id/results/"
for k, v in data.items():
    slug = k.split('_')[0] if '_' in k else k.replace('.json', '')
    if 'para' in k:
        type_str = 'para'
        index = int(k.split('_')[2].split('.')[0])
        out = {"slug": slug, "type": type_str, "index": index, "id_text": v}
    else:
        type_str = 'title'
        out = {"slug": slug, "type": type_str, "id_text": v}
    with open(os.path.join(out_dir, k), 'w', encoding='utf-8') as f:
        json.dump(out, f, ensure_ascii=False, indent=2)

print("Saved batch 3.")
