import json
import os

data = {
  "disney-imagination-market_para_000.json": "Pada tahun 1920-an, sebuah era yang diselimuti oleh bayang-bayang Depresi Besar yang membayangi, dunia dibanjiri ketidakpastian dan kecemasan. Orang-orang kehilangan pekerjaan, harapan menyusut, dan beban kenyataan terasa sangat menghimpit. Hal ini mencerminkan kemerosotan ekonomi, tekanan teknologi, dan persaingan tanpa henti yang kita hadapi saat ini, memicu perasaan tidak nyaman yang serupa. Di tengah kegelapan sejarah ini, seorang pria tampil beda. Namanya adalah Walt Disney. Bahkan di tengah kebisuan monokrom dari sinema awal dan kesulitan kehidupan sehari-hari, ia memegang keyakinan yang tak tergoyahkan pada kekuatan imajinasi murni – sebuah kekuatan yang menolak untuk meredup. Kisahnya melampaui sejarah animasi; ini adalah perjalanan epik seorang pria yang menyulap harapan dari keputusasaan, menciptakan sesuatu dari ketiadaan, dan pada akhirnya membangun kerajaan bernilai miliaran. Kisahnya sangat selaras dengan calon pengusaha, pemilik bisnis muda, dan siapa saja yang mengarungi kompleksitas kehidupan modern, mencari jalan mereka sendiri di tengah tantangan yang luar biasa.",
  "disney-imagination-market_para_001.json": "Walt Disney jauh lebih dari sekadar seniman yang menggambar kartun atau membuat film. Ia adalah seorang pengusaha visioner dengan pemahaman tajam tentang zamannya dan pandangan ke masa depan. Di atas segalanya, ia adalah seorang alkemis, diberkahi dengan kemampuan luar biasa untuk merangkai cerita yang memikat hati orang-orang di seluruh dunia. Ciptaannya, seperti Mickey Mouse, lebih dari sekadar hiburan semata; mereka menjadi sumber kegembiraan, penghiburan, dan impian bagi jutaan orang. Ia tanpa henti berinovasi, menantang status quo, mendorong batas-batas teknologi, dan memelopori bentuk-bentuk hiburan baru. Kelahiran Disneyland adalah puncak dari visi ini – mimpi ambisius untuk mewujudkan surga imajinasi ke dalam dunia nyata. Industri taman hiburan, film animasi, dan kerajaan pernak-pernik yang kita alami saat ini berhutang keberadaannya pada jejak yang dirintis Walt Disney. Kehidupannya mendemonstrasikan bagaimana mengubah mimpi yang tampaknya mustahil menjadi kenyataan dan bagaimana mentransmutasikan imajinasi murni menjadi kekayaan dan pengaruh yang luar biasa.",
  "disney-imagination-market_para_002.json": "### Tekad Pantang Menyerah untuk Mewujudkan Impian",
  "disney-imagination-market_para_003.json": "Karier awal Walt Disney adalah sebuah saga tentang kemunduran dan kegagalan. Perusahaan animasi pertamanya, 'Laugh-O-Gram Studio,' bangkrut, dan ia kehilangan hak atas ciptaan kesayangannya, 'Oswald the Lucky Rabbit.' Hal ini mencerminkan perjuangan para pendiri startup modern yang menghadapi penolakan pendanaan atau melihat teknologi inti mereka direbut oleh pesaing. Namun, Walt tidak menyerah pada keputusasaan. Sebaliknya, ia menggunakan pengalaman pahit ini sebagai batu loncatan untuk menciptakan karakter yang bahkan lebih ikonik: Mickey Mouse. Awalnya diperkenalkan sebagai 'Mortimer Mouse' sebelum berganti nama, Mickey menjadi simbol Walt Disney dan sosok yang dipuja secara global. Ketekunan dan ketangguhannya dalam mengatasi 역경 (kesulitan) berfungsi sebagai bukti kuat pepatah bahwa 'kegagalan adalah ibu dari kesuksesan' dalam dunia bisnis modern. Ia menolak dikekang oleh kenyataan, terus-menerus mengeksplorasi ide-ide baru dan tanpa henti mengatasi rintangan teknis. Perkembangannya dari film bisu hitam-putih menjadi animasi berwarna, bersuara, dan akhirnya animasi berdurasi panjang menunjukkan bagaimana perpaduan antara inovasi teknologi dan kreativitas dapat memunculkan pasar yang sama sekali baru.",
  "disney-imagination-market_para_004.json": "### Kekuatan Bercerita: Dari Emosi Menjadi Keuntungan",
  "disney-imagination-market_para_005.json": "Walt Disney memiliki pemahaman tak tertandingi tentang kekuatan bercerita. Ia tidak hanya menciptakan karakter-karakter menawan; ia merangkai narasi petualangan dan konflik yang beresonansi dengan emosi manusia secara universal. 'Putri Salju dan Tujuh Kurcaci,' fitur animasi berdurasi panjang pertama, adalah upaya berani yang pada akhirnya meraih kesuksesan monumental, membuka cakrawala baru bagi industri animasi. Kemenangan ini bukan sekadar pencapaian artistik; ini mendemonstrasikan bagaimana sebuah cerita yang memikat dapat dikomersialkan dan diperluas menjadi perusahaan besar. Pernak-pernik karakter, pengalaman imersif Disneyland, dan film serta acara TV yang tak terhitung jumlahnya yang menyusul kemudian, semuanya bermula dari benih sebuah 'cerita,' yang tumbuh menjadi ekosistem bisnis yang luas. Ini menawarkan wawasan krusial bagi para pembuat konten saat ini, dari bintang YouTube hingga seniman webtoon, tentang bagaimana membangun fandom dan menghasilkan pendapatan berdasarkan narasi. Kesuksesan Disney membuktikan bahwa 'cerita yang bagus' bukan sekadar hiburan melainkan pendorong utama untuk membangun loyalitas merek yang kuat dan model bisnis yang berkelanjutan.",
  "disney-imagination-market_para_006.json": "### Kewirausahaan yang Tak Pernah Berhenti Berinovasi",
  "disney-imagination-market_para_007.json": "Walt Disney tidak pernah berpuas diri dengan pencapaiannya. Ia selalu memimpikan garda depan berikutnya. Ia membayangkan kemajuan dalam teknologi animasi, video, dan pada akhirnya, penciptaan ruang fisik yang imersif. Disneyland berdiri sebagai puncak dari semangat inovatif ini. Dibangun dengan skala dan kecanggihan teknologi yang tak terbayangkan pada masa itu, Disneyland lebih dari sekadar taman hiburan; itu adalah perwujudan dari visi ambisiusnya untuk menciptakan 'dunia impian untuk seluruh keluarga.' Ia bertujuan untuk memberikan pengalaman yang melampaui sekadar menonton film, menawarkan pengunjung sensasi memasuki cerita itu sendiri. Hal ini selaras dengan pembuatan konten imersif modern menggunakan teknologi VR dan AR, serta strategi pemasaran eksperiensial. Walt Disney merangkul teknologi tanpa rasa takut, terus memperluas batas-batas hiburan. Dorongan kewirausahaannya tidak hanya berasal dari pengejaran keuntungan, tetapi dari gairah yang tak tergoyahkan untuk menghadirkan pengalaman dan kegembiraan baru bagi orang-orang.",
  "disney-imagination-market_para_008.json": "### Panduan 4 Langkah untuk Mewujudkan Imajinasi Anda Menjadi Kenyataan",
  "disney-imagination-market_para_009.json": "Dari kehidupan dan kesuksesan Walt Disney, kita dapat memetik kebijaksanaan untuk menavigasi tantangan modern dan merintis jalan kita sendiri menuju pencapaian. Berikut adalah panduan 4 langkah untuk menerapkan kemampuan alkemisnya dalam hidup Anda sendiri:",
  "disney-imagination-market_para_010.json": "1. Temukan 'Mickey Mouse' Anda: Kenali hasrat Anda, ide atau bakat yang menyalakan antusiasme Anda dan melihat kemungkinan yang dilewatkan orang lain. Entah itu bisnis, seni, atau tujuan pribadi Anda, temukan dan pelihara 'karakter' unik Anda.",
  "disney-imagination-market_para_011.json": "2. Rangkul Kegagalan sebagai Peluang Belajar: Walt Disney menghadapi banyak kegagalan tetapi belajar dan berkembang dari masing-masing kegagalan tersebut. Gunakan kemunduran sebagai batu loncatan untuk berkembang, mengekstraksi pelajaran berharga untuk tahap berikutnya.",
  "disney-imagination-market_para_012.json": "3. Rangkai 'Cerita' yang Memikat: Pastikan ide atau bisnis Anda diresapi dengan narasi menawan yang menggerakkan orang. Audiens merespons bukan hanya logika tetapi juga emosi. Buatlah cerita yang membagikan visi Anda dan memancing empati.",
  "disney-imagination-market_para_013.json": "4. Berinovasi dan Menantang Secara Konstan: Jangan pernah puas dengan status quo. Jelajahi teknologi dan ide baru untuk memperluas cakrawala Anda. Seperti Walt Disney, tetapkan tujuan yang berani dan beranikan diri untuk mengejarnya, bahkan ketika itu tampaknya mustahil.",
  "disney-imagination-market_para_014.json": "Walt Disney bukan sekadar kartunis atau pembuat film; ia adalah inovator dan ahli strategi bisnis yang memanfaatkan sumber daya paling murni – imajinasi – untuk menciptakan nilai miliaran sambil menavigasi masa-masa yang tidak pasti. Kisahnya terus menawarkan pesan vital: dengan bermimpi, terus-menerus menantang diri kita sendiri, dan menceritakan kisah yang menyentuh hati orang, kita dapat melampaui batasan yang kita rasakan dan mencapai hal yang luar biasa.\n[Jika Anda ingin mendiskusikan masalah Anda langsung dengan raksasa ini, mulai ruang obrolan 1:1 di sini](/giant/walt-disney)",
  "disney-imagination-market_title.json": "Walt Disney: Sang Alkemis yang Mengubah Imajinasi Murni Menjadi Pasar Bernilai Miliaran Dolar"
}

out_dir = "C:/Users/user/.gemini/antigravity/brain/45f5002d-398c-41ef-8740-cf257710e53c/scratch/pipeline/id/results/"
for k, v in data.items():
    slug = k.split('_')[0] if '_' in k else k.replace('.json', '')
    if 'para' in k:
        type_str = 'para'
        index = int(k.split('_')[2].split('.')[0])
        out = {"slug": slug, "type": type_str, "index": index, "id_text": v}
    else:
        type_str = 'title'
        out = {"slug": slug, "type": type_str, "id_text": v}
    with open(os.path.join(out_dir, k), 'w', encoding='utf-8') as f:
        json.dump(out, f, ensure_ascii=False, indent=2)

print("Saved disney.")
