import os
import json

tasks_dir = 'C:/Users/user/.gemini/antigravity/brain/45f5002d-398c-41ef-8740-cf257710e53c/scratch/pipeline/id/tasks/'
results_dir = 'C:/Users/user/.gemini/antigravity/brain/45f5002d-398c-41ef-8740-cf257710e53c/scratch/pipeline/id/results/'

json_str = r'''{
  "quotes-leadership-modern_para_000.json": "## Gema Abadi dari Komando Kuno",
  "quotes-leadership-modern_para_001.json": "Di dunia kita yang sangat terhubung dan berkembang pesat, tantangan memimpin dan berkolaborasi dalam tim bisa terasa belum pernah terjadi sebelumnya. Namun, di balik lapisan kemajuan teknologi dan pasar global, dinamika fundamental dari interaksi manusia, motivasi, dan eksekusi strategis tetap sangat konstan. Sejarah, yang sering dianggap sebagai arsip berdebu dari kejayaan dan kegagalan masa lalu, menawarkan sumber kebijaksanaan yang mendalam untuk menavigasi kompleksitas modern ini. Dengan meneliti kehidupan dan filosofi tokoh-tokoh sejarah penting, kita dapat menggali strategi kepemimpinan abadi yang melampaui zaman dan memberikan wawasan yang dapat ditindaklanjuti untuk mencapai kinerja tinggi di lingkungan profesional kontemporer.",
  "quotes-leadership-modern_para_002.json": "### Sun Tzu: Seni Pandangan Strategis ke Depan",
  "quotes-leadership-modern_para_003.json": "Sun Tzu, jenderal dan ahli strategi Tiongkok yang penuh teka-teki, menulis \"Seni Perang\" (The Art of War) lebih dari dua milenium yang lalu, namun prinsip-prinsipnya terus bergema di kalangan para pemimpin di berbagai bidang. Penekanannya bukan pada kekerasan, melainkan pada perencanaan yang cermat, memahami musuh dan diri sendiri, serta mencapai kemenangan dengan konflik yang minimal. Hal ini sangat kontras dengan gaya manajemen yang sering kali reaktif dan didorong oleh krisis yang lazim terjadi saat ini. Filosofi inti Sun Tzu menekankan pentingnya mengetahui medan, cuaca, dan disposisi kekuatan Anda sendiri maupun musuh. Untuk tim modern, ini diterjemahkan menjadi pemahaman yang mendalam mengenai kondisi pasar, lanskap pesaing, kemampuan internal, dan dinamika tim sebelum memulai proyek signifikan atau inisiatif strategis apa pun.",
  "quotes-leadership-modern_para_004.json": "Salah satu pelajaran Sun Tzu yang paling berdampak adalah konsep \"mengenali musuhmu dan mengenali dirimu sendiri, maka kamu tidak akan berada dalam bahaya dalam seratus pertempuran.\" Kebijaksanaan ini dapat diterapkan secara langsung pada strategi bisnis modern. Sebelum meluncurkan produk baru, sebuah tim harus meneliti persaingan dengan cermat (\"musuh\") dan secara jujur menilai kekuatan dan kelemahan mereka sendiri (diri mereka sendiri). Kesadaran diri ini mencegah kesalahan langkah yang merugikan dan memungkinkan strategi yang lebih bertarget dan efektif. Terlebih lagi, nasihatnya tentang penipuan dan kemampuan beradaptasi sangat penting. Dalam konteks bisnis, ini tidak berarti praktik yang tidak etis, melainkan kemampuan untuk menjadi gesit, untuk berputar ketika keadaan berubah, dan untuk menampilkan barisan depan yang bersatu dan percaya diri bahkan ketika menghadapi ketidakpastian internal.",
  "quotes-leadership-modern_para_005.json": "### Raja Sejong yang Agung: Kebajikan dalam Pengkultivasian",
  "quotes-leadership-modern_para_006.json": "Mengalihkan pandangan kita ke semenanjung Asia Timur, Raja Sejong dari Joseon (Korea) berdiri sebagai mercusuar kepemimpinan yang tercerahkan, bukan melalui penaklukan militer, melainkan melalui kemajuan intelektual dan budaya. Naik takhta pada tahun 1418, Raja Sejong menyadari bahwa kekuatan nasional yang sejati terletak pada pemberdayaan rakyatnya. Pencapaiannya yang paling dirayakan, penciptaan alfabet Korea, Hangeul, adalah tindakan aksesibilitas yang revolusioner. Sebelum Hangeul, literasi sebagian besar terbatas pada kaum elit yang mampu menguasai karakter bahasa Mandarin yang kompleks. Dengan mengembangkan skrip fonetik yang sederhana, Raja Sejong mendemokratisasi pengetahuan, memungkinkan rakyat jelata untuk membaca, menulis, dan berinteraksi dengan informasi secara langsung. Hal ini mendorong masyarakat yang lebih terinformasi, meningkatkan efisiensi administrasi, dan meletakkan dasar bagi identitas budaya Korea yang abadi.",
  "quotes-leadership-modern_para_007.json": "Kepemimpinan Raja Sejong mencontohkan kekuatan berinvestasi pada sumber daya manusia. Pencarian pengetahuannya yang tak kenal lelah, dukungannya terhadap para sarjana, dan komitmennya pada inovasi praktis, seperti pengembangan instrumen ilmiah dan teknik pertanian, menunjukkan pemahaman yang mendalam bahwa peran utama seorang pemimpin adalah mengembangkan potensi di dalam masyarakatnya. Untuk tim modern, ini diterjemahkan menjadi memprioritaskan pengembangan karyawan, menumbuhkan budaya pembelajaran berkelanjutan, dan menciptakan lingkungan di mana berbagai bakat dapat berkembang. Warisan Raja Sejong mengingatkan kita bahwa memberdayakan individu dengan alat dan pengetahuan yang mereka butuhkan bukanlah sekadar tindakan kebajikan, melainkan keharusan strategis untuk kesuksesan dan ketahanan jangka panjang. Visinya adalah untuk sebuah bangsa di mana setiap suara dapat didengar dan dipahami, sebuah aspirasi yang kuat bagi organisasi modern mana pun yang berjuang untuk inklusivitas dan inovasi.",
  "quotes-leadership-modern_para_008.json": "### Julius Caesar: Karisma Tindakan Tegas",
  "quotes-leadership-modern_para_009.json": "Dalam catatan sejarah Barat, Julius Caesar tetap menjadi tokoh yang menjulang tinggi, identik dengan ambisi, kegeniusan militer, dan kepemimpinan politik yang transformatif. Kampanyenya di Galia, yang didokumentasikan dengan cermat dalam bukunya \"Commentarii de Bello Gallico,\" tidak hanya memamerkan kecemerlangan strategisnya di medan perang tetapi juga kemampuannya yang luar biasa untuk menginspirasi kesetiaan dan mendorong legiunnya untuk mencapai prestasi yang tampaknya mustahil. Caesar memahami dimensi psikologis dari kepemimpinan. Ia memimpin dari depan, berbagi penderitaan dengan tentaranya, memupuk rasa persahabatan yang mendalam dan tujuan bersama. Hubungan pribadi ini berperan penting dalam membentuk pasukan yang tangguh dalam pertempuran sekaligus sangat mengabdi kepada komandannya.",
  "quotes-leadership-modern_para_010.json": "Langkah Caesar yang terkenal saat melintasi sungai Rubicon pada tahun 49 SM adalah momen tindakan yang tegas, meskipun kontroversial, yang secara tidak dapat ditarik kembali mengubah jalannya sejarah Romawi. Hal itu mencontohkan kesediaannya untuk mengambil risiko yang diperhitungkan dan bertindak dengan tekad yang tak tergoyahkan saat dihadapkan pada titik-titik kritis. Pernyataannya yang terkenal, yang sering diparafrasekan sebagai \"dadu telah dilempar,\" merangkum semangat pengambilan keputusan yang berani. Di tempat kerja modern, tim sering kali menghadapi momen ketidakpastian dan poin keputusan penting. Teladan Caesar, meskipun bersifat peringatan dalam konsekuensi akhirnya bagi Republik, mengajarkan nilai kejelasan, keyakinan, dan keberanian untuk berkomitmen pada jalan yang dipilih setelah semua pertimbangan yang semestinya dilakukan. Ini tentang mengubah kelumpuhan analisis menjadi tindakan yang bertujuan, dengan memahami bahwa terkadang, risiko terbesar adalah tidak bertindak. Kemampuannya untuk mengomunikasikan visinya dan menggalang dukungan, baik kepada pasukannya maupun penduduk Romawi, menyoroti kekuatan abadi dari retorika yang meyakinkan dan tujuan yang jelas dalam menyatukan kelompok menuju tujuan bersama.",
  "quotes-leadership-modern_para_011.json": "## Mensintesis Kebijaksanaan Kuno untuk Tim Modern",
  "quotes-leadership-modern_para_012.json": "Dari pandangan strategis Sun Tzu ke depan hingga penekanan Raja Sejong pada pengembangan manusia dan komando tegas Caesar, para raksasa sejarah ini menawarkan jalinan pelajaran kepemimpinan yang kaya. Di lingkungan kerja yang kompleks saat ini, tekanan tenggat waktu, pencarian kepuasan karier, dan pencarian makna adalah tantangan abadi. Menerapkan model-model kuno ini membutuhkan integrasi yang bijaksana. Kita harus menumbuhkan perencanaan strategis dan kemampuan beradaptasi yang didukung oleh Sun Tzu, dengan menyadari bahwa tinjauan ke masa depan dan pemahaman adalah yang terpenting. Pada saat yang sama, kita harus merangkul visi Raja Sejong dalam memberdayakan dan mengembangkan anggota tim kita, memupuk lingkungan tempat pengetahuan dibagikan dan potensi dipelihara. Terakhir, ketika momen krusial muncul, kita harus memanfaatkan ketegasan yang diwujudkan oleh Caesar, diimbangi dengan kebijaksanaan dan pertimbangan etis, untuk bergerak maju dengan kejelasan dan keyakinan. Dengan belajar dari masa lalu, kita melengkapi diri kita dengan prinsip-prinsip abadi yang diperlukan untuk membangun tim modern yang berkinerja tinggi, tangguh, dan benar-benar berdampak.",
  "quotes-leadership-modern_title.json": "Menerapkan Kepemimpinan Kuno pada Tim Modern: Kebijaksanaan untuk Kinerja Tinggi"
}'''

T = json.loads(json_str)

for filename, text in T.items():
    in_path = os.path.join(tasks_dir, filename)
    out_path = os.path.join(results_dir, filename)
    with open(in_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    out_data = {
        'slug': data['slug'],
        'type': data['type']
    }
    if 'index' in data:
        out_data['index'] = data['index']
    out_data['id_text'] = text
    
    with open(out_path, 'w', encoding='utf-8') as f:
        json.dump(out_data, f, ensure_ascii=False, indent=2)

print('Done quotes-leadership-modern')
