const fs = require('fs');

const dataFile = './src/data/final-narratives.json';
const data = JSON.parse(fs.readFileSync(dataFile, 'utf8'));

const translations = {
  "genghis-khan": {
    era_it: "Gigante del XII-XIII Secolo (1162~1227)",
    epic_it: "Nel 1162, nelle aspre praterie spazzate dal vento della Mongolia, nacque un bambino di nome Temujin stringendo un grumo di sangue nel pugno — un antico presagio di un destino monumentale. La sua giovinezza fu un incubo di sopravvivenza; suo padre fu avvelenato da rivali e la sua famiglia fu abbandonata dalla propria tribù a morire di fame. Temujin fu costretto a uccidere il proprio fratellastro per garantire la sopravvivenza della famiglia e in seguito fu ridotto in schiavitù dai suoi nemici. Eppure, fu proprio in questa fucina di assoluta privazione che si temprò la sua monumentale volontà. Si rese conto che il caos della steppa era una malattia e sviluppò la radicale ambizione di unificare le tribù in guerra in un'unica nazione inarrestabile.\n\nIl più grande balzo di Gengis Khan fu l'invenzione di una macchina militare meritocratica che distrusse le basi del feudalesimo. Ignorò la nobiltà di nascita e promosse i suoi generali in base al talento e alla lealtà, creando una disciplina e una velocità tattica che il mondo non aveva mai visto. Il suo trionfo fu la creazione dell'Impero Mongolo, il più grande impero contiguo della storia umana. Non fu semplicemente una forza distruttiva; fu un gigante della globalizzazione che stabilì la 'Pax Mongolica', mettendo in sicurezza la Via della Seta e consentendo lo scambio senza precedenti di idee, tecnologie e commerci tra Oriente e Occidente. Introdusse una scrittura e stabilì la tolleranza religiosa in metà del pianeta.\n\nLa sua eredità fu definita dal rifiuto di rammollirsi col potere. Visse in una tenda di feltro fino alla morte, temendo che il lusso delle città avrebbe corrotto lo spirito del suo popolo. Divenne celebre la sua frase: 'Se costruisci un muro, gli appartieni; se ti muovi, appartieni al mondo.' Si erse come un gigante di visione strategica, dimostrando che 'conquistare il mondo a cavallo è facile; è smontare e governare che è difficile.' Quando morì nel 1227, ordinò che il suo luogo di sepoltura rimanesse segreto, assicurandosi di tornare alla terra in modo altrettanto anonimo di come vi era giunto, lasciando solo la sua monumentale influenza a dominare i secoli a venire.\n\nOggi, Gengis Khan rimane la suprema icona globale per organizzazione, resilienza e trasformazione totale. Insegnò all'umanità che 'la forza di un muro non è né maggiore né minore del coraggio di chi lo difende' e che la vittoria inizia con la conquista delle proprie paure interiori. Dimostrò che un gigante può sorgere dagli assoluti margini della civiltà per rimodellare il centro del mondo. La sua vita fu una grande epopea di sopravvivenza ed espansione, un costante promemoria che le origini non dettano la destinazione. Continua ad affascinare ogni leader che cerca di costruire un sistema duraturo dalle materie prime del caos e della grinta.",
    trials_it: "La sopravvivenza a un'estrema povertà infantile e la schiavitù dopo l'assassinio del padre. L'affrontare il monumentale compito di unificare centinaia di tribù in guerra e il pedaggio psicologico di combattere il suo ex fratello di sangue, Jamukha, in una brutale lotta per l'anima della Mongolia.",
    overcoming_it: "Stabilì il primo sistema internazionale autenticamente meritocratico, dimostrando che il talento e la lealtà sono superiori ai privilegi ereditari. Costruì un'infrastruttura globale di commercio e comunicazione che colmò il divario tra Europa e Asia, ponendo fine per sempre all'isolamento delle civiltà antiche.",
    era_pt: "Gigante do Século XII-XIII (1162~1227)",
    epic_pt: "Em 1162, nas duras e castigadas pastagens da Mongólia, um menino chamado Temujin nasceu segurando um coágulo de sangue no punho — um antigo presságio de um destino monumental. Sua juventude foi um pesadelo de sobrevivência; seu pai foi envenenado por rivais e sua família foi abandonada pela tribo para morrer de fome. Temujin foi forçado a matar o próprio meio-irmão para garantir a sobrevivência de sua família e, mais tarde, foi escravizado por seus inimigos. No entanto, foi nesta forja de privação absoluta que a sua vontade monumental foi temperada. Ele percebeu que o caos da estepe era uma doença e desenvolveu a ambição radical de unificar as tribos em guerra em uma nação única e implacável.\n\nO maior salto de Genghis Khan foi a invenção de uma máquina militar meritocrática que destruiu as bases do feudalismo. Ele desconsiderou o nascimento nobre e promoveu seus generais com base no talento e na lealdade, criando uma disciplina e uma velocidade tática que o mundo nunca tinha visto. Seu triunfo foi a criação do Império Mongol, o maior império terrestre contíguo da história da humanidade. Ele não foi apenas uma força destrutiva; ele foi um gigante da globalização que estabeleceu a 'Pax Mongolica', garantindo a Rota da Seda e permitindo o intercâmbio sem precedentes de ideias, tecnologia e comércio entre o Oriente e o Ocidente. Ele introduziu um roteiro escrito e estabeleceu a tolerância religiosa em metade do planeta.\n\nSeu legado foi definido por sua recusa em amolecer com o poder. Ele viveu em uma tenda de feltro até sua morte, temendo que o luxo das cidades apodrecesse o espírito de seu povo. É famosa a sua frase: 'Se você constrói um muro, você pertence a ele; se você se move, você pertence ao mundo.' Ele se destacou como um gigante de visão estratégica, mostrando que 'conquistar o mundo a cavalo é fácil; desmontar e governar é que é difícil'. Quando morreu, em 1227, ele ordenou que o local de seu sepultamento permanecesse em segredo, garantindo que ele retornaria à terra de forma tão anônima quanto havia chegado, deixando apenas a sua influência monumental para governar os próximos séculos.\n\nHoje, Genghis Khan permanece como o ícone global definitivo de organização, resiliência e transformação total. Ele ensinou à humanidade que 'a força de uma muralha não é maior nem menor do que a coragem daqueles que a defendem' e que a vitória começa com a conquista dos próprios medos internos. Ele provou que um gigante pode surgir das margens absolutas da civilização para remodelar o centro do mundo. Sua vida foi um grandioso épico de sobrevivência e expansão, um lembrete constante de que suas origens não ditam seu destino. Ele continua a fascinar todos os líderes que buscam construir um sistema duradouro a partir das matérias-primas do caos e da determinação.",
    trials_pt: "A sobrevivência a uma extrema pobreza na infância e à escravidão após o assassinato do pai. O enfrentamento da tarefa monumental de unificar centenas de tribos em guerra e o custo psicológico de lutar contra seu ex-irmão de sangue, Jamukha, em uma luta brutal pela alma da Mongólia.",
    overcoming_pt: "Estabeleceu o primeiro sistema internacional verdadeiramente meritocrático, provando que o talento e a lealdade são superiores aos privilégios hereditários. Construiu uma infraestrutura global de comércio e comunicação que preencheu a lacuna entre a Europa e a Ásia, acabando para sempre com o isolamento de antigas civilizações.",
    wisdom: [
      {
        quote_it: "Ho conquistato il mondo perché per prima cosa ho conquistato me stesso. Il più grande nemico che dovrai mai affrontare è quello che ti fissa allo specchio.",
        meaning_it: "Sulla Sovranità della Padronanza di Sé: La vittoria è una conquista interna molto prima che sia un evento esterno. Un gigante si rende conto di non poter governare una nazione o un'azienda se non è in grado di governare i propri impulsi e le proprie paure; vinci la battaglia interiore e il mondo si allineerà.",
        quote_pt: "Eu conquistei o mundo porque primeiro conquistei a mim mesmo. O maior inimigo que você enfrentará é aquele que olha para você no espelho.",
        meaning_pt: "Sobre a Soberania do Autodomínio: A vitória é uma conquista interna muito antes de ser um evento externo. Um gigante percebe que não pode governar uma nação ou uma empresa se não puder governar seus próprios impulsos e medos; vença a batalha interior, e o mundo se alinhará."
      },
      {
        quote_it: "Colui che costruisce un muro ne diventa prigioniero. Il successo appartiene ai mobili, agli adattabili e agli instancabili. Non smettere mai di muoverti.",
        meaning_it: "Sulla Disciplina dell'Adattabilità: La sicurezza è un'illusione pericolosa. Un gigante comprende che la sua forza risiede nella sua capacità di cambiare rotta ed evolversi; non aggrapparti alle strutture di ieri, ma resta fluido e pronto a cogliere le opportunità che solo il movimento può rivelare.",
        quote_pt: "Aquele que constrói um muro torna-se prisioneiro dele. O sucesso pertence aos móveis, aos adaptáveis e aos implacáveis. Nunca pare de se mover.",
        meaning_pt: "Sobre a Disciplina da Adaptabilidade: A segurança é uma ilusão perigosa. Um gigante entende que a sua força reside na sua capacidade de girar e evoluir; não se apegue às estruturas de ontem, mas permaneça fluido e pronto para aproveitar as oportunidades que só o movimento pode revelar."
      },
      {
        quote_it: "Un sogno che sogni da solo è solo un sogno. Un sogno che sognate insieme è realtà. La visione condivisa è l'arma più potente al mondo.",
        meaning_it: "Sull'Architettura dell'Unità: La grandezza è un atto collettivo. Essere un gigante significa articolare un futuro così avvincente che gli altri sono disposti a offrire le loro vite e il loro lavoro per raggiungerlo; costruisci una tribù basata su uno scopo e non ci sarà ostacolo che non potrai superare.",
        quote_pt: "Um sonho que você sonha sozinho é apenas um sonho. Um sonho que vocês sonham juntos é a realidade. A visão compartilhada é a arma mais poderosa do mundo.",
        meaning_pt: "Sobre a Arquitetura da Unidade: A grandeza é um ato coletivo. Ser um gigante é articular um futuro tão convincente que os outros estejam dispostos a oferecer as suas vidas e o seu trabalho para o alcançar; construa uma tribo baseada em um propósito, e não há obstáculo que você não consiga superar."
      }
    ]
  },
  "alexander-the-great": {
    era_it: "Gigante del IV Secolo a.C. (356 a.C.~323 a.C.)",
    epic_it: "Nel 356 a.C., nella capitale macedone di Pella, nacque un bambino che avrebbe ridefinito i confini del mondo conosciuto. La giovinezza di Alessandro Magno fu un'educazione monumentale sotto la tutela di Aristotele, combinata con la disciplina marziale di suo padre, re Filippo II. Celebre è il suo aver domato lo stallone selvaggio Bucefalo, dimostrando fin da piccolo di possedere una volontà che avrebbe potuto piegare ai propri scopi anche le forze più ribelli. Spinto da una monumentale ambizione di superare le leggende di Achille ed Eracle, salì al trono a vent'anni e mise immediatamente gli occhi sul vasto e apparentemente invincibile Impero Persiano.\n\nIl più grande balzo di Alessandro fu l'invenzione di un nuovo tipo di guerra e una visione radicale di unità globale. Guidò il suo esercito oltre l'Ellesponto, sconfiggendo il re persiano Dario III in una serie di battaglie brillanti come Isso e Gaugamela. Il suo trionfo non fu solo militare; cercò di fondere le culture dell'Occidente e dell'Oriente in un'unica civiltà ellenistica. Costruì oltre settanta città chiamate Alessandria, che divennero monumenti allo scambio di conoscenze e commerci. Fu un gigante dell'integrazione, incoraggiando i suoi soldati a sposare donne locali e adottando usanze persiane per dimostrare che un sovrano deve appartenere a tutti i suoi sudditi, non solo alla sua stirpe.\n\nLa sua eredità raggiunse l'apice ai confini del mondo, nella valle dell'Indo, prima che il suo esercito esausto lo costringesse a tornare indietro. Morì a Babilonia all'età di trentatré anni, non avendo mai perso una battaglia ma alla fine soccombendo a un'improvvisa febbre. Lasciò il suo impero 'al più forte', scatenando una monumentale lotta che avrebbe plasmato la storia del Mediterraneo e dell'Asia per secoli. Si erse come un gigante che dimostrò che la giovinezza non è una barriera alla grandezza e che una singola vita, quando spinta da una visione titanica, può alterare fondamentalmente la traiettoria della civiltà umana.\n\nOggi, Alessandro Magno rimane l'archetipo supremo del conquistatore-filosofo. Insegnò all'umanità che 'non c'è nulla di impossibile per colui che ci proverà' e che il pericolo maggiore per un leader è la perdita di slancio. Dimostrò che l'impatto di un gigante si misura dalla permanenza delle idee che pianta, non solo dalle città che brucia. La sua vita fu una grande epopea di movimento e fusione, un promemoria che il mondo è un palcoscenico unico per coloro che osano attraversarne i confini. Continua a perseguitare l'immaginazione di ogni stratega e visionario, il suo nome un richiamo costante per raggiungere l'orizzonte.",
    trials_it: "L'affrontare la monumentale instabilità politica seguita all'assassinio di suo padre e la costante minaccia di rivolta delle città-stato greche. L'immenso sforzo fisico e psicologico di condurre una campagna decennale che ha attraversato migliaia di chilometri, culminando nella sua morte prematura a trentatré anni.",
    overcoming_it: "Superò i limiti del suo piccolo regno per creare il più grande impero del mondo antico attraverso puro genio tattico e carisma personale. Stabilì un'eredità culturale che collegava Oriente e Occidente, dimostrando che la visione di un gigante può unire popoli disparati sotto un unico ideale.",
    era_pt: "Gigante do Século IV a.C. (356 a.C.~323 a.C.)",
    epic_pt: "Em 356 a.C., na capital macedônia de Pella, nasceu um menino que redefiniria as fronteiras do mundo conhecido. A juventude de Alexandre, o Grande, foi uma educação monumental sob a tutela de Aristóteles, combinada com a disciplina marcial de seu pai, o rei Filipe II. Ele domou o garanhão selvagem Bucéfalo de forma famosa, provando logo cedo que possuía uma vontade que poderia curvar até mesmo as forças mais rebeldes ao seu propósito. Impulsionado por uma ambição monumental de superar as lendas de Aquiles e Hércules, ele ascendeu ao trono aos vinte anos e imediatamente voltou seus olhos para o vasto e aparentemente invencível Império Persa.\n\nO maior salto de Alexandre foi a invenção de um novo tipo de guerra e uma visão radical de unidade global. Ele liderou seu exército através do Helesponto, derrotando o rei persa Dario III em uma série de batalhas brilhantes como Isso e Gaugamela. Seu triunfo não foi apenas militar; ele procurou fundir as culturas do Ocidente e do Oriente em uma única civilização helenística. Ele construiu mais de setenta cidades chamadas Alexandria, que se tornaram monumentos de intercâmbio de conhecimento e comércio. Ele foi um gigante da integração, encorajando seus soldados a se casarem com mulheres locais e adotando costumes persas para provar que um governante deve pertencer a todos os seus súditos, não apenas aos seus parentes.\n\nSeu legado atingiu seu auge nos confins do mundo, no Vale do Indo, antes que seu exausto exército o forçasse a recuar. Ele morreu na Babilônia aos trinta e três anos, nunca tendo perdido uma batalha, mas no fim sucumbindo a uma febre repentina. Ele deixou seu império 'para o mais forte', desencadeando uma luta monumental que moldaria a história do Mediterrâneo e da Ásia durante séculos. Ele se destacou como um gigante que provou que a juventude não é barreira para a grandeza e que uma única vida, quando impulsionada por uma visão titânica, pode alterar fundamentalmente a trajetória da civilização humana.\n\nHoje, Alexandre, o Grande, continua sendo o arquétipo definitivo do conquistador-filósofo. Ele ensinou à humanidade que 'não há nada impossível para quem tentar' e que o maior perigo para um líder é a perda de impulso. Ele provou que o impacto de um gigante é medido pela permanência das ideias que ele planta, não apenas pelas cidades que ele queima. Sua vida foi um grandioso épico de movimento e fusão, um lembrete de que o mundo é um palco único para aqueles que ousam cruzar suas fronteiras. Ele continua a assombrar a imaginação de todo estrategista e visionário, e seu nome é um chamado constante para alcançar o horizonte.",
    trials_pt: "O enfrentamento da instabilidade política monumental após o assassinato de seu pai e a constante ameaça de revolta das cidades-estado gregas. O imenso esforço físico e psicológico de liderar uma campanha de uma década que se estendeu por milhares de quilômetros, culminando com a sua morte prematura aos trinta e três anos.",
    overcoming_pt: "Superou as limitações do seu pequeno reino para criar o maior império do mundo antigo, por meio de puro gênio tático e carisma pessoal. Estabeleceu um legado cultural que uniu o Oriente e o Ocidente, provando que a visão de um gigante pode unificar povos díspares sob um único ideal.",
    wisdom: [
      {
        quote_it: "Non c'è nulla di impossibile per colui che ci proverà. Il cielo non può tollerare due soli, né la terra due padroni. La fortuna favorisce gli audaci.",
        meaning_it: "Sulla Sovranità dell'Azione: L'impossibilità è un confine tracciato dai timidi. Un gigante capisce che l'unico modo per testare i limiti del possibile è andarvi oltre; agisci con una risoluzione così monumentale che la realtà non ha altra scelta se non riorganizzarsi attorno al tuo sforzo.",
        quote_pt: "Não há nada de impossível para quem tentar. O céu não pode tolerar dois sóis, nem a terra dois mestres. A sorte favorece os audazes.",
        meaning_pt: "Sobre a Soberania da Ação: A impossibilidade é uma fronteira traçada pelos tímidos. Um gigante entende que a única maneira de testar os limites do possível é ir além deles; atue com uma determinação tão monumental que a realidade não tenha escolha a não ser se reorganizar em torno do seu esforço."
      },
      {
        quote_it: "Non ho paura di un esercito di leoni guidato da una pecora; ho paura di un esercito di pecore guidato da un leone. Il carattere del leader è lo spirito dell'esercito.",
        meaning_it: "Sull'Alchimia della Leadership: Un gruppo è semplicemente il riflesso della sua guida. Essere un gigante significa fornire il fuoco che accende il potenziale di tutti intorno a te; il tuo coraggio personale è il catalizzatore che trasforma una folla frammentata in una forza monumentale di cambiamento.",
        quote_pt: "Não tenho medo de um exército de leões liderado por uma ovelha; tenho medo de um exército de ovelhas liderado por um leão. O caráter do líder é o espírito do exército.",
        meaning_pt: "Sobre a Alquimia da Liderança: Um grupo é apenas um reflexo da sua liderança. Ser um gigante é fornecer o fogo que acende o potencial de todos ao seu redor; a sua coragem pessoal é o catalisador que transforma uma multidão fragmentada numa força monumental de mudança."
      },
      {
        quote_it: "Sono in debito con mio padre per vivere, ma con il mio maestro per vivere bene. Ma ancor di più, sono in debito con la mia stessa ambizione per aver reso la mia vita una leggenda.",
        meaning_it: "Sulla Disciplina del Progresso: Il successo è un carburante, non una destinazione. Un gigante vede ogni vittoria come un accampamento temporaneo sulla via per la vetta; non lasciare mai che la soddisfazione di ciò che hai fatto ti accechi davanti al potenziale monumentale di ciò che devi ancora realizzare.",
        quote_pt: "Devo ao meu pai por viver, mas ao meu professor por viver bem. Mas ainda mais, devo à minha própria ambição por fazer da minha vida uma lenda.",
        meaning_pt: "Sobre a Disciplina do Progresso: O sucesso é um combustível, não um destino. Um gigante vê cada vitória como um acampamento temporário a caminho do cume; nunca deixe que a satisfação pelo que você realizou o cegue para o potencial monumental do que você ainda tem a realizar."
      }
    ]
  }
};

for (const id in translations) {
  if (data[id]) {
    const t = translations[id];
    data[id].era_it = t.era_it;
    data[id].epic_it = t.epic_it;
    data[id].trials_it = t.trials_it;
    data[id].overcoming_it = t.overcoming_it;
    
    data[id].era_pt = t.era_pt;
    data[id].epic_pt = t.epic_pt;
    data[id].trials_pt = t.trials_pt;
    data[id].overcoming_pt = t.overcoming_pt;
    
    for (let i = 0; i < t.wisdom.length; i++) {
      if (data[id].wisdom[i]) {
        data[id].wisdom[i].quote_it = t.wisdom[i].quote_it;
        data[id].wisdom[i].meaning_it = t.wisdom[i].meaning_it;
        data[id].wisdom[i].quote_pt = t.wisdom[i].quote_pt;
        data[id].wisdom[i].meaning_pt = t.wisdom[i].meaning_pt;
      }
    }
  }
}

fs.writeFileSync(dataFile, JSON.stringify(data, null, 2));
console.log('Done mapping Genghis Khan and Alexander the Great');
