import os
import json

tasks_dir = 'C:/Users/user/.gemini/antigravity/brain/45f5002d-398c-41ef-8740-cf257710e53c/scratch/pipeline/id/tasks/'
results_dir = 'C:/Users/user/.gemini/antigravity/brain/45f5002d-398c-41ef-8740-cf257710e53c/scratch/pipeline/id/results/'

json_str = r'''{
  "quotes-loneliness_para_000.json": "## Ujian Tak Terlihat: Kesendirian sebagai Katalis bagi Kejeniusan",
  "quotes-loneliness_para_001.json": "Dalam riuhnya dunia modern yang tak kenal lelah, di mana koneksi konstan sering dipuji sebagai kebajikan tertinggi, konsep kesendirian dapat terasa ketinggalan zaman, bahkan mengasingkan. Namun, sejarah dipenuhi dengan individu-individu yang kontribusi paling mendalamnya tidak muncul dari pasar ide yang ramai, melainkan dari ujian yang sunyi dan sering kali menantang dari pikiran mereka sendiri. Tokoh-tokoh ini, bukannya lumpuh karena isolasi, belajar untuk memanfaatkan energi uniknya, mengubah potensi kesepian menjadi kekuatan ampuh untuk kreativitas dan penemuan diri. Kehidupan mereka menawarkan narasi tandingan yang menarik untuk kecemasan kontemporer kita, menunjukkan bahwa periode introspeksi tidak hanya ditoleransi tetapi sering kali penting untuk pencapaian inovatif dan penanaman kehidupan batin yang kaya.",
  "quotes-loneliness_para_002.json": "### Nikola Tesla: Sang Visioner dalam Keterasingan",
  "quotes-loneliness_para_003.json": "Nikola Tesla, penemu keturunan Serbia-Amerika yang penuh teka-teki, berdiri sebagai tokoh inovasi yang menjulang tinggi, seorang pria yang pikirannya berderak dengan aliran listrik masa depan. Kehidupannya ditandai oleh dedikasi yang mendalam dan hampir seperti biarawan terhadap pekerjaannya, yang sering kali mengorbankan keterlibatan sosial. Tesla dikenal menghabiskan waktu bertahun-tahun tenggelam dalam penelitiannya, kadang-kadang dalam pengasingan yang hampir total, didorong oleh visi internal yang hanya sedikit orang yang dapat memahaminya. Sifat penyendirinya bukanlah gejala ketidakmampuan sosial, melainkan pilihan yang disengaja, kondisi yang diperlukan untuk konsentrasi intens yang dibutuhkan dalam bergulat dengan prinsip-prinsip ilmiah yang kompleks dan membayangkan teknologi yang akan mendefinisikan ulang dunia. Ia adalah seorang pria yang menemukan persahabatan dalam ide-idenya, dan yang laboratoriumnya menjadi tempat perlindungan di mana hal yang mustahil dapat dipahami.",
  "quotes-loneliness_para_004.json": "Wawasannya mengenai elektromagnetisme, sistem arus bolak-balik, dan banyak penemuan lainnya mengalir dari pikiran yang dibiarkan mengembara, merenung, dan bereksperimen tanpa gangguan terus-menerus dari tuntutan sosial. Meskipun ia mengalami periode kolaborasi dan pengakuan publik, terobosan-terobosannya yang paling revolusioner sering kali tumbuh di tanah subur dari kesendiriannya sendiri. Ini memungkinkannya untuk mengejar jalur-jalur yang tidak konvensional, untuk memercayai intuisinya, dan untuk bertahan melalui kegagalan-kegagalan yang mungkin akan menghalangi individu yang lebih berorientasi sosial. Volume dan keberanian dari penemuan-penemuannya merupakan bukti nyata dari kekuatan pemikiran yang terfokus dan mandiri.",
  "quotes-loneliness_para_005.json": "### Friedrich Nietzsche: Sang Filsuf Jurang Maut",
  "quotes-loneliness_para_006.json": "Friedrich Nietzsche, filsuf Jerman yang bersinar terang, bergulat dengan pertanyaan-pertanyaan mendalam tentang keberadaan, moralitas, dan kondisi manusia. Perjalanan filosofisnya sangat pribadi, sering kali dilakukan dalam isolasi fisik dan intelektual. Nietzsche berusaha membongkar nilai-nilai konvensional dan menempa nilai-nilai baru, sebuah tugas yang menuntut introspeksi besar-besaran dan kesediaan untuk menghadapi kebenaran-kebenaran yang tidak nyaman tentang umat manusia dan dirinya sendiri. Masa-masa pengembaraannya melalui Pegunungan Alpen, atau tinggal di sudut-sudut terpencil Eropa, bukanlah sekadar pelarian melainkan tindakan pengasingan diri yang disengaja, menciptakan jarak yang diperlukan dari norma-norma sosial untuk berpikir dengan kejelasan dan orisinalitas yang tak tertandingi.",
  "quotes-loneliness_para_007.json": "Konsep Nietzsche tentang *Übermensch* (Manusia Unggul) dan kritiknya terhadap mentalitas kawanan menggarisbawahi keyakinannya pada kekuatan individu untuk melampaui batasan. Ia memahami bahwa penaklukan diri yang sejati, proses menjadi siapa diri seseorang yang sebenarnya, membutuhkan penarikan diri dari hiruk pikuk opini publik. Wawasan mendalamnya mengenai kehendak untuk berkuasa dan perulangan abadi lahir dari sumur-sumur dalam perenungannya yang menyendiri. Ia dengan terkenal menulis:",
  "quotes-loneliness_para_008.json": "> \"Dia yang memiliki alasan mengapa ia harus hidup, hampir bisa menanggung dengan cara apa pun ia harus menjalaninya.\"",
  "quotes-loneliness_para_009.json": "Kutipan ini, lebih dari sekadar pernyataan ketangguhan, berbicara mengenai kompas internal yang dapat dibantu temukan oleh kesendirian. Bagi Nietzsche, 'alasan mengapa' tidak ditemukan dalam validasi eksternal melainkan dalam penerimaan yang berani akan kebebasan eksistensialnya sendiri dan penciptaan makna pribadi di alam semesta yang tak bertuhan. Filosofinya adalah sebuah undangan untuk merangkul tantangan eksistensi bukan sebagai beban, melainkan sebagai kesempatan untuk pertumbuhan yang mendalam, sebuah proses yang paling baik dilakukan dengan suara batin yang jernih dan tak berkabut.",
  "quotes-loneliness_para_010.json": "### Vincent van Gogh: Seniman Perasaan Intens",
  "quotes-loneliness_para_011.json": "Vincent van Gogh, pelukis Pasca-Impresionis Belanda, mungkin adalah salah satu contoh paling mengharukan dalam sejarah tentang seorang seniman yang kehidupan emosionalnya yang intens dan hasil kreatifnya yang mendalam terkait erat dengan periode kesendirian dan pergulatan yang mendalam. Meskipun ia mendambakan koneksi dan mengalami momen-momen persahabatan, karya-karyanya yang paling ikonik, yang berdenyut dengan warna cerah dan emosi mentah, sering kali diciptakan selama masa-masa isolasi yang mendalam. Kepindahannya ke Arles di Prancis Selatan, mencari cahaya dan warna yang intens dari wilayah tersebut, adalah upaya untuk menemukan surga kreatif, tempat di mana ia dapat mendedikasikan dirinya sepenuhnya untuk seninya, jauh dari gangguan dan penilaian dunia seni Paris.",
  "quotes-loneliness_para_012.json": "Surat-suratnya kepada saudaranya Theo mengungkapkan seorang pria yang bergulat dengan kesepian, penderitaan mental, dan kesulitan keuangan, namun tanpa henti didorong oleh keinginan tak terpuaskan untuk melukis. Ia melihat seninya sebagai cara untuk mengomunikasikan perasaan dan persepsinya yang terdalam tentang dunia, suatu bentuk ekspresi yang melampaui batasan bahasa verbal. Dedikasinya mutlak, sering kali bekerja dari fajar hingga senja, sepenuhnya terserap dalam kanvas-kanvasnya. Intensitas visinya, cara ia menangkap esensi cahaya dan kehidupan dalam sapuan kuasnya, menunjukkan seorang seniman yang telah belajar untuk menarik dari reservoir perasaan yang sangat besar di dalam dirinya, sebuah reservoir yang sering kali terisi kembali di keheningan studionya atau di tengah-tengah pemandangan sunyi yang ia gambarkan.",
  "quotes-loneliness_para_013.json": "Kehidupan Van Gogh, meskipun tragisnya singkat dan ditandai oleh penderitaan besar, berfungsi sebagai bukti kuat akan potensi transformatif dari dedikasi kreatif. Ia mencurahkan seluruh keberadaannya ke dalam seninya, menemukan penghiburan dan tujuan dalam tindakan penciptaan, bahkan ketika keadaan eksternal sedang suram. Ia menulis:",
  "quotes-loneliness_para_014.json": "> \"Saya memimpikan lukisan saya, lalu saya melukiskan impian saya.\"",
  "quotes-loneliness_para_015.json": "Pernyataan sederhana namun mendalam ini merangkum dunia batin sang seniman, sebuah ruang di mana inspirasi dipelihara dan kemudian diwujudkan ke dalam bentuk nyata. Pengejarannya yang menyendiri akan kebenaran artistik, komitmennya yang tak tergoyahkan pada visinya, terus bergaung dengan para seniman maupun pecinta seni, mengingatkan kita bahwa ekspresi yang paling otentik sering kali muncul dari mata air keberadaan yang terdalam dan paling pribadi.",
  "quotes-loneliness_para_016.json": "## Menerapkan Pelajaran Mereka pada Kehidupan Modern",
  "quotes-loneliness_para_017.json": "Dalam masyarakat kita yang sangat terhubung dan selalu aktif, pelajaran dari Tesla, Nietzsche, dan Van Gogh menjadi lebih relevan daripada sebelumnya. Tekanan untuk terus-menerus tampil, berjejaring, dan menyajikan versi diri kita yang telah dikuratori dapat mengarah pada rasa kelelahan yang menyebar luas dan terputusnya hubungan dari diri kita yang otentik. Mengakui nilai kesendirian yang kreatif tidak berarti menganjurkan penarikan diri sepenuhnya, melainkan untuk periode-periode yang disengaja dari introspeksi terfokus dan keterlibatan kreatif.",
  "quotes-loneliness_para_018.json": "Bagi mereka yang menavigasi tekanan pekerjaan, transisi karier, atau pencarian makna, tokoh-tokoh sejarah ini menawarkan kerangka kerja yang kuat. Sama seperti Tesla mundur ke laboratoriumnya untuk menyempurnakan penemuannya, kita dapat meluangkan waktu khusus untuk pekerjaan yang mendalam, bebas dari gangguan digital. Hal ini mungkin melibatkan penyisihan jam-jam tertentu untuk tugas-tugas terfokus, terlibat dalam praktik-praktik mindfulness, atau sekadar membiarkan pikiran kita mengembara tanpa tujuan langsung. Tindakan 'mencabut kabel' yang disengaja ini dapat mengarah pada wawasan tak terduga dan kreativitas yang diperbarui, seperti halnya tombol reset mental.",
  "quotes-loneliness_para_019.json": "Penekanan Nietzsche pada menemukan 'alasan mengapa' seseorang mendorong kita untuk melihat ke dalam diri guna mencari motivasi dan nilai inti kita, alih-alih semata-mata mencari validasi eksternal. Dalam pencarian karier, ini berarti menyelaraskan jalur profesional kita dengan minat terdalam dan prinsip-prinsip etis kita, bahkan jika itu berarti mengambil rute yang kurang konvensional. Introspeksi ini dapat ditumbuhkan melalui penjurnalan, penyelidikan filosofis, atau berinteraksi dengan seni dan sastra yang menantang perspektif kita. Pengejaran akan makna, sebagaimana dipahami oleh Nietzsche, adalah proses yang aktif dan diarahkan oleh diri sendiri.",
  "quotes-loneliness_para_020.json": "Dedikasi Van Gogh yang tak kenal lelah pada visi artistiknya, bahkan dalam menghadapi kesulitan, mengingatkan kita akan kekuatan gairah dan ketekunan. Saat dihadapkan pada tugas yang menakutkan dalam membangun karier atau mencapai tujuan yang signifikan, sangat penting untuk menumbuhkan dorongan batin yang tidak semata-mata bergantung pada hasil langsung atau persetujuan eksternal. Ini melibatkan merangkul prosesnya, menemukan kegembiraan dalam tindakan penciptaan atau pemecahan masalah, dan belajar untuk menarik kekuatan dari sumber daya internal kita sendiri. Dengan merangkul periode kesendirian yang kreatif, kita dapat mengubah apa yang mungkin terasa seperti kesepian menjadi sumber energi, kejernihan, dan kepuasan pribadi yang mendalam yang ampuh, yang memungkinkan kita untuk menghadapi kompleksitas kehidupan modern dengan ketahanan dan tujuan yang lebih besar.",
  "quotes-loneliness_title.json": "Merangkul Kesendirian Kreatif: Mengubah Kesepian Menjadi Energi"
}'''

T = json.loads(json_str)

for filename, text in T.items():
    in_path = os.path.join(tasks_dir, filename)
    out_path = os.path.join(results_dir, filename)
    with open(in_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    out_data = {
        'slug': data['slug'],
        'type': data['type']
    }
    if 'index' in data:
        out_data['index'] = data['index']
    out_data['id_text'] = text
    
    with open(out_path, 'w', encoding='utf-8') as f:
        json.dump(out_data, f, ensure_ascii=False, indent=2)

print('Done quotes-loneliness')
