import { GoogleGenAI } from '@google/genai';
import dotenv from 'dotenv';
import path from 'path';
import fs from 'fs';
import { giantsData } from '../src/data/giants';

dotenv.config({ path: '.env.local' });

// Ensure service account credentials are used
process.env.GOOGLE_APPLICATION_CREDENTIALS = path.resolve(process.cwd(), "google-service-account.json");
delete process.env.GEMINI_API_KEY;
delete process.env.NEXT_PUBLIC_GEMINI_API_KEY;

process.env.GOOGLE_CLOUD_PROJECT = 'giantswisdom-8dc26';
process.env.GOOGLE_CLOUD_LOCATION = 'us-central1';

const ai = new GoogleGenAI({
  vertexai: {
    project: 'giantswisdom-8dc26',
    location: 'us-central1'
  }
});

async function run() {
  console.log(`Loaded ${giantsData.length} giants from database.`);
  
  const prompt = `
You are a historical data classifier. Classify each of the following historical giants (with name and slug) into one of the following 6 region keys based on their historical area of activity, birth, or influence:
1. 'east-asia' (Korea, China, Japan, Mongolia, etc.)
2. 'europe' (UK, France, Germany, Italy, Russia, Greece, Rome, etc.)
3. 'americas' (North and South America, e.g., US, Mexico, Colombia, etc.)
4. 'middle-east-turkey' (Turkey, Egypt, Iraq, Iran, Saudi Arabia, Syria, ancient Persia, Ottoman, Byzantine, etc.)
5. 'africa' (Sub-Saharan Africa, e.g., Mali, Zaire, Carthage, Ethiopia, etc. Note: exclude Egypt if it aligns better with middle-east-turkey, but put it in middle-east-turkey or africa consistently. Let's place Egypt/Cleopatra under 'middle-east-turkey' or 'africa'. Please place general sub-Saharan/North African historical kingdoms under 'africa', and Egypt/Mesopotamia/Ottoman/Persia under 'middle-east-turkey').
6. 'south-southeast-asia' (India, Vietnam, Thailand, Indonesia, etc.)

Return the output strictly as a valid JSON object mapping the giant's slug to one of the 6 string region values above. Do not include markdown code block formatting or any explanation, just the raw JSON.

Here is the list of giants:
${JSON.stringify(giantsData.map(g => ({ name: g.name, slug: g.slug })), null, 2)}
`;

  try {
    console.log("Calling Vertex AI for classification...");
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      generationConfig: {
        responseMimeType: 'application/json'
      }
    });

    let text = response.text?.trim() || "{}";
    if (text.startsWith("```")) {
      text = text.replace(/^```[a-zA-Z]*\n/, "").replace(/\n```$/, "").trim();
    }
    const mapping = JSON.parse(text);
    console.log(`Successfully classified ${Object.keys(mapping).length} giants.`);

    // Verify all giants are mapped
    const missing = giantsData.filter(g => !mapping[g.slug]);
    if (missing.length > 0) {
      console.warn(`Warning: ${missing.length} giants were not classified:`, missing.map(m => m.slug));
      // Default missing ones to europe
      missing.forEach(m => {
        mapping[m.slug] = 'europe';
      });
    }

    const outputFileContent = `// Automatically generated by scripts/classify-existing-regions.ts
export const regionsMap: Record<string, 'east-asia' | 'europe' | 'americas' | 'middle-east-turkey' | 'africa' | 'south-southeast-asia'> = ${JSON.stringify(mapping, null, 2)};
`;

    const outputPath = path.resolve(process.cwd(), 'src/data/regions-map.ts');
    fs.writeFileSync(outputPath, outputFileContent, 'utf-8');
    console.log(`Saved regions map to ${outputPath}`);
  } catch (err: any) {
    console.error("Classification failed:", err.message || err);
    process.exit(1);
  }
}

run();
