module.exports = [
  // BATCH 1: 동양 위인 15명
  { slug: 'king-jeongjo', name: 'King Jeongjo', category: '성취', birth: 1752, death: 1800, nationality: 'Korean', keyword: '조선의 르네상스 개혁군주' },
  { slug: 'jeong-yak-yong', name: 'Jeong Yak-yong (Dasan)', category: '지혜', birth: 1762, death: 1836, nationality: 'Korean', keyword: '실학의 거두, 목민심서' },
  { slug: 'ahn-jung-geun', name: 'Ahn Jung-geun', category: '성취', birth: 1879, death: 1910, nationality: 'Korean', keyword: '대의와 결단, 동양평화론' },
  { slug: 'mencius', name: 'Mencius', category: '지혜', birth: -372, death: -289, nationality: 'Chinese', keyword: '왕도정치, 대장부의 길' },
  { slug: 'zhuangzi', name: 'Zhuangzi', category: '지혜', birth: -369, death: -286, nationality: 'Chinese', keyword: '자유와 비워냄의 철학' },
  { slug: 'sima-qian', name: 'Sima Qian', category: '역경', birth: -145, death: -86, nationality: 'Chinese', keyword: '불굴의 의지로 역사를 기록' },
  { slug: 'empress-wu-zetian', name: 'Empress Wu Zetian', category: '성취', birth: 624, death: 705, nationality: 'Chinese', keyword: '중국 역사상 유일한 여황제' },
  { slug: 'zhuge-liang', name: 'Zhuge Liang', category: '성취', birth: 181, death: 234, nationality: 'Chinese', keyword: '삼국지 최고의 전략가' },
  { slug: 'li-bai', name: 'Li Bai', category: '창의', birth: 701, death: 762, nationality: 'Chinese', keyword: '낭만과 자유의 시선, 시선(詩仙)' },
  { slug: 'sun-yat-sen', name: 'Sun Yat-sen', category: '성취', birth: 1866, death: 1925, nationality: 'Chinese', keyword: '중국 근대화의 아버지' },
  { slug: 'tokugawa-ieyasu', name: 'Tokugawa Ieyasu', category: '성취', birth: 1543, death: 1616, nationality: 'Japanese', keyword: '인내와 최후의 승리' },
  { slug: 'miyamoto-musashi', name: 'Miyamoto Musashi', category: '지혜', birth: 1584, death: 1645, nationality: 'Japanese', keyword: '오륜서, 승부와 실전의 철학' },
  { slug: 'oda-nobunaga', name: 'Oda Nobunaga', category: '성취', birth: 1534, death: 1582, nationality: 'Japanese', keyword: '파격과 혁신의 풍운아' },
  { slug: 'toyotomi-hideyoshi', name: 'Toyotomi Hideyoshi', category: '성취', birth: 1537, death: 1598, nationality: 'Japanese', keyword: '최하층에서 천하통일' },

  // BATCH 2: 유럽 위인 15명
  { slug: 'voltaire', name: 'Voltaire', category: '지혜', birth: 1694, death: 1778, nationality: 'French', keyword: '날카로운 이성과 비판' },
  { slug: 'dante-alighieri', name: 'Dante Alighieri', category: '창의', birth: 1265, death: 1321, nationality: 'Italian', keyword: '신곡, 인간 내면의 탐구' },
  { slug: 'archimedes', name: 'Archimedes', category: '창의', birth: -287, death: -212, nationality: 'Greek', keyword: '유레카! 몰입과 발상의 전환' },
  { slug: 'copernicus', name: 'Nicolaus Copernicus', category: '창의', birth: 1473, death: 1543, nationality: 'Polish', keyword: '패러다임을 뒤집는 용기' },
  { slug: 'machiavelli', name: 'Niccolò Machiavelli', category: '지혜', birth: 1469, death: 1527, nationality: 'Italian', keyword: '현실주의와 권력의 본질' },
  { slug: 'adam-smith', name: 'Adam Smith', category: '지혜', birth: 1723, death: 1790, nationality: 'Scottish', keyword: '국부론, 경제의 본질' },
  { slug: 'louis-pasteur', name: 'Louis Pasteur', category: '성취', birth: 1822, death: 1895, nationality: 'French', keyword: '집요한 관찰로 인류를 구한 과학' },
  { slug: 'johannes-gutenberg', name: 'Johannes Gutenberg', category: '창의', birth: 1400, death: 1468, nationality: 'German', keyword: '인쇄술, 정보혁명의 시초' },
  { slug: 'queen-victoria', name: 'Queen Victoria', category: '성취', birth: 1819, death: 1901, nationality: 'British', keyword: '대영제국 전성기의 아이콘' },
  { slug: 'alexander-fleming', name: 'Alexander Fleming', category: '성취', birth: 1881, death: 1955, nationality: 'Scottish', keyword: '페니실린, 우연을 기회로' },
  { slug: 'johannes-kepler', name: 'Johannes Kepler', category: '창의', birth: 1571, death: 1630, nationality: 'German', keyword: '행성운동법칙, 천문학 혁명' },
  { slug: 'francis-bacon', name: 'Francis Bacon', category: '지혜', birth: 1561, death: 1626, nationality: 'British', keyword: '아는 것이 힘이다, 과학적 방법론' },

  // BATCH 3: 미국 위인 25명
  { slug: 'benjamin-franklin', name: 'Benjamin Franklin', category: '지혜', birth: 1706, death: 1790, nationality: 'American', keyword: '실용주의와 시간관리의 끝판왕' },
  { slug: 'thomas-jefferson', name: 'Thomas Jefferson', category: '성취', birth: 1743, death: 1826, nationality: 'American', keyword: '독립선언서, 자유의 설계자' },
  { slug: 'alexander-hamilton', name: 'Alexander Hamilton', category: '성취', birth: 1755, death: 1804, nationality: 'American', keyword: '금융시스템 설계, 뮤지컬로 부활' },
  { slug: 'john-f-kennedy', name: 'John F. Kennedy', category: '성취', birth: 1917, death: 1963, nationality: 'American', keyword: '달 정복 선언, 비전의 아이콘' },
  { slug: 'susan-b-anthony', name: 'Susan B. Anthony', category: '성취', birth: 1820, death: 1906, nationality: 'American', keyword: '여성 참정권 운동의 선구자' },
  { slug: 'edgar-allan-poe', name: 'Edgar Allan Poe', category: '창의', birth: 1809, death: 1849, nationality: 'American', keyword: '추리·공포문학의 개척자' },
  { slug: 'henry-david-thoreau', name: 'Henry David Thoreau', category: '지혜', birth: 1817, death: 1862, nationality: 'American', keyword: '월든, 본질에 집중하는 삶' },
  { slug: 'ralph-waldo-emerson', name: 'Ralph Waldo Emerson', category: '지혜', birth: 1803, death: 1882, nationality: 'American', keyword: '자기신뢰(Self-Reliance)' },
  { slug: 'walt-whitman', name: 'Walt Whitman', category: '창의', birth: 1819, death: 1892, nationality: 'American', keyword: '풀잎, 미국 자유정신의 시인' },
  { slug: 'ernest-hemingway', name: 'Ernest Hemingway', category: '창의', birth: 1899, death: 1961, nationality: 'American', keyword: '노인과 바다, 빙산의 일각 문체' },
  { slug: 'andrew-carnegie', name: 'Andrew Carnegie', category: '성취', birth: 1835, death: 1919, nationality: 'American', keyword: '철강왕, 부의 사회환원 철학' },
  { slug: 'alexander-graham-bell', name: 'Alexander Graham Bell', category: '창의', birth: 1847, death: 1922, nationality: 'American', keyword: '전화기 발명, 소통의 혁명' },
  { slug: 'jp-morgan', name: 'J.P. Morgan', category: '성취', birth: 1837, death: 1913, nationality: 'American', keyword: '금융제국, 월가의 거물' },
  { slug: 'amelia-earhart', name: 'Amelia Earhart', category: '성취', birth: 1897, death: 1937, nationality: 'American', keyword: '여성 최초 대서양 단독비행' },
  { slug: 'wright-brothers', name: 'Wright Brothers', category: '창의', birth: 1867, death: 1948, nationality: 'American', keyword: '인류 최초 비행기' },
  { slug: 'robert-oppenheimer', name: 'Robert Oppenheimer', category: '성취', birth: 1904, death: 1967, nationality: 'American', keyword: '원자폭탄의 아버지' },

  // BATCH 4: 인도/중동/동남아/아프리카 15명
  { slug: 'ashoka-the-great', name: 'Ashoka the Great', category: '성취', birth: -304, death: -232, nationality: 'Indian', keyword: '불교 전파, 비폭력 통치의 이상' },
  { slug: 'chandragupta-maurya', name: 'Chandragupta Maurya', category: '성취', birth: -340, death: -297, nationality: 'Indian', keyword: '인도 최초 통일 제국 건설자' },
  { slug: 'swami-vivekananda', name: 'Swami Vivekananda', category: '지혜', birth: 1863, death: 1902, nationality: 'Indian', keyword: '힌두 철학을 서양에 전파' },
  { slug: 'srinivasa-ramanujan', name: 'Srinivasa Ramanujan', category: '창의', birth: 1887, death: 1920, nationality: 'Indian', keyword: '독학으로 수학사를 바꾼 천재' },
  { slug: 'br-ambedkar', name: 'B.R. Ambedkar', category: '성취', birth: 1891, death: 1956, nationality: 'Indian', keyword: '인도 헌법의 아버지, 반카스트' },
  { slug: 'saladin', name: 'Saladin', category: '성취', birth: 1137, death: 1193, nationality: 'Kurdish-Syrian', keyword: '예루살렘 탈환, 기사도의 표본' },
  { slug: 'suleiman-the-magnificent', name: 'Suleiman the Magnificent', category: '성취', birth: 1494, death: 1566, nationality: 'Ottoman', keyword: '오스만 제국 최전성기 군주' },
  { slug: 'al-khwarizmi', name: 'Al-Khwarizmi', category: '창의', birth: 780, death: 850, nationality: 'Persian', keyword: '대수학의 아버지, Algorithm의 기원' },
  { slug: 'omar-khayyam', name: 'Omar Khayyam', category: '지혜', birth: 1048, death: 1131, nationality: 'Persian', keyword: '수학자이자 시인, 루바이야트' },
  { slug: 'ibn-battuta', name: 'Ibn Battuta', category: '성취', birth: 1304, death: 1368, nationality: 'Moroccan', keyword: '중세 최고의 여행가 (117,000km)' },
  { slug: 'chulalongkorn', name: 'King Chulalongkorn', category: '성취', birth: 1853, death: 1910, nationality: 'Thai', keyword: '태국 근대화, 노예제 폐지' },
  { slug: 'jayavarman-vii', name: 'Jayavarman VII', category: '성취', birth: 1122, death: 1218, nationality: 'Khmer', keyword: '앙코르 톰 건설, 크메르 전성기' },
  { slug: 'mansa-musa', name: 'Mansa Musa', category: '성취', birth: 1280, death: 1337, nationality: 'Malian', keyword: '역사상 가장 부유한 인물' },
  { slug: 'shaka-zulu', name: 'Shaka Zulu', category: '성취', birth: 1787, death: 1828, nationality: 'Zulu', keyword: '줄루 왕국, 군사혁신의 천재' },
  { slug: 'hannibal-barca', name: 'Hannibal Barca', category: '성취', birth: -247, death: -183, nationality: 'Carthaginian', keyword: '알프스를 넘은 전략의 천재' }
];
