import json

out1 = {
  "charles-darwin": {
    "slug": "charles-darwin",
    "timeline": [
      { "year": "12 ga Fabrairu, 1809", "event": "An haife shi a Shrewsbury, Birtaniya." },
      { "year": "1817 - 1825", "event": "Ya sami ilimin firamare da sakandare." },
      { "year": "1818", "event": "Ya fara karatu a Makarantar Shrewsbury." },
      { "year": "1825", "event": "Ya fara karatun likitanci a Jami'ar Edinburgh." },
      { "year": "1827", "event": "Ya bar Jami'ar Edinburgh ya shiga sashen ilimin addini a Jami'ar Cambridge." },
      { "year": "1831", "event": "Ya kammala karatu a Jami'ar Cambridge da kyakkyawan sakamako, kuma ya hau jirgin Beagle a ranar 27 ga Disamba." },
      { "year": "10 ga Fabrairu, 1836", "event": "Ya kammala tafiyar bincike na jirgin Beagle." },
      { "year": "2 ga Oktoba, 1836", "event": "Jirgin Beagle ya isa Falmouth a Cornwall." },
      { "year": "4 ga Janairu, 1837", "event": "An rarraba takardarsa ta farko game da tasowar nahiyar Amurka ta Kudu a Kungiyar Nazarin Kasa ta London, kuma ya gabatar da samfuran dabbobi masu shayarwa da tsuntsaye ga Kungiyar Nazarin Dabbobi." },
      { "year": "17 ga Fabrairu, 1837", "event": "An zabe shi a matsayin memba na majalisar Kungiyar Nazarin Kasa." },
      { "year": "Farkon Maris 1837", "event": "Ya koma London don shiga kungiyar kimiyya ta Lyell." },
      { "year": "Tsakiyar Maris 1837", "event": "Ya yi tunani game da 'yuwuwar wata halitta ta rikida zuwa wata' a cikin littafinsa na rubutu ja." },
      { "year": "1838", "event": "An zabe shi a matsayin sakataren Kungiyar Nazarin Kasa." },
      { "year": "Janairu 1839", "event": "Ya auri Emma Wedgwood, kuma ya wallafa \"Tafiyar Jirgin Beagle\"." },
      { "year": "1842", "event": "Ya zauna a wajen birnin London, yana tattarawa da tsara bayanai game da juyin halitta." },
      { "year": "1842", "event": "Ya wallafa littafinsa na farko akan halittu, \"Rarrabuwa da Tsarin Murjani\"." },
      { "year": "Yuni 1842", "event": "Ya rubuta da fensir daftarin shafuka 35 na ka'idar juyin halitta ta hanyar zabi na halitta." },
      { "year": "1844", "event": "Ya wallafa \"Lura da Yanayin Kasa na Tsibirin Duwatsu masu Aman Wuta\"." },
      { "year": "1846", "event": "Ya wallafa \"Lura da Yanayin Kasa na Amurka ta Kudu\" dangane da bayanan binciken jirgin Beagle." },
      { "year": "1856", "event": "Ya fara rubuta ka'idar juyin halitta." },
      { "year": "1858", "event": "Ya gabatar da ka'idarsa tare da takardar Alfred Wallace a taron Kungiyar Linnean." },
      { "year": "1859", "event": "Ya wallafa \"Asalin Halittu\", wanda ya tabbatar da gaskiyar juyin halitta da 'zabi na halitta'." },
      { "year": "1871", "event": "Ya wallafa \"Asalin Dan Adam\", wanda ya tattauna juyin halittar dan adam." },
      { "year": "1872", "event": "Ya wallafa \"Bayyanar Zuciya a Mutane da Dabbobi\"." },
      { "year": "1881", "event": "Ya wallafa \"Ayyukan Tsutsa da Samuwar Kasa\"." },
      { "year": "19 ga Afrilu, 1882", "event": "Ya rasu yana da shekaru 73, an binne shi a Westminster Abbey." }
    ],
    "keyAchievements": [
      { "title": "Babban gudummawa ga ka'idar juyin halitta", "description": "A matsayinsa na masanin kimiyyar halittu kuma masanin ilimin kasa na Birtaniya, ya bayar da babbar gudummawa ga ka'idar juyin halitta." },
      { "title": "Gabatar da ka'idar zabi na halitta", "description": "A cikin takardar hadin gwiwa da Alfred Wallace, ya gabatar da zabi na halitta wanda ke faruwa ta hanyar gasa don tsira." },
      { "title": "Rubuta \"Asalin Halittu\" da gabatar da ka'idar juyin halitta", "description": "A shekarar 1859, ya rubuta \"Asalin Halittu\", yana gabatar da ka'idar juyin halitta da tabbataccen shaida." },
      { "title": "Bayar da ka'idar dunkulewar kimiyyar rayuwa", "description": "Binciken kimiyyar Darwin yana bayanin bambancin rayuwa a matsayin dunkulewar ka'idar kimiyyar rayuwa." },
      { "title": "Kalubale ga ka'idar halitta", "description": "Ta hanyar gabatar da ka'idar juyin halitta a cikin \"Asalin Halittu\", ya kifar da ka'idar halitta da ke da karfi a wancan lokacin sannan ya bude sabon zamani." },
      { "title": "Tabbatar da juyin halitta ta hanyar tafiyar jirgin Beagle", "description": "Ta hanyar binciken Beagle, ya lura da yanayin kasa, tsirrai, da dabbobi dalla-dalla, kuma ya tabbatar da juyin halitta." },
      { "title": "Wallafa manyan littattafai", "description": "Ya bar littattafan ilimi da yawa, ciki har da \"Rarrabuwa da Tsarin Murjani\" (1842), \"Lura da Yanayin Kasa na Tsibirin Duwatsu masu Aman Wuta\" (1844), \"Lura da Yanayin Kasa na Amurka ta Kudu\" (1846), da \"Asalin Dan Adam\" (1871)." }
    ],
    "faq": [
      { "question": "Yaushe aka haifi Charles Darwin kuma yaushe ya rasu?", "answer": "An haifi Charles Darwin a ranar 12 ga Fabrairu, 1809, kuma ya rasu a ranar 19 ga Afrilu, 1882." },
      { "question": "Menene mafi mahimmancin nasarar Charles Darwin?", "answer": "Charles Darwin ya ba da babbar gudummawa ga ka'idar juyin halitta, kuma ya wallafa \"Asalin Halittu\" a shekarar 1859 don kafa zabi na halitta." },
      { "question": "Wane matsayi Charles Darwin ya dauka game da bauta?", "answer": "Charles Darwin ya yi adawa da bauta saboda ya fusata da tsarin bautar bakar fata na farar fata yayin tafiyarsa zuwa Amurka ta Kudu." },
      { "question": "Menene manufar hawaw Charles Darwin a jirgin Beagle?", "answer": "Da farko ya hau a matsayin dan kasa bisa bukatar kyaftin din don samun cudanya da masu ilimi, amma daga baya an san shi da kwarewar kimiyyar yanayi wanda yasa yayi aiki a matsayin masanin kimiyyar yanayi." },
      { "question": "Shin jita-jitar cewa Charles Darwin ya canza addininsa a karshen rayuwarsa gaskiya ne?", "answer": "Jita-jitar cewa Darwin ya amince da ka'idar halitta ta Littafi Mai Tsarki na Ibrananci a matsayin gaskiya kuma ya dawo da imaninsa ga Yesu Almasihu kafin mutuwarsa ba gaskiya ba ne." }
    ],
    "sourceVerified": True,
    "missingDataNote": ""
  },
  "michelangelo": {
    "slug": "michelangelo",
    "timeline": [
      { "year": "1475", "event": "An haifi Michelangelo di Lodovico Buonarroti Simoni." },
      { "year": "1488", "event": "Ya shiga bitar Domenico Ghirlandaio a matsayin mai koyan aiki." },
      { "year": "1499", "event": "Ya kammala \"Pieta\" bisa bukatar Kadanal Jean de Bilhères dan Faransa." },
      { "year": "1501", "event": "Ya fara sassaka \"Dawuda\" bisa umarnin zauren birnin Florence." },
      { "year": "1505", "event": "Ya koma Roma bisa gayyatar Paparoma Julius II kuma aka ba shi alhakin gina kabarin Paparoma." },
      { "year": "1508", "event": "Ya fara aikin zanen rufin dakin ibada na Sistine na fadar Manzanni a Vatican bisa umarni." },
      { "year": "1512", "event": "Ya kammala zanen rufin dakin ibada na Sistine." },
      { "year": "1534", "event": "Ya bar Florence har abada kuma ya zauna a Roma." },
      { "year": "1535", "event": "Paparoma Bulus na III ya ba shi aikin zanen bangon gaba \"Hukuncin Karshe\" a dakin ibada na Sistine." },
      { "year": "1541", "event": "Ya kammala \"Hukuncin Karshe\"." },
      { "year": "1545", "event": "Ya kammala siffar \"Musa\" a kabarin Julius II." },
      { "year": "1549", "event": "Ya kammala zanen bango \"Tuben Bulus\" a dakin ibada na Pauline a Vatican." },
      { "year": "1550", "event": "Ya kammala zanen bango \"Gicciyen Bitrus\" a dakin ibada na Pauline a Vatican." },
      { "year": "1564", "event": "Ya rasu a Roma yana da shekaru 89." }
    ],
    "keyAchievements": [
      { "title": "Pieta", "description": "An kammala shi a shekarar 1499 a Roma bisa bukatar Kadanal Jean de Bilhères na Faransa, kuma yana daya daga cikin fitattun ayyukan sassaka na zamanin Renaissance." },
      { "title": "Dawuda", "description": "Siffar yaron nan Dawuda ce da aka kammala cikin shekaru uku daga 1501 bisa umarnin zauren birnin Florence." },
      { "title": "Zanen rufin dakin ibada na Sistine", "description": "Zanen rufi ne na fadar Manzanni ta Vatican wanda aka kammala cikin shekaru hudu daga 1508 bisa umarnin Paparoma Julius II, kuma yana nuna mafi yawan koyaswar Katolika, ciki har da Halitta." },
      { "title": "Hukuncin Karshe", "description": "Babban zanen bango ne na gaba a dakin ibada na Sistine da aka kammala cikin shekaru shida daga 1535 bisa umarnin Paparoma Bulus III." },
      { "title": "Kabarin Julius II", "description": "Wani abin tunawa ne na jana'iza da aka kammala cikin shekaru 40 bayan an ba shi aikin gina kabarin Paparoma Julius II a shekarar 1505, kuma siffar \"Musa\" ce mafi shahara." }
    ],
    "faq": [
      { "question": "Michelangelo ya kasance mai fasaha a wane fanni?", "answer": "Ya kasance mai sassaka dan kasar Italiya, mai zane, masanin zane-zanen gine-gine, kuma mawaki, sannan babban jagora ne na zamanin Renaissance." },
      { "question": "Menene fitattun ayyukan sassaka na Michelangelo?", "answer": "Fitattun ayyukan sassakansa sun hada da \"Pieta\" da aka kammala a shekarar 1499 da \"Dawuda\" wanda aka yi shi cikin shekaru uku daga 1501." },
      { "question": "Wanene ya zana rufin dakin ibada na Sistine?", "answer": "Michelangelo ne ya kammala shi cikin shekaru hudu bayan an bashi aikin a shekarar 1508 ta Paparoma Julius II." },
      { "question": "A ina \"Hukuncin Karshe\" na Michelangelo yake?", "answer": "An kammala wannan aikin cikin shekaru shida bisa umarnin Paparoma Bulus III a shekarar 1535, kuma babban zanen bangon gaba ne na dakin ibada na Sistine." }
    ],
    "sourceVerified": True,
    "missingDataNote": ""
  },
  "claude-monet": {
    "slug": "claude-monet",
    "timeline": [
      { "year": "1840", "event": "An haifi Claude Monet a ranar 14 ga Nuwamba a gundumar 9 ta Paris." },
      { "year": "1841", "event": "An yi masa baftisma da sunan Oscar-Claude a Cocin Notre-Dame de Lorette a ranar 20 ga Mayu." },
      { "year": "1845", "event": "Iyalinsa sun koma Le Havre a Normandy." },
      { "year": "1851", "event": "Ya shiga Makarantar Sakandaren Fasaha ta Le Havre a ranar 1 ga Afrilu." },
      { "year": "1857", "event": "Mahaifiyarsa ta rasu." },
      { "year": "1858", "event": "Ya hadu da abokin zanensa Eugène Boudin." },
      { "year": "1859", "event": "Ya isa Paris a watan Afrilu kuma ya sauka a otal din 'Du Nouveau Monde'." },
      { "year": "1860", "event": "A farkon (watan Fabrairu) ya shiga Académie Suisse wanda Charles Suisse ke gudanarwa, inda ya hadu da Camille Pissarro." },
      { "year": "1861", "event": "An dauke shi aikin soja a Le Havre a ranar 2 ga Maris sannan ya shiga rundunar dawakai na Afirka a ranar 29 ga Afrilu." },
      { "year": "1862", "event": "Ya kamu da zazzabin cizon sauro (typhoid) a lokacin bazara sannan ya koma Le Havre don murmurewa, kuma ya hadu da Johan Jongkind da rani." },
      { "year": "1862", "event": "Ya koma Paris a watan Disamba ya yi rajista a dakin zane na Charles Gleyre inda ya hadu da Auguste Renoir da Frédéric Bazille." },
      { "year": "1865", "event": "Ya fara nuna zane-zane cikin nasara a Salon da \"Pointe de la Hève at Low Tide\" da \"Mouth of the Seine at Honfleur\"." },
      { "year": "1866", "event": "Ya gabatar da \"Mace sanye da koren kaya\" da \"Titin Paving na Chailly\" ga Salon inda aka zabe su." },
      { "year": "1867", "event": "Budurwarsa a wancan lokacin, Camille Doncieux, ta haifi dansu na fari Jean." },
      { "year": "1870", "event": "Ya auri Camille a ranar 28 ga Yuni, kuma ya rayu a matsayin dan gudun hijira a London da Netherlands gabanin barkewar yakin Franco-Prussian." },
      { "year": "1871", "event": "Mahaifinsa ya rasu, sannan iyalinsa sun koma Argenteuil." },
      { "year": "1874", "event": "Ya koma 'gidan ruwan hoda mai koren taga' a Argenteuil, kuma ya nuna \"Impression, Sunrise\" da sauransu a Bikin baje koli na Impressionism na farko." },
      { "year": "1875", "event": "Ya zana \"Mace mai laima - Madame Monet da Danta\"." },
      { "year": "1876", "event": "Camille Monet ta yi rashin lafiya sosai, kuma ya gudanar da wani bikin baje koli don nuna adawa da Salon." },
      { "year": "1877", "event": "Ya gabatar da zane-zane 7 na \"Gare Saint-Lazare\" a Bikin baje koli na Impressionism na 3 a ranar 5 ga Afrilu." },
      { "year": "1878", "event": "An haifi dansa na biyu Michel, ya koma kauyen Vétheuil, kuma aka gano Camille tana da cutar daji ta mahaifa." },
      { "year": "1879", "event": "Camille ta rasu." },
      { "year": "1880", "event": "Ya gabatar da zane-zane biyu ga Salon wanda aka amince da daya." },
      { "year": "1881", "event": "A watan Disamba ya koma Poissy tare da Alice, matar Ernest Hoschedé, da 'ya'yanta." },
      { "year": "1882", "event": "Ya shiga Bikin baje koli na Impressionism na 7 a karo na karshe." },
      { "year": "1883", "event": "Ya koma wani gidan haya a Giverny tare da 'ya'yansa a ranar 29 ga Afrilu, kuma an gudanar da babban bikin baje kolin ayyukansa na farko." },
      { "year": "1883", "event": "Ya yi gajeruwar tafiya ta zane tare da Auguste Renoir zuwa yankin Riviera na Italiya da Genoa a watan Disamba." },
      { "year": "1884", "event": "Ya zauna a Bordighera daga 18 ga Janairu zuwa 5 ga Afrilu yana zana zane-zane guda 38." },
      { "year": "1886", "event": "Ya yi tafiya don zana furen tulip a Netherlands." },
      { "year": "1887", "event": "Ya hadu da John Singer Sargent a lokacin bazara." },
      { "year": "1890", "event": "Ya sayi gidan Giverny." },
      { "year": "1891", "event": "An nuna zane-zane 15 na \"Haystacks\" a Gidan zane na Durand-Ruel." },
      { "year": "1892", "event": "Ya zana zane-zane 26 na wuraren \"Rouen Cathedral\"." },
      { "year": "1895", "event": "Ya nuna zane-zane 20 na \"Rouen Cathedral\"." },
      { "year": "1898", "event": "An nuna zane-zane 61 a Galerie Georges Petit." },
      { "year": "1899", "event": "Ya fara zana furannin ruwa (Water Lilies), kuma ya zauna a London tsawon makonni 6." },
      { "year": "1900", "event": "Ya nuna zane-zanen lambunsa na farko da suka fi mayar da hankali kan gadar salon kasar Japan." },
      { "year": "1901", "event": "Ya fadada tafkin gidansa, kuma bikin baje kolin furannin ruwa a birnin New York a watan Fabrairu ya yi nasara sosai." },
      { "year": "1902", "event": "Ya fadada girman lambun ruwansa zuwa kusan murabba'in mita 4000." },
      { "year": "1904", "event": "An nuna zane-zanen 'Gare-garen Kogin Thames, London - 1900-1904' a watan Mayu da Yuni." },
      { "year": "1908", "event": "Ya zauna a Fadar Barbaro a Venice tare da Alice a lokacin kaka." },
      { "year": "1909", "event": "An gudanar da bikin baje koli mai taken \"Water Lilies\" a ranar 6 ga Mayu, inda aka nuna zane-zane 48." },
      { "year": "1911", "event": "Matarsa ta biyu Alice ta rasu." },
      { "year": "1913", "event": "Ya yi tafiya zuwa London don ganin likitan ido na kasar Jamus Richard Liebreich." },
      { "year": "1914", "event": "Dansa na fari Jean ya rasu." },
      { "year": "1916", "event": "Ya fara aikin 'zanen bango' don gwamnatin Faransa." },
      { "year": "1919", "event": "Ya fara tsarin zane-zanen wuri \"da dukkan karfinsa\"." },
      { "year": "1922", "event": "Matsalar ganinsa ta dan samu sauki sakamakon maganin fadada idanu." },
      { "year": "1923", "event": "An yi masa aikin tiyatar cire yanar ido (cataract)." },
      { "year": "1925", "event": "Ya fara yi wa wasu ayyukan da ya yi gabanin tiyatar kwaskwarima sakamakon samun saukin ganinsa." },
      { "year": "1926", "event": "Ya rasu sakamakon cutar sankarar huhu a ranar 5 ga Disamba yana da shekaru 86, kuma an binne shi a makabartar cocin Giverny." },
      { "year": "1927", "event": "An nuna zane-zanen alluna guda 27 a Gidan Tarihi na Orangerie a watan Mayu." },
      { "year": "1952", "event": "Mukalar André Masson ta taimaka wajen canza yadda ake kallon zane-zanen Monet." },
      { "year": "1956", "event": "Gobara a Gidan Tarihin Fasaha na Zamani da ke New York ta lalata zane-zanen furannin ruwa da suke adanawa." },
      { "year": "1966", "event": "Michel ya bayar da kyautar gidan Monet, lambun, da tafkin furannin ruwa ga Cibiyar Fasaha ta Faransa." },
      { "year": "1978", "event": "An gyara lambun Monet sannan aka bude shi ga jama'a." },
      { "year": "2001", "event": "An yi alamar Google Doodle don murnar cika shekaru 161 da haihuwar Claude Monet a ranar 14 ga Nuwamba." },
      { "year": "2004", "event": "An sayar da \"London, the Parliament, Effects of Sun in the Fog\" kan dalar Amurka miliyan 20.1." },
      { "year": "2006", "event": "An wallafa takarda a mujallar Proceedings of the Royal Society game da wuraren zane-zanen London." },
      { "year": "2007", "event": "An saci \"Cliffs near Dieppe\" a karo na biyu a watan Agusta." },
      { "year": "2008", "event": "An sayar da \"The Railway Bridge at Argenteuil\" a kan dala miliyan 41.4 a ranar 6 ga Mayu." },
      { "year": "2008", "event": "An gano \"Cliffs near Dieppe\" a watan Yuni." },
      { "year": "2008", "event": "An sayar da \"Water Lily Pond\" akan fam 40,921,250 (kimanin dala 80,451,178) a ranar 24 ga Yuni." },
      { "year": "2013", "event": "\"The Church at Vétheuil\" da \"Water Lily Pond\" sun zama batun shari'a a kotun New York a watan Oktoba." },
      { "year": "2014", "event": "An gano wani zanen Monet da wani dan kasuwan yahudawa ya mallaka a cikin akwatin Cornelius Gurlitt." },
      { "year": "2016", "event": "An mayar da \"On the Beach\", wani aikin da 'yan Nazi suka sace, ga jikokin Falgi." }
    ],
    "keyAchievements": [
      { "title": "Samarwa da Fara Impressionism", "description": "Ana kiransa 'Uban Impressionism', an san shi a matsayin wanda ya kirkiro kuma ya fara Impressionism kuma babban jagora ne na fasahar zamani (Modernism)." },
      { "title": "Asalin Kalmar Impressionism", "description": "Kalmar 'Impressionism' ta samo asali ne daga sunan zanensa \"Impression, Sunrise\" da aka nuna a Bikin baje koli na Impressionism na farko a shekarar 1874." },
      { "title": "Aiwatar da Zane-zane na waje akai-akai", "description": "A matsayinsa na mai zane da ya fi dacewa wajen aiwatar da falsafar Impressionism a tsawon rayuwarsa ta aiki, ya bayyana fahimtarsa game da dabi'a ta hanyar zane-zane a waje." },
      { "title": "Samar da Tsarin zane-zane (Series)", "description": "Ya bullo da dabarar zana wuri guda sau da yawa don nuna sauyin haske da na yanayi, sannan fitattun ayyukansa sun hada da tsarin \"Haystacks\", tsarin \"Rouen Cathedral\", da tsarin \"Water Lilies\"." },
      { "title": "Samar da Lambun Giverny", "description": "Ya sayi gida da fili a Giverny da ke arewacin Faransa sannan ya fara babban aikin gyaran lambu wanda ya hada da tafkin furannin ruwa, wanda ya zama babban abin da ke karfafa masa gwiwa a fannin fasaha." },
      { "title": "Tasiri ga Fasahar Zamani", "description": "Ayyukansa na baya-bayan nan da yayi a Giverny karkashin tasirin yanar ido, ana kallonsu a matsayin abin da ya ba da 'babban' kwarin gwiwa ga fasahar karni na 20 da fasahar zamani ta (abstract)." }
    ],
    "faq": [
      { "question": "Wanene Claude Monet?", "answer": "Claude Monet mai zanen Impressionist ne na kasar Faransa wanda ake kira 'Uban Impressionism', kuma shine wanda ya kirkiro sannan ya fara motsin Impressionism." },
      { "question": "Daga ina kalmar 'Impressionism' ta samo asali?", "answer": "Kalmar 'Impressionism' ta samo asali ne daga taken zanensa \"Impression, Sunrise\" wanda aka nuna a Bikin baje koli na Impressionism na farko a shekarar 1874." },
      { "question": "Menene fitattun zane-zane na Monet?", "answer": "Fitattun zane-zanensa sun hada da tsarin \"Haystacks\", tsarin \"Rouen Cathedral\", da tsarin \"Water Lilies\", wanda ya fi mayar da hankali akai a cikin shekaru 20 na karshen rayuwarsa." },
      { "question": "A ina Monet ya fi yin ayyukansa?", "answer": "Ya rayu a Giverny da ke arewacin Faransa tun daga shekarar 1883, inda ya sayi gida da fili kuma ya fara wani babban aikin gyaran kasa wanda ya hada da tafkin furannin ruwa." },
      { "question": "Wane tasiri gani yayi a kan ayyukan Monet?", "answer": "Saboda yanar ido, ya ci gaba da fuskantar wahala wajen gane launuka, don haka zane-zanensa suka zama manya kuma a lollokace (abstract), kuma bayan tiyatar, zanensa sun fi nuna launin shudi fiye da da." },
      { "question": "Wane tasiri ayyukan Monet sukayi ga fasahar zamani?", "answer": "Ayyukansa na baya-bayan nan da yayi a Giverny karkashin tasirin yanar ido ana daukarsu a matsayin wani abu da ya ba da 'babban' kwarin gwiwa ga fasahar karni na 20 da fasahar zamani ta (abstract)." }
    ],
    "sourceVerified": True,
    "missingDataNote": ""
  },
  "fyodor-dostoevsky": {
    "slug": "fyodor-dostoevsky",
    "timeline": [
      { "year": "11 ga Nuwamba, 1821", "event": "An haife shi a Moscow a matsayin da na biyu daga cikin yara bakwai na Mikhail Andreyevich da Maria Fyodorovna." },
      { "year": "1834", "event": "Ya shiga makarantar kwana ta Chermak a Moscow tare da dan'uwansa Mikhail, inda yayi karatu na shekaru 3." },
      { "year": "1837", "event": "Mahaifiyarsa Maria Fyodorovna ta rasu sakamakon tarin fuka; mahaifinsa ya tura shi da dan'uwansa Mikhail zuwa St. Petersburg don shiga makarantar injiniyan soji." },
      { "year": "1838", "event": "Ya ci jarrabawar shiga makarantar injiniyan soji kuma ya sami horon soja." },
      { "year": "6 ga Yuni, 1839", "event": "Bayin dake gonar mahaifinsa sun kashe shi." },
      { "year": "Agusta 1841", "event": "Ya kammala makarantar injiniyan soji kuma an bashi matsayin laftanar a ofishin zane na Ma'aikatar Yaki." },
      { "year": "Oktoba 1844", "event": "Ya bar aikin soja don zama marubuci sannan ya mai da hankali kan adabi." },
      { "year": "1846", "event": "Ya fara rubutu tare da babban yabo daga mai sukar lamiri Vissarion Belinsky kan aikinsa na farko, \"Matasa Masu Talauci\"." },
      { "year": "23 ga Afrilu, 1849", "event": "Hukumomi sun kama shi saboda ya shiga kungiyar Mikhail Petrashevsky kuma ya karanta \"Wasika zuwa ga Gogol\" na Belinsky." },
      { "year": "1854", "event": "Ya kammala wa'adin daurinsa na shekaru 4 a gidan yarin Omsk." },
      { "year": "1857", "event": "Ya auri Maria Isaeva." },
      { "year": "1859", "event": "Ya koma Petersburg." },
      { "year": "1861", "event": "Ya wallafa mujallar \"Lokaci\" tare da dan'uwansa, kuma ya buga \"Wadanda Aka Zalunta\" da \"Tarihin Gidan Matattu\" a matsayin jerin labarai." },
      { "year": "1864", "event": "Ya kafa sabuwar mujalla \"Karni\" tare da dan'uwansa, amma bai yi nasara ba." },
      { "year": "1866", "event": "Ya kammala babban aikinsa \"Zunubi da Hukunci\"." },
      { "year": "1867", "event": "Yayin da yake zaune a kasashen waje (musamman Dresden), ya rubuta \"Wawa\", \"Shaidanu\", da sauransu kafin ya dawo gida." },
      { "year": "1874", "event": "Ya wallafa \"Saurayi\", inda ya sami makudan kudi sannan ya tsira daga talauci." },
      { "year": "1880", "event": "Ya kammala rubuta babban aikinsa na karshe, wato littafin \"'Yan Uwa Karamazov\"." },
      { "year": "28 ga Janairu, 1881", "event": "Ya rasu yana da shekaru 60 sakamakon fashewar jijiyar huhu." },
      { "year": "31 ga Janairu, 1881", "event": "An binne gawarsa a makabartar gidan ibada na Alexander Nevsky da ke Petersburg." }
    ],
    "keyAchievements": [
      { "title": "Matasa Masu Talauci", "description": "Aikinsa na farko a shekarar 1846 wanda ya ba shi damar fara rubutu cikin armashi inda ya sami yabo daga mai sukar lamiri Vissarion Belinsky a matsayin 'Gogol na biyu'." },
      { "title": "Tarihin Gidan Matattu", "description": "Wannan aiki ne da aka wallafa bisa la'akari da abubuwan da ya fuskanta yayin zaman gudun hijira a Siberia." },
      { "title": "Zunubi da Hukunci", "description": "Ya kammala wannan aikin, wanda ake daukarsa a matsayin daya daga cikin fitattun ayyukansa, a shekarar 1866." },
      { "title": "Saurayi", "description": "Ya wallafa wannan aikin a shekarar 1874 kuma ya sami makudan kudi, abin da ya ba shi damar tsira daga talauci." },
      { "title": "'Yan Uwa Karamazov", "description": "A shekarar 1880, ya kammala rubuta wani littafi da ake daukarsa a matsayin babban aikinsa na karshe." },
      { "title": "Littafin Tarihin Marubuci", "description": "Ya hada da bayanan adabi, sharhin siyasa da zamantakewa, makaloli, gajerun labarai, da sauransu, wadanda daga baya suka zama muhimman bayanai ga bincike akan Dostoevsky." }
    ],
    "faq": [
      { "question": "Wane canji na akida Dostoevsky ya samu?", "answer": "Ya fuskanci canjin akida daga gurguzu zuwa tsarin dan adam na Kirista sakamakon karatun Littafi Mai Tsarki da zurfi da kuma rayuwar fursunoni da mutanen da ya gani a gidan yari yayin gudun hijira a Siberia." },
      { "question": "Wane kwarewa ta kashin kai ce tayi tasiri a duniyar ayyukan Dostoevsky?", "answer": "Abubuwan da suka shafe shi na siyasa inda aka rage masa hukunci gab da zartar da hukuncin kisa, gudun hijira a Siberia, cutar farfadiya, da kuma caca wadda tayi tasiri a matsayin muhimman abubuwa a cikin ayyukansa." },
      { "question": "Wane irin yanayi ne littattafan Dostoevsky ke da shi?", "answer": "Littattafansa sukan nuna haruffa dake da halaye na daban kuma masu tsauri, inda suke nuna fahimta mai ban mamaki game da tunanin dan adam, kuma sun yi nazari sosai kan siyasa, zamantakewa, da ruhin Rasha a lokacinsa." },
      { "question": "Shin Dostoevsky yana da alaka da wanzuwa?", "answer": "Walter Kaufmann ya siffanta littafin Dostoevsky \"Bayanan Daga Karkashin Kasa\" a matsayin 'mafi kyawun shiri don wanzuwa', kuma a wasu lokuta ana daukarsa a matsayin wanda ya kirkiro tsarin wanzuwa." }
    ],
    "sourceVerified": True,
    "missingDataNote": ""
  },
  "victor-hugo": {
    "slug": "victor-hugo",
    "timeline": [
      { "year": "26 ga Fabrairu, 1802", "event": "An haife shi a Besançon, gabashin Faransa a matsayin da na uku na Leopold Hugo." },
      { "year": "1815 - 1818", "event": "Ya yi sha'awar karatu da rubuta waka a makarantar kwana ta Cordier da ke Paris sannan ya yi alkawarin zama babban marubuci a Faransa." },
      { "year": "1822", "event": "Ya wallafa littafin wakokinsa na farko, \"Odes et Poésies Diverses\", kuma ya yi aure." },
      { "year": "1823", "event": "Ya wallafa littafin \"Han d'Islande\"." },
      { "year": "1825", "event": "Gidan sarautar Faransa sun ba shi lambar yabo ta Chevalier de la Légion d'honneur a matsayin amincewa da gudummawarsa a matsayin marubuci." },
      { "year": "1826", "event": "Ya wallafa littafin wakoki \"Odes et Ballades\" da littafin \"Bug-Jargal\"." },
      { "year": "1827", "event": "Ta hanyar wallafa gabatarwar wasan kwaikwayo \"Cromwell\", ya fito fili ya yi adawa da adabin gargajiya sannan ya jagoranci marubutan Romanticism." },
      { "year": "1829", "event": "Ya wallafa \"Les Orientales\" da \"Ranar Karshe ta Mai Yanke Hukuncin Kisa\"." },
      { "year": "Fabrairu 1830", "event": "Gabatowar wasan kwaikwayon \"Hernani\" na farko ya haifar da 'Yakin Hernani' tsakanin masu goyon bayan Romanticism da na gargajiya." },
      { "year": "1831", "event": "Ya wallafa littafin \"Notre-Dame de Paris\", littafin wakoki \"Les Feuilles d'automne\", da wasan kwaikwayo \"Marion Delorme\"." },
      { "year": "1832", "event": "Ya wallafa wasan kwaikwayo \"Sarki yana jin dadi\"." },
      { "year": "1833", "event": "Ya wallafa wasan kwaikwayo \"Lucrèce Borgia\" da \"Marie Tudor\"." },
      { "year": "1835", "event": "Ya wallafa littafin wakoki \"Wakokin Yamma\"." },
      { "year": "1837", "event": "Ya wallafa littafin wakoki \"Muryoyin Ciki\"." },
      { "year": "1838", "event": "Ya wallafa wasan kwaikwayo na waka \"Ruy Blas\"." },
      { "year": "1840", "event": "Ya wallafa littafin wakoki \"Haske da Inuwa\"." },
      { "year": "1841", "event": "Ya zama memba na Académie Française." },
      { "year": "1843", "event": "Wasan kwaikwayonsa \"Les Burgraves\" ya sha suka sosai, sannan babbar diyarsa Léopoldine da mijinta suka rasu a hatsarin juye jirgin ruwa." },
      { "year": "Kimanin shekaru 10 bayan 1843", "event": "Kusan bai wallafa kowane aiki ba inda ya sadaukar da kansa ga ayyukan siyasa." },
      { "year": "Fabrairu 1848", "event": "Juyin Juya Halin Fabrairu da sauran yanayi sun sa ya karfafa manufarsa na tausayin dan adam." },
      { "year": "1851", "event": "Saboda adawarsa da juyin mulkin Napoleon III, an kore shi daga kasar inda ya fara rayuwar gudun hijira na kusan shekaru 19." },
      { "year": "1853", "event": "Ya wallafa littafin wakoki \"Hukunci\"." },
      { "year": "1856", "event": "Ya wallafa littafin wakoki \"Abubuwan Lura\"." },
      { "year": "1859", "event": "Ya wallafa kundi na farko na littafin wakoki \"Almara na Karni\"." },
      { "year": "1862", "event": "Ya wallafa littafin \"Les Misérables\"." },
      { "year": "1866", "event": "Ya wallafa littafin \"Ma'aikatan Teku\"." },
      { "year": "1869", "event": "Ya rubuta \"Shekaru Masu Tsauri\", inda ya kwatanta halin da ma'aikata ke ciki." },
      { "year": "1870", "event": "Ya koma Paris a matsayin mai kare tsarin jamhuriya tare da faduwar Napoleon III sakamakon yakin Franco-Prussian." },
      { "year": "1872", "event": "Ya wallafa \"Shekara Mai Muni\"." },
      { "year": "1874", "event": "Ya wallafa littafin \"'93\"." },
      { "year": "1877", "event": "Ya wallafa kundi na biyu na \"Almara na Karni\"." },
      { "year": "31 ga Agusta, 1881", "event": "Ya rubuta wasiyyarsa." },
      { "year": "1883", "event": "Ya wallafa kundi na uku na \"Almara na Karni\"." },
      { "year": "22 ga Mayu, 1885", "event": "Ya rasu, sannan an binne gawarsa a Panthéon tare da jana'izar kasa." }
    ],
    "keyAchievements": [
      { "title": "Jagorancin Adabin Romanticism", "description": "Ya gabatar da ka'idar wasan kwaikwayo ta Romanticism a cikin gabatarwar \"Cromwell\", ya yi nasara a 'Yakin Hernani', kuma ya jagoranci marubutan Romanticism." },
      { "title": "Rubuta Litattafai Masu Kyau", "description": "Ya tabbatar da matsayinsa a matsayin marubucin litattafai da \"Notre-Dame de Paris\", kuma ya rubuta fitattun ayyuka da yawa ciki har da \"Les Misérables\" yayin gudun hijirarsa." },
      { "title": "Sukar Zamantakewa da Tausayin Dan Adam", "description": "Ya bayyana kaunarsa ga matalauta ma'aikata ta hanyar ayyukansa, ya jaddada fasahar jama'a, kuma ya karfafa manufofin tausayin dan adam." },
      { "title": "Muhimmin Mutum a Adabin Faransa", "description": "Ya rike matsayi mai mahimmanci a adabin Faransa, kamar karbar lambar yabo ta Chevalier de la Légion d'honneur a shekarar 1825 da zama memba na Académie Française a shekarar 1841." }
    ],
    "faq": [
      { "question": "Wanene Victor Hugo?", "answer": "Mawaki ne, marubucin litattafai, kuma marubucin wasan kwaikwayo na Faransa." },
      { "question": "Wane tasiri Victor Hugo ya yi akan Romanticism?", "answer": "Ya gabatar da ka'idar wasan kwaikwayo ta Romanticism ta hanyar gabatarwar wasan kwaikwayo \"Cromwell\", yayi nasara a 'Yakin Hernani', kuma ya jagoranci marubutan Romanticism." },
      { "question": "Menene fitattun ayyukan Victor Hugo?", "answer": "Sun hada da litattafan \"Notre-Dame de Paris\" da \"Les Misérables\"." },
      { "question": "Me yasa Victor Hugo yayi rayuwar gudun hijira?", "answer": "Saboda adawarsa da juyin mulkin Napoleon III a shekarar 1851, an kore shi daga kasar inda ya fara rayuwar gudun hijira ta kimanin shekaru 19." },
      { "question": "Wace dangantaka Victor Hugo ke da ita da Katolika?", "answer": "Cocin Katolika ta haramta ayyukansa, sannan ya kasa yin sulhu da Katolika har ma ya ki amincewa da addu'o'in cocin." },
      { "question": "Yaushe Victor Hugo ya rasu kuma a ina aka binne shi?", "answer": "Ya rasu a ranar 22 ga Mayu, 1885, kuma an binne gawarsa a Panthéon." }
    ],
    "sourceVerified": True,
    "missingDataNote": ""
  }
}

with open("scratch/out1.json", "w", encoding="utf-8") as f:
    json.dump(out1, f, ensure_ascii=False, indent=2)
