const fs = require('fs');

const dataToInject = {
  "genghis-khan": {
    "era_ko": "12세기 후반 - 13세기 초반 (1162?~1227)",
    "era_en": "Late 12th - Early 13th Century (1162?~1227)",
    "category": "leadership",
    "epic_ko": "매서운 눈보라가 몰아치고 강자만이 살아남는 잔혹한 몽골 초원, 아홉 살 소년 테무친의 삶은 아버지가 적대 부족에게 독살당하는 순간 돌이킬 수 없는 처참한 지옥으로 변해버렸습니다. 아버지가 죽자마자 매정하게 등 돌린 부족원들에게 버림받은 채, 어머니와 함께 메마른 들판을 헤매며 쥐와 나무뿌리를 씹어 연명하던 그에게 세상은 단 한 줌의 자비도 베풀지 않았습니다. 심지어 갓 결혼한 사랑하는 아내 보르테마저 적에게 납치당하는 뼈에 사무치는 수모를 겪었을 때, 그는 운명을 저주하며 주저앉아 눈물짓지 않았습니다. 오히려 가슴속 깊은 곳에서 차갑고 예리한 복수의 칼날을 무섭게 벼려나갔습니다. 배신이 판치는 초원의 잔혹한 생존 법칙을 온몸으로 뼈저리게 체득한 그는, 기존의 핏줄과 가문을 철저히 파괴하고 오직 '개인의 능력'과 '변치 않는 충성심'만으로 사람을 평가하고 거느리는 전에 없던 새로운 질서를 초원 위에 세우기 시작했습니다.\n\n그는 이기적인 이합집산을 거듭하던 몽골의 야성적인 기병들을 규합하여, 일사분란하게 움직이는 거대한 태풍 같은 군대로 탈바꿈시켰습니다. 수백 년간 몽골을 분열시키며 교묘하게 이간질하고 짓밟았던 거대 제국 금나라와 호라즘을 향해 진격할 때, 그의 몽골군은 육포를 씹고 말 위에서 쪽잠을 자며 상상을 초월하는 기동력으로 대륙 전체에 피바람을 몰고 왔습니다. 칭기즈 칸은 무의미한 학살자가 아니었습니다. 자신에게 스스로 무릎을 꿇고 항복하는 자에게는 출신과 종교를 불문하고 세계 제국의 신민이라는 영광과 자유로운 상업의 기회를 베풀었지만, 끝까지 저항하는 자의 도시는 가차 없이 잿더미로 만들고 수레바퀴보다 키가 큰 남자는 모조리 도륙해 버리는 압도적이고 극단적인 공포를 세계에 심어주었습니다.\n\n말발굽으로 유라시아 대륙을 가로지르며 인류 역사상 가장 광활한 대제국을 건설한 것은 결코 우연이 아니었습니다. 그것은 끊임없이 진격하고 이동하며 적의 새로운 전술과 공성 무기를 스펀지처럼 흡수하고, 낡은 관습을 박살 내버린 맹렬한 혁신의 결과물이었습니다. 죽는 순간까지도 편안한 성채를 거부하고 초원의 텐트 속에서 야성을 잃지 않은 채 세상을 떠난 칭기즈 칸. 그의 삶은 인간이 떨어질 수 있는 가장 비참한 밑바닥에서 시작하여 결국 세계의 절반을 집어삼킨 거대한 늑대의 불멸의 서사시로 역사의 한 페이지를 지배하고 있습니다.",
    "epic_en": "On the cruel Mongolian steppes, where fierce blizzards raged and only the strong survived, the life of nine-year-old Temujin turned into an irreversible, miserable hell the moment his father was poisoned by a rival tribe. Abandoned by tribesmen who coldly turned their backs the instant his father died, wandering the arid plains with his mother and surviving by chewing on field mice and tree roots, the world offered him not a single ounce of mercy. Even when he suffered the bone-chilling humiliation of his newlywed, beloved wife Borte being abducted by enemies, he did not sit down and curse his fate in tears. Instead, deep within his heart, he terrifyingly forged a cold, sharp blade of vengeance. Having bitterly learned the cruel survival laws of the steppe with his entire body, he completely destroyed the existing reliance on bloodlines and clans, beginning to establish an unprecedented new order on the steppe that evaluated and commanded people based solely on 'individual ability' and 'unwavering loyalty.'\n\nHe rallied the wild Mongolian cavalry—who had repeatedly engaged in selfish, shifting alliances—and transformed them into a massive, typhoon-like army moving with absolute discipline. As he marched against the massive Jin dynasty and Khwarazmian Empire, which had divided, subtly manipulated, and trampled Mongolia for centuries, his army brought storms of blood across the continent with unimaginable mobility, chewing dried meat and sleeping on horseback. Genghis Khan was no senseless slaughterer. To those who willingly knelt and surrendered, he granted the glory of becoming subjects of a world empire and the opportunity for free commerce, regardless of their origin or religion. However, he instilled an overwhelming and extreme terror into the world by ruthlessly reducing the cities of those who resisted to ashes and slaughtering every man taller than a cartwheel.\n\nBuilding the most expansive empire in human history stretching across the Eurasian continent by horseback was no mere accident. It was the result of a fierce innovation that constantly advanced and moved, absorbing new enemy tactics and siege weapons like a sponge, and smashing old customs. Refusing comfortable fortresses until the moment of his death and passing away in a steppe tent without ever losing his wildness, Genghis Khan's life dominates a page of history as the immortal epic of a giant wolf that started from the most miserable bottom a human could fall to and ultimately swallowed half the world.",
    "trials_ko": "유년 시절 아버지의 독살로 시작된 극한의 가난과 부족원들의 매정한 배신, 아내의 납치, 그리고 매 순간 자신의 피를 흘려야만 했던 잔혹한 초원의 적자생존 경쟁.",
    "trials_en": "Extreme poverty and the cold betrayal of his tribesmen following his father's poisoning in childhood, the abduction of his wife, and the cruel survival-of-the-fittest competition on the steppe where he had to risk bleeding at every moment.",
    "overcoming_ko": "낡은 혈연주의를 박살 내고 철저한 실력주의와 보상 체계, 그리고 포용과 극한의 공포를 자유자재로 오가는 압도적 리더십으로 분열된 부족을 규합하여 인류 최대의 제국을 건설함.",
    "overcoming_en": "He smashed old nepotism and built the largest empire in human history by uniting divided tribes through strict meritocracy, a clear reward system, and overwhelming leadership that freely oscillated between ultimate inclusion and extreme terror.",
    "wisdom": [
      {
        "quote_ko": "적은 밖에 있는 것이 아니라 내 안에 있다. 나는 내게 거추장스러운 것은 깡그리 쓸어버렸다.",
        "quote_en": "The enemy is not outside, but within me. I swept away everything that was cumbersome to me.",
        "meaning_ko": "당신을 끊임없이 주저앉히고 좌절하게 만드는 진짜 무서운 적은 세상의 가혹한 풍파가 아닙니다. 끊임없이 핑계를 대며 현실에 안주하려는 당신 내면의 나약함과 두려움입니다. 불필요하고 알량한 자존심, 그리고 타인의 시선이라는 거추장스럽고 무거운 짐들을 가차 없이 베어버리십시오. 당신의 몸과 정신이 극한으로 가벼워질 때, 비로소 세상을 향해 맹렬하게 달릴 수 있는 법입니다.",
        "meaning_en": "The truly terrifying enemy that constantly brings you down and frustrates you is not the harsh storms of the world. It is the weakness and fear within yourself that constantly makes excuses and seeks to settle for reality. Ruthlessly cut away the cumbersome and heavy burdens of unnecessary, petty pride and the consciousness of others' gaze. Only when your body and mind become extremely light can you fiercely run toward the world."
      },
      {
        "quote_ko": "배운 게 없다고 탓하지 마라. 나는 내 이름도 쓸 줄 몰랐지만 남의 말에 귀 기울이면서 현명해지는 법을 배웠다.",
        "quote_en": "Do not blame having no education. I did not even know how to write my own name, but I learned to become wise by listening to the words of others.",
        "meaning_ko": "학교에서 많이 배우지 못했다고, 가진 지식이 부족하다고 세상의 거대한 벽 앞에서 지레 겁먹고 고개를 숙이지 마시길 바랍니다. 책에 박제된 죽은 지식보다, 당신보다 나은 타인의 살아있는 지혜를 스펀지처럼 유연하게 빨아들이는 겸손한 귀야말로 세상을 정복하는 가장 예리하고 무서운 무기입니다.",
        "meaning_en": "I hope you will not preemptively be frightened and bow your head before the massive walls of the world just because you lack formal education or sufficient knowledge. A humble ear that flexibly absorbs the living wisdom of others who are better than you, like a sponge, is a far sharper and more terrifying weapon for conquering the world than dead knowledge stuffed in books."
      },
      {
        "quote_ko": "집안이 나쁘다고 탓하지 마라. 나는 아홉 살 때 고아가 되었고 들쥐를 잡아먹으며 살아남았다.",
        "quote_en": "Do not blame a bad family background. I became an orphan at nine and survived by eating field mice.",
        "meaning_ko": "남들보다 불공평한 출발선에 섰다고 부모와 세상을 원망하느라 당신의 그 눈부시고 소중한 젊음을 탕진하지 마십시오. 처절한 밑바닥을 쳐본 자만이 그 반동으로 가장 높이 튀어 오를 수 있는 무서운 독기를 품는 법입니다. 당신이 겪은 그 끔찍한 결핍이야말로, 역설적으로 세상을 통째로 집어삼킬 수 있는 가장 거대한 에너지의 불쏘시개임을 절대 잊지 마십시오.",
        "meaning_en": "Do not squander your dazzling, precious youth resenting your parents and the world because you stand at an unfair starting line compared to others. Only one who has hit the desperate rock bottom harbors the terrifying venom to bounce back the highest from the recoil. Please never forget that the horrific deficiency you experienced is, paradoxically, the very kindling of the most colossal energy capable of swallowing the world whole."
      }
    ]
  },
  "alexander-the-great": {
    "era_ko": "기원전 4세기의 거인 (BC 356~323)",
    "era_en": "4th Century BC Giant (356~323 BC)",
    "category": "leadership",
    "epic_ko": "고대 그리스의 거칠고 투박한 변방 국가 마케도니아. 위대한 철학자 아리스토텔레스의 가르침을 스펀지처럼 온몸으로 빨아들이며 자란 젊고 오만한 왕자 알렉산드로스의 가슴속에는, 일리아드의 아킬레우스와 같은 신화적 불멸의 영웅이 되겠다는 거대하고 미친 불꽃이 타오르고 있었습니다. 불과 20세의 너무나도 어린 나이에 아버지가 암살당하고 피 묻은 왕좌에 올랐을 때, 주변국의 반란군과 노련한 정치가들은 그를 애송이라 부르며 비웃었습니다. 그러나 그는 자비 없는 태풍처럼 휘몰아쳐 그리스 전역을 단숨에 피로 물들이며 제압했고, 모두가 불가능하다며 만류했던 아득히 먼 동방의 거대 제국, 페르시아를 향해 거침없이 정복의 창을 겨누었습니다.\n\n가우가멜라 전투의 흙먼지 속에서 수십만 명의 페르시아 대군이 땅을 뒤흔들며 몰려올 때, 그는 압도적인 공포 앞에서도 단 한 걸음도 물러서지 않았습니다. 안전한 후방에 머물기를 거부하고 직접 정예 컴패니언 기병대의 최선봉에 선 그는, 적의 대열에 생긴 찰나의 틈새를 송곳처럼 꿰뚫고 페르시아의 군주 다리우스 3세를 향해 미친 듯이 돌진했습니다. 그가 휘두른 것은 단순한 무력의 칼날이 아니라, 동양과 서양을 융합하여 하나의 거대한 보편적 문명으로 묶어내겠다는 숭고하고도 광기 어린 야망이었습니다. 그는 승자의 오만함으로 정복한 땅의 문화를 짓밟지 않았습니다. 스스로 페르시아 황제의 화려한 옷을 입고 이민족들을 고위직에 기용하며, '헬레니즘'이라는 완전히 새롭고 거대한 세계의 씨앗을 유라시아 대륙에 뿌렸습니다.\n\n하지만 그의 영혼을 좀먹는 끝없는 정복욕은 그를 이집트의 불타는 사막을 넘어 아득한 인도의 울창한 정글까지 미친 듯이 몰아넣었습니다. 수만 킬로미터의 행군 끝에 32세의 젊은 나이로 원인 모를 열병에 걸려 침상에 누웠을 때, 거대한 제국을 물려받을 후계자를 묻는 장군들의 절박한 질문에 그는 가쁜 숨을 몰아쉬며 \"가장 강한 자에게(To the strongest)\"라는 섬뜩하고 위태로운 유언을 남긴 채 세상을 떠났습니다. 비록 그의 생애는 밤하늘을 가르는 혜성처럼 짧게 타오르고 소멸했지만, 그가 피 묻은 군화발로 휩쓸고 지나간 발자취는 동서양의 오랜 경계를 산산조각 내고 인류 역사의 흐름을 영원히 뒤틀어버린 가장 압도적이고 불멸하는 대서사시로 기록되어 있습니다.",
    "epic_en": "In Macedonia, the rugged and unrefined periphery of ancient Greece. Within the heart of the young, arrogant Prince Alexander, who grew up absorbing the teachings of the great philosopher Aristotle with his entire body like a sponge, burned a colossal, crazy flame to become a mythical, immortal hero like Achilles from the Iliad. When he ascended to the blood-stained throne following his father's assassination at the incredibly young age of 20, rebels from surrounding nations and seasoned politicians mocked him as a greenhorn. However, sweeping through like a merciless typhoon, he subdued all of Greece in a bloodbath in a single breath, and relentlessly leveled his spear of conquest toward the vast, distant empire of Persia—a feat everyone tried to dissuade him from, calling it impossible.\n\nIn the dust of the Battle of Gaugamela, as hundreds of thousands of Persian troops surged forward shaking the earth, he did not take a single step back in the face of overwhelming terror. Refusing to stay in the safe rear, he stood at the absolute vanguard of his elite Companion Cavalry, piercing a momentary gap in the enemy lines like an awl and charging madly toward the Persian monarch, Darius III. What he wielded was not a simple blade of martial force, but a sublime and crazed ambition to fuse the East and West into one colossal, universal civilization. With the arrogance of a victor, he did not trample the cultures of the lands he conquered. Donning the luxurious robes of the Persian emperor himself and appointing foreigners to high positions, he sowed the seeds of an entirely new and massive world called 'Hellenism' across the Eurasian continent.\n\nYet, the endless lust for conquest that gnawed at his soul drove him madly past the burning deserts of Egypt into the dense, distant jungles of India. Bedridden with an unknown fever at the young age of 32 after marching tens of thousands of kilometers, when asked by his desperate generals to whom he would leave his massive empire, he took a ragged breath and left the chilling, perilous final words, \"To the strongest,\" before passing away. Though his life burned brightly and vanished as briefly as a comet crossing the night sky, the footsteps he swept through with blood-stained military boots shattered the long-standing boundaries of East and West, recorded as the most overwhelming and immortal epic that permanently twisted the flow of human history.",
    "trials_ko": "20세의 어린 나이에 감당해야 했던 암살의 위협과 국가 분열의 위기, 페르시아 대군을 마주하며 겪은 압도적인 수적 열세, 그리고 낯선 대륙에서 끊임없이 밀려오는 미지의 공포.",
    "trials_en": "The threat of assassination and the crisis of national division he had to bear at the young age of 20, the overwhelming numerical disadvantage faced against the massive Persian army, and the relentless fear of the unknown surging continuously on unfamiliar continents.",
    "overcoming_ko": "단 한 번도 후방에 숨지 않고 최선봉에서 기병대를 이끌며 돌진하는 광기 어린 용맹함으로 적을 붕괴시켰고, 이민족의 문화를 철저히 수용하는 파격적인 융합 정책(헬레니즘)으로 세계를 하나로 묶어냄.",
    "overcoming_en": "He collapsed the enemy with mad valor, never once hiding in the rear but always leading the cavalry charge from the vanguard, and bound the world together through an unconventional integration policy (Hellenism) that thoroughly embraced the cultures of foreign peoples.",
    "wisdom": [
      {
        "quote_ko": "세상의 어떤 성벽도 뚫을 수 있다. 당나귀 한 마리에 황금을 가득 싣고 갈 수만 있다면.",
        "quote_en": "No fortress is so strong that it cannot be taken, if only a donkey loaded with gold can be led inside.",
        "meaning_ko": "당신이 간절히 원하는 목표를 이루기 위해, 때로는 우직하게 몸을 부딪치는 물리적인 힘보다 상대의 심리를 꿰뚫는 교묘한 지혜와 자본이 훨씬 강력하고 효과적인 무기가 되는 법입니다. 꽉 막힌 차가운 성벽을 맨주먹으로 치느라 손에 피를 내지 마십시오. 대신, 철벽같은 사람의 마음조차 스르르 열게 만들 가장 현실적이고 날카로운 지렛대가 무엇인지 찾아내시길 바랍니다.",
        "meaning_en": "To achieve the goal you desperately desire, cunning wisdom and capital that pierce the opponent's psychology are sometimes far more powerful and effective weapons than the physical force of stubbornly throwing your body against it. Do not bloody your hands punching a solid, cold wall with bare fists. Instead, please find the most practical, sharp lever that will smoothly open even the iron-clad hearts of people."
      },
      {
        "quote_ko": "나는 승리를 훔치지 않는다.",
        "quote_en": "I will not steal a victory.",
        "meaning_ko": "눈앞의 이익에 눈이 멀어 치졸한 꼼수와 비겁한 속임수로 얻어낸 성공은, 아침 햇살에 금방 증발해 버리는 이슬처럼 허망한 것입니다. 진정한 거인은 잔머리를 굴리지 않고 정정당당하게 적의 가장 무서운 한가운데로 돌진하여 순수한 실력으로 상대를 압도합니다. 당신 자신에게조차 떳떳하지 못한 더러운 승리는, 차라리 명예로운 패배보다 못한 것임을 영원히 명심하십시오.",
        "meaning_en": "Success obtained through petty tricks and cowardly deception, blinded by immediate profit, is as vain as dew that quickly evaporates in the morning sun. A true giant does not resort to cheap tricks but fairly charges into the most terrifying center of the enemy, overwhelming the opponent with pure skill. Remember forever that a dirty victory, of which even you cannot be proud, is worse than an honorable defeat."
      },
      {
        "quote_ko": "운명은 용기 있는 자의 편이다.",
        "quote_en": "Fortune favors the bold.",
        "meaning_ko": "모든 것이 완벽하게 준비된 타이밍과 안락한 조건이 갖춰지기만을 기다리며 방구석에 비겁하게 숨어있지 마십시오. 인생을 뒤바꾸는 거대한 파도는, 오직 실패의 두려움을 씹어 삼키고 미친 듯이 거친 바다로 돌진하는 자의 배만을 온 힘을 다해 밀어주는 법입니다. 단 1초도 주저하지 말고, 당신이 가진 가장 예리한 창을 세상의 가장 깊은 곳을 향해 힘껏 던지십시오.",
        "meaning_en": "Do not hide cowardly in the corner of your room, waiting only for perfect timing and comfortable conditions to be fully prepared. The massive waves that overturn life only push with all their might the ships of those who chew through the fear of failure and madly charge into the rough seas. Do not hesitate for even a single second; hurl the sharpest spear you possess toward the deepest part of the world with all your strength."
      }
    ]
  },
  "walt-disney": {
    "era_ko": "20세기의 거인 (1901~1966)",
    "era_en": "20th Century Giant (1901~1966)",
    "category": "arts",
    "epic_ko": "어린 시절, 가족 농장에서 뼈가 으스러지도록 혹독한 노동에 시달렸던 소년은 어두컴컴한 헛간의 생쥐라든가 농장의 동물들을 그리며 자신의 멱살을 잡고 있는 지독한 가난의 현실을 도피했습니다. 세계의 문화 대통령이 된 월트 디즈니의 시작은 결코 동화처럼 화려하고 낭만적이지 않았습니다. 청년이 되어 야심 차게 세운 첫 애니메이션 회사는 빚더미 속에 참담하게 파산했고, 뼈를 깎는 고생 끝에 만들어낸 첫 번째 성공작 '오스왈드 래빗'마저 악덕 배급사의 농간에 휘말려 판권과 유능한 애니메이터들을 몽땅 빼앗기는 비참한 사기를 당했습니다. 단 한 푼도 남지 않은 빈털터리가 되어 뉴욕에서 LA로 돌아오는 절망적이고 우울한 기차 안에서, 그는 분노의 눈물을 삼키며 낡은 수첩에 조그만 생쥐 한 마리를 쓱쓱 스케치했습니다. 그것이 바로 할리우드를 넘어 전 세계의 문화사를 영원히 뒤바꿔놓을 '미키 마우스'가 탄생하는 경이로운 순간이었습니다.\n\n그는 애니메이션이 단지 아이들이나 보는 시간 때우기용 저급한 장난이라는 세상의 오만한 편견을 산산조각 내버렸습니다. 역사상 최초로 캐릭터의 입모양과 소리가 일치하는 유성 애니메이션 '증기선 윌리'를 대성공시켰고, 모든 할리우드의 제작자들이 \"디즈니가 미쳤다. 분명 파산할 것이다\"라며 비웃었던 세계 최초의 장편 애니메이션 '백설공주와 일곱 난쟁이'를 제작하기 위해 자신이 살던 집마저 은행에 담보로 잡히는 광기를 보여주었습니다. 빛과 그림자 하나까지 파고드는 그의 지독하고 편집광적인 완벽주의는, 단순한 종이에 그려진 그림들이 마치 뜨거운 피가 흐르는 생명체처럼 관객의 눈물과 감동을 자아내게 만들었고, 마침내 극장 개봉 날 할리우드의 어른들을 기립박수와 눈물바다에 빠뜨렸습니다.\n\n거기에 멈추지 않고 그는 은막의 환상을 현실의 단단한 흙바닥 위에 진짜로 건설하겠다는 더욱 미치고 몽상적인 꿈을 꾸었습니다. 부모와 아이들이 세상의 지독한 현실을 잠시 잊고 영원한 동심으로 돌아갈 수 있는 거대하고 완벽한 마법의 왕국, '디즈니랜드'를 세운 것입니다. 비록 폐암으로 쓰러져 디즈니월드가 완공되는 환희의 순간을 보지 못하고 쓸쓸히 눈을 감았지만, 월트 디즈니의 삶은 가난과 끔찍한 사기라는 차갑고 잔혹한 현실 속에서도 '꿈꾸는 능력을 결코 잃지 않는 자'가 어떻게 이 거친 세상을 가장 압도적이고 아름다운 마법으로 물들일 수 있는지를 증명해 낸 불멸의 대서사시입니다.",
    "epic_en": "In his childhood, a boy who suffered bone-crushing, grueling labor on his family's farm escaped the harsh reality of severe poverty gripping his collar by drawing the mice in the dark barn and the farm animals. The beginnings of Walt Disney, who became the world's cultural president, were by no means glamorous or romantic like a fairy tale. His first animation company, ambitiously founded in his youth, went bankrupt miserably in a mountain of debt, and even his first successful work, 'Oswald the Lucky Rabbit,' created after bone-grinding hardship, was lost in a miserable fraud—losing both the rights and his talented animators to the manipulations of a ruthless distributor. Left completely penniless with not a single cent to his name, on a despairing, gloomy train ride back to LA from New York, he swallowed tears of anger and sketched a small mouse in his worn-out notebook. That was the marvelous moment when 'Mickey Mouse,' which would forever change the cultural history of the entire world beyond Hollywood, was born.\n\nHe shattered the world's arrogant prejudice that animation was merely a low-class toy for children to kill time. He succeeded massively with 'Steamboat Willie,' the first animated film in history where the characters' lip movements matched the sound, and demonstrated the madness of mortgaging his own home to the bank to produce the world's first feature-length animated film, 'Snow White and the Seven Dwarfs,' a project that all Hollywood producers mocked, saying, \"Disney is crazy; he will definitely go bankrupt.\" His fierce, paranoid perfectionism that scrutinized every single light and shadow made the drawings on plain paper evoke tears and deep emotion from the audience, as if they were living creatures with hot blood flowing through them, ultimately plunging the adults of Hollywood into a sea of tears and standing ovations on premiere night.\n\nNot stopping there, he dreamed an even crazier, more visionary dream: to genuinely construct the illusions of the silver screen on the solid soil of reality. He built 'Disneyland,' a massive, perfect magical kingdom where parents and children alike could momentarily forget the world's harsh reality and return to eternal childhood. Although he collapsed from lung cancer and passed away quietly without seeing the joyful moment of Disney World's completion, Walt Disney's life is an immortal epic proving how 'one who never loses the ability to dream' can paint this rough world with the most overwhelming and beautiful magic, even amidst the cold, cruel realities of poverty and horrific fraud.",
    "trials_ko": "뼈를 깎는 노력 끝에 세운 첫 회사의 파산과 성공작 판권 탈취라는 참혹한 배신, 장편 애니메이션의 막대한 제작비를 충당하기 위한 지독한 자금난, 그리고 끝없는 세상의 비웃음.",
    "trials_en": "The catastrophic betrayal of his first company's bankruptcy after bone-grinding effort and the theft of his successful work's rights, severe financial struggles to cover the massive production costs of a feature-length animation, and the world's endless mockery.",
    "overcoming_ko": "모든 것을 잃은 절망의 기차 안에서 미키 마우스를 창조해 냈고, 전 재산을 거는 광기 어린 도전으로 애니메이션을 숭고한 예술의 경지로, 환상을 디즈니랜드라는 현실의 마법으로 완벽히 승화시킴.",
    "overcoming_en": "He created Mickey Mouse on a train of despair after losing everything, and through a mad challenge risking his entire fortune, perfectly sublimated animation into the realm of sublime art and fantasy into the real-world magic of Disneyland.",
    "wisdom": [
      {
        "quote_ko": "꿈을 꿀 수 있다면, 해낼 수도 있다.",
        "quote_en": "If you can dream it, you can do it.",
        "meaning_ko": "당신의 앞을 가로막은 차갑고 거대한 현실의 벽 앞에서, 지레 겁을 먹고 위대한 상상하기를 멈추지 마십시오. 당신의 머릿속에 구체적이고 생생하게 그려낼 수 없는 꿈은, 현실에서도 결코 이루어질 수 없는 법입니다. 세상 사람들이 당신을 보며 손가락질하고 비웃을 만큼 거대하고 미친 꿈을 꾸십시오. 오직 그 미치도록 강렬한 꿈만이, 이 잿빛 세상을 당신만의 아름다운 마법으로 칠할 수 있는 유일한 붓이 되어줄 것입니다.",
        "meaning_en": "Do not be prematurely frightened and stop your great imagination before the cold, massive wall of reality blocking your path. A dream you cannot concretely and vividly picture in your mind can never be achieved in reality. Please dream a colossal, crazy dream big enough for the people of the world to point fingers and laugh at you. Only that maddeningly intense dream will become the sole brush capable of painting this gray world with your own beautiful magic."
      },
      {
        "quote_ko": "모든 역경과 실패는 나를 더 강하게 만들었다.",
        "quote_en": "All the adversity I've had in my life, all my troubles and obstacles, have strengthened me.",
        "meaning_ko": "당신이 가장 굳게 믿었던 이에게 철저히 배신당하고, 가진 것을 몽땅 빼앗겨 초라한 빈털터리가 되셨습니까? 그 피눈물 나는 참담한 절망감이야말로, 지금껏 당신 내면의 가장 깊은 곳에 잠들어 있던 '진짜 거인'을 후려쳐 깨우는 가장 날카로운 바늘입니다. 억울함의 눈물을 닦고, 당신이 쓰러진 바로 그 밑바닥에서 인생의 가장 위대한 스케치를 다시 시작하시길 바랍니다.",
        "meaning_en": "Have you been thoroughly betrayed by someone you trusted most firmly, lost everything you had, and become a shabby pauper? That miserable despair that brings tears of blood is the very sharpest needle that strikes and awakens the 'true giant' that has been sleeping deep within you until now. Wipe away your tears of grievance, and please begin life's greatest sketch anew right there on the bottom where you fell."
      },
      {
        "quote_ko": "차이를 만드는 것은 오직 끝까지 해내는 능력이다.",
        "quote_en": "The difference in winning and losing is most often...not quitting.",
        "meaning_ko": "이쯤 하면 충분하다며 적당히 타협하고 싶은 그 달콤한 유혹을, 뼈를 깎아내는 심정으로 단호히 거부하십시오. 99%의 완성과 100%의 완성 사이를 가르는 그 미세한 1%의 차이가, 결국 세상의 기립박수를 이끌어내는 가장 결정적인 차이인 법입니다. 당신이 가진 육체와 영혼의 모든 것을 갈아 넣어 당신의 일에 생명을 불어넣는 그 순간, 비로소 세상이 진동하는 진짜 마법이 펼쳐질 것입니다.",
        "meaning_en": "With a bone-grinding resolve, strictly reject the sweet temptation to compromise lazily, thinking this is enough. The minute 1% difference that separates 99% completion from 100% completion is ultimately the most decisive difference that draws the world's standing ovation. The moment you grind up everything of your body and soul to breathe life into your work, only then will true magic unfold, vibrating the world."
      }
    ]
  }
};

const finalNarratives = JSON.parse(fs.readFileSync('src/data/final-narratives.json', 'utf8'));

for (const [slug, data] of Object.entries(dataToInject)) {
  finalNarratives[slug] = data;
}

fs.writeFileSync('src/data/final-narratives.json', JSON.stringify(finalNarratives, null, 2), 'utf8');
console.log('Successfully injected Platinum rewritten giants (4-6) into final-narratives.json');
