const fs = require('fs');

const dataToInject = {
  "helen-keller": {
    "era_ko": "20세기의 거인 (1880~1968)",
    "era_en": "20th Century Giant (1880~1968)",
    "category": "arts",
    "epic_ko": "태어난 지 불과 19개월 무렵, 원인을 알 수 없는 끔찍한 급성 뇌척수막염이 아기 헬렌 켈러를 덮쳤습니다. 고열이 휩쓸고 지나간 자리에 남은 것은 빛과 소리가 완벽하게 소멸해 버린 절대적인 칠흑 같은 어둠과 침묵뿐이었습니다. 세상을 볼 수도, 들을 수도, 그래서 스스로 말을 배울 수도 없게 된 삼중고(三重苦)의 참혹한 감옥에 갇힌 어린 소녀는, 짐승처럼 울부짖으며 자신의 몸을 할퀴고 물어뜯는 난폭하고 통제 불능인 맹수로 변해갔습니다. 모두가 이 저주받은 아이의 인생이 그저 끔찍한 비극으로 끝날 것이라며 동정하고 포기했을 때, 그녀의 곁으로 앤 설리번이라는 한 줄기 눈부신 구원의 빛이 찾아왔습니다. 설리번 선생님 역시 과거에 시력을 잃어본 뼈저린 고통과 고아원의 끔찍한 학대를 견뎌낸 상처투성이의 영혼이었기에, 헬렌의 닫힌 문을 부수기 위해 자신의 손등을 내어주며 포기하지 않고 미친 듯이 문자를 가르쳤습니다.\n\n차가운 펌프실의 물줄기가 헬렌의 손등을 타고 흘러내리던 어느 운명적인 날, 설리번 선생님이 손바닥에 끊임없이 적어주던 'W-A-T-E-R'라는 단어가 마치 번개처럼 소녀의 뇌리를 강타했습니다. 사물에는 이름이 존재한다는, 인류 역사상 가장 위대하고 소름 끼치는 지적 폭발의 순간이었습니다. 그날 이후 그녀의 영혼을 옭아매고 있던 어둠의 족쇄는 산산조각 났습니다. 그녀는 손끝의 미세한 감각만으로 점자를 스펀지처럼 빨아들이며 읽었고, 타인의 입술과 성대의 미세한 떨림을 손으로 어루만지며 피나는 발성 연습 끝에 마침내 기적처럼 인간의 언어를 되찾았습니다. 하버드 대학교의 래드클리프 칼리지에 입학하여 비장애인들과 당당히 경쟁하며 학사 학위를 취득한 그녀의 모습은 전 세계를 경악과 감동의 도가니로 몰아넣었습니다.\n\n하지만 그녀는 자신의 기적적인 개인적 성공과 쏟아지는 찬사에 만족하며 안락한 삶에 안주하지 않았습니다. 그녀는 눈먼 자신보다, 세상의 부조리를 뻔히 두 눈으로 보면서도 외면하는 '영혼이 눈먼 자들'이 훨씬 더 불행하다며 통렬하게 세상을 일갈했습니다. 사회주의자이자 여성 참정권 운동가, 인종차별 철폐론자로 변신한 그녀는, 평생 전 세계를 누비며 시각 장애인뿐만 아니라 가난하고 억압받는 모든 약자들의 생존권을 위해 최전선에서 투쟁했습니다. 헬렌 켈러의 삶은, 시각과 청각이라는 인간의 가장 기본적인 감각이 철저히 거세당한 최악의 지옥 속에서도, '포기하지 않는 맹렬한 의지'와 '배움을 향한 갈망'이 한 인간을 얼마나 위대하고 거대한 빛으로 진화시킬 수 있는지를 증명한 인류 역사상 가장 숭고한 기적의 대서사시입니다.",
    "epic_en": "At a mere 19 months of age, a horrific, mysterious acute meningitis struck baby Helen Keller. In the wake of the high fever, all that remained was an absolute, pitch-black darkness and silence where light and sound had perfectly ceased to exist. Trapped in a catastrophic prison of triple afflictions—unable to see the world, unable to hear it, and thus unable to learn to speak—the young girl devolved into a violent, uncontrollable beast, howling like an animal and scratching and biting her own body. When everyone pitied her and gave up, believing this cursed child's life would merely end in horrific tragedy, a dazzling ray of salvation named Anne Sullivan arrived by her side. Teacher Sullivan was a scarred soul herself, having endured the bitter pain of losing her vision in the past and horrific abuse in an orphanage; thus, to break down Helen's closed doors, she offered the back of her own hand and madly taught her letters without ever giving up.\n\nOn a fateful day when the cold stream of water from the pump house cascaded over Helen's hand, the word 'W-A-T-E-R' that Teacher Sullivan had relentlessly spelled into her palm struck the girl's mind like lightning. It was the moment of the greatest, most chilling intellectual explosion in human history: the realization that things have names. From that day forward, the shackles of darkness binding her soul shattered into pieces. She absorbed Braille like a sponge using only the subtle sensations of her fingertips, and after blood-curdling vocal practice by touching the minute vibrations of others' lips and vocal cords, she finally miraculously regained human speech. Entering Radcliffe College at Harvard University and competing proudly alongside non-disabled peers to earn her bachelor's degree, she threw the entire world into a cauldron of shock and deep emotion.\n\nHowever, she did not settle for a comfortable life, satisfied with her miraculous personal success and the pouring accolades. She fiercely rebuked the world, declaring that 'those who are blind in their souls'—who clearly see the world's absurdities with both eyes yet turn away—are far more miserable than her blind self. Transforming into a socialist, a women's suffrage activist, and an abolitionist of racial discrimination, she traveled the globe her entire life, struggling at the forefront not only for the visually impaired but for the right to survive of all the poor and oppressed marginalized people. Helen Keller's life is the most sublime epic of miracles in human history, proving how 'a fierce, unyielding will' and 'a thirst for learning' can evolve a human into a great, colossal light, even in the worst hell where humanity's most basic senses of sight and hearing are thoroughly castrated.",
    "trials_ko": "생후 19개월 만에 시각과 청각을 동시에 상실하여 언어조차 배울 수 없었던 삼중고(三重苦)의 참혹하고 절대적인 고립, 그리고 평생을 그림자처럼 따라다닌 신체적 장애라는 거대한 장벽.",
    "trials_en": "The horrific, absolute isolation of the triple afflictions—losing both sight and hearing at just 19 months old, rendering her unable to even learn language—and the massive barrier of severe physical disability that followed her like a shadow her entire life.",
    "overcoming_ko": "설리번 선생님과의 피눈물 나는 교감으로 장애의 족쇄를 박살 내고 언어와 학문을 마스터했으며, 개인의 기적적 성취를 넘어 억압받는 모든 약자들의 인권을 위해 전 세계를 누비며 맹렬히 투쟁함.",
    "overcoming_en": "Shattering the shackles of disability and mastering language and academics through tearful, bloody communion with Teacher Sullivan, she went beyond miraculous personal achievement to fiercely struggle worldwide for the human rights of all oppressed and marginalized people.",
    "wisdom": [
      {
        "quote_ko": "시력을 잃은 것보다 더 비극적인 일은 눈은 보이지만 비전(Vision)이 없는 것이다.",
        "quote_en": "The only thing worse than being blind is having sight but no vision.",
        "meaning_ko": "단지 두 눈을 뜨고 세상을 선명하게 바라볼 수 있다고 해서 당신이 진정으로 눈뜬 자라 착각하지 마십시오. 가슴속을 뜨겁게 달구는 위대한 꿈과 확고한 목적의식, 즉 '비전'이 없다면, 두 눈이 멀쩡해도 칠흑 같은 어둠 속을 헤매는 맹인보다 훨씬 더 비참하고 허망한 삶일 뿐입니다. 영혼의 눈을 크게 뜨십시오.",
        "meaning_en": "Do not mistakenly believe you are truly awakened just because you can open your two eyes and see the world clearly. If you lack a great dream and a firm sense of purpose that hotly ignites your heart—that is, 'vision'—then even with perfectly healthy eyes, your life is far more miserable and vain than a blind person wandering in pitch-black darkness. Open the eyes of your soul wide."
      },
      {
        "quote_ko": "비관주의자는 별의 비밀을 발견하거나, 미지의 섬으로 항해하거나, 인간 영혼의 새로운 지평을 열어주지 못한다.",
        "quote_en": "No pessimist ever discovered the secrets of the stars, or sailed to an uncharted land, or opened a new heaven to the human spirit.",
        "meaning_ko": "현실의 차가운 벽에 부딪힐 때마다 냉소적으로 한숨 쉬며, 모든 일의 안 되는 이유만을 교묘하게 찾아내는 비관주의의 늪에 빠지지 마시길 바랍니다. 인류 역사의 거대한 진보와 당신 삶의 눈부신 기적은 오직 한계 앞에서도 희망을 맹렬하게 부르짖으며 무모하게 뛰어드는 광기 어린 낙관주의자들의 손에서만 탄생하는 법입니다.",
        "meaning_en": "I hope you will not fall into the swamp of pessimism, cynically sighing every time you hit the cold walls of reality and cunningly finding only the reasons why things won't work. The colossal progress of human history and the dazzling miracles of your life are born solely from the hands of those crazed optimists who fiercely cry out for hope and recklessly plunge in even before their limits."
      },
      {
        "quote_ko": "세상이 비록 고통으로 가득 차 있지만, 그것을 극복하는 힘 또한 가득 차 있다.",
        "quote_en": "Although the world is full of suffering, it is also full of the overcoming of it.",
        "meaning_ko": "잔혹한 세상이 수없이 당신을 무참히 짓밟고 가혹한 고통의 나락으로 밀어 떨어뜨리려 할지라도 결코 절망의 구석에 웅크리고 포기하지 마십시오. 당신의 영혼 가장 깊은 곳에는 그 어떤 참혹한 지옥의 불길조차 가볍게 짓밟고 우뚝 일어설 수 있는, 경이롭고 거대한 초인적인 회복의 에너지가 이미 폭발할 준비를 마친 채 숨겨져 있습니다.",
        "meaning_en": "Even if the cruel world ruthlessly tramples you countless times and tries to push you down into the abyss of harsh suffering, never crouch in the corner of despair and give up. Hidden in the deepest part of your soul is a marvelous, colossal, superhuman energy of recovery—already prepared to explode—that can lightly trample and rise tall above the flames of even the most horrific hell."
      }
    ]
  },
  "stephen-hawking": {
    "era_ko": "20세기의 거인 (1942~2018)",
    "era_en": "20th Century Giant (1942~2018)",
    "category": "science",
    "epic_ko": "우주의 기원과 별들의 탄생을 탐구하던 전도유망한 스물한 살의 천재 물리학도 스티븐 호킹. 그러나 찬란해야 할 그의 청춘에 어느 날 갑자기 루게릭병(근위축성측삭경화증)이라는 사형 선고가 날아들었습니다. \"앞으로 살날이 2년밖에 남지 않았습니다.\" 온몸의 근육이 서서히 말라 비틀어져 죽어가는 이 참혹하고 불치인 병은, 걷고 말하는 숨 쉬는 모든 육체적 자유를 가차 없이 앗아갔습니다. 시한부 선고를 받고 지독한 우울증의 늪에 빠져 술과 바그너의 음악으로 도피하던 그에게, 세상은 끝없는 절망만을 속삭였습니다. 하지만 그 깊은 절망의 밑바닥에서 그의 심장을 다시 뛰게 한 것은, 사랑하는 연인 제인 와일드와의 결혼, 그리고 \"아직 나에게는 우주의 비밀을 파헤칠 뇌가 온전히 살아있다\"는 맹렬한 깨달음이었습니다.\n\n점점 굳어가는 손가락과 뒤틀려가는 육체라는 끔찍한 감옥 속에 갇혀서도, 그의 찬란하고 위대한 정신만은 결코 휠체어에 결박당하지 않았습니다. 목소리를 완전히 잃어버려 뺨의 미세한 근육 떨림만으로 음성 합성기를 조작해 단어를 힘겹게 한 글자 한 글자 골라야 하는 끔찍한 극도의 불편함 속에서도, 그는 일반인들은 감히 상상조차 할 수 없는 광활하고 거대한 우주로 자유롭게 비상했습니다. 마침내 그는 모든 것을 빨아들이기만 한다고 믿어졌던 블랙홀이 빛과 입자를 방출하며 증발할 수 있다는 '호킹 복사(Hawking Radiation)' 이론을 발표하여, 낡은 양자역학과 상대성이론을 결합시키는 세기의 대통합을 이뤄내며 전 세계 과학계를 발칵 뒤집어 놓았습니다.\n\n그가 단 몇 개의 손가락으로 수년에 걸쳐 피땀 흘려 집필한 '시간의 역사'는 전 세계적으로 수천만 부가 팔리며 대중들에게 우주의 신비를 선사했습니다. 호킹은 2년이라는 시한부 선고를 비웃듯 무려 55년을 더 치열하게 살아남으며, 무중력 체험을 하고 유명 시트콤에 출연하는 등 인생의 유머와 도전을 결코 멈추지 않았습니다. 스티븐 호킹의 삶은, 비록 육체는 단 1센티미터도 마음대로 움직일 수 없는 가장 처참한 감옥에 철저히 갇혔을지라도, 진정으로 자유로운 인간의 상상력과 위대한 의지는 수백억 광년의 저 아득하고 거대한 우주조차 완벽하게 집어삼킬 수 있음을 입증한 인류 역사상 가장 찬란하고 경이로운 과학적 서사시입니다.",
    "epic_en": "Stephen Hawking, a promising twenty-one-year-old genius physics student exploring the origins of the universe and the birth of stars. However, a death sentence suddenly struck his brilliant youth: Lou Gehrig's disease (ALS). \"You have only two years left to live.\" This horrific, incurable disease, in which the muscles of the entire body slowly wither and die, ruthlessly stripped away every physical freedom to walk, speak, and even breathe. Plunging into the swamp of severe depression after receiving his terminal diagnosis, escaping through alcohol and Wagner's music, the world whispered only endless despair to him. Yet, at the very bottom of that profound despair, what made his heart beat again was his marriage to his beloved Jane Wilde, and the fierce realization that \"My brain, capable of unraveling the secrets of the universe, is still perfectly alive.\"\n\nEven trapped in the horrific prison of increasingly stiffening fingers and a twisting body, his brilliant and great mind was never bound to a wheelchair. Amidst the extreme, horrific discomfort of completely losing his voice and having to painstakingly select words letter by letter by manipulating a voice synthesizer using only the minute twitches of his cheek muscle, he soared freely into a vast, colossal universe that ordinary people could scarcely even imagine. Finally, he announced the 'Hawking Radiation' theory—that black holes, previously believed to only suck everything in, can emit light and particles and evaporate—achieving the century's grand unification of classical quantum mechanics and the theory of relativity, turning the global scientific community upside down.\n\n'A Brief History of Time,' a book he spent years writing through blood and sweat with just a few fingers, sold tens of millions of copies worldwide, bestowing the mysteries of the universe upon the public. As if mocking his two-year terminal diagnosis, Hawking fiercely survived an astounding 55 more years, never stopping his humor and challenges in life—even experiencing zero gravity and appearing on famous sitcoms. Stephen Hawking's life is the most brilliant and marvelous scientific epic in human history, proving that even if the physical body is thoroughly locked in the most miserable prison unable to move even one centimeter at will, the imagination and great will of a truly free human being can perfectly swallow even that distant, colossal universe of tens of billions of light-years.",
    "trials_ko": "21살에 내려진 루게릭병이라는 잔혹한 사형 선고, 온몸의 근육이 마비되어 휠체어에 갇히고 목소리마저 잃어버린 극도의 육체적 절망과 감옥 같은 고립감.",
    "trials_en": "The cruel death sentence of ALS handed down at 21, the extreme physical despair and prison-like isolation of having his entire body's muscles paralyzed, confining him to a wheelchair and completely losing his voice.",
    "overcoming_ko": "부서져 가는 육체적 한계를 아득히 초월하는 위대한 정신력과 상상력으로 '호킹 복사' 이론 등 우주 물리학의 거대한 업적을 이룩하며, 인간 정신의 무한한 자유를 증명함.",
    "overcoming_en": "Transcending his crumbling physical limitations by far with great mental strength and imagination, he achieved colossal milestones in astrophysics, such as the 'Hawking Radiation' theory, proving the infinite freedom of the human spirit.",
    "wisdom": [
      {
        "quote_ko": "내 몸은 휠체어에 갇혀 있지만, 내 마음은 우주를 날아다닌다.",
        "quote_en": "Although I cannot move and I have to speak through a computer, in my mind I am free.",
        "meaning_ko": "당신이 처한 초라한 현실의 제약과 부족한 자원들을 끝없이 핑계 삼으며, 불평불만 속에 자신을 가둬두지 마십시오. 육체가 1평짜리 차가운 독방에 철저히 갇히고 두 다리가 묶여있을지언정, 당신의 머릿속에서 폭발하는 광활하고 무한한 영혼의 상상력만큼은 수백억 광년 밖의 우주조차 완벽하게 넘나들 수 있는 절대적인 자유를 누리고 있음을 깨달으셔야 합니다.",
        "meaning_en": "Do not endlessly use the restrictions of your shabby reality and lacking resources as excuses, locking yourself away in complaints and dissatisfaction. Even if your physical body is thoroughly trapped in a cold, one-square-meter solitary cell and your two legs are bound, you must realize that the vast, infinite imagination of your soul exploding within your mind enjoys the absolute freedom to perfectly traverse even the universe tens of billions of light-years away."
      },
      {
        "quote_ko": "삶이 아무리 힘들어 보여도, 당신이 할 수 있고 성공할 수 있는 무언가는 항상 존재한다. 중요한 것은 포기하지 않는 것이다.",
        "quote_en": "However difficult life may seem, there is always something you can do and succeed at. It matters that you don't just give up.",
        "meaning_ko": "모든 문이 쾅 하고 닫히고 사방이 캄캄한 절벽으로 둘러싸여 숨조차 쉴 수 없는 것 같은 끔찍한 절망의 순간에도, 당신이 기어이 파고들어 꽃을 피워낼 수 있는 단 하나의 작은 틈새는 세상 어딘가에 반드시 존재하는 법입니다. 남들이 불가능하다고 비웃든 말든, 당신의 심장이 뛰고 있는 한 결단코 삶을 포기하는 비겁한 짓은 하지 마시길 바랍니다.",
        "meaning_en": "Even in horrific moments of despair when every door slams shut and you are surrounded by pitch-black cliffs, seemingly unable to even breathe, there is always absolutely one small crevice somewhere in the world where you can stubbornly dig in and bloom a flower. Whether others mock it as impossible or not, I hope you never commit the cowardly act of giving up on life as long as your heart is beating."
      },
      {
        "quote_ko": "우주의 기본 법칙 중 하나는 완벽한 것은 없다는 것이다. 불완전함이 없었다면 당신도 나도 존재하지 않았을 것이다.",
        "quote_en": "One of the basic rules of the universe is that nothing is perfect. Perfection simply doesn't exist.....Without imperfection, neither you nor I would exist.",
        "meaning_ko": "당신이 가진 뼈아픈 결함과 씻고 싶은 치명적인 콤플렉스를 부끄러워하며 숨기려 애쓰지 마십시오. 완벽에 도달하려는 강박관념은 오히려 당신을 갉아먹을 뿐입니다. 우주조차도 미세한 불균형과 불완전함의 폭발 속에서 지금의 찬란한 별들을 잉태했습니다. 당신의 그 거칠고 모난 상처투성이의 불완전함이야말로, 당신이라는 우주를 가장 유일하고 매혹적인 존재로 완성시키는 눈부신 특권임을 잊지 마십시오.",
        "meaning_en": "Do not try to hide the bitter flaws and fatal complexes you wish to wash away out of shame. The obsessive compulsion to reach perfection will only gnaw away at you. Even the universe birthed its currently brilliant stars within explosions of minute imbalances and imperfections. Do not forget that your rough, jagged, scar-filled imperfection is the very dazzling privilege that completes the universe named 'you' into the most unique and captivating existence."
      }
    ]
  },
  "malala-yousafzai": {
    "era_ko": "21세기의 거인 (1997~ )",
    "era_en": "21st Century Giant (1997~ )",
    "category": "leadership",
    "epic_ko": "총성방울이 빗발치고 피비린내가 진동하는 파키스탄 스와트 밸리. 극단주의 무장 단체 탈레반이 마을을 무력으로 장악하고, \"여성들이 학교에 가는 것은 신에 대한 반역\"이라며 여학교들을 무참히 폭파시켜 버렸을 때, 모든 사람들은 숨죽여 떨었습니다. 하지만 불과 11살의 앳된 소녀 말랄라 유사프자이는 그들의 미개한 야만에 굴복하지 않았습니다. 아버지가 운영하는 학교에 다니며 학문적 호기심을 키워가던 그녀는, 가명으로 BBC 블로그에 탈레반 통치하의 끔찍한 실상을 폭로하는 글을 올리며, 목숨을 걸고 여자아이들의 '교육받을 권리'를 전 세계에 맹렬히 부르짖었습니다.\n\n그녀의 용기 있는 목소리가 널리 퍼져나가며 탈레반의 거대한 심기를 건드리자, 어느 날 하굣길 스쿨버스에 복면을 쓴 무장 괴한이 난입했습니다. \"누가 말랄라냐?\"라는 살기 어린 외침 직후, 괴한이 쏜 총탄이 15살 소녀의 머리와 목을 잔혹하게 관통했습니다. 선혈이 낭자한 채 쓰러진 그녀를 보며 탈레반은 드디어 눈엣가시를 제거했다고 기뻐했지만, 총알은 결단코 그녀의 위대한 신념을 뚫지 못했습니다. 기적적으로 목숨을 건진 후 영국에서 여러 차례의 끔찍한 대수술을 받고 깨어난 그녀는, 총구의 공포에 질려 침묵하기는커녕 더욱 강철처럼 단단해져 세상 밖으로 다시 걸어 나왔습니다.\n\n유엔 연설대에 오른 16살의 이 작은 거인은 전 세계의 정상들 앞에서 흔들림 없는 단호한 목소리로 일갈했습니다. \"탈레반은 총알로 우리를 침묵시킬 수 있다고 생각했지만, 그들은 실패했습니다. 그날 약약함과 공포, 절망이 죽고 힘과 용기가 태어났습니다.\" 역사상 최연소인 17세의 나이로 노벨 평화상을 수상하며 전 세계의 찬사를 받았음에도, 그녀는 그 영광에 도취하지 않고 아프리카와 시리아 난민촌 등 전 세계의 소외된 소녀들을 위한 가장 치열한 전방위 투쟁을 지금 이 순간에도 이어가고 있습니다. 말랄라의 삶은, 권력자의 무자비한 총칼과 끔찍한 테러조차 책을 펼쳐 든 어린 소녀의 숭고한 용기 앞에서는 한낱 무력한 쇳덩어리에 불과하다는 것을 증명해 낸 가장 위대하고 가슴 뜨거운 승리의 서사시입니다.",
    "epic_en": "In Pakistan's Swat Valley, where hailstorms of bullets rained and the stench of blood lingered. When the extremist armed group Taliban seized the village by force and ruthlessly blew up girls' schools, declaring that \"women going to school is treason against God,\" everyone trembled in bated breath. However, Malala Yousafzai, a tender girl of merely 11 years old, did not submit to their barbaric ignorance. Nurturing her academic curiosity by attending the school her father ran, she used a pseudonym to post articles on a BBC blog exposing the horrific reality under Taliban rule, fiercely crying out to the world for the 'right to education' for girls, risking her very life.\n\nAs her courageous voice spread far and wide, touching the colossal nerves of the Taliban, one day masked armed assailants stormed her school bus on the way home. Following the murderous shout, \"Who is Malala?\" a bullet fired by a gunman brutally pierced the head and neck of the 15-year-old girl. Seeing her collapse covered in fresh blood, the Taliban rejoiced that they had finally removed the thorn in their side, but the bullet categorically failed to pierce her great conviction. Miraculously surviving and waking up after several horrific major surgeries in the UK, rather than remaining silent out of terror from the muzzle, she emerged back into the world even more hardened like steel.\n\nStepping onto the UN podium, this 16-year-old little giant roared before the world's leaders with an unwavering, resolute voice: \"The Taliban thought that the bullets would silence us, but they failed. And out of that silence came thousands of voices. Weakness, fear, and hopelessness died. Strength, power, and courage was born.\" Even after receiving global acclaim by winning the Nobel Peace Prize at the age of 17, making her the youngest laureate in history, she did not become intoxicated by the glory. To this very moment, she continues her fiercest, all-encompassing struggles for marginalized girls worldwide, including those in African and Syrian refugee camps. Malala's life is the most immense, heart-pounding epic of victory, proving that even a tyrant's ruthless guns and horrific terror are but helpless lumps of iron before the sublime courage of a young girl holding an open book.",
    "trials_ko": "여성의 교육과 권리를 철저히 억압하는 탈레반의 무자비한 폭압 통치, 그리고 15살의 어린 나이에 머리에 총탄을 맞고 생사를 오가는 끔찍한 테러를 당한 극단의 생존 위협.",
    "trials_en": "The ruthless, oppressive rule of the Taliban thoroughly suppressing women's education and rights, and the extreme threat to survival of suffering a horrific terrorist attack, taking a bullet to the head at the tender age of 15, hovering between life and death.",
    "overcoming_ko": "머리에 총을 맞는 끔찍한 공포 앞에서도 결코 침묵하지 않고, 오히려 기적적으로 살아나 세계의 무대에서 교육의 힘을 부르짖으며 최연소 노벨평화상 수상자이자 억압받는 모든 소녀들의 희망으로 우뚝 섬.",
    "overcoming_en": "Never remaining silent even before the horrific terror of being shot in the head, she instead miraculously survived to roar the power of education on the global stage, standing tall as the youngest Nobel Peace Prize laureate and the hope for all oppressed girls.",
    "wisdom": [
      {
        "quote_ko": "한 명의 아이, 한 명의 선생님, 한 권의 책, 그리고 한 자루의 펜이 세상을 바꿀 수 있습니다.",
        "quote_en": "One child, one teacher, one book, one pen can change the world.",
        "meaning_ko": "세상의 거대한 불의와 거악 앞에서 당신이 쥐고 있는 무기가 너무나 작고 초라해 보인다고 지레 포기하며 눈물 흘리지 마십시오. 칼과 총은 인간의 육체를 파괴할 뿐이지만, 교육의 빛과 당신의 작은 펜촉 하나는 폭군들의 심장을 가장 서늘하게 얼어붙게 만들고 세상의 거대한 어둠을 걷어내는 가장 파괴적이고 무서운 무기임을 반드시 기억하십시오.",
        "meaning_en": "Do not preemptively give up and shed tears, thinking the weapon you hold seems too small and shabby before the world's colossal injustices and great evils. Swords and guns only destroy the human body, but please remember that the light of education and your single small pen nib are the most destructive and terrifying weapons that freeze the hearts of tyrants the coldest and sweep away the world's colossal darkness."
      },
      {
        "quote_ko": "나는 내 얼굴에 총을 쏜 사람도 용서했습니다. 이것이 바로 나의 종교가 가르쳐 준 용서입니다.",
        "quote_en": "I don't want revenge on the Taliban, I want education for sons and daughters of the Taliban.",
        "meaning_ko": "당신의 영혼에 씻을 수 없는 끔찍한 상처와 공포를 각인시킨 자들에게, 똑같은 피의 복수로 갚아주려며 당신의 소중한 인생을 분노의 노예로 전락시키지 마시길 바랍니다. 진정으로 위대하고 가장 잔인한 복수는, 오히려 그들을 압도적으로 용서해버리고, 당신이 그토록 이루고 싶었던 눈부신 선한 목표를 기어이 달성해 내어 그들을 한없이 초라하게 만들어버리는 것입니다.",
        "meaning_en": "I hope you do not degrade your precious life into a slave of anger by trying to repay those who etched unerasable, horrific wounds and terror into your soul with the exact same bloody revenge. Truly great and the most cruel revenge is to instead overwhelmingly forgive them, and to relentlessly achieve the dazzling, good goal you so desperately wanted, rendering them infinitely pathetic."
      },
      {
        "quote_ko": "목소리를 높일 수 있는 힘이 있는데 왜 침묵해야 합니까?",
        "quote_en": "When the whole world is silent, even one voice becomes powerful.",
        "meaning_ko": "모두가 두려움에 떨며 부조리와 악습 앞에 비겁하게 침묵할 때, 타인의 시선 뒤로 교묘하게 숨어 당신의 양심마저 침묵시키지 마십시오. 거대한 침묵 속에서 용기 있게 터져 나오는 단 한 사람의 외침은, 견고한 권력의 철벽을 산산조각 내는 벼락보다 무거운 폭발력을 지니고 있습니다. 당신의 입술을 열어 세상의 불의를 향해 거침없이 포효하십시오.",
        "meaning_en": "When everyone is trembling in fear and cowardly silent before absurdity and evil customs, do not cunningly hide behind the gaze of others and silence even your own conscience. The single cry courageously bursting out from a massive silence carries an explosive power heavier than a thunderbolt that shatters the solid iron walls of power. Open your lips and roar relentlessly at the world's injustices."
      }
    ]
  }
};

const finalNarratives = JSON.parse(fs.readFileSync('src/data/final-narratives.json', 'utf8'));

for (const [slug, data] of Object.entries(dataToInject)) {
  finalNarratives[slug] = data;
}

fs.writeFileSync('src/data/final-narratives.json', JSON.stringify(finalNarratives, null, 2), 'utf8');
console.log('Successfully injected Platinum rewritten giants (14-16) into final-narratives.json');
