const fs = require('fs');

const dataToInject = {
  "franklin-d-roosevelt": {
    "era_ko": "20세기의 거인 (1882~1945)",
    "era_en": "20th Century Giant (1882~1945)",
    "category": "leadership",
    "epic_ko": "미국 최고의 명문가 출신으로 탄탄대로의 젊은 시절을 보내며 떠오르는 정치 신성으로 주목받던 프랭클린 D. 루스벨트. 그러나 39세의 한창나이에 차가운 호수에서 수영을 한 뒤, 그의 인생을 영원히 뒤바꿔놓을 잔혹한 비극이 들이닥쳤습니다. 소아마비로 인해 하반신이 완전히 마비되어, 평생 두 다리로 땅을 딛고 일어설 수 없는 치명적인 불구의 몸이 된 것입니다. 휠체어에 갇혀 절망의 늪에 빠질 법도 했지만, 그는 쇠로 된 10kg짜리 무거운 다리 보호대를 차고 지옥 같은 통증을 견디며 지팡이에 의지해 다시 대중 앞에 당당히 서는 초인적인 불굴의 의지를 보여주었습니다. 육체의 마비는 역설적으로 그의 오만했던 귀족적 영혼을 가장 낮고 소외된 자들의 고통에 공감하는 따뜻하고 거대한 리더의 심장으로 진화시켰습니다.\n\n그가 미국 대통령에 취임했을 때, 나라는 역사상 유례없는 최악의 경제 대공황으로 산산조각 나 있었습니다. 거리에는 실업자들이 넘쳐나고 은행들은 도산했으며, 미국 국민들의 가슴속에는 내일 당장 굶어 죽을지 모른다는 짙은 절망과 공포만이 맴돌았습니다. 그때 그는 라디오 마이크 앞에 앉아 따뜻하고 확신에 찬 목소리로 '노변담화(Fireside Chats)'를 진행하며 \"우리가 두려워해야 할 유일한 것은 두려움 그 자체입니다\"라고 미국인들의 심장을 맹렬하게 깨웠습니다. 자유방임주의라는 낡은 경제 교리를 과감히 쓰레기통에 처박고, 정부가 적극적으로 시장에 개입하여 공공사업을 일으키는 파격적인 '뉴딜 정책(New Deal)'을 밀어붙여 무너져가는 미국 자본주의의 심장을 다시 강제 박동시켰습니다.\n\n그의 시련은 여기서 끝나지 않았습니다. 일본의 진주만 기습으로 발발한 제2차 세계대전이라는 인류 역사상 최악의 학살극 한가운데서, 그는 소아마비로 병들어가는 몸을 이끌고 세계를 구원할 연합군의 거대한 기둥으로 우뚝 섰습니다. 처칠, 스탈린과 함께 전쟁을 이끌며 파시즘의 어둠으로부터 세계의 자유를 수호한 그는, 전쟁의 승리와 미국의 완전한 경제 회복을 눈앞에 둔 채 조용히 숨을 거두었습니다. 미국 역사상 유일무이한 4선 대통령이라는 대기록을 남긴 프랭클린 D. 루스벨트의 삶은, 두 다리를 잃은 극복 불가능해 보이는 개인의 참혹한 비극조차 오히려 절망에 빠진 전 세계를 구원하는 가장 눈부시고 위대한 동력으로 승화될 수 있음을 증명한 압도적인 승리의 서사시입니다.",
    "epic_en": "Franklin D. Roosevelt, born into America's most prestigious family, spending his youth on a smooth path and receiving attention as a rising political star. However, in his prime at age 39, a cruel tragedy struck after swimming in a cold lake, permanently altering his life. Paralyzed from the waist down by polio, he became fatally crippled, unable to ever stand on his two feet on the ground again. Though he could have fallen into the swamp of despair trapped in a wheelchair, he demonstrated superhuman, indomitable will, strapping on heavy 10kg iron leg braces and enduring hellish pain to stand proudly before the public once again, leaning on a cane. Paradoxically, the paralysis of his body evolved his arrogant aristocratic soul into the warm, colossal heart of a leader who empathized with the suffering of the lowest and most marginalized.\n\nWhen he was inaugurated as US President, the nation was shattered by the worst Great Depression in history, unprecedented in scope. Streets overflowed with the unemployed, banks went bankrupt, and only a dense despair and terror of potentially starving to death tomorrow lingered in the hearts of the American people. At that moment, sitting before a radio microphone with a warm, confident voice conducting his 'Fireside Chats,' he fiercely awakened the hearts of Americans, declaring, \"The only thing we have to fear is fear itself.\" Boldly tossing the old economic doctrine of laissez-faire into the trash, he aggressively pushed forward the unconventional 'New Deal'—having the government actively intervene in the market to initiate public works—forcibly restarting the failing heart of American capitalism.\n\nHis trials did not end there. In the midst of World War II, the worst massacre in human history sparked by the Japanese surprise attack on Pearl Harbor, he led his disease-ridden, polio-stricken body to stand tall as the massive pillar of the Allied forces to save the world. Leading the war alongside Churchill and Stalin, defending the world's freedom from the darkness of fascism, he passed away quietly just on the verge of wartime victory and America's complete economic recovery. Leaving the monumental record as the one and only four-term president in US history, Franklin D. Roosevelt's life is an overwhelming epic of victory, proving that even a seemingly insurmountable personal tragedy—the horrific loss of his two legs—could instead be sublimated into the most dazzling and great driving force to save a world drowning in despair.",
    "trials_ko": "39세 한창나이에 소아마비로 인한 하반신 영구 마비라는 참혹한 신체적 절망, 취임 직후 마주한 전례 없는 최악의 경제 대공황, 그리고 인류 역사상 최악의 전쟁인 제2차 세계대전의 참상.",
    "trials_en": "The horrific physical despair of permanent lower-body paralysis from polio in his prime at age 39, the unprecedented worst Great Depression faced immediately upon taking office, and the atrocities of World War II, the worst war in human history.",
    "overcoming_ko": "무거운 철제 보호대와 지팡이에 의지해 두 발로 서는 초인적 의지로 대중 앞에 섰으며, '뉴딜 정책'과 '노변담화'로 대공황의 공포를 이겨내고 제2차 세계대전을 연합군의 승리로 이끌며 자유세계를 수호함.",
    "overcoming_en": "Standing before the public with superhuman will to stand on two feet relying on heavy iron braces and a cane, he overcame the terror of the Great Depression with the 'New Deal' and 'Fireside Chats,' and defended the free world by leading the Allies to victory in World War II.",
    "wisdom": [
      {
        "quote_ko": "우리가 두려워해야 할 유일한 것은 두려움 그 자체입니다.",
        "quote_en": "The only thing we have to fear is fear itself.",
        "meaning_ko": "눈앞에 닥친 끔찍한 경제적 위기나 실패보다 당신을 진짜로 파멸시키는 것은, 한 번도 일어난 적 없는 최악의 상황을 상상하며 뒷걸음질 치게 만드는 내면의 허상, 즉 '두려움'입니다. 보이지 않는 유령 같은 두려움에 사로잡혀 당신의 귀중한 영혼을 갉아먹게 내버려 두지 마십시오. 당당하게 가슴을 펴고 그 두려움의 실체를 정면으로 쏘아보며 과감하게 전진하시길 바랍니다.",
        "meaning_en": "What truly destroys you more than the horrific economic crisis or failure immediately before you is the internal illusion—'fear'—that makes you step back while imagining the worst-case scenario that has never even happened. Do not allow yourself to be consumed by invisible, ghost-like fear and let it gnaw at your precious soul. Proudly stick your chest out, glare directly at the true nature of that fear, and boldly march forward."
      },
      {
        "quote_ko": "항구를 떠나지 않는 배는 안전하지만, 그것이 배가 만들어진 이유는 아니다.",
        "quote_en": "A smooth sea never made a skilled sailor.",
        "meaning_ko": "세상의 비바람을 피해 안전하고 따뜻한 방구석에만 숨어 안주하려 하지 마십시오. 단 한 번의 실패도, 상처도 없이 평온하게만 살아가는 것은 당신이 가진 무한한 잠재력에 대한 가장 끔찍한 직무유기입니다. 거친 파도 속으로 기꺼이 배를 몰고 들어가, 무자비한 폭풍우를 온몸으로 두들겨 맞으며 당신만의 위대한 항로를 개척해 내는 진짜 선장이 되십시오.",
        "meaning_en": "Do not seek to settle by hiding only in the safe, warm corner of your room to avoid the wind and rain of the world. Living peacefully without a single failure or wound is the most horrific dereliction of duty regarding the infinite potential you possess. Willingly steer your ship into the rough waves, get battered by the merciless storm with your whole body, and become a true captain who pioneers your own great voyage."
      },
      {
        "quote_ko": "상식에 어긋나는 일은 시도해 보라. 실패하면 솔직히 인정하고 다른 것을 시도하라. 무엇이든 시도해 보는 것이 중요하다.",
        "quote_en": "It is common sense to take a method and try it. If it fails, admit it frankly and try another. But above all, try something.",
        "meaning_ko": "완벽한 계획과 정답이 주어질 때까지 행동을 멈춘 채 머뭇거리며 당신의 젊은 시간을 허비하지 마시길 바랍니다. 때로는 남들이 미쳤다고 손가락질하는 파격적인 방법조차 일단 저질러 보는 맹렬한 실행력이 필요합니다. 호기롭게 시도했다가 뼈아프게 넘어졌다면, 군말 없이 깨끗하게 패배를 인정하고 훌훌 털고 일어나 즉시 새로운 실험을 다시 시작하면 그만입니다.",
        "meaning_en": "I hope you do not waste your young time hesitating and stopping action until a perfect plan and the right answer are given. Sometimes, a fierce execution power is needed to just blindly try even unconventional methods that others point fingers at as crazy. If you boldly try and take a bitter fall, simply cleanly admit defeat without complaint, brush yourself off, rise, and immediately begin a new experiment."
      }
    ]
  },
  "marcus-aurelius": {
    "era_ko": "2세기의 거인 (121~180)",
    "era_en": "2nd Century Giant (121~180)",
    "category": "arts",
    "epic_ko": "권력의 정점에서 무소불위의 힘을 휘두를 수 있었던 로마 제국의 최고 통치자. 그러나 마르쿠스 아우렐리우스에게 황제의 자리란 화려한 쾌락의 왕좌가 아니라, 피와 흙먼지가 진동하는 끔찍하고 무거운 책임감의 사슬이었습니다. 그가 통치하던 시기 로마 제국은 사방에서 몰려드는 흉포한 야만족(게르만족)의 끝없는 침입, 인구의 절반 가까이를 휩쓸어간 안토니누스 역병(천연두)의 창궐, 그리고 부하 장군의 뼈아픈 반역이라는 전례 없는 삼중고의 대위기에 직면해 있었습니다. 하지만 그는 안전한 로마 황궁으로 도망쳐 안락함 속에 숨지 않았습니다. 오히려 차갑고 진흙투성이인 도나우강 최전선 군사 캠프의 천막 속에서 병사들과 똑같이 혹독한 추위를 견디며 제국을 수호하기 위해 평생토록 칼을 쥐고 피 튀기는 최전선을 뒹굴었습니다.\n\n적의 맹렬한 화살이 빗발치고 시체가 산처럼 쌓이는 끔찍한 전장의 한가운데서, 그가 칼을 내려놓은 고요한 깊은 밤에 홀로 손에 쥔 것은 작고 낡은 수첩이었습니다. 황제라는 최고 권력에 취해 타락하지 않기 위해, 그리고 극한의 공포와 스트레스 속에서 미쳐버리지 않기 위해 그는 매일 밤 촛불 아래서 스스로의 영혼을 가차 없이 채찍질하는 글을 써 내려갔습니다. 타인에게 보여주기 위한 가식적인 철학서가 아니라, 오직 자신만을 향한 뼈 때리는 반성문인 '명상록(Meditations)'은 그렇게 피비린내 나는 전쟁터의 야영지에서 기적처럼 탄생했습니다. 세상이 아무리 혼란스럽고 악인들이 득세할지라도, 오직 자기 내면의 흔들리지 않는 이성과 통제력(스토아철학)만이 구원임을 그는 일기장에 절박하게 새겨 넣었습니다.\n\n말년에는 최전선의 병영에서 원인 모를 열병에 걸려 죽음의 그림자가 턱밑까지 다가왔을 때조차, 그는 당황하거나 죽음을 두려워하지 않았습니다. \"자연의 순리에 따라 평온하게 떠나라\"는 자신의 스토아적 신념을 마지막 숨을 거두는 순간까지 완벽하게 증명하며 조용히 눈을 감았습니다. 마르쿠스 아우렐리우스의 삶은, 인간이 쥘 수 있는 가장 거대하고 압도적인 권력과 쾌락 앞에서도 결코 자신을 잃지 않고, 오직 내면의 단단한 성채를 쌓아 올려 시련을 철학으로 완벽하게 승화시킨 인류 역사상 가장 위대한 철인 황제의 숭고한 대서사시입니다.",
    "epic_en": "The supreme ruler of the Roman Empire, capable of wielding absolute power at its pinnacle. Yet for Marcus Aurelius, the position of emperor was not a throne of glamorous pleasure, but a horrific, heavy chain of responsibility reeking of blood and dust. During his reign, the Roman Empire faced an unprecedented triple crisis: endless invasions by ferocious barbarians (Germanic tribes) swarming from all sides, the outbreak of the Antonine Plague (smallpox) that swept away nearly half the population, and a bitter rebellion by a subordinate general. However, he did not flee to the safe Roman palace to hide in comfort. Instead, inside a tent at a cold, muddy military camp on the Danube frontline, he endured the harsh cold exactly like his soldiers, grasping his sword his entire life and rolling in the blood-spattered frontlines to defend the empire.\n\nIn the midst of the horrific battlefield where fierce enemy arrows rained down and corpses piled like mountains, in the quiet, deep night after setting down his sword, what he held alone in his hand was a small, worn notebook. To avoid becoming corrupted by the supreme power of the emperor, and to keep from going mad amidst extreme terror and stress, he ruthlessly whipped his own soul in writing under candlelight every night. Not a pretentious philosophical text meant to be shown to others, but a bone-striking confession directed solely at himself, 'Meditations' was miraculously born in the encampment of that blood-stained battlefield. He desperately engraved into his journal that no matter how chaotic the world may be and how villains may prevail, only one's inner, unshakeable reason and self-control (Stoicism) is the true salvation.\n\nIn his final years, even when the shadow of death reached his doorstep after catching an unknown fever in a frontline barracks, he did not panic or fear death. He passed away quietly, perfectly proving his Stoic conviction to \"depart peacefully according to the course of nature\" until his very last breath. Marcus Aurelius's life is the sublime epic of the greatest philosopher-king in human history, one who never lost himself even before the most massive, overwhelming power and pleasure a human could hold, and who perfectly sublimated his trials into philosophy by building a solid inner fortress.",
    "trials_ko": "천연두(안토니누스 역병)의 대유행과 게르만족의 끊임없는 침입, 믿었던 부하 장군(카시우스)의 참혹한 반역 등 로마 제국의 통치자로서 겪어야 했던 살인적인 스트레스와 전쟁의 공포.",
    "trials_en": "The murderous stress and terror of war he had to endure as the ruler of the Roman Empire, including the pandemic of the Antonine Plague (smallpox), the endless invasions of Germanic tribes, and the horrific rebellion of a trusted subordinate general (Cassius).",
    "overcoming_ko": "황제의 안락함을 포기하고 평생을 피비린내 나는 최전선의 천막에서 지내며, 밤마다 자신을 가혹하게 성찰하는 스토아철학의 일기('명상록')를 써 내려가며 제국과 스스로의 영혼을 무너지지 않게 수호함.",
    "overcoming_en": "Renouncing the comforts of the emperor, he spent his life in tents on the blood-stained frontlines, writing a daily journal of harsh Stoic self-reflection ('Meditations') every night to guard both the empire and his own soul from collapsing.",
    "wisdom": [
      {
        "quote_ko": "당신에게 일어나는 일들 때문에 상처받지 마라. 상처를 받았다고 생각하는 당신의 판단이 문제다. 판단을 멈추면 상처도 사라진다.",
        "quote_en": "If you are pained by any external thing, it is not this thing that disturbs you, but your own judgment about it. And it is in your power to wipe out this judgment now.",
        "meaning_ko": "타인의 날 선 비난이나 가혹한 불운이 닥쳤을 때, 스스로를 불쌍한 피해자로 규정하며 방구석에서 억울한 눈물을 짜내지 마십시오. 당신의 영혼에 진짜 치명적인 상처를 입히는 것은 바깥 세상의 칼날이 아니라, 그것을 '불행'이라고 멋대로 꼬리표를 붙여버린 당신 머릿속의 나약한 판단입니다. 당신의 허락 없이는 세상의 어떤 누구도 당신의 단단한 내면을 침범할 수 없음을 명심하십시오.",
        "meaning_en": "When faced with sharp criticism from others or harsh misfortune, do not frame yourself as a pitiful victim and squeeze out tears of grievance in the corner of your room. What truly inflicts fatal wounds on your soul is not the blade of the outside world, but the weak judgment in your head that arbitrarily labels it 'misfortune.' Please keep in mind that without your permission, absolutely no one in the world can invade your solid inner self."
      },
      {
        "quote_ko": "아침에 일어나기 싫을 때마다 스스로에게 말하라. '나는 인간으로서 해야 할 일을 하기 위해 깨어난다.'",
        "quote_en": "When you arise in the morning think of what a privilege it is to be alive, to think, to enjoy, to love...",
        "meaning_ko": "포근한 이불의 달콤한 유혹에 빠져 게으름을 피우고 핑계를 대느라 당신에게 주어진 기적 같은 아침의 시간을 허망하게 시궁창에 버리지 마시길 바랍니다. 당신이 살아 숨 쉬며 두 발로 땅을 딛고 세상에 나아가 맹렬하게 부딪칠 수 있다는 것 자체가 우주가 허락한 가장 눈부신 특권입니다. 핑계 대는 입을 다물고 인간으로서의 숭고한 의무를 다하기 위해 지금 당장 박차고 일어나십시오.",
        "meaning_en": "I hope you do not vainly throw away the miraculous morning time granted to you into the gutter by falling for the sweet temptation of a warm blanket, lazing about, and making excuses. The very fact that you are alive and breathing, able to step on the ground with two feet, go out into the world, and fiercely clash with it, is the most dazzling privilege allowed by the universe. Shut your excuse-making mouth and kick off the covers right now to fulfill your sublime duty as a human being."
      },
      {
        "quote_ko": "가장 훌륭한 복수는 당신의 적과 똑같이 되지 않는 것이다.",
        "quote_en": "The best revenge is not to be like your enemy.",
        "meaning_ko": "당신의 뒤통수를 치고 끔찍한 배신을 안겨준 쓰레기 같은 자들을 향해, 똑같은 저열한 방식으로 피의 복수를 하려 당신의 귀중한 영혼을 진흙탕에 처박지 마십시오. 그들이 얼마나 바닥을 기는 천박한 존재이든, 당신은 언제나 구름 위를 걷는 고결하고 우아한 태도를 지켜내야 합니다. 적들이 뿜어내는 독기를 거울처럼 반사해버리고 흔들림 없는 성자가 되는 것, 그것이 바로 세상에서 가장 우아하고 치명적인 복수입니다.",
        "meaning_en": "Do not shove your precious soul into the mud by attempting a bloody revenge using the same low-class methods against the trash-like people who struck you in the back and handed you horrific betrayal. No matter how vulgar and bottom-dwelling they may be, you must always maintain a noble and elegant attitude, as if walking on clouds. Reflecting the venom they spew like a mirror and becoming an unshakeable saint—that is the most elegant and fatal revenge in the world."
      }
    ]
  },
  "confucius": {
    "era_ko": "기원전 6세기~5세기의 거인 (BC 551~479)",
    "era_en": "6th~5th Century BC Giant (551~479 BC)",
    "category": "arts",
    "epic_ko": "힘센 자가 약한 자를 잔인하게 짓밟고 짐승처럼 살육하는 약육강식의 피비린내 나는 춘추시대. 공자는 고대 중국 노나라에서 하급 무사였던 아버지와 이름 없는 천민 어머니 사이에서 사생아에 가까운 신분으로 태어났습니다. 불과 세 살에 아버지를 잃고 홀어머니 밑에서 지독한 가난에 시달리며 자란 그는, 창고지기와 목장 관리인 같은 궂은일을 전전하며 멸시와 천대를 온몸으로 견뎌내야만 했습니다. 밥벌이의 지긋지긋한 굴레 속에서도 그는 결단코 학문을 향한 갈증을 멈추지 않았습니다. 세상의 모든 예법과 지식을 무섭게 흡수하며 마침내 노나라의 최고 사법관인 대사구의 자리까지 올랐지만, 부패한 기득권 귀족들의 교묘한 견제와 모함에 시달리다 결국 조국에서 쫓겨나듯 스스로 벼슬을 버리고 망명길에 올랐습니다.\n\n그가 나이 쉰이 넘어 시작한 철환천하(천하 주유)는 화려한 마차를 탄 권력자의 여행이 아니었습니다. 무려 14년이라는 아득하고 기나긴 세월 동안, 그는 자신의 사상인 '인(仁)'과 '덕치(德治)'를 받아들여 줄 현명한 군주를 찾아 제자들과 함께 이리저리 떠돌아다니는 상갓집 개(상가구)의 신세였습니다. 무력만이 진리라고 믿던 야만적인 제후들은 도덕과 예의를 논하는 늙은 사상가를 비웃고 외면했습니다. 때로는 적대 세력에게 포위되어 며칠을 굶으며 죽음의 문턱까지 가는 끔찍한 공포를 겪기도 했지만, 공자는 진흙탕에 처박혀서도 수금을 타며 제자들에게 흔들리지 않는 숭고한 인간의 길을 묵묵히 설파했습니다.\n\n살아서는 끝내 자신의 거대한 정치적 이상을 현실의 진흙탕 속에 뿌리내리지 못한 채, 고향으로 돌아와 사랑하는 제자 안연과 외아들마저 먼저 떠나보내는 참혹한 슬픔 속에서 쓸쓸히 눈을 감아야만 했습니다. 당시의 기준으로 보았을 때 그의 생애는 완벽하고 철저한 실패작이었습니다. 그러나 그가 남긴 한 줌의 말들은 제자들의 손을 거쳐 '논어'라는 불멸의 기록으로 부활했고, 훗날 동아시아 2천 년의 정신세계를 완벽하게 지배하는 거대하고 압도적인 문명의 뼈대가 되었습니다. 공자의 삶은 살아생전의 철저한 외면과 굶주림이라는 끔찍한 시련 속에서도, 결단코 타협하지 않고 우직하게 좇았던 보편적 인류애와 도덕의 깃발이 죽음 이후에 세상을 얼마나 무섭게 통째로 집어삼킬 수 있는지를 보여주는 역사상 가장 역설적이고 위대한 서사시입니다.",
    "epic_en": "During the Spring and Autumn Period, a bloody era of the law of the jungle where the strong ruthlessly trampled and slaughtered the weak like beasts. Confucius was born in the ancient Chinese state of Lu to a low-ranking warrior father and an unknown commoner mother, in a status akin to an illegitimate child. Losing his father at merely three years of age and growing up suffering from severe poverty under a single mother, he had to endure contempt and mistreatment with his entire body, wandering through menial jobs like a warehouse keeper and pasture manager. Yet, even within the tiresome yoke of earning a living, he categorically never ceased his thirst for learning. Fiercely absorbing all the etiquette and knowledge of the world, he eventually rose to the position of Minister of Crime, the highest judicial officer in Lu. However, tormented by the cunning checks and framed charges of the corrupt establishment nobility, he ultimately discarded his office and embarked on a path of exile, effectively chased out of his homeland.\n\nHis journeying across the world (Cheolhwancheonha), which began when he was past fifty, was not a trip of a powerful man in a luxurious carriage. For an unimaginably long 14 years, he was in the state of a 'stray dog at a funeral house,' wandering here and there with his disciples in search of a wise monarch who would accept his ideologies of 'Ren (Benevolence)' and 'Moral Rule.' The barbaric feudal lords, who believed martial force was the only truth, mocked and turned away from the old thinker discussing morality and propriety. Sometimes surrounded by hostile forces and starving for days, reaching the terrifying threshold of death, Confucius silently preached the unshakeable, sublime path of humanity to his disciples, even while shoved into the mud, playing his zither.\n\nUnable to ultimately root his colossal political ideals into the mud of reality during his lifetime, he had to pass away quietly in his hometown amidst the horrific sorrow of outliving his beloved disciple Yan Hui and his only son. Judged by the standards of his time, his life was a perfect and thorough failure. However, the handful of words he left behind resurrected into the immortal record 'The Analects' through the hands of his disciples, later becoming the colossal and overwhelming backbone of civilization that perfectly dominated the spiritual world of East Asia for 2,000 years. Confucius's life is the most paradoxical and great epic in history, showing how the flag of universal humanism and morality, stubbornly pursued without compromise even amidst the horrific trials of total neglect and starvation during one's lifetime, can terrifyingly swallow the world whole after death.",
    "trials_ko": "신분이 미천한 사생아 출신이라는 꼬리표와 지독한 유년기의 가난, 정치적 모함으로 조국에서 쫓겨나 14년간 상갓집 개처럼 떠돌며 겪은 굶주림과 생명의 위협, 그리고 자신의 이상이 살아서는 끝내 실현되지 못한 좌절감.",
    "trials_en": "The stigma of being born an illegitimate child of lowly status and severe childhood poverty, political framing that drove him out of his homeland to wander like a stray dog for 14 years enduring starvation and death threats, and the frustration that his ideals were never realized during his lifetime.",
    "overcoming_ko": "14년간의 참혹한 방랑과 권력자들의 외면 속에서도 결코 무력과 타협하지 않고 '인(仁)'이라는 인간에 대한 지극한 사랑의 철학을 가르쳤으며, 살아서는 실패자였으나 사후 동아시아 2천 년의 문명을 지배하는 사상적 기틀을 완성함.",
    "overcoming_en": "Never compromising with martial force even amidst 14 years of horrific wandering and neglect by those in power, he taught the philosophy of 'Ren' (extreme love for humans), and though a failure in life, he completed the ideological foundation that dominated East Asian civilization for 2,000 years posthumously.",
    "wisdom": [
      {
        "quote_ko": "내가 원하지 않는 바를 남에게 행하지 말라.",
        "quote_en": "What you do not wish for yourself, do not do to others. (己所不欲, 勿施於人)",
        "meaning_ko": "자신의 이기적인 욕심을 채우기 위해 타인의 가슴에 교묘하게 비수를 꽂고 상처를 주는 비겁한 짓을 당장 멈추시길 바랍니다. 내 살갗이 찢어지는 고통이 끔찍하다면, 타인의 고통 역시 똑같이 끔찍하다는 이 당연하고도 서늘한 우주의 진리를 가슴 깊이 새기십시오. 남을 짓밟고 올라선 그 더러운 자리는, 결국 더 크고 잔인한 타인의 군화발에 짓밟혀 산산조각 날 운명임을 명심하셔야 합니다.",
        "meaning_en": "Please immediately stop the cowardly act of cunningly stabbing a dagger into the hearts of others and causing them wounds just to satisfy your own selfish greed. If the pain of your own flesh tearing is horrific, engrave deeply into your heart this obvious yet chilling universal truth that the pain of others is equally horrific. You must keep in mind that the dirty seat you took by trampling on others is destined to ultimately be shattered, trampled by the larger, more cruel jackboots of someone else."
      },
      {
        "quote_ko": "세 사람이 길을 걸어가면 그중 반드시 내 스승이 있다. 좋은 점은 가려서 따르고, 나쁜 점은 거울삼아 내 잘못을 고친다.",
        "quote_en": "When three people walk together, there is always a teacher among them. I select their good qualities to follow, and their bad qualities to correct myself.",
        "meaning_ko": "스스로 세상의 모든 것을 다 안다고 착각하며 타인을 거만하게 내리깔아 보는 뻣뻣한 목을 꺾으십시오. 세상에서 가장 무섭고 예리한 지혜는 높은 단상의 학자가 아니라, 당신 곁을 스쳐 지나가는 평범하고 때로는 보잘것없어 보이는 사람들의 뒷모습에 숨어 있습니다. 누군가의 선행은 훔쳐서라도 내 것으로 만들고, 타인의 역겨운 악행을 볼 때마다 내 내면의 오물을 도려내는 채찍으로 맹렬하게 삼으십시오.",
        "meaning_en": "Snap your stiff neck that arrogantly looks down on others, mistakenly believing you know everything in the world. The most terrifying and sharp wisdom in the world hides not in scholars on high podiums, but in the backs of the ordinary and sometimes seemingly insignificant people who pass by you. Make someone's good deeds your own, even if you must steal them, and fiercely use the sight of others' disgusting evil deeds as a whip to carve out the filth from your own inner self."
      },
      {
        "quote_ko": "가장 큰 영광은 한 번도 넘어지지 않는 것이 아니라, 넘어질 때마다 다시 일어나는 것이다.",
        "quote_en": "Our greatest glory is not in never falling, but in rising every time we fall.",
        "meaning_ko": "인생의 치열한 진흙탕 싸움에서 처참하게 미끄러져 무릎이 깨졌다고, 그 자리에 주저앉아 하늘을 원망하며 눈물이나 짜내지 마십시오. 당신의 그 찌질한 실패의 횟수가 당신의 멱살을 잡고 나락으로 끌어내리지 못합니다. 오히려 코가 깨지고 피가 터져도 이를 꽉 깨물고 다시 기어 올라오는 그 미친듯한 끈질김만이, 세상이 당신을 두려워하고 경외하게 만드는 유일하고 압도적인 무기입니다.",
        "meaning_en": "Do not sit down on the spot, resent the sky, and squeeze out tears just because you slipped miserably and scraped your knees in the fierce mud fight of life. The number of your pathetic failures cannot grab you by the collar and drag you down to the abyss. Rather, only that crazed persistence of gritting your teeth and crawling back up—even with a broken nose and bursting blood—is the sole, overwhelming weapon that forces the world to fear and revere you."
      }
    ]
  },
  "socrates": {
    "era_ko": "기원전 5세기~4세기의 거인 (BC 470~399)",
    "era_en": "5th~4th Century BC Giant (470~399 BC)",
    "category": "arts",
    "epic_ko": "고대 그리스 아테네. 펠로폰네소스 전쟁의 참혹한 패배 이후 민주주의는 타락하고, 사람들은 궤변론자(소피스트)들의 화려한 말장난에 속아 진리를 철저히 외면하던 극도의 혼란기였습니다. 이 무지몽매한 시대의 한복판에, 맨발에 낡은 옷을 걸치고 아테네의 아고라 광장을 헤매는 볼품없는 외모의 노인이 있었습니다. 소크라테스는 웅장한 학당을 짓고 돈을 받으며 지식을 팔아넘기던 위선적인 학자들과는 차원이 달랐습니다. 그는 길거리에 서서 정치가, 장군, 학자 할 것 없이 누구에게나 다가가 집요하고 날카로운 질문을 던졌습니다. \"정의란 무엇인가?\", \"용기란 무엇인가?\" 스스로 모든 것을 안다고 자만하던 아테네의 기득권들은 그의 끝없는 '산파술' 질문 폭격 앞에서 논리의 밑천을 드러내며 얼굴을 붉혀야만 했습니다.\n\n그는 아테네인들에게 스스로가 얼마나 무지한지 뼈저리게 깨닫게 만드는 피곤하고 성가신 '등에(가축의 피를 빠는 파리)'를 자처했습니다. 그러나 권력자들의 허영심을 찌르는 그의 날 선 질문들은 오만한 기득권층의 극심한 분노와 증오를 샀습니다. 결국 그는 '아테네의 젊은이들을 타락시키고 국가가 인정하는 신을 믿지 않는다'는 억지스럽고 황당한 죄목으로 칠십 노구의 나이에 공개 재판에 회부되었습니다. 살기 위해 비굴하게 눈물로 목숨을 구걸하거나 타협하면 얼마든지 살아남을 수 있었지만, 그는 500명의 배심원 앞에서 죽음의 공포에 굴복하지 않고 당당하게 자신의 철학적 신념을 사자후처럼 쏟아냈습니다. \"검토되지 않은 삶은 살 가치가 없다.\"\n\n마침내 사형이 선고되고, 감옥을 찾아온 제자 크리톤이 눈물을 흘리며 탈옥을 간청했을 때도 그의 표정은 호수처럼 평온했습니다. 도망치는 것은 스스로 법과 정의를 무너뜨리고 자신의 철학적 삶을 부정하는 비겁한 짓이라며 단호히 거절한 그는, 독미나리 즙이 담긴 사약 잔을 미소 지으며 단숨에 들이켰습니다. 몸이 서서히 마비되어 가는 죽음의 끔찍한 고통 속에서도, 그는 오히려 제자들을 위로하며 흔들림 없는 성자의 모습으로 숨을 거두었습니다. 소크라테스의 삶은, 무지라는 영혼의 질병을 치유하기 위해 세상의 권력과 타협하기를 단호히 거부하고, 자신의 생명조차 가장 위대한 철학적 가르침의 제물로 바쳐버린 인류 역사상 가장 숭고하고 지독한 진리 탐구의 대서사시입니다.",
    "epic_en": "Ancient Athens, Greece. Following the horrific defeat in the Peloponnesian War, democracy had become corrupted, and it was a period of extreme chaos where people thoroughly ignored the truth, deceived by the flashy wordplay of sophists. In the middle of this ignorant era, there was a barefoot old man with a shabby appearance wandering the Agora square in worn-out clothes. Socrates was on an entirely different level from the hypocritical scholars who built grand academies and sold knowledge for money. He stood on the streets and approached anyone—politicians, generals, scholars—hurling relentless and sharp questions: \"What is justice?\" \"What is courage?\" The Athenian establishment, who arrogantly believed they knew everything, were forced to reveal the bottom of their logic and turn red-faced before his endless bombardment of 'maieutic' questioning.\n\nHe willingly took on the role of a tiresome and annoying 'gadfly' to make the Athenians bitterly realize how ignorant they truly were. However, his sharp questions, which pierced the vanity of those in power, earned the extreme anger and hatred of the arrogant establishment. Ultimately, he was brought to a public trial at the age of seventy on the forced and absurd charges of 'corrupting the youth of Athens and not believing in the gods recognized by the state.' Though he could easily have survived by cowardly begging for his life with tears or compromising to live, he did not submit to the terror of death before the 500 jurors, proudly roaring his philosophical convictions like a lion: \"The unexamined life is not worth living.\"\n\nWhen he was finally sentenced to death, and his disciple Crito visited the prison, tearfully begging him to escape, his expression remained as calm as a lake. Decisively refusing, stating that fleeing would be a cowardly act that undermined law and justice and negated his own philosophical life, he drank the cup of hemlock poison with a smile in a single breath. Even within the horrific agony of death as his body slowly paralyzed, he instead comforted his disciples, passing away with the unshakeable appearance of a saint. Socrates's life is the most sublime and fierce epic of truth-seeking in human history, of a man who decisively refused to compromise with worldly power to cure the soul's disease of ignorance, offering even his own life as a sacrifice for the greatest philosophical teaching.",
    "trials_ko": "권력자들의 허영과 기득권을 비판하여 받아야 했던 세상의 지독한 미움과 조롱, 그리고 70세의 나이에 억울한 누명을 쓰고 독배를 마셔야만 했던 사형 선고와 죽음의 공포.",
    "trials_en": "The severe hatred and mockery of the world he had to endure for criticizing the vanity and vested interests of those in power, and the terror of death and the death sentence of having to drink poison under false charges at the age of 70.",
    "overcoming_ko": "목숨을 구걸하여 비굴하게 연명하는 대신 독배를 기꺼이 마심으로써 자신의 철학적 신념과 정의를 지켜냈고, 서양 철학의 위대한 토대를 스스로의 죽음으로 찬란하게 완성함.",
    "overcoming_en": "Rather than cowardly begging for his life to merely exist, he willingly drank the poison to defend his philosophical convictions and justice, brilliantly completing the great foundation of Western philosophy through his own death.",
    "wisdom": [
      {
        "quote_ko": "너 자신을 알라.",
        "quote_en": "Know thyself.",
        "meaning_ko": "거울 앞의 잘난 척하는 껍데기를 당장 부숴버리고, 그 너머에 숨겨진 추악하고 텅 빈 당신의 진짜 민낯을 소름 돋도록 서늘하게 직면하십시오. 세상의 모든 지식을 다 섭렵한 체 오만하게 목을 빳빳이 세우는 그 얄팍한 자만심이야말로 당신을 철저하게 파멸시키는 가장 치명적인 영혼의 맹독입니다. '내가 사실은 아무것도 모르는 멍청이일지도 모른다'는 그 처절하고 무서운 자기 부정의 바닥에서부터, 당신 삶의 진짜 거대한 기적이 시작되는 법입니다.",
        "meaning_en": "Shatter the show-off shell in front of the mirror right now, and face the ugly, empty, true bare face hidden beyond it with chilling clarity. That shallow arrogance of keeping a stiff neck, pretending to have mastered all the knowledge in the world, is the most fatal, deadly poison to the soul that will thoroughly ruin you. True, colossal miracles in your life begin from the desperate, terrifying rock bottom of self-denial—admitting 'I might actually be an idiot who knows nothing.'"
      },
      {
        "quote_ko": "검토되지 않은 삶은 살 가치가 없다.",
        "quote_en": "The unexamined life is not worth living.",
        "meaning_ko": "남들이 정해놓은 천편일률적인 정답과 성공의 기준에 맞춰, 그저 하루하루 숨만 쉬며 기계처럼 끌려다니는 맹목적인 삶을 당장 멈추시길 바랍니다. \"나는 지금 도대체 왜 이 짓을 하고 있는가?\"라는 피가 뚝뚝 떨어질 만큼 날카로운 질문의 비수를 당신 자신의 심장에 매일 밤 꽂아 넣지 않는다면, 당신은 살아있으되 이미 죽어 썩어가고 있는 송장과 다를 바가 결코 없음을 명심하십시오.",
        "meaning_en": "I hope you immediately stop leading a blind life, merely breathing day by day and being dragged around like a machine according to the uniform right answers and standards of success set by others. Please keep in mind that unless you plunge the sharply bleeding dagger of the question \"Why on earth am I doing this right now?\" into your own heart every night, you are no different from a corpse that is alive but already rotting."
      },
      {
        "quote_ko": "살기 위해서 먹어야지, 먹기 위해서 살아서는 안 된다.",
        "quote_en": "Thou shouldst eat to live; not live to eat.",
        "meaning_ko": "단순히 배를 불리고 안락한 쾌락을 쫓는 짐승 같은 욕망에 당신의 고귀한 영혼을 팔아넘기지 마십시오. 육체의 본능에 굴복하여 그것의 노예로 전락하는 순간, 인간의 위대한 존엄은 산산조각이 나고 맙니다. 당신은 한낱 고깃덩어리를 채우기 위해 태어난 것이 아니라, 우주를 품을 수 있는 거대한 이성을 불태워 세상을 호령하기 위해 태어난 숭고한 존재임을 절대 잊지 마십시오.",
        "meaning_en": "Do not sell your noble soul to beast-like desires of merely filling your stomach and chasing comfortable pleasure. The moment you submit to the instincts of the flesh and degenerate into its slave, human's great dignity shatters into pieces. Never forget that you were not born merely to stuff a lump of meat, but are a sublime being born to burn with a colossal reason capable of embracing the universe and commanding the world."
      }
    ]
  }
};

const finalNarratives = JSON.parse(fs.readFileSync('src/data/final-narratives.json', 'utf8'));

for (const [slug, data] of Object.entries(dataToInject)) {
  finalNarratives[slug] = data;
}

fs.writeFileSync('src/data/final-narratives.json', JSON.stringify(finalNarratives, null, 2), 'utf8');
console.log('Successfully injected Platinum rewritten giants (17-20) into final-narratives.json');
