import json

translations1 = {
  "thomas-edison": {
    "timeline": [
      "Alizaliwa Milan, Ohio, na kukulia Port Huron, Michigan.",
      "Alivumbua telegrafu inayojiendesha.",
      "Alianzisha maabara ya Menlo Park, kituo cha kwanza cha utafiti binafsi.",
      "Alivumbua kinasa sauti (phonograph).",
      "Alivumbua kisambaza sauti cha simu.",
      "Alivumbua jenereta mpya na vifaa vya taa vya umeme.",
      "Alifanya majaribio ya treni ya umeme.",
      "Alijenga kituo cha umeme na kuboresha sekta hiyo.",
      "Alitengeneza injini na betri za kuhifadhi umeme.",
      "Alihutubia kwenye maadhimisho ya miaka 50 ya balbu akiwa na umri wa miaka 82.",
      "Alifariki dunia Oktoba 18 akiwa na umri wa miaka 84."
    ],
    "keyAchievements": [
      {"title": "Uvumbuzi wa kinasa sauti", "description": "Moja ya uvumbuzi wake mkubwa na kati ya hataza zake nyingi."},
      {"title": "Uvumbuzi wa balbu ya umeme", "description": "Kifaa kilichoangaza usiku, kikachochea maendeleo ya usambazaji umeme na kuufikisha majumbani."},
      {"title": "Kuanzisha Maabara ya Menlo Park", "description": "Mwaka 1876, alianzisha kituo cha kwanza cha utafiti binafsi ili kuendeleza uvumbuzi."},
      {"title": "Kuanzishwa kwa General Electric", "description": "Kampuni yake ya umeme ilikua na baadaye kuwa General Electric."},
      {"title": "Ugunduzi wa Edison Effect", "description": "Ugunduzi muhimu wa kisayansi ulioweka msingi wa mirija ya utupu na ugunduzi wa redio."}
    ],
    "faq": [
      {"question": "Thomas Edison alisajili hataza ngapi?", "answer": "Ana hataza za Kimarekani 1,093 zinazotambulika rasmi, na inasemekana alivumbua vitu 2,332 isivyo rasmi."},
      {"question": "Edison alipata elimu rasmi kwa muda gani?", "answer": "Alisoma kwa miezi mitatu pekee, lakini alikuza kipaji chake kutokana na juhudi za mama yake mwalimu."},
      {"question": "Edison alikuwa mtu wa namna gani kwa familia yake?", "answer": "Alijikita zaidi kwenye uvumbuzi na biashara na kutelekeza familia; hakuhudhuria mazishi ya mke wake wa kwanza na maisha ya watoto wake yalikuwa magumu."},
      {"question": "Uvumbuzi wa Edison uliathiri vipi teknolojia nchini Marekani?", "answer": "Kwa kutegemea majaribio na udadisi badala ya nadharia za kisomi, aliifanya Marekani kuipiku Ulaya katika teknolojia tumizi."}
    ],
    "missingDataNote": ""
  },
  "frida-kahlo": {
    "timeline": [
      "Alizaliwa kama Magdalena Carmen Frida Kahlo y Calderón.",
      "Alipata ugonjwa wa polio akiwa na miaka 6, uliodhoofisha mguu wake wa kulia.",
      "Aliumia vibaya uti wa mgongo, mguu wa kulia na fumbatio kwenye ajali akiwa na miaka 18.",
      "Alifunga ndoa na Diego Rivera.",
      "Alitalikiana na Diego Rivera mnamo Novemba.",
      "Aliolewa tena na Diego Rivera.",
      "Alichora mchoro wa \"The Love Embrace of the Universe\".",
      "Alifariki Julai 13 kutokana na homa ya mapafu.",
      "Maonyesho ya kazi zake yalifanyika kwenye majumba ya makumbusho ya Sejong na Soma.",
      "Kazi zake na za Diego Rivera zilionyeshwa kwenye Kituo cha Sanaa cha Seoul."
    ],
    "keyAchievements": [
      {"title": "Kuanzisha mtindo wa Kimexico", "description": "Aliunda mtindo wa kipekee uliochanganya uhalisia, usureali, usimbolizi na tamaduni za Kimexico."},
      {"title": "Sanaa maarufu \"Frida and the Cesarean Operation\"", "description": "Mchoro unaoonyesha mateso ya maisha yake kutokana na ulemavu wa kuzaliwa."},
      {"title": "Sanaa maarufu \"Henry Ford Hospital\"", "description": "Mchoro maarufu unaosawiri maumivu aliyoyapitia kutokana na matatizo yake ya nyonga."},
      {"title": "Sanaa maarufu \"The Love Embrace of the Universe\"", "description": "Mchoro unaomuonyesha akimkumbatia mpenzi wake Diego Rivera kama mtoto."}
    ],
    "faq": [
      {"question": "Frida Kahlo alikuwa mchoraji wa aina gani?", "answer": "Alikuwa mchoraji msureali na mkomunisti wa Kimexico aliyeanzisha mtindo uliochanganya uhalisia, usureali na utamaduni wa asili."},
      {"question": "Maisha ya Frida Kahlo yalikuwaje?", "answer": "Yalijaa mateso, akipata polio akiwa na miaka 6 na kujeruhiwa vibaya katika ajali akiwa na miaka 18."},
      {"question": "Ni kazi zipi maarufu za Frida Kahlo?", "answer": "Kazi zake maarufu ni pamoja na \"Frida and the Cesarean Operation\", \"Henry Ford Hospital\", na \"The Love Embrace of the Universe\"."},
      {"question": "Frida Kahlo aliolewa na nani?", "answer": "Aliolewa na mchoraji na mwanamapinduzi Diego Rivera, akatalikiana naye na kuolewa naye tena."},
      {"question": "Jina 'Frida' linamaanisha nini?", "answer": "Lilitolewa na baba yake Mjerumani, Guillermo Kahlo; kwa Kijerumani linamaanisha amani."}
    ],
    "missingDataNote": ""
  },
  "helen-keller": {
    "timeline": [
      "Helen Adams Keller alizaliwa nyumbani kwao Ivy Green, Tuscumbia, Alabama.",
      "Mama yake, Kate Keller, alivutiwa na \"American Notes\" ya Charles Dickens na kusafiri hadi Baltimore kumwona J. Julian Chisolm.",
      "Anne Sullivan aliwasili nyumbani kwa Helen na kuanza kumfundisha.",
      "Helen alisajiliwa katika Shule ya Vipofu ya Perkins.",
      "Aliandika \"The Frost King\" akiwa na umri wa miaka 11.",
      "Alihamia New York na Anne Sullivan kusoma katika shule za viziwi za Wright-Humason na Horace Mann.",
      "Alirudi Massachusetts na kusoma Shule ya Wasichana ya Cambridge.",
      "Alidahiliwa katika Chuo Kikuu cha Radcliffe, tawi la wanawake la Harvard.",
      "Alichapisha tawasifu yake, \"The Story of My Life,\" na Anne Sullivan na John Macy.",
      "Alihitimu Radcliffe akiwa na miaka 24 na kuwa mtu wa kwanza kiziwi na asiyeona kupata Shahada ya Sanaa.",
      "Aliandika kitabu \"The World I Live In\".",
      "Alijiunga na Chama cha Kisoshalisti cha Marekani akiwa na miaka 29.",
      "Alijiunga na Wafanyakazi wa Viwanda Duniani (IWW).",
      "Alichapisha mfululizo wa insha za usoshalisti uitwao \"Out of the Dark\".",
      "Alianzisha shirika la Helen Keller International akiwa na George Kessler.",
      "Aliandika makala nyingi kuunga mkono IWW.",
      "Alionekana kwenye filamu ya kimya \"Deliverance\".",
      "Alisaidia kuanzisha Umoja wa Kutetea Haki za Kiraia wa Marekani (ACLU).",
      "Alichapisha tawasifu yake ya kiroho, \"My Religion\".",
      "Anne Sullivan alifariki dunia.",
      "Aliuliza kuhusu mbwa Hachikō akiwa Akita, Japani, na kupewa mbwa aina ya Akita aitwaye \"Kamikaze-go\".",
      "Baada ya kifo cha \"Kamikaze-go,\" alipewa mbwa \"Kenzan-go\" kama zawadi rasmi na Japani.",
      "Maandishi ya William Gibson yalionyeshwa kama \"The Miracle Worker\" kwenye Playhouse 90.",
      "Polly Thomson alifariki kwa kiharusi.",
      "Alipata viharusi mfululizo na kutumia miaka yake ya mwisho nyumbani.",
      "Filamu ya \"The Miracle Worker\" ilishinda Tuzo ya Oscar.",
      "Alitunukiwa Nishani ya Rais ya Uhuru na Rais Lyndon B. Johnson.",
      "Aliingizwa kwenye Ukumbi wa Umaarufu wa Wanawake wa Marekani.",
      "Alifariki dunia akiwa na miaka 88 nyumbani kwake Arcan Ridge, Connecticut.",
      "Alitajwa na Gallup miongoni mwa watu 18 wanaoheshimiwa sana karne ya 20.",
      "Jimbo la Alabama lilimweka kwenye sarafu ya robo dola ya Marekani.",
      "Sanamu ya shaba ya Helen Keller iliwekwa kwenye Ukumbi wa Sanamu za Kitaifa."
    ],
    "keyAchievements": [
      {"title": "Kiziwi asiyeona wa kwanza kupata shahada", "description": "Mwaka 1904, alihitimu Radcliffe na kuwa wa kwanza kupata Shahada ya Sanaa."},
      {"title": "Mwandishi na mwalimu mahiri", "description": "Alichapisha vitabu 12 na makala nyingi, akiwa mwandishi na mwalimu anayetambulika sana."},
      {"title": "Mwanaharakati wa usoshalisti na haki za binadamu", "description": "Alipigania haki ya wanawake kupiga kura, amani, na kupinga ajira za watoto, ubaguzi wa rangi na adhabu ya kifo."},
      {"title": "Uanzishaji wa Helen Keller International", "description": "Mwaka 1915, alishirikiana na George Kessler kuanzisha shirika hili la utafiti wa uoni na afya."},
      {"title": "Mchango katika kuanzisha ACLU", "description": "Mwaka 1920, alishiriki kikamilifu katika uanzishwaji wa ACLU."},
      {"title": "Heshima za kitaifa", "description": "Alitunukiwa Nishani ya Rais ya Uhuru mwaka 1964, kuingizwa kwenye Ukumbi wa Umaarufu wa Wanawake mwaka 1965, na kuenziwa baada ya kifo chake."}
    ],
    "faq": [
      {"question": "Helen Keller alizaliwa na kufariki lini?", "answer": "Alizaliwa Juni 27, 1880, na kufariki Juni 1, 1968, akiwa na umri wa miaka 88."},
      {"question": "Helen Keller alipotezaje uwezo wake wa kuona na kusikia?", "answer": "Akiwa na miezi 19 alipatwa na ugonjwa ulioaminika kuwa homa nyekundu na homa ya uti wa mgongo, uliompofusha na kumtia uziwi maisha yake yote."},
      {"question": "Nani alikuwa na ushawishi mkubwa katika elimu ya Helen Keller?", "answer": "Anne Sullivan, aliyewasili Machi 1887 na kumfundisha kuwasiliana kwa kumwandikia maneno kwenye kiganja chake."},
      {"question": "Helen Keller alihusika katika harakati zipi za kijamii?", "answer": "Alikuwa msomi wa kisoshalisti aliyepigania haki ya kupiga kura kwa wanawake, amani, na kupinga ajira za watoto na ubaguzi wa rangi."},
      {"question": "Kazi ipi maarufu inayosawiri maisha ya Helen Keller?", "answer": "Filamu ya \"The Miracle Worker,\" inayosimulia utoto wake na uhusiano wake na Anne Sullivan; ilishinda Tuzo ya Oscar mwaka 1962."}
    ],
    "missingDataNote": "Mwaka rasmi alipopoteza uwezo wa kuona na kusikia baada ya kuugua akiwa na miezi 19 haujatajwa kwenye chanzo asili, hivyo umeachwa kwenye matukio."
  },
  "beethoven": {
    "timeline": [
      "Alibatizwa katika Parokia ya Kikatoliki ya Mtakatifu Remigius huko Bonn, Ujerumani.",
      "Alitangazwa kama 'mtoto wa ajabu' mwenye umri wa miaka sita katika tamasha lake la kwanza la wazi.",
      "Alianza kupokea mafunzo kutoka kwa Christian Gottlob Neefe huko Bonn.",
      "Alianza kufanya kazi kama mpiga kinanda msaidizi wa Neefe.",
      "Kazi yake ya kwanza kuchapishwa, tofauti tisa za piano (WoO 63), ilitolewa.",
      "Sonata zake tatu za piano, WoO 47, zilichapishwa.",
      "Makala ya kwanza kuhusu Beethoven ilichapishwa katika Magazin der Musik.",
      "Alianza kufanya kazi ya kulipwa kwenye kanisa la kifalme na kuteuliwa kama mpiga kinanda wa pili wa kifalme wa kudumu.",
      "Babake Johann alilazimishwa kujiuzulu na nusu ya pensheni yake ililipwa moja kwa moja kwa Beethoven kwa matunzo ya familia.",
      "Inasemekana aliombwa kutunga Kantata za kuomboleza kifo cha Joseph II na kusherehekea kutawazwa kwa Leopold II.",
      "Inasadikiwa alitambulishwa kwa mara ya kwanza kwa Joseph Haydn akiwa njiani kwenda London.",
      "Aliombwa kutunga muziki wa ballet, Musik zu einem Ritterballett, WoO 1.",
      "Alikutana tena na Haydn, ambaye aliahidi kumchukua kama mwanafunzi.",
      "Aliondoka Bonn kwenda Vienna kwa msaada wa Elector.",
      "Muda mfupi baada ya kuwasili Vienna, alipata habari za kifo cha babake.",
      "Alijijengea sifa kama gwiji wa piano huko Vienna.",
      "Bonn ilitekwa na Ufaransa.",
      "Alipiga moja ya konsati zake za piano katika onyesho lake la kwanza Vienna.",
      "Alitunga kazi yake ya kwanza yenye namba ya Op. 1.",
      "Alifanya ziara katika vituo vya kitamaduni vya Ulaya ya Kati.",
      "Akiwa Berlin, alitunga sonata mbili za cello (Op. 5) na kumkabidhi Mfalme Friedrich Wilhelm II.",
      "Alirudi Vienna.",
      "Alisafiri kwenda Pressburg na Pest.",
      "Aliugua sana wakati wa kiangazi na vuli.",
      "Alianza kutambua matatizo ya usikivu wake kwa mara ya kwanza.",
      "Usikivu wake ulizidi kudhoofika hadi kuachana na ziara za kimuziki.",
      "Alitunga quartet sita za kwanza za nyuzi (Op. 18) kwa ombi la Prince Lobkowitz.",
      "Alishinda 'pambano' la piano dhidi ya Joseph Wölfl.",
      "Sonata namba 8 ya piano 'Pathétique' ilichapishwa.",
      "Alikamilisha Septet, Op. 20.",
      "Alianza kuwafundisha binti za Anna Brunsvik piano.",
      "Alimshinda Daniel Steibelt katika pambano la piano.",
      "Alikodi Burgtheater kuandaa programu kubwa ya muziki kwa onyesho la kwanza la Simfoni Namba 1.",
      "Onyesho la simfoni namba 1 na 2 lilimfanya aonekane miongoni mwa watunzi vijana muhimu.",
      "Quartet sita za kwanza za nyuzi zilichapishwa.",
      "Alikamilisha muziki wa ballet \"The Creatures of Prometheus\" uliochezwa Vienna.",
      "Alikutana na Countess Giulietta Guicciardi.",
      "Alimfundisha Ferdinand Ries.",
      "Carl Czerny mchanga alijifunza chini ya Beethoven.",
      "Alichapisha Sonata namba 14 ('Moonlight') na kumpatia Giulietta Guicciardi.",
      "Alikamilisha Simfoni Namba 2, lakini tamasha lake lilifutwa.",
      "Alihamia Heiligenstadt nje ya Vienna na kuandika Wosia wa Heiligenstadt.",
      "Alianza kusomea piano na utunzi chini ya Archduke Rudolph wa Austria.",
      "Alitunga Simfoni Namba 3 'Eroica'.",
      "Count Joseph Deym alifariki.",
      "Ajira yake katika Theater an der Wien ilikoma.",
      "Alifuta jina la Napoleon kwenye muswada wa Simfoni Namba 3 kutokana na kuvunjwa moyo.",
      "Simfoni Namba 3 'Eroica' ilionyeshwa kwa mara ya kwanza.",
      "Opera Fidelio ilionyeshwa kwa mara ya kwanza mbele ya hadhira ndogo.",
      "Simfoni Namba 3 'Eroica' ilichapishwa.",
      "Muzio Clementi alipata haki za kuchapisha kazi zake nchini Uingereza.",
      "Prince Esterházy alimwomba atunge Misa C major, Op. 86.",
      "Aliandaa tamasha kubwa lililojumuisha Simfoni namba 5 na 6, na nyinginezo.",
      "Alikataa nafasi ya kuwa Kapellmeister kutoka kwa Jérôme Bonaparte baada ya kuahidiwa pensheni na waheshimiwa wa Vienna.",
      "Aliombwa kutunga muziki wa igizo la Egmont la Goethe.",
      "Muziki wa Egmont (Op. 84) ulitolewa.",
      "Alikataliwa ombi lake la ndoa na Therese Malfatti.",
      "Prince Lobkowitz alisitisha malipo ya pensheni yake.",
      "Aliugua sana kutokana na homa kali na maumivu ya kichwa.",
      "Alikutana na Goethe huko Teplitz.",
      "Alimwandikia barua ya kurasa 10 \"Immortal Beloved\" akiwa Teplitz.",
      "Alimtembelea kaka yake Johann ili kuzuia mahusiano yake na Therese Obermayer.",
      "Johann na Therese Obermayer walifunga ndoa.",
      "Prince Kinsky alifariki baada ya kuanguka kutoka kwenye farasi.",
      "Alipitia kipindi kigumu cha kihisia na kushuka kwa uzalishaji wake.",
      "Alimkopesha kaka yake Kaspar florin 1500.",
      "Alipata msukumo wa kutunga baada ya habari za kushindwa kwa Napoleon na Duke wa Wellington.",
      "Wellington's Victory na Simfoni Namba 7 zilionyeshwa kwa mara ya kwanza.",
      "Wellington's Victory iliendelea kuonyeshwa kwa mafanikio.",
      "Alicheza kwa mara ya mwisho wazi kama mpiga kinanda katika Archduke Trio.",
      "Alianza kutumia vifaa vya kusaidia kusikia vya tarumbeta vilivyotengenezwa na Mälzel.",
      "Alitunga muziki wa kizalendo kuburudisha viongozi katika Bunge la Vienna.",
      "Alilipwa fidia na Prince Lobkowitz kupitia hatua za kisheria.",
      "Alitunga Calm Sea and Prosperous Voyage, Op. 112 kutokana na shairi la Goethe.",
      "Baada ya kifo cha kaka yake Kaspar, aliingia katika mgogoro wa kisheria wa mlezi dhidi ya Johanna.",
      "Uzalishaji wa Beethoven ulipungua kwa kiwango kikubwa zaidi maishani mwake.",
      "Alifanikiwa kumpokonya Johanna haki ya kumlea mpwa wake Karl.",
      "Alikamilisha An die ferne Geliebte, Op. 98.",
      "Aliugua homa ya uchochezi kwa zaidi ya mwaka mmoja.",
      "Mälzel alipata uungwaji mkono wa Beethoven kwa metronome yake mpya.",
      "Afya yake iliimarika na Karl alihamia kuishi naye.",
      "Alikamilisha Sonata ya piano Namba 29 'Hammerklavier'.",
      "Alianza michoro ya muziki itakayokuwa sehemu ya Simfoni Namba 9.",
      "Alipoteza haki ya ulezi wa pekee mahakamani.",
      "Uteuzi wa Archduke Rudolph kama Kadinali-Askofu Mkuu ulitangazwa.",
      "Anton Diabelli aliwaalika watunzi 50 wa Vienna, akiwemo Beethoven, kutunga tofauti za muziki.",
      "Alikamilisha tofauti 20 zitakazounda Diabelli Variations, Op. 120.",
      "Moritz Schlesinger alimtembelea kwa mara ya kwanza.",
      "Alishinda tena haki ya kisheria ya kumlea mpwa wake Karl.",
      "Uzinduzi wa Rudolph huko Olomouc ulichochea utunzi wa Missa solemnis.",
      "Sonata ya piano Namba 30 ilitumwa kwa wachapishaji.",
      "Alisumbuliwa tena na yabisi-kavu na homa ya manjano.",
      "Alionyesha imani yake binafsi kwa Mungu katika barua kwa Rudolph.",
      "Sonata ya piano Namba 31 ilichapishwa.",
      "Alitaka kupatana na kaka yake Johann.",
      "Calm Sea and Prosperous Voyage ilichapishwa na kutolewa wakfu kwa Goethe.",
      "London Philharmonic Society walitoa ofa kwa ajili ya simfoni.",
      "Prince Nikolai Galitzin alimwomba atunge quartet tatu za nyuzi.",
      "Anton Schindler alifanywa kuwa katibu wake asiyelipwa.",
      "Missa solemnis, Simfoni Namba 9 na Diabelli Variations zilikamilishwa.",
      "Alimkabidhi Rudolph nakala kamili ya Missa solemnis.",
      "Simfoni Namba 9 ilionyeshwa kwa mara ya kwanza na kupokelewa kwa sifa kuu.",
      "Onyesho la pili lilihudhuriwa na watu wachache sana.",
      "Quartet namba 12 ya nyuzi (Op. 127) ilionyeshwa.",
      "Aliugua ghafla wakati akitunga Quartet Namba 15.",
      "Harakati ya mwisho ya Quartet Namba 13 ilithibitika kuwa ngumu sana kwa wanamuziki na watazamaji.",
      "Ingawa alipatana na Schindler, katibu wake alibadilishwa na Karl Holz.",
      "Mpwa wake Karl alijaribu kujiua.",
      "Alihamia kwa kaka yake Johann huko Gneixendorf kwa miezi mitatu.",
      "Alikamilisha fainali mbadala ya Quartet Namba 13.",
      "Alipata ugonjwa wa mapafu wakati wa safari yake ya kurudi Vienna.",
      "Mpwa wake Karl aliondoka kujiunga na jeshi.",
      "Aliwaambia Schindler na marafiki, \"Pigeni makofi, marafiki, komedi imekwisha.\"",
      "Alifariki akiwa na umri wa miaka 56."
    ],
    "keyAchievements": [
      {"title": "Mtunzi na mpiga piano", "description": "Mtunzi mkuu wa muziki wa kitambo wa Kijerumani aliyevusha kipindi cha Klasiki kwenda cha Romantiki."},
      {"title": "Jina la heshima \"Mtakatifu wa Muziki\"", "description": "Mara nyingi hutajwa kama shujaa na gwiji mkubwa wa muziki aliyepewa heshima kama \"Mtakatifu wa Muziki\"."},
      {"title": "Kazi zake kuu", "description": "Kazi zinazofahamika zaidi ni pamoja na Simfoni Namba 3, 5, 6, 9, na Sonata za Pathétique na Moonlight."},
      {"title": "Chapisho lake la kwanza", "description": "Mwaka 1783, alichapisha kazi yake ya kwanza, tofauti tisa za piano (WoO 63)."},
      {"title": "Sonata za mwanzo za piano", "description": "Sonata zake tatu zilizochapishwa 1783 zilionyesha kipaji chake tangu akiwa mdogo."},
      {"title": "Ombi la muziki wa ballet", "description": "Mwaka 1791 aliombwa na kutunga muziki wa Ritterballett, kazi yake ya kwanza kwa ukumbi."},
      {"title": "Kazi ya kwanza yenye namba ya Op.", "description": "Mwaka 1795 alipata mafanikio ya kifedha kwa kuchapisha piano trio tatu (Op. 1)."},
      {"title": "Sonata za Cello 1-2, Op. 5", "description": "Zilitungwa Berlin 1796, zikisifiwa kwa muunganiko bora wa sello na piano."},
      {"title": "Sonata namba 8 'Pathétique'", "description": "Iliyochapishwa 1799, inasifiwa kwa hisia nzito na ubunifu usio na kifani."},
      {"title": "Septet, Op. 20", "description": "Ilikamilishwa 1799 na ikawa kazi maarufu zaidi wakati wa uhai wake."},
      {"title": "Quartet sita za kwanza za nyuzi", "description": "Zilitungwa kati ya 1798 na 1800 na kutolewa wakfu kwa Prince Lobkowitz."},
      {"title": "Simfoni Namba 1 na 2", "description": "Zilionyeshwa mwaka 1800 na 1803, zikimfanya kuwa mtunzi kijana maarufu baada ya Haydn na Mozart."},
      {"title": "The Creatures of Prometheus", "description": "Muziki wa ballet uliokamilika na kuonyeshwa Vienna msimu wa kuchipua 1801 kwa mafanikio makubwa."},
      {"title": "Sonata Namba 14 'Moonlight'", "description": "Ilichapishwa 1802 na kutolewa wakfu kwa Giulietta Guicciardi."},
      {"title": "Simfoni Namba 3 'Eroica'", "description": "Ilitungwa 1803-04 na kuanzisha kipindi chake cha \"Ushujaa\"."},
      {"title": "Opera Fidelio", "description": "Ilionyeshwa mara ya kwanza 1805 na baadaye kufanyiwa marekebisho mengi."},
      {"title": "Misa C major, Op. 86", "description": "Iliombwa na Prince Esterházy mwaka 1807."},
      {"title": "Tamasha kubwa la hisani", "description": "Mwaka 1808 aliandaa tamasha lililojumuisha Simfoni Namba 5 na 6 na Choral Fantasy."},
      {"title": "Muziki wa igizo la Egmont la Goethe", "description": "Uliombwa mwaka 1809 na kutolewa 1810, ukikidhi mtindo wake wa ushujaa."},
      {"title": "Quartet namba 11 ya nyuzi 'Serioso'", "description": "Kazi maarufu ya kipindi hiki iliyojaa hisia."},
      {"title": "Archduke Trio", "description": "Ilitolewa wakfu kwa mfadhili wake mkuu, Archduke Rudolph."},
      {"title": "Wellington's Victory na Simfoni Namba 7", "description": "Zilionyeshwa mwaka 1813 kwa mafanikio makubwa."},
      {"title": "Sonata namba 27 ya piano, Op. 90", "description": "Sonata yake ya kwanza tangu miaka mitano iliyopita iliyotungwa 1814."},
      {"title": "An die ferne Geliebte", "description": "Ilikamilishwa 1816, ikiingiza mtindo mpya wa mizunguko ya nyimbo."},
      {"title": "Sonata namba 29 'Hammerklavier'", "description": "Ilikamilishwa 1818, ikawa kati ya kazi zake kuu za piano."},
      {"title": "Missa solemnis", "description": "Ilichochewa na kuteuliwa kwa Rudolph mwaka 1819 na kukamilika 1823."},
      {"title": "Diabelli Variations", "description": "Ilianza mwaka 1819 kwa ombi la Diabelli na kukamilika 1823."},
      {"title": "Sonata Namba 30 na 31", "description": "Zilichapishwa mwaka 1820 na 1821, zikiwa ni miongoni mwa sonata zake za mwisho."},
      {"title": "Simfoni Namba 9", "description": "Ilionyeshwa 1824 na kuchukuliwa kama kito cha fikra mpya."},
      {"title": "Quartet Namba 12", "description": "Ilionyeshwa na kikundi cha Schuppanzigh mwaka 1825."},
      {"title": "Quartet Namba 14", "description": "Alioichukulia kama kazi yake kamilifu zaidi."},
      {"title": "Quartet Namba 16", "description": "Quartet ya nyongeza aliyokamilisha akiwa Gneixendorf."}
    ],
    "faq": [
      {"question": "Beethoven alizaliwa wapi na lini?", "answer": "Alizaliwa Bonn, Ujerumani. Rekodi zinaonyesha alibatizwa Desemba 17, 1770, hivyo inaaminika alizaliwa Desemba 16 kwa kuzingatia desturi za kipindi hicho."},
      {"question": "Kazi kuu za Beethoven ni zipi?", "answer": "Kazi zake kuu zinazojulikana zaidi ni pamoja na Simfoni Namba 3, 5, 6, 9, \"Pathétique Sonata\", na \"Moonlight Sonata\"."},
      {"question": "Lini alikufa na nini kilikuwa chanzo cha kifo chake?", "answer": "Alikufa Machi 26, 1827 akiwa na miaka 56; vyanzo vinavyohisiwa ni pamoja na ugonjwa wa ini, nimonia, na sumu ya madini ya risasi."},
      {"question": "Je, Beethoven alikuwa kiziwi kabisa?", "answer": "Alipoteza usikivu wake polepole lakini hakuwa kiziwi kabisa kwani aliweza kusikia sauti za chini na sauti kubwa za ghafla hadi mwisho wa uhai wake."},
      {"question": "Beethoven alikuwa na majina gani ya utani?", "answer": "Alitajwa mara kwa mara kama shujaa na kupewa jina la heshima kama \"Mtakatifu wa Muziki\"."},
      {"question": "Beethoven aliishi katika kipindi gani cha kimuziki?", "answer": "Alikuwa gwiji aliyeongoza kipindi cha mpito kati ya muziki wa Klasiki na Romantiki."}
    ],
    "missingDataNote": "Siku kamili ya kuzaliwa haijulikani kwa uhakika na imekisiwa kulingana na rekodi zake za ubatizo. Sababu za kifo pia hazijathibitishwa na inabaki kuwa nadharia nyingi tu."
  },
  "marcus-aurelius": {
    "timeline": [
      "Marcus Aurelius Antoninus alizaliwa Roma.",
      "Alianza kuvaa mavazi ya kifalsafa na kufuata maisha ya wanafalsafa kwa agizo la Diognetus.",
      "Hadrian alimwagiza Antoninus Pius kumchukua Marcus kama mtoto wake wa kuasili.",
      "Baada ya kifo cha Hadrian, Antoninus Pius aliapishwa kuwa Mfalme.",
      "Alihudumu kama balozi chini ya Antoninus Pius.",
      "Alikuwa balozi mwenza akiwa na Antoninus Pius.",
      "Alihudumu kama balozi kwa mara ya pili.",
      "Alimuoa Faustina, binti wa Antoninus Pius.",
      "Binti yao wa kwanza, Domitia Faustina, alizaliwa.",
      "Antoninus Pius alimpa Marcus madaraka ya kikabila na kijeshi (imperium).",
      "Faustina alijifungua mapacha wa kiume, Titus na Tiberius, ambao hawakuishi muda mrefu.",
      "Binti yao Annia Aurelia Galeria Lucilla alizaliwa.",
      "Inaaminika binti yao Domitia Faustina alifariki mwaka huu.",
      "Mtoto wa kiume Tiberius Aelius Antoninus alizaliwa lakini hakudumu sana.",
      "Mama yake Marcus, Domitia Lucilla, alifariki katika kipindi hiki.",
      "Walipoteza mtoto mwingine ambaye jina lake halikurekodiwa.",
      "Faustina aliwazaa binti Fadilla na Cornificia.",
      "Baada ya kifo cha Antoninus Pius, Marcus na Lucius Verus waliapishwa kama watawala wenza.",
      "Alishusha ubora wa fedha wa sarafu za denarius kutoka asilimia 83.5 hadi 79.",
      "Vologases IV wa Parthia aliivamia Armenia na kumuweka mfalme wake.",
      "Vita vya Parthia vilipiganwa.",
      "Lucius alikwenda vitani kusimamia Vita vya Parthia.",
      "Mji mkuu wa Armenia, Artaxata, ulitekwa.",
      "Lucius alitunukiwa taji la \"Armeniacus\".",
      "Kaine Polis ilichukua nafasi ya Artaxata kuwa mji mkuu mpya wa Armenia.",
      "Majeshi ya Roma yaliingia Mesopotamia na kumweka Mfalme Mannus madarakani.",
      "Wanajeshi wa Cassius waliteka Ctesiphon, kuchoma ikulu, na kupora Seleucia.",
      "Janga la magonjwa la Antonine lilianza Mesopotamia na kusambaa Roma.",
      "Jeshi la Cassius lilivuka mto Tigris. Lucius alipokea taji la \"Medicus\".",
      "Marcus aliwatangaza wanawe mapacha, Annius na Commodus, kuwa warithi wake.",
      "Vita dhidi ya makabila ya Kijerumani viliendelea.",
      "Alipandisha ubora wa sarafu ya denarius hadi asilimia 82.",
      "Mtawala mwenza Lucius anasadikiwa kufariki kutokana na janga la ugonjwa.",
      "Jeshi la Roma liliwashinda Wajerumani huko Dacia lakini kamanda wao Fronto aliuawa.",
      "Waasia walijaribu kuasi huko Afrika Kaskazini hadi kufikia Hispania.",
      "Alianza kutawala pamoja na mwanaye Commodus.",
      "Alifariki akiwa na umri wa miaka 58 karibu na makambi ya kijeshi Vindobona au Sirmium."
    ],
    "keyAchievements": [
      {"title": "Mfalme wa Milki ya Roma", "description": "Alikuwa mfalme wa 16 na wa mwisho wa \"Wafalme Watano Wazuri\" walioiongoza Roma kwenye kipindi cha amani (Pax Romana)."},
      {"title": "Mwanafalsafa wa Kistoa", "description": "Aliandika kitabu maarufu \"Tafakari\" (Meditations), moja ya kazi kuu za falsafa ya Kistoa."},
      {"title": "Ushindi wa kijeshi", "description": "Alifanikiwa kupambana na Milki ya Parthia Mashariki na kudhibiti makabila ya Kijerumani wakati wa Vita vya Marcomannic."},
      {"title": "Mageuzi ya Kifedha", "description": "Alisimamia mabadiliko katika ubora wa sarafu ya fedha (denarius) kudhibiti uchumi wa Roma."},
      {"title": "Utawala na Sheria", "description": "Alipigania haki za watumwa waliowekwa huru, kusaidia watoto mayatima, na kuwajali masikini."},
      {"title": "Ujenzi wa kumbukumbu", "description": "Nguzo ya Marcus Aurelius na sanamu yake ya farasi zilijengwa huko Roma kuashiria ushindi wake."}
    ],
    "faq": [
      {"question": "Marcus Aurelius alikuwa nani?", "answer": "Alikuwa mfalme wa 16 wa Roma, mwanafalsafa wa Kistoa, na Mfalme wa mwisho wa \"Wafalme Watano Wazuri\" wa enzi ya Pax Romana."},
      {"question": "Nini mafanikio yake makubwa ya kijeshi?", "answer": "Alifanikiwa kushinda milki za Parthia na Armenia, na akatuliza uasi wa makabila ya Marcomanni, Quadi, na Sarmatia."},
      {"question": "Ni kitabu gani alichokiandika?", "answer": "Aliandika \"Tafakari\" (Meditations), kitabu ambacho ni msingi muhimu wa Falsafa ya Kistoa na kinatoa taswira ya maisha yake ya kiroho."},
      {"question": "Milki ya Roma ilipitia magumu gani wakati wa utawala wake?", "answer": "Pamoja na vita vingi, janga la magonjwa la Antonine liliua takriban watu milioni tano kati ya watu milioni kumi nchini."},
      {"question": "Marcus Aurelius aliteuaje mrithi wake?", "answer": "Tofauti na watangulizi wake, alimchagua mwanaye wa kumzaa, Commodus, kuwa mrithi wake, jambo lililozua shutuma nyingi kutoka kwa wanahistoria wa kale na wa sasa."}
    ],
    "missingDataNote": ""
  },
  "confucius": {
    "timeline": [
      "Alizaliwa Changping huko Qufu, Dola la Lu; wazazi wake wakiwa Shuliang He na Yan Zhengzai.",
      "Babake Shuliang He alifariki (akiwa na miaka 3).",
      "Alifunga ndoa.",
      "Mama yake Yan Zhengzai alifariki (akiwa na miaka 16).",
      "Alimuoa binti wa familia ya Bingguan katika Dola la Song.",
      "Alipata mtoto wa kiume, Kong Li (akiwa na miaka 20).",
      "Alifungua shule Dola la Lu na kuanza kufundisha wanafunzi akiwa kwenye miaka ya 30.",
      "Alianza kazi za serikali kama mhasibu kisha msimamizi wa malisho ya wanyama akiwa na miaka 30.",
      "Alikimbilia Dola la Qi kumfuata Mfalme Zhao aliyeondolewa madarakani kutokana na Machafuko ya Lu (akiwa na miaka 35).",
      "Alirejea kutoka Qi.",
      "Aliteuliwa kuwa hakimu wa Zhongdu akiwa na miaka 46 hivi.",
      "Alipandishwa cheo na kuwa Waziri wa Sheria (Da Sikou) akiwa na miaka 52 hivi.",
      "Aliondoka Dola la Lu baada ya kutofautiana na Ji Huanzi, kisha akasafiri kwenye dola mbalimbali kwa miaka 14.",
      "Alipatwa na msiba mfululizo wa mwanaye Boyu na wanafunzi wake Yan Hui na Zilu.",
      "Alirudi nyumbani Qufu na kujikita katika kulea kizazi kipya cha wasomi.",
      "Alifariki akiwa na miaka 72, akizungukwa na wanafunzi wake.",
      "Mfalme Xuanzong wa Enzi ya Tang alimpa heshima ya \"Mfalme Wenxuan\".",
      "Mfalme Zhenzong wa Enzi ya Song alimpa heshima ya \"Mfalme Zhisheng Wenxuan\".",
      "Wakati wa Enzi ya Yuan, alianza kutambuliwa kama \"Mfalme Dacheng Zhisheng Wenxuan\".",
      "Baada ya Enzi ya Ming kuanzishwa, alitunukiwa heshima ya \"Mwalimu Mkuu Zhisheng\".",
      "Alitunukiwa heshima ya \"Mwalimu Dacheng Zhisheng Wenxuan\"."
    ],
    "keyAchievements": [
      {"title": "Uanzishaji wa shule ya kwanza Uchina", "description": "Alikuwa mtu wa kwanza katika historia ya Uchina kuanzisha shule binafsi na kufundisha wanafunzi."},
      {"title": "Kukomesha mila ya kuzikwa na wafu", "description": "Alimshauri Mfalme na kufanikiwa kufuta mila potofu ya kikatili ya kuzika watu hai pamoja na watawala waliokufa."},
      {"title": "Kurejesha ardhi ya Lu", "description": "Alitumia uhodari na maarifa kwenye majadiliano na Dola la Qi, hivyo kurudisha ardhi iliyokuwa imepotezwa na Dola la Lu."},
      {"title": "Mafunzo ya Vitabu Sita", "description": "Alitumia Vitabu Sita vya Kale (Sanaa, Ushairi, Nyaraka, Ibada, Muziki, na Majira) kuwafundisha wanafunzi wake."},
      {"title": "Falsafa ya Ren (Utu)", "description": "Alihubiri kuhusu upendo na utu, akisisitiza 'Ren' kama lengo kuu la matendo ya kibinadamu."},
      {"title": "Kulea wasomi vijana", "description": "Katika uzee wake, alirudi nyumbani na kulea kizazi cha wanafunzi mashuhuri waliokuja kueneza mawazo yake."}
    ],
    "faq": [
      {"question": "Confucius alikuwa nani?", "answer": "Alikuwa mwanasiasa, mwanafalsafa, na mwalimu nchini Uchina wakati wa Kipindi cha Spring na Autumn, anayetambulika kama mwanzilishi wa Uconfucius."},
      {"question": "Nini wazo kuu la Confucius?", "answer": "Mawazo yake yanapatikana kwenye kitabu chake \"Analects,\" akitetea uhumanisti ambapo lengo kuu la binadamu ni 'Ren' (Utu na Upendo)."},
      {"question": "Confucius alifanya kazi gani za elimu?", "answer": "Alianzisha shule ya kwanza binafsi Uchina, akiwafundisha wanafunzi wake vitabu kama Kitabu cha Mashairi, Nyaraka, na I Ching."},
      {"question": "Dira gani za kisiasa za Confucius?", "answer": "Aliamini katika kutawala nchi kupitia maadili na wema badala ya sheria kali, akithamini utu kuliko vitu vyote."},
      {"question": "Confucius alifariki lini?", "answer": "Alifariki mwaka wa 479 KK, akiwa na umri wa miaka 72, mbele ya wanafunzi wake."}
    ],
    "missingDataNote": ""
  },
  "leonardo-da-vinci": {
    "timeline": [
      "Alizaliwa katika kijiji cha milimani cha Vinci, eneo la Tuscany.",
      "Rekodi za ushuru zinaonyesha kuwa aliishi pamoja na baba yake.",
      "Mama yake wa kambo, Albiera, alifariki.",
      "Akiwa na miaka kumi na nne, alihamia Florence na kujiunga na karakana ya Andrea del Verrocchio.",
      "Alijiandikisha katika Chama cha Wachoraji cha Florence na kuanza kutambulika rasmi.",
      "Alishiriki kuchora mchoro wa \"Ubatizo wa Kristo\" wa mwalimu wake, akichora malaika wa kushoto.",
      "Alialikwa kuwa mchoraji wa familia ya kifalme ya Sforza huko Milan.",
      "Alitengeneza mchoro wa \"The Virgin of the Rocks\" (uliopo Louvre).",
      "Alijikita kwenye utafiti wa anatomia, akiandika kuhusu mwili wa binadamu, urukaji wa ndege na masuala ya mwanga (optics).",
      "Alichora mchoro wake maarufu \"Karamu ya Mwisho\" (The Last Supper).",
      "Kufuatia uvamizi wa Mfalme Louis XII wa Ufaransa, alirudi Florence mwaka 1500.",
      "Aliajiriwa na Cesare Borgia kama mhandisi wa kutengeneza mifereji na kupanga miji.",
      "Alirudi Florence na kuanza kuchora mchoro wa \"Mona Lisa\".",
      "Baba yake, Piero, alifariki akiwa na miaka 77.",
      "Alikua mchoraji wa Mfalme Louis XII wa Ufaransa huko Milan.",
      "Alirudi Florence kisha akahamia Roma chini ya ufadhili wa Giuliano de' Medici.",
      "Alikutana na Mfalme Francis I huko Bologna na kualikwa Ufaransa.",
      "Mfadhili wake Giuliano de' Medici alifariki.",
      "Alisafiri na mwanafunzi wake Francesco Melzi kwenda Amboise, Ufaransa.",
      "Aliandika wosia wake akihisi kifo kukaribia.",
      "Alifariki akiwa na miaka 67 nyumbani kwake Château du Clos Lucé, Ufaransa.",
      "Kufuatia kifo cha Francesco Melzi, michoro yake mingi ikajulikana ulimwenguni.",
      "Wakati wa Mapinduzi ya Ufaransa, kanisa alimozikwa lilibomolewa, jambo lililosababisha kupotea kwa mabaki yake."
    ],
    "keyAchievements": [
      {"title": "Msomi wa nyanja mbalimbali", "description": "Alikuwa mchoraji, mchongaji, mvumbuzi, mhandisi, mwanaanatomia na mwanamuziki aliyeiwakilisha vyema Italia."},
      {"title": "Mtu mbunifu zaidi katika historia", "description": "Mnamo 2007, jarida la Nature lilimtaja kama fikra mbunifu zaidi kati ya watu kumi waliorejesha historia ya mwanadamu."},
      {"title": "Mchoro wa Mona Lisa", "description": "Mchoro maarufu zaidi ulimwenguni na unaotambulika kama kielelezo kikuu cha Makumbusho ya Louvre."},
      {"title": "Karamu ya Mwisho", "description": "Moja ya kazi zake bora inayosifika miongoni mwa picha bora za karne zote."},
      {"title": "Uvumbuzi wa mtindo wa Sfumato", "description": "Alivumbua Sfumato, mbinu inayoonyesha hali ya hewa kuzunguka vitu, na kuunda taswira halisi ya asili na anga."},
      {"title": "Utafiti wa Sayansi", "description": "Aligundua kanuni nyingi za kisayansi zikiwemo msukumo wa maji, sheria za upaa, hewa, na anatomia ya mimea."},
      {"title": "Kitabu cha Uchoraji", "description": "Aliacha makala muhimu ikijumuisha 'Mkataba wa Uchoraji,' ambao ni andiko muhimu katika sanaa za Renaissance."}
    ],
    "faq": [
      {"question": "Leonardo da Vinci alizaliwa wapi na lini?", "answer": "Alizaliwa usiku wa manane mnamo Jumamosi Aprili 15, 1452, kwenye kijiji cha Vinci kilichopo eneo la Tuscany, Italia."},
      {"question": "Kazi kuu za Leonardo da Vinci ni zipi?", "answer": "\"Mona Lisa\" ndio mchoro wake unaojulikana zaidi duniani kote, huku \"Karamu ya Mwisho\" (The Last Supper) ikiwa pia miongoni mwa kazi zake bora kabisa."},
      {"question": "Leonardo da Vinci alihusika katika nyanja zipi?", "answer": "Alifanya kazi katika fani nyingi zikiwemo uchoraji, uchongaji, uvumbuzi, usanifu majengo, anatomia, na jiografia."},
      {"question": "Je, Leonardo da Vinci alipata elimu rasmi?", "answer": "Kwa vile alizaliwa nje ya ndoa, hakupata elimu rasmi ya kusoma na kuandika Kilatini na Kigiriki au masomo ya jadi shuleni."},
      {"question": "Leonardo da Vinci alifariki wapi?", "answer": "Alifariki akiwa na miaka 67, Mei 2, 1519, nyumbani kwake Château du Clos Lucé, Ufaransa."},
      {"question": "Mabaki ya Leonardo da Vinci bado yapo hadi sasa?", "answer": "Kutokana na kuvunjwa kwa kanisa alipozikwa wakati wa Mapinduzi ya Ufaransa mwaka 1802, mabaki yake yalipotea."},
      {"question": "Leonardo da Vinci aliwahi kuoa?", "answer": "Hapana, aliishi maisha ya ukapera muda wote na hakuacha mtoto yeyote."}
    ],
    "missingDataNote": ""
  },
  "william-shakespeare": {
    "timeline": [
      "Alizaliwa Stratford-upon-Avon, Uingereza.",
      "Alisimamisha masomo kutokana na hali ngumu ya kiuchumi ya familia na akaanza kusaidia kazi za nyumbani.",
      "Alimuoa Anne Hathaway, aliyezidi umri wake kwa miaka minane, akiwa na umri wa miaka 18.",
      "Alipata leseni ya ndoa kutoka mahakama ya Kanisa la Anglikana huko Worcester.",
      "Binti yao wa kwanza, Susanna, alizaliwa.",
      "Watoto wao mapacha, Hamnet na Judith, walizaliwa.",
      "Aliwasili jijini London na kuanza kujishughulisha na ushairi na maigizo.",
      "Aliandika michezo 38 ikiwemo tanzia na vichekesho katika kipindi cha miaka 24 kama mwandishi.",
      "Alikuwa tayari mwandishi maarufu wa michezo ya kuigiza jijini London.",
      "Alichapisha shairi refu, \"Venus and Adonis\".",
      "Alichapisha shairi la \"The Rape of Lucrece\" na kuwa mwandishi mkuu wa kikundi cha uigizaji cha Lord Chamberlain's Men.",
      "Mchezo wake wa vichekesho \"A Midsummer Night's Dream\" ulipokelewa vizuri sana kwenye onyesho lake.",
      "Kikundi chake cha uigizaji kilijenga Jumba la Kuigiza la Globe kusini mwa Mto Thames.",
      "Kufuatia kifo cha Malkia Elizabeth I, kikundi kilijulikana kama King's Men (Watu wa Mfalme).",
      "Binti yake mkubwa, Susanna, aliolewa na daktari John Hall.",
      "Alichapisha kitabu chake cha mashairi ya Soneti, \"Shakespeare's Sonnets\".",
      "Habari zilienea kuwa alirejea katika mji wake wa kuzaliwa, Stratford, miaka michache kabla ya kifo chake.",
      "Aliitwa kutoa ushahidi mahakamani kuhusiana na ndoa ya binti wa Mountjoy, Mary.",
      "Alinunua lango ambalo hapo awali lilikua sehemu ya watawa wa Blackfriars, London.",
      "Binti yake mdogo, Judith, aliolewa na mtengenezaji wa divai Thomas Quiney.",
      "Alifariki dunia, akiwaacha mkewe na mabinti wawili.",
      "Mkusanyiko wa michezo yake ya kuigiza (ikijumuisha 36) ulichapishwa ulimwenguni kwa msaada wa wenzake."
    ],
    "keyAchievements": [
      {"title": "Mwandishi mkuu wa michezo ya kuigiza Uingereza", "description": "Wakati wa uhai wake, alipewa heshima ya kuwa \"mwandishi bora wa maigizo nchini Uingereza\"."},
      {"title": "Kazi bora za asili", "description": "Michezo yake kama \"Romeo and Juliet\" na \"Hamlet\" inachukuliwa kuwa hazina kubwa inayozama katika hisia za mwanadamu na zimebaki kama kazi bora za kudumu."},
      {"title": "Umahiri katika aina zote na utunzi mkubwa", "description": "Alitunga kazi katika tanzia, vichekesho, tanzia-kichekesho na historia; akiandika michezo 36, soneti 154 na mashairi mawili marefu."},
      {"title": "Mchango katika Kiingereza cha kisasa", "description": "Alionyesha uwezo halisi wa lugha ya Kiingereza kwa uvumbuzi wa maneno mapya, akiathiri utajiri wa Kiingereza cha leo."},
      {"title": "Tragedia nne kuu", "description": "Aliandika tanzia nne kuu: \"Hamlet,\" \"Othello,\" \"King Lear,\" na \"Macbeth,\" ambazo zilimpa sifa ya milele duniani."}
    ],
    "faq": [
      {"question": "Je, William Shakespeare alisoma chuo kikuu?", "answer": "Hakupata elimu ya juu kama waandishi wengine wa wakati wake, lakini alitumia kipaji chake cha asili na hisia za ukumbi kuwa mwandishi mkuu."},
      {"question": "Kuna utata wowote kuhusu mtunzi halisi wa kazi za Shakespeare?", "answer": "Kuna maswali juu ya uwezo wake wa kutunga kazi zote bila elimu ya chuo kikuu, ingawa hakuna ushahidi wa kuthibitisha kwamba ziliandikwa na Francis Bacon au mtu mwingine yeyote."},
      {"question": "Ni aina gani ya kazi alizoandika Shakespeare?", "answer": "Aliandika tanzia, vichekesho, na historia, ikijumuisha jumla ya michezo 36 ya ukumbi, soneti 154, na mashairi mawili marefu."},
      {"question": "Tragedia (tanzia) zake nne kuu ni zipi?", "answer": "Ni \"Hamlet,\" \"Othello,\" \"King Lear,\" na \"Macbeth,\" ambazo zimempa umaarufu mkubwa katika historia ya fasihi ulimwenguni."}
    ],
    "missingDataNote": "Nyaraka kuhusu maisha yake ni chache; kwa hiyo matukio mengi hasa kipindi alichokuwa hasikiki na mwanzo wake kwenye uandishi, hutegemea makadirio na sio taarifa kamili. Utata kuhusu majina ya wazazi wake haujaingizwa."
  }
}

import codecs
with codecs.open(r"c:\Users\user\OneDrive\바탕 화면\wisdom-giants-20260512T091146Z-3-001\wisdom-giants\scratch\t1.json", "w", encoding="utf-8") as f:
    json.dump(translations1, f, ensure_ascii=False, indent=2)
