import json

translations = {
    # J.P. Morgan
    "1871년": "Shekarar 1871",
    "안토니 드렉셀과 파트너십을 맺고 J.P. 모건 앤 컴퍼니의 전신인 드렉셀, 모건 앤 컴퍼니를 설립했습니다.": "Ya kulla haɗin gwiwa da Anthony Drexel kuma ya kafa Drexel, Morgan & Co., wanda ya gabaci J.P. Morgan & Co.",
    "1892년": "Shekarar 1892",
    "에디슨 제너럴 일렉트릭과 톰슨-휴스턴 일렉트릭 컴퍼니의 합병을 주도하여 제너럴 일렉트릭을 설립했습니다.": "Ya jagoranci haɗewar Edison General Electric da Thomson-Houston Electric Company don kafa General Electric.",
    "1895년": "Shekarar 1895",
    "미국 재무부에 350만 온스의 금을 공급하는 신디케이트를 이끌어 경제를 안정시켰습니다.": "Ya jagoranci wata ƙungiya don samar da oza miliyan 3.5 na zinariya ga Baitulmalin Amurka, don daidaita tattalin arziki.",
    "1901년": "Shekarar 1901",
    "앤드류 카네기의 회사를 인수하여 세계 최초의 10억 달러 규모 기업인 미국 철강 회사(US 스틸)를 설립했습니다.": "Ya sayi kamfanin Andrew Carnegie kuma ya kafa United States Steel Corporation (US Steel), kamfanin farko na dala biliyan a duniya.",
    "1907년": "Shekarar 1907",
    "1907년의 금융 공황을 막기 위해 다수의 주요 기관에 대한 금융 구제를 진두지휘했습니다.": "Ya jagoranci ceton kuɗi ga manyan cibiyoyi da yawa don hana rikicin kuɗi na 1907.",
    # Ralph Waldo Emerson
    "1803년": "Shekarar 1803",
    "매사추세츠주 보스턴의 유니테리언 목사 가문에서 태어났습니다.": "An haife shi a Boston, Massachusetts, a cikin dangin limaman Unitarian.",
    "1836년": "Shekarar 1836",
    "미국 초월주의의 근본적인 철학적 신조를 세운 그의 첫 번째 에세이 자연을 출판했습니다.": "Ya buga makalarsa ta farko, 'Nature,' wacce ta kafa tsarin falsafar Amurka na Transcendentalism.",
    "1837년": "Shekarar 1837",
    "유럽으로부터의 지적 독립을 유명하게 촉구한 미국의 학자 연설을 했습니다.": "Ya gabatar da jawabin 'The American Scholar,' inda ya yi kira mai shahara don neman yancin ilimi daga Turai.",
    "1841년": "Shekarar 1841",
    "영향력 있는 에세이 자기 신뢰가 수록된 에세이 제1집을 출판했습니다.": "Ya buga 'Essays: First Series,' wanda ya ƙunshi makala mai tasiri 'Self-Reliance.'",
    "1844년": "Shekarar 1844",
    "저명한 반노예제 연사로 부상하여 노예제 폐지 운동을 위해 활발하게 강연했습니다.": "Ya fito a matsayin fitaccen mai jawabi na adawa da bauta, yana gabatar da laccoci sosai don ƙungiyar kawar da bauta.",
    # Susan B. Anthony
    "1851년": "Shekarar 1851",
    "엘리자베스 캐디 스탠턴을 만나 여성 권리 운동에서 강력하고 평생 지속되는 파트너십을 맺었습니다.": "Ta haɗu da Elizabeth Cady Stanton, wanda ya haifar da haɗin gwiwa mai karfi da ɗorewa a ƙungiyar yancin mata.",
    "1869년": "Shekarar 1869",
    "여성 투표권을 위한 헌법 개정 확보에 헌신하는 전국 여성 참정권 협회를 공동 설립했습니다.": "Ta kafa National Woman Suffrage Association (NWSA), wacce aka sadaukar don tabbatar da gyaran tsarin mulki don ba mata yancin yin zaɓe.",
    "1872년": "Shekarar 1872",
    "수정 헌법 제14조를 시험하기 위해 뉴욕주 로체스터에서 열린 대통령 선거에서 투표했다가 체포되었습니다.": "An kama ta saboda jefa ƙuri'a a zaben shugaban kasa a Rochester, New York, don gwada Kwaskwarima na 14.",
    "1881년": "Shekarar 1881",
    "스탠턴, 마틸다 조슬린 게이지와 함께 다권으로 구성된 여성 참정권의 역사를 출판하기 시작했습니다.": "Ta fara buga jerin littattafan 'History of Woman Suffrage' tare da Stanton da Matilda Joslyn Gage.",
    "1920년": "Shekarar 1920",
    "그녀가 사망한 지 14년 후, 여성에게 투표권을 부여하는 수정 헌법 제19조가 비준되었으며, 이는 흔히 수잔 B. 앤서니 수정안으로 알려져 있습니다.": "Shekaru 14 bayan mutuwarta, an amince da Kwaskwarima na 19, wanda ya ba mata yancin yin zaɓe, kuma aka fi sani da Kwaskwarimar Susan B. Anthony.",
    # Walt Whitman
    "1819년": "Shekarar 1819",
    "뉴욕주 웨스트 힐스의 노동자 계급 가정에서 아홉 자녀 중 둘째로 태어났습니다.": "An haife shi na biyu a cikin yara tara a cikin dangin masu aiki a West Hills, New York.",
    "1855년": "Shekarar 1855",
    "미국 시의 지형을 급격히 변화시킨 풀잎 초판을 자비로 출판했습니다.": "Ya buga bugu na farko na 'Leaves of Grass' da kudinsa, wanda ya canza yanayin waƙoƙin Amurka sosai.",
    "1862년": "Shekarar 1862",
    "부상당한 형제를 돌보기 위해 워싱턴 D.C.로 여행을 갔으며, 이후 남북전쟁 기간 동안 자원 간호사로 일했습니다.": "Ya yi tafiya zuwa Washington D.C. don kula da ɗan'uwansa da ya ji rauni, kuma ya yi aiki a matsayin ma'aikacin jinya na sa kai a lokacin Yaƙin Basasa.",
    "1865년": "Shekarar 1865",
    "미국 남북전쟁 당시의 경험을 반영한 깊은 감동을 주는 시집 드럼 탭스를 출판했습니다.": "Ya buga 'Drum-Taps,' tarin waƙoƙi masu taɓa zuciya waɗanda ke nuna abubuwan da ya gani a Yaƙin Basasa na Amurka.",
    "1892년": "Shekarar 1892",
    "뉴저지주 캠던에서 세상을 떠나기 직전 풀잎의 마지막 임종판을 준비했습니다.": "Ya shirya bugu na ƙarshe (deathbed edition) na 'Leaves of Grass' kafin ya mutu a Camden, New Jersey.",
    # Max Planck
    "1858": "Shekarar 1858",
    "홀슈타인의 킬에서 태어남.": "An haife shi a Kiel, Holstein.",
    "1864": "Shekarar 1864",
    "제2차 슐레스비히 전쟁 중 킬로의 프로이센과 오스트리아 군대 행군을 목격함.": "Ya shaida tafiyar sojojin Prussia da Ostiriya a Kiel yayin Yaƙin Schleswig na Biyu.",
    "1867": "Shekarar 1867",
    "가족이 뮌헨으로 이사하고 막시밀리안 김나지움에 등록함.": "Iyalinsa sun koma Munich, kuma ya shiga Makarantar Maximilian.",
    "1874": "Shekarar 1874",
    "뮌헨 대학교에서 연구를 시작함.": "Ya fara karatunsa a Jami'ar Munich.",
    "1877": "Shekarar 1877",
    "베를린의 프리드리히 빌헬름 대학교에서 1년 동안 연구함.": "Ya yi karatu a Jami'ar Friedrich Wilhelm da ke Berlin na tsawon shekara ɗaya.",
    "1879": "Shekarar 1879",
    "박사 학위 논문 '열역학 제2법칙에 관하여'를 방어함.": "Ya kare takardar shaidar digirin digirgir ɗin sa (Ph.D.) mai taken 'Game da Dokar Thermodynamics ta Biyu.'",
    "1880": "Shekarar 1880",
    "하빌리타치온 논문 '서로 다른 온도에서 등방성 물체의 평형 상태'를 발표하여 하빌리타치온을 획득함.": "Ya sami Habilitation ta hanyar buga takardar Habilitation 'Equilibrium states of isotropic bodies at different temperatures.'",
    "1885": "Shekarar 1885",
    "킬 대학교의 이론물리학 부교수로 임명됨.": "An naɗa shi a matsayin mataimakin farfesa na theoretical physics a Jami'ar Kiel.",
    "1887": "Shekarar 1887",
    "마리 머르크와 결혼함.": "Ya auri Marie Merck.",
    "1889": "Shekarar 1889",
    "베를린 프리드리히-빌헬름스-대학교의 키르히호프 직위를 계승하는 사람으로 임명됨.": "An naɗa shi a matsayin magajin Kirchhoff a Jami'ar Friedrich-Wilhelms ta Berlin.",
    "1892": "Shekarar 1892",
    "정교수가 됨.": "Ya zama cikakken farfesa.",
    "1894": "Shekarar 1894",
    "흑체 복사 문제에 관심을 돌림.": "Ya karkata hankalinsa kan matsalar black-body radiation.",
    "1897": "Shekarar 1897",
    "'열역학에 관한 논문'을 출판함.": "Ya buga 'Treatise on Thermodynamics.'",
    "1898": "Shekarar 1898",
    "독일 물리학회(DPG) 형성에 기여함.": "Ya ba da gudummawa wajen kafa Ƙungiyar Masana Physics ta Jamus (DPG).",
    "1900": "Shekarar 1900",
    "에너지 양자화 가설을 포함한 플랑크 흑체 복사 법칙의 새로운 유도를 발표함.": "Ya gabatar da sabon ƙirƙira na dokar Planck's black-body radiation, wanda ya haɗa da tsinkayen ƙididdigar makamashi (energy quantization).",
    "1905": "Shekarar 1905",
    "독일 물리학회(DPG) 회장이 됨 (1909년까지).": "Ya zama shugaban Ƙungiyar Masana Physics ta Jamus (DPG) (har zuwa 1909).",
    "1909": "Shekarar 1909",
    "첫 번째 부인 마리 플랑크가 사망함.": "Matarsa ta farko, Marie Planck, ta mutu.",
    "1911": "Shekarar 1911",
    "두 번째 부인 마르가 폰 회슬린과 결혼함.": "Ya auri matarsa ta biyu, Marga von Hoesslin.",
    "1914": "Shekarar 1914",
    "아인슈타인을 베를린으로 불러 새로운 교수직을 만들 수 있었음.": "Ya yi nasarar kawo Einstein zuwa Berlin ta hanyar ƙirƙirar masa sabon matsayin farfesa.",
    "1916": "Shekarar 1916",
    "장남 카를이 베르됭 전투에서 전사함.": "Babban ɗansa, Karl, ya mutu a Yaƙin Verdun.",
    "1917": "Shekarar 1917",
    "딸 그레테가 첫 아이를 낳다가 사망함.": "Diyarsa, Grete, ta mutu tana haihuwar ɗanta na fari.",
    "1918": "Shekarar 1918",
    "에너지 양자의 발견으로 노벨 물리학상을 수상함 (실제 수상은 1919년).": "Ya lashe kyautar Nobel a Physics saboda gano quanta na makamashi (an bayar da shi ne a 1919).",
    "1919": "Shekarar 1919",
    "딸 엠마가 사망함.": "Diyarsa, Emma, ta mutu.",
    "1920": "Shekarar 1920",
    "프리츠 하버와 함께 독일 과학 비상기구(Notgemeinschaft der Deutschen Wissenschaft)를 설립함.": "Tare da Fritz Haber, ya kafa Notgemeinschaft der Deutschen Wissenschaft (Ƙungiyar Taimakon Gaggawa ta Kimiyyar Jamus).",
    "1926": "Shekarar 1926",
    "베를린에서 은퇴하고 에르빈 슈뢰딩거가 그의 뒤를 이음.": "Ya yi ritaya daga Berlin, kuma Erwin Schrödinger ya gaje shi.",
    "1930": "Shekarar 1930",
    "카이저 빌헬름 협회(KWG)의 회장이 됨.": "Ya zama shugaban Ƙungiyar Kaiser Wilhelm (KWG).",
    "1933": "Shekarar 1933",
    "나치가 집권했을 때 74세였으며, 히틀러와 유대인 교수 처우에 대해 논의함.": "Yana da shekaru 74 a lokacin da 'yan Nazi suka hau mulki, kuma ya tattauna batun kula da farfesoshi na Yahudawa tare da Hitler.",
    "1936": "Shekarar 1936",
    "카이저 빌헬름 협회(KWG) 회장 임기가 끝남.": "Wa'adinsa na shugabancin Ƙungiyar Kaiser Wilhelm (KWG) ya ƙare.",
    "1938": "Shekarar 1938",
    "80세 생일을 맞았고, 프로이센 아카데미가 나치에 인수되자 회장직을 사임함.": "Ya cika shekaru 80 da haihuwa, kuma ya yi murabus daga shugabancin Cibiyar Ilimi ta Prussian a lokacin da 'yan Nazi suka karbe ta.",
    "1944": "Shekarar 1944",
    "베를린에 있는 그의 집이 공습으로 파괴되어 모든 과학 기록과 서신이 소실됨.": "Gidansa da ke Berlin ya lalace sakamakon harin bama-bamai daga sama, wanda ya haifar da asarar dukkan bayanan kimiyya da wasiƙunsa.",
    "1945": "Shekarar 1945",
    "아들 에르빈이 히틀러 암살 시도에 가담했다는 이유로 처형됨.": "An kashe ɗansa, Erwin, saboda shiga cikin yunkurin kisan Hitler.",
    "1947": "Shekarar 1947",
    "괴팅겐에서 사망함.": "Ya mutu a Göttingen.",
    "1948": "Shekarar 1948",
    "카이저 빌헬름 협회가 막스 플랑크 협회(MPG)로 이름이 변경됨.": "An canza sunan Ƙungiyar Kaiser Wilhelm zuwa Ƙungiyar Max Planck (MPG).",
    "에너지 양자 발견": "Gano Quanta na Makamashi",
    "에너지 양자의 발견으로 1918년 노벨 물리학상을 수상했으며, 이는 원자 및 아원자 과정에 대한 이해에 혁명을 일으켰습니다.": "Ya lashe kyautar Nobel a Physics a shekarar 1918 don gano quanta na makamashi, wanda ya canza fahimtar tsarin atomic da subatomic.",
    "양자 이론의 창시": "Ƙirƙirar Ka'idar Quantum",
    "물리학자로서의 명성은 주로 양자 이론의 창시자로서의 역할에 있으며, 이는 고전 물리학과 양립할 수 없는 혁명적인 아이디어였습니다.": "Shahararsa a matsayin masanin kimiyyar physics tana da nasaba ne da rawar da ya taka a matsayin wanda ya kirkiro ka'idar quantum, wani ra'ayi ne na juyin juya hali wanda ya ci karo da classical physics.",
    "플랑크 흑체 복사 법칙": "Dokar Planck's Black-Body Radiation",
    "흑체 복사 문제에 대한 연구를 통해 실험적으로 관찰된 흑체 스펙트럼을 잘 설명하는 플랑크 흑체 복사 법칙을 유도했습니다.": "Ta hanyar nazarinsa kan matsalar black-body radiation, ya samo dokar Planck's black-body radiation wacce ke bayyana ainihin abin da aka gani ta hanyar gwaji na tsarin black-body spectrum.",
    "플랑크 상수 (h)": "Planck Constant (h)",
    "전자기 에너지가 양자화된 형태로만 방출될 수 있다는 가설을 통해 플랑크 상수(h)를 도입하여 양자 이론의 근간을 마련했습니다.": "Ya gabatar da Planck constant (h) ta hanyar hasashen cewa makamashin electromagnetic yana fita ne kawai a cikin yanayin ƙididdigewa, yana aza harsashin ka'idar quantum.",
    "상대성 이론의 초기 인식 및 기여": "Fahimtar Farko da Gudummawa ga Ka'idar Relativity",
    "알베르트 아인슈타인의 특수 상대성이론의 중요성을 즉시 인식한 몇 안 되는 사람 중 하나였으며, 이론을 재구성하는 데 기여했습니다.": "Yana daga cikin mutane kalilan da suka gane muhimmancin ka'idar special relativity ta Albert Einstein nan take, kuma ya ba da gudummawa wajen sake tsara ka'idar.",
    "독일 과학 기관의 리더십": "Shugabancin Cibiyoyin Kimiyyar Jamus",
    "독일 물리학회(DPG) 회장과 카이저 빌헬름 협회(KWG) 회장을 역임하며 독일 과학계의 주요 직책을 수행했습니다.": "Ya yi aiki a matsayin shugaban Kungiyar Masana Physics ta Jamus (DPG) da shugaban Kungiyar Kaiser Wilhelm (KWG), yana rike da manyan mukamai a fagen kimiyyar Jamus.",
    "막스 플랑크는 어떤 중요한 과학적 발견을 했나요?": "Wane muhimmin gano na kimiyya Max Planck ya yi?",
    "막스 플랑크는 에너지 양자를 발견하고 양자 이론을 창시하여 원자 및 아원자 과정에 대한 이해에 혁명을 일으켰습니다.": "Max Planck ya gano quanta na makamashi kuma ya kafa ka'idar quantum, wanda ya kawo juyin juya hali ga fahimtar tsarin atomic da subatomic.",
    "막스 플랑크는 언제 노벨 물리학상을 수상했나요?": "Yaushe Max Planck ya lashe Kyautar Nobel ta Physics?",
    "그는 에너지 양자의 발견으로 1918년에 노벨 물리학상을 수상했으며, 실제 수상은 1919년에 이루어졌습니다.": "Ya lashe kyautar Nobel ta Physics a shekarar 1918 don gano quanta na makamashi, kodayake an ba shi a zahiri a shekarar 1919.",
    "막스 플랑크는 나치 정권에 대해 어떤 입장을 취했나요?": "Wane matsayi Max Planck ya ɗauka game da gwamnatin Nazi?",
    "그는 유대인 동료들을 돕고 과학의 독립성을 지키려 노력했으며, 히틀러와 유대인 교수 처우에 대해 논의하고 프로이센 아카데미 회장직을 사임하며 나치에 항의했습니다.": "Ya yi kokarin taimakawa abokan aikinsa Yahudawa da kuma kare yancin kimiyya, ya tattauna yadda ake kula da farfesoshi na Yahudawa tare da Hitler, kuma ya yi murabus daga shugabancin Cibiyar Prussian don nuna adawa da 'yan Nazi.",
    "막스 플랑크의 종교적 견해는 어떠했나요?": "Menene ra'ayin Max Planck game da addini?",
    "그는 독일 루터교 교인이었으며, 전능하고 전지전능하며 자비로운 신(반드시 인격적인 신은 아니더라도)을 믿었고, 과학과 종교 모두 '신을 향하여!'라는 목표를 가지고 있다고 보았습니다.": "Shi ɗan darikar Lutheran na Jamus ne, kuma ya yi imani da Allah mai iko da komai, masani, kuma mai jin ƙai (kodayake ba lallai ba ne a matsayin allahntaka na mutum ba), kuma ya gani cewa duka kimiyya da addini suna da buri daya: 'Zuwa ga Allah!'",
    # Ibn al-Haytham
    "965년": "Shekarar 965",
    "이슬람 황금기 시대에 오늘날 이라크의 바스라에서 태어났습니다.": "An haife shi a Basra, a Iraki ta yanzu, a lokacin Zamanin Zinare na Musulunci.",
    "1011년": "Shekarar 1011",
    "나일강의 범람을 통제하는 데 실패한 후 파티마 왕조 칼리프의 분노를 피하기 위해 미친 척했습니다.": "Ya yi ikirarin hauka don kauce wa fushin Halifa Fatimid bayan ya gaza shawo kan ambaliyar kogin Nilu.",
    "1021년": "Shekarar 1021",
    "빛에 대한 과학적 이해에 지대한 영향을 미친 대작 광학서(키탑 알-마나지르)를 완성했습니다.": "Ya kammala babban aikinsa, 'The Book of Optics' (Kitab al-Manazir), wanda ya yi tasiri matuka kan fahimtar kimiyya game da haske.",
    "1027년": "Shekarar 1027",
    "프톨레마이오스 모델에 도전하는 천문학과 수학에 관한 비판적 저작들을 저술했습니다.": "Ya rubuta muhimman ayyuka kan ilimin taurari da lissafi wanda ya kalubalanci tsarin Ptolemy.",
    "1040년": "Shekarar 1040",
    "현대 광학의 아버지이자 과학적 방법론의 선구자로서 유산을 남기고 카이로에서 사망했습니다.": "Ya mutu a Alkahira, ya bar tarihi a matsayin uban kimiyyar haske (optics) na zamani kuma jagora a tsarin kimiya (scientific methodology).",
    # Dmitri Mendeleev
    "1834년": "Shekarar 1834",
    "시베리아 토볼스크에서 대가족의 막내로 태어났습니다.": "An haife shi auta a cikin babban iyali a Tobolsk, Siberiya.",
    "1855년": "Shekarar 1855",
    "상트페테르부르크의 중앙 사범 대학에서 과학 학위로 졸업했습니다.": "Ya kammala digirin kimiyya daga Main Pedagogical Institute a Saint Petersburg.",
    "1869년": "Shekarar 1869",
    "러시아 화학회에서 원소의 주기율을 발표하여 최초의 원소 주기율표를 만들었습니다.": "Ya gabatar da Tsarin Lokaci na abubuwa (Periodic Law of elements) ga Kungiyar Masana Kimiyya ta Rasha, inda ya kirkiro Jadawalin Tsarin Lokaci (Periodic Table) na farko.",
    "1871년": "Shekarar 1871",
    "주기율표의 빈칸을 채우기 위해 갈륨과 저마늄 같은 아직 발견되지 않은 원소들의 존재와 성질을 정확하게 예측했습니다.": "Don cike gibin da ke cikin jadawalin, ya yi hasashen kasancewa da kaddarorin abubuwan da ba a gano ba kamar su gallium da germanium daidai.",
    "1893년": "Shekarar 1893",
    "러시아의 도량형 국장으로 임명되어 러시아의 측정 시스템을 표준화했습니다.": "An naɗa shi Darakta na Ma'auni da Sikeli (Weights and Measures) na Rasha, kuma ya daidaita tsarin auna na Rasha.",
    # Ada Lovelace
    "1815년": "Shekarar 1815",
    "런던에서 시인 조지 고든 바이런의 유일한 적출 자녀인 어거스타 에이다 바이런으로 태어났습니다.": "An haife ta da sunan Augusta Ada Byron a Landan, 'ya ɗaya tilo halacciya ga mawaƙi George Gordon Byron.",
    "1833년": "Shekarar 1833",
    "탁월한 박식가인 찰스 배비지를 소개받아 그의 계산기에 깊은 흥미를 느끼게 되었습니다.": "An gabatar da ita ga Charles Babbage, fitaccen masani, kuma ta yi matukar sha'awar injinsa na lissafi.",
    "1842년": "Shekarar 1842",
    "배비지가 제안한 해석기관에 관한 이탈리아 엔지니어의 논문을 번역하기 시작했습니다.": "Ta fara fassara takardar wani injiniyan Italiya game da Injin Bincike (Analytical Engine) wanda Babbage ya tsara.",
    "1843년": "Shekarar 1843",
    "최초의 컴퓨터 알고리즘으로 여겨지는 내용이 담긴 방대한 주석을 덧붙여 번역본을 출판했습니다.": "Ta buga fassarar tare da ƙarin bayanai masu yawa, waɗanda ake ganin su ne algorithm na farko na kwamfuta.",
    "1852년": "Shekarar 1852",
    "세계 최초의 컴퓨터 프로그래머라는 유산을 남기고 36세의 나이에 자궁암으로 사망했습니다.": "Ta mutu sakamakon cutar kansa ta mahaifa tana da shekaru 36, ta bar tarihi a matsayin mai tsara shirye-shiryen kwamfuta na farko a duniya.",
    # Alan Turing
    "1912": "Shekarar 1912",
    "6월 23일 출생": "An haife shi a ranar 23 ga Yuni",
    "1931": "Shekarar 1931",
    "케임브리지 대학교에서 수학 전공 시작": "Ya fara karatun lissafi a Jami'ar Cambridge",
    "1933": "Shekarar 1933",
    "물리학자 에딩턴의 과학적 방법론 수강 및 중심극한정리 증명": "Ya halarci darussan masanin kimiyyar physics Eddington kan tsarin kimiya kuma ya tabbatar da Central Limit Theorem",
    "1936": "Shekarar 1936",
    "결정가능성 문제에 대한 부정적 증명을 해낸 후 프린스턴 대학교로 떠남": "Ya bayar da hujjojin korewa ga matsalar Entscheidungsproblem (decision problem) sannan ya tafi Jami'ar Princeton",
    "1939": "Shekarar 1939",
    "프린스턴 대학교 학업을 마치고 케임브리지로 돌아옴": "Ya kammala karatunsa a Jami'ar Princeton kuma ya koma Cambridge",
    "1940": "Shekarar 1940",
    "제2차 세계 대전 중 암호학 부서(GCCS)에 들어가 암호학 연구 시작": "Ya shiga Sashen Rubutun Sirri (GCCS) lokacin Yaƙin Duniya na Biyu kuma ya fara nazarin cryptography",
    "1945": "Shekarar 1945",
    "튜링 머신 고안; 10월 1일 국립물리연구소(NPL)에서 전자 계산기 제작을 위한 수학 부서 창설 추진": "Ya ƙirƙiro Injin Turing; a ranar 1 ga Oktoba, ya tura gaba don ƙirƙirar sashin lissafi a Cibiyar Kula da Kimiyyar Physics (NPL) don yin injin ƙirga na lantarki",
    "1946": "Shekarar 1946",
    "대영 제국 훈장 4등급(OBE) 수훈": "Ya sami lambar yabo ta Order of the British Empire (OBE) mataki na 4",
    "1950": "Shekarar 1950",
    "철학 저널 '마인드'에 '기계가 생각할 수 있는가?'라는 주제의 논문을 발표": "Ya buga takarda a jaridar falsafa ta 'Mind' kan taken 'Shin injuna za su iya tunani?'",
    "1952": "Shekarar 1952",
    "동성애 혐의로 영국 경찰에 체포돼 유죄 판결을 받음": "'Yan sandan Burtaniya sun kama shi bisa zargin luwadi kuma an same shi da laifi",
    "1953": "Shekarar 1953",
    "제타 함수에 대한 논문을 발표": "Ya buga takarda kan Zeta function",
    "1954": "Shekarar 1954",
    "6월 7일 사이안화 칼륨에 중독되어 사망": "Ya mutu saboda gubar potassium cyanide a ranar 7 ga Yuni",
    "2013": "Shekarar 2013",
    "12월 24일 엘리자베스 2세 여왕이 튜링의 동성애 죄를 사면": "Sarauniya Elizabeth ta II ta yafe wa Turing laifin luwadi a ranar 24 ga Disamba",
    "튜링 기계 고안": "Ƙirƙirar Injin Turing",
    "알고리즘과 계산 개념을 튜링 기계라는 추상 모델을 통해 형식화하여 컴퓨터 과학 발전에 지대한 공헌을 했습니다.": "Ya kafa qa'idodin algorithm da ƙididdiga ta hanyar wani ƙirar ƙima da ake kira Injin Turing, wanda ya ba da babbar gudummawa ga ci gaban kimiyyar kwamfuta.",
    "튜링 테스트 제안": "Gabatar da Gwajin Turing",
    "'기계가 생각하는 것이 가능한가?'라는 명제로 기계의 답이 얼마나 인간다운지 평가하는 실험을 제안하여 성과를 거두었습니다.": "Ya sami gagarumar nasara ta hanyar ba da shawarar gwaji wanda ke tantance yadda martanin inji ya zama irin na ɗan adam, tare da tambayar 'Shin yana yiwuwa inji ya yi tunani?'",
    "에니그마 해독": "Fassara Sirrin Enigma",
    "제2차 세계 대전 동안 독일군의 암호를 해독하기 위해 봄베라는 암호 해독기를 도입하여 해독에 성공했습니다.": "A lokacin Yaƙin Duniya na Biyu, ya yi nasarar warware bayanan sirri na sojojin Jamus ta hanyar gabatar da na'urar fassarar sirri da ake kira Bombe.",
    "중심극한정리 증명": "Tabbatar da Central Limit Theorem",
    "1933년에 핀란드의 수학자 얄 발데마르 린데베리가 1922년에 먼저 증명한 내용을 모르는 상태에서 이를 증명했습니다.": "Ya tabbatar da wannan a cikin 1933 ba tare da sanin cewa masanin lissafi na ƙasar Finland Jarl Waldemar Lindeberg ya riga ya tabbatar da shi a shekarar 1922 ba.",
    "결정가능성 문제 부정적 증명": "Hujjar Korewa ga Matsalar Entscheidungsproblem",
    "1936년에 결정가능성 문제에 대한 부정적 증명을 해냈습니다.": "Ya gudanar da hujjojin korewa ga matsalar Entscheidungsproblem (decision problem) a cikin 1936.",
    "앨런 튜링은 어떤 분야의 선구적 인물인가요?": "A wane fanni ne Alan Turing ya zama jagora?",
    "잉글랜드의 컴퓨터 과학자, 수학자, 암호학자, 논리학자이며 컴퓨터 과학의 선구적 인물입니다.": "Shi masanin kimiyyar kwamfuta ne, masanin lissafi, masanin rubutun sirri (cryptographer), kuma masanin dabaru (logician) na kasar Ingila wanda yake jigo ne a fagen kimiyyar kwamfuta.",
    "튜링상은 무엇을 기리기 위해 제정되었나요?": "Don girmama me aka kafa Kyautar Turing?",
    "ACM에서 컴퓨터 과학에 중요한 업적을 남긴 사람들에게 매년 시상하는 상으로, 튜링의 공로를 기리기 위해 1966년부터 제정되었습니다.": "Kyauta ce ta shekara-shekara da ACM ke bayarwa ga masu bayar da gagarumar gudummawa a kimiyyar kwamfuta, kuma an kafa ta a cikin 1966 don girmama gudummawar Turing.",
    "앨런 튜링은 왜 '컴퓨터 과학의 아버지'라고 불리나요?": "Me yasa ake kiran Alan Turing 'Uban Kimiyyar Kwamfuta'?",
    "이론 컴퓨터 과학과 인공지능 분야에 지대한 공헌을 했기 때문에 '컴퓨터 과학의 아버지'라고 불립니다.": "Ana kiransa 'Uban Kimiyyar Kwamfuta' saboda gudummawar da ya bayar ga tsarin ka'idar kimiyyar kwamfuta da basirar wucin gadi (AI).",
    "앨런 튜링의 동성애 죄는 언제 사면되었나요?": "Yaushe aka yafe wa Alan Turing laifin luwadi?",
    "사후 59년만인 2013년 12월 24일에 엘리자베스 2세 여왕이 튜링의 동성애 죄를 사면하였습니다.": "Sarauniya Elizabeth ta II ta yafe wa Turing laifin luwadi a ranar 24 ga Disamba, 2013, shekaru 59 bayan mutuwarsa.",
    # Charles Babbage
    "1791년": "Shekarar 1791",
    "런던에서 태어나 일찍부터 수학에 강렬한 매력을 보였습니다.": "An haife shi a Landan, inda ya nuna tsananin sha'awar ilimin lissafi tun yana ƙarami.",
    "1822년": "Shekarar 1822",
    "천문학 및 수학 표 계산을 기계화하기 위해 차분기관 제작을 제안했습니다.": "Ya ba da shawarar gina Injin Difference Engine don sarrafa ƙididdigar ilimin taurari da teburin lissafi a matsayin inji.",
    "1828년": "Shekarar 1828",
    "케임브리지 대학교의 루카스 수학 석좌 교수로 임명되었습니다.": "An nada shi a matsayin Lucasian Professor na Mathematics a Jami'ar Cambridge.",
    "1837년": "Shekarar 1837",
    "완전히 프로그래밍 가능한 기계식 컴퓨터를 구상한 혁명적인 디자인인 해석기관을 고안했습니다.": "Ya ƙirƙiro Injin Bincike (Analytical Engine), wani tsari mai kawo canji wanda ya ba da damar gina injin kwamfuta na zamani wanda za'a iya tsara masa aiki.",
    "1871년": "Shekarar 1871",
    "선구적인 기계식 컴퓨터를 미완성으로 남긴 채 런던에서 사망했지만, 현대 컴퓨팅의 개념적 틀을 확립했습니다.": "Ya mutu a Landan ya bar injinsa na lissafi na farko bai kammalu ba, amma ya aza harsashin tsarin kirkirar kwamfuta na zamani.",
    # Ibn Sina
    "980년": "Shekarar 980",
    "사만 왕조의 징세관 압둘라흐 이븐 알 하산과 시타라의 자식으로 부하라 근교의 아프샤나에서 태어났다.": "An haife shi a Afshana, kusa da Bukhara, ɗa ne ga Abdullah ibn al-Hasan, mai tara haraji na Daular Samanid, da matarsa Sitara.",
    "985년": "Shekarar 985",
    "다섯 살 때 일가가 부하라로 이주하였고, 부하라의 사숙에 들어갔다.": "Iyalinsa sun koma Bukhara lokacin da yake da shekaru biyar, kuma ya shiga wata makaranta mai zaman kanta a Bukhara.",
    "990년": "Shekarar 990",
    "열 살 때 이미 아랍의 많은 문학 작품과 꾸란을 암송할 수 있었다.": "Ya iya haddace ayyukan adabin Larabawa da yawa da kuma Alkur'ani lokacin yana da shekaru goma kacal.",
    "996년": "Shekarar 996",
    "열여섯 살 때 환자를 진료하기 시작했다.": "Ya fara duba marasa lafiya lokacin yana da shekaru goma sha shida.",
    "998년": "Shekarar 998",
    "열여덟 살 때 독학을 하였고, 알 파라비의 주석서를 통해 아리스토텔레스 철학을 이해하게 되었다.": "Ya yi karatun kansa tun yana da shekaru goma sha takwas, kuma ya fahimci Falsafar Aristotle ta hanyar sharhin al-Farabi.",
    "열여덟 살 때 이웃 알-아루디를 위해 최초의 저작 《여러 학문의 집성》을 저술하였다.": "Ya rubuta littafinsa na farko, 'Tarin Ilimi Daban-daban' (Compendium of Sciences), ga makwabcinsa al-Aruzi, a lokacin yana da shekaru goma sha takwas.",
    "999년": "Shekarar 999",
    "사만 왕조가 가즈나 왕조와 카라한 왕조의 공격으로 멸망하였다.": "Daular Samanid ta faɗi bayan hare-haren da Daular Ghaznavid da Daular Karakhanid suka kaddamar.",
    "아버지 압둘라흐가 세상을 떠났다.": "Mahaifinsa, Abdullah, ya mutu.",
    "스물한 살 때 법학자 알 바르키를 위해 전20권의 백과사전 《공정한 판단의 서》를 써서 올렸다.": "Ya rubuta kundin sani (encyclopedia) mai juzu'i 20 na 'The Book of Fair Judgment' ga masanin shari'a al-Barqi lokacin yana ɗan shekara ashirin da ɗaya.",
    "1002년": "Shekarar 1002",
    "스물두 살 때 부하라를 떠나 방랑길에 올랐다.": "Ya bar Bukhara ya fara tafiye-tafiye a lokacin yana da shekaru ashirin da biyu.",
    "1012년": "Shekarar 1012",
    "호라즘 지방의 우르겐치 통치자 마문 2세에게 기용되어 관리가 되었고, 《의학전범》의 집필을 시작하였다.": "Mamun na biyu, mai mulkin Urgench a yankin Khwarazm ne ya dauke shi aiki, ya zama jami'in gwamnati, sannan ya fara rubuta littafin 'The Canon of Medicine.'",
    "1014년": "Shekarar 1014",
    "테헤란 근교의 레이로 옮겨 30여 편의 단편을 써 냈다.": "Ya koma Rey, kusa da Tehran, kuma ya rubuta gajerun ayyuka sama da 30.",
    "1020년": "Shekarar 1020",
    "이전부터 집필해 오던 《의학전범》을 완성시켰다.": "Ya kammala rubuta littafinsa na 'The Canon of Medicine,' wanda ya fara tun da dadewa.",
    "1021년": "Shekarar 1021",
    "샴스 웃다울라가 세상을 떠나고, 이븐 시나는 관직을 버리고 은거하였다.": "Shams al-Dawla ya mutu, sannan Ibn Sina ya yi murabus daga mukamin gwamnati kuma ya koma rayuwar keɓewa.",
    "1021년 이후": "Bayan Shekarar 1021",
    "하마단의 새로운 군주 사마 웃다울라에 의해 감옥에 갇혔다.": "Sama al-Dawla, sabon mai mulkin Hamadan ne ya daure shi.",
    "1030년": "Shekarar 1030",
    "이스파한이 가즈나 왕조의 군주 마스우드 1세의 공격을 받아 이븐 시나의 장서를 포함한 소유물들이 빼앗겼다.": "Isfahan ya fuskanci hari daga Mas'ud na I, mai mulkin Daular Ghaznavid, wanda ya haifar da sace dukiyoyin Ibn Sina, ciki har da tarin littattafansa.",
    "1037년 6월 18일": "18 ga Yuni, 1037",
    "하마단에서 사망하였다.": "Ya mutu a Hamadan.",
    "철학 및 의학 집대성": "Tattara Falsafa da Magunguna",
    "그리스와 아라비아의 철학과 의학을 집대성하였으며, 아리스토텔레스 철학과 신플라톤주의를 통합하여 유럽의 의학, 철학에 큰 영향을 미쳤다.": "Ya tattara ilimin falsafa da magunguna na Girka da Larabawa, tare da haɗa falsafar Aristotle da Neoplatonism, wanda ya yi babban tasiri ga kimiyyar magunguna da falsafar Turai.",
    "의학 전범 저술": "Rubuta 'The Canon of Medicine'",
    "당시 알려진 모든 의학 정보를 집대성한 《의학 전범》을 저술하여 17세기에 이르기까지 유럽 의학의 기본서로 사용되었다.": "Ya rubuta 'The Canon of Medicine,' wanda ya tattara duk wani bayanin likitanci da aka sani a wancan lokacin, wanda aka yi amfani da shi a matsayin asalin rubutun likitancin Turai har zuwa karni na 17.",
    "치유의 서 저술": "Rubuta 'The Book of Healing'",
    "윤리학과 정치학을 제외한 모든 영역의 학문을 포괄하는 백과사전인 《치유의 서》를 저술하였다.": "Ya rubuta 'The Book of Healing,' kundin sani da ya shafi dukkanin fannonin ilimi banda ɗa'a (ethics) da siyasa.",
    "자연과학 연구": "Bincike a Kimiyyar Halitta (Natural Science)",
    "연금술의 금속 변환 가능성을 부정하고, 수학, 물리학, 천문학, 광물학 등 다양한 자연과학 분야를 연구하였다.": "Ya musanta yiwuwar sauya karafa na alchemy, kuma ya gudanar da bincike a fannoni daban-daban na kimiyyar halitta, kamar lissafi, physics, ilimin taurari, da kimiyyar ma'adanai.",
    "유럽 학계 영향": "Tasiri ga Ilimin Turai",
    "토마스 아퀴나스에게 영향을 주었으며, 12세기 후반 유럽의 아리스토텔레스 부흥운동의 계기가 되었다.": "Ya yi tasiri ga Thomas Aquinas, kuma ya zama silar farkawarka na Aristotle a Turai a karshen karni na 12.",
    "이븐 시나는 어떤 인물로 평가받나요?": "Yaya ake kallon matsayin Ibn Sina?",
    "페르시아 제국의 철학자이자 의학자, 과학자로, 중세 최대 의학자 중 한 명이며 이슬람 세계가 낳은 최고의 지식인으로 평가받습니다.": "Ana ɗaukarsa a matsayin masanin falsafa na Daular Farisa, masanin likitanci, masanin kimiyya, ɗaya daga cikin manyan likitoci na tsakiyar zamani, kuma babban malami wanda duniyar Islama ta samar.",
    "이븐 시나의 주요 의학 저서는 무엇인가요?": "Wane ne babban littafin likitanci na Ibn Sina?",
    "당시 알려진 모든 의학 정보를 집대성한 《의학 전범》을 저술하였으며, 이 책은 17세기에 이르기까지 유럽 의학의 기본서로 사용되었습니다.": "Ya rubuta 'The Canon of Medicine,' wanda ya tattara dukkanin bayanan likitancin da aka sani a wancan lokacin; an yi amfani da wannan littafin a matsayin ginshiƙin ilimin likitanci na Turai har zuwa ƙarni na 17.",
    "이븐 시나는 어떤 철학적 기여를 했나요?": "Wace irin gudummawar falsafa Ibn Sina ya bayar?",
    "그리스와 아라비아의 철학을 집대성하고 아리스토텔레스 철학과 신플라톤주의를 통합하여 유럽의 의학 및 철학에 큰 영향을 미쳤습니다.": "Ya tattara ilimin falsafar Girka da Larabawa, inda ya haɗa falsafar Aristotle da Neoplatonism, wanda ya yi tasiri matuka a likitanci da falsafar Turai.",
    "이븐 시나는 연금술에 대해 어떤 입장이었나요?": "Wane matsayi Ibn Sina yake da shi game da alchemy (kimiyyar sauya karafa)?",
    "당시 연금술사들이 신봉하던 금속 변환의 가능성을 부정하며, 금속의 차이가 심오하여 연금술로 만든 귀금속은 모조품에 불과하다고 주장했습니다.": "Ya musanta yiwuwar sauya karafa da masu ilimin alchemy na lokacin suka yi imani da shi, yana mai cewa bambance-bambancen dake tsakanin karafa yana da zurfi, kuma karafa masu daraja da ake sarrafawa ta hanyar alchemy jabu ne kawai.",
    # James Watt
    "1736년": "Shekarar 1736",
    "스코틀랜드 그리녹에서 상인과 조선공 가문에서 태어났습니다.": "An haife shi a cikin dangin 'yan kasuwa da masu kera jiragen ruwa a Greenock, Scotland.",
    "1765년": "Shekarar 1765",
    "뉴코먼 증기 기관의 효율을 크게 높이기 위해 분리형 응축기에 대한 아이디어를 고안했습니다.": "Ya ƙirƙiro dabarar (separate condenser) don ƙara ƙarfin aikin Injin Tururi (Steam engine) na Newcomen sosai.",
    "1769년": "Shekarar 1769",
    "연료를 획기적으로 절약하는 분리형 응축기를 도입한 혁신적인 증기 기관 설계로 특허를 획득했습니다.": "Ya mallaki haƙƙin mallaka na na'urar tururi mai kawo sauyi, wacce ta haɗa da injin na musamman don rage yawan amfani da makamashi (man fetur) sosai.",
    "1775년": "Shekarar 1775",
    "매튜 볼턴과 함께 성공적인 파트너십을 맺고 개선된 증기 기관을 제조 및 판매했습니다.": "Ya ƙirƙiri kyakkyawan haɗin gwiwa da Matthew Boulton don kerawa da sayar da ingantaccen injin tururi.",
    "1781년": "Shekarar 1781",
    "태양과 행성 기어 시스템의 특허를 획득하여 증기 기관이 제분소와 공장을 위한 회전 운동을 생성하도록 개조했습니다.": "Ya mallaki haƙƙin (sun and planet gear system), yana canza injunan tururi don samar da motsin jujjuya don amfanin injin niƙa da masana'antu.",
    # George Stephenson
    "1781년": "Shekarar 1781",
    "잉글랜드 노섬벌랜드주 와일럼에서 태어나 어린 나이에 지역 탄광에서 일하기 시작했습니다.": "An haife shi a Wylam, Northumberland, a Ingila, kuma ya fara aiki a ma'adanin kwal na yankin tun yana ƙarami.",
    "1814년": "Shekarar 1814",
    "킬링워스 탄광에서 석탄을 운반하기 위해 첫 번째 증기 기관차인 블뤼허를 제작했습니다.": "Ya gina Injin Tururi na farko, 'Blücher,' don jigilar kwal a tashar ma'adinai ta Killingworth.",
    "1825년": "Shekarar 1825",
    "스톡턴-달링턴 철도를 개통하여 세계 최초의 공공 여객 증기 열차인 로코모션 1호를 운행했습니다.": "Ya bude hanyar dogo ta Stockton and Darlington Railway, inda ya gudanar da jirgin fasinja na farko na tururi a duniya, mai suna 'Locomotion No. 1.'",
    "1829년": "Shekarar 1829",
    "유명한 기관차 로켓호로 레인힐 트라이얼에서 우승하여 증기 동력 철도의 실행 가능성을 입증했습니다.": "Ya lashe gasar Rainhill Trials da sanannen jirginsa na 'Rocket,' wanda ya tabbatar da aikin jiragen kasa masu amfani da tururi.",
    "1830년": "Shekarar 1830",
    "세계 최초의 도시간 여객 철도인 리버풀-맨체스터 철도의 개통을 감독했습니다.": "Ya kula da bude hanyar dogo tsakanin biranen Liverpool da Manchester, layin dogo na farko a duniya na fasinjoji a tsakanin birane biyu.",
    # Gregor Mendel
    "1822년": "Shekarar 1822",
    "오스트리아 제국의 하인첸도르프에서 농부의 아들로 태어났습니다.": "An haife shi ga wani manomi a Heinzendorf, wanda ke cikin Daular Ostiriya.",
    "1843년": "Shekarar 1843",
    "브르노의 아우구스티노회 성 토마스 수도원에 들어갔으며, 훗날 이곳에서 유명한 실험을 수행하게 됩니다.": "Ya shiga Majami'ar St. Thomas Abbey na Augustinian a Brno, inda daga baya zai gudanar da shahararrun gwaje-gwajensa.",
    "1856년": "Shekarar 1856",
    "수도원 정원에서 수천 그루의 완두콩을 교배하는 체계적인 다년 간의 실험을 시작했습니다.": "Ya fara wani gwaji na tsari wanda zai ɗauki shekaru da yawa, inda ya haɗa shuke-shuken wake dubbai a gonar majami'ar.",
    "1865년": "Shekarar 1865",
    "브르노 자연사 협회에 우성 및 열성 형질을 포함한 유전 법칙에 대한 연구 결과를 발표했습니다.": "Ya gabatar da sakamakon bincikensa game da dokokin gado, wadanda suka hada da sifofin karfi (dominant) da kuma marasa karfi (recessive), ga Ƙungiyar Tarihin Halitta ta Brno.",
    "1866년": "Shekarar 1866",
    "식물 잡종에 관한 실험 논문을 발표했지만, 그가 사망한 지 수십 년 후에 재발견될 때까지 크게 무시되었습니다.": "Ya buga takardarsa kan 'Experiments on Plant Hybridization,' wacce aka yi watsi da ita har sai bayan wasu shekaru da dama bayan mutuwarsa kafin a sake gano ta.",
    # Antoine Lavoisier
    "1743년": "Shekarar 1743",
    "파리에서 장앙투안 라부아지에와 에밀리 라부아지에의 첫째 아들로 태어났다.": "An haife shi a matsayin ɗa na fari ga Jean-Antoine Lavoisier da Émilie Lavoisier a birnin Paris.",
    "1761년": "Shekarar 1761",
    "콜레주 마자랭을 졸업했다.": "Ya kammala karatu daga Kwalejin Mazarin.",
    "1764년": "Shekarar 1764",
    "법학 학사 학위를 취득했다.": "Ya sami digiri a fannin shari'a.",
    "1768년": "Shekarar 1768",
    "프랑스 과학 아카데미의 회원이 되었고, 세금 징수 조합인 페름 제네랄의 일원이 되었다.": "Ya zama mamba a Cibiyar Kimiyya ta Faransa sannan ya zama mamba a kamfanin masu karbar haraji na Ferme générale.",
    "1770년": "Shekarar 1770",
    "물이 흙으로 변할 수 없다는 결론을 내놓은 논문을 발표하여 유명해졌다.": "Ya yi fice bayan buga wata kasida da ta nuna cewa ba za a iya mai da ruwa zuwa kasa ba.",
    "1771년": "Shekarar 1771",
    "마리안 피에레트 폴즈와 결혼했다.": "Ya auri Marie-Anne Pierrette Paulze.",
    "1774년": "Shekarar 1774",
    "《물리와 화학 소론》(Opuscules Physiques et chimiques)을 출판했다.": "Ya buga 'Opuscules Physiques et chimiques' (Gajerun Ayyukan Physics da Chemistry).",
    "1775년": "Shekarar 1775",
    "재정 총감 안 로베르 자크 튀르고에 의해 화약국장으로 임명되었다.": "Anne Robert Jacques Turgot, Controller-General na Kudi ne ya naɗa shi a matsayin Kwamishinan Gunpowder.",
    "1783년": "Shekarar 1783",
    "피에르 시몽 라플라스와 협조하여 수소를 연소시킬 경우 물이 생성된다는 것을 밝혔다.": "Ta hanyar aiki tare da Pierre-Simon Laplace, ya gano cewa ƙone sinadarin hydrogen yana haifar da ruwa.",
    "1785년": "Shekarar 1785",
    "프랑스 과학 아카데미의 이사가 되었다.": "Ya zama darakta a Cibiyar Kimiyya ta Faransa.",
    "1787년": "Shekarar 1787",
    "클로드 루이 베르톨레 등과 함께 화학적 명명법을 개정하여 Méthode de nomenclature chimique를 내놓았다.": "Tare da Claude Louis Berthollet da sauran su, ya sake sabunta sunayen sinadarai kuma ya buga 'Méthode de nomenclature chimique'.",
    "1789년": "Shekarar 1789",
    "《화학 원론》을 출판했다.": "Ya buga 'Traité Élémentaire de Chimie' (Kananan Ka'idojin Chemistry).",
    "1790년": "Shekarar 1790",
    "국회의 의뢰로 도량형 통일안 제작에 참여했다.": "Majalisar Dokoki ta ƙasa ta buƙace shi ya shiga cikin tsarin ƙirƙirar ma'aunin nauyi da ma'auni guda ɗaya.",
    "1793년": "Shekarar 1793",
    "프랑스 과학 아카데미를 비롯한 수많은 아카데미가 문을 닫았다.": "An rufe Cibiyar Kimiyya ta Faransa da sauran cibiyoyi da yawa.",
    "장인 자크 폴즈와 함께 감옥에 수감되었다.": "An daure shi tare da surukinsa, Jacques Paulze.",
    "1794년": "Shekarar 1794",
    "유죄 선고를 받고 혁명 광장의 단두대에서 참수되었다.": "An same shi da laifi kuma an fille masa kai a Place de la Révolution ta amfani da injin kisan kai (guillotine).",
    "1796년": "Shekarar 1796",
    "마리안 라부아지에가 공식적으로 라부아지에의 유품을 돌려받을 수 있었다.": "A hukumance an bar Marie-Anne Lavoisier ta karɓi kayan mijinta da aka kwace.",
    "화학 혁명 주도": "Jagorantar Juyin Juya Halin Kimiyyar Sinadarai (Chemistry)",
    "18세기 화학 혁명을 주도하며 화학사와 생물학사에 족적을 남겼다.": "Ya jagoranci juyin juya halin kimiyyar sinadarai a ƙarni na 18, wanda ya bar tarihi a cikin tsarin juyin halitta na chemistry da biology.",
    "플로지스톤설 폐기 및 연소 이론 확립": "Rushewar Tsarin Phlogiston Theory da Tabbatar da Ka'idar Konewa",
    "연소에 관한 새로운 이론을 주장하여 플로지스톤설을 폐기하고 산소의 작용을 규명하며 화학을 크게 발전시켰다.": "Ya gabatar da sabon ka'ida kan ƙonewa wanda ya musanta ka'idar phlogiston, ya nuna aikin oxygen a cikin abubuwa, kuma ya haɓaka kimiyyar chemistry da gaske.",
    "질량 보존의 법칙 확립": "Tabbatar da Dokar Kiyaye Matsayi (Law of Conservation of Mass)",
    "화학 반응에서 물질은 생성되거나 파괴되지 않고 단지 형태가 바뀔 뿐이라는 질량 보존의 법칙을 확립하였다.": "Ya kafa Dokar Kiyaye Matsayi, wacce ke nuna cewa a yayin wani canji na sinadarai (chemical reaction), ba a kirkirar abu ko kuma lalata shi, kawai yana canza yanayi ne.",
    "근대 화학 명명법 기초 마련": "Aza Harsashin Sunayen Sinadaran Chemistry Na Zamani",
    "원소와 화합물을 구분하고 체계적인 화학적 명명법 개혁을 주도하여 근대 화학의 기초를 마련하였다.": "Ya bambanta tsakanin abubuwa (elements) da hadadden abu (compounds), wanda ya jagoranci canjin sunayen sinadarai masu tsari, kuma ya kafa harsashin kimiyyar chemistry na zamani.",
    "정량적 방법 도입 및 원소 목록 작성": "Gabatar da Hanyoyin Lissafi da Rubuta Jerin Abubuwan Sinadarai (Elements)",
    "화학에 정량적인 방법을 처음으로 도입하고, 원소 목록을 최초로 광범위하게 작성하여 규소의 존재를 예측했다.": "Ya fara gabatar da hanyoyin ƙididdiga masu tsari a cikin kimiyyar chemistry, sannan ya shirya cikakken jerin abubuwan farko, yana mai hasashen samun kasancewar silicon.",
    "앙투안 라부아지에는 어떤 이유로 처형되었나요?": "Wane dalili ya sa aka yanke wa Antoine Lavoisier hukuncin kisa?",
    "프랑스 혁명 절정기에 조세 사기와 불량 담배 판매 혐의로 기소되었으며, 과학에 기여한 공로에도 불구하고 단두대에서 처형되었습니다.": "An zarge shi da zamba wajen biyan haraji da kuma sayar da gurbataccen taba a daidai lokacin Juyin Juya Halin Faransa yake tsanani, kuma an fille masa kai duk da irin gudummawar da ya bayar ga kimiyya.",
    "라부아지에의 가장 중요한 과학적 업적은 무엇인가요?": "Menene muhimmin nasarar kimiyya na Lavoisier?",
    "그는 플로지스톤설을 폐기하고 산소의 연소 및 호흡에서의 역할을 규명하여 화학 혁명을 주도했으며, 질량 보존의 법칙을 확립하고 근대 화학 명명법의 기초를 마련했습니다.": "Ya jagoranci juyin juya halin kimiyyar chemistry ta hanyar rushe tsarin phlogiston da gano muhimmancin iskar oxygen a cikin yanayin konewa da kuma shakar iska, inda ya tabbatar da Dokar kiyaye tsarin kwayar halitta kuma ya tsara tushen sunayen sinadaran chemistry na zamani.",
    "라부아지에의 아내 마리안 폴즈 라부아지에는 남편의 연구에 어떻게 기여했나요?": "Wace gudummawa matar Lavoisier, Marie-Anne Paulze Lavoisier ta bayar a binciken mijinta?",
    "마리안은 실험 조수로서 실험기구 묘사, 결과 기록, 영어 논문 번역 등을 도왔으며, 미터법 측정 시스템 개발에도 함께 참여했습니다.": "A matsayin mataimakiyar gwaji, Marie-Anne ta taimaka wajen zayyana kayan gwajin, yin rubutun bayanan sakamakon bincike, da fassarar rubuce-rubuce daga Ingilishi, sannan ta halarci tsarin gina ma'auni na (metric system)."
}

def translate_node(node):
    if isinstance(node, str):
        if node in translations:
            return translations[node]
        else:
            print(f"Warning: untranslated string '{node}'")
            return node
    elif isinstance(node, dict):
        return {k: translate_node(v) for k, v in node.items()}
    elif isinstance(node, list):
        return [translate_node(item) for item in node]
    else:
        return node

with open('c:\\Users\\natey\\Desktop\\wisdom-giants\\scratch\\ha_agent_8.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

translated_data = translate_node(data)

with open('c:\\Users\\natey\\Desktop\\wisdom-giants\\scratch\\ha_agent_8_out.json', 'w', encoding='utf-8') as f:
    json.dump(translated_data, f, ensure_ascii=False, indent=2)

print("Translation done.")
