import json
import os

in_path = r'c:\Users\natey\Desktop\wisdom-giants\scratch\ha_agent_6.json'
out_path = r'c:\Users\natey\Desktop\wisdom-giants\scratch\ha_agent_6_out.json'

with open(in_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

translations = {
    '1866년': 'Shekara ta 1866',
    '11월 12일 광둥성 샹산현에서 출생.': 'An haife shi a ranar 12 ga Nuwamba a yankin Xiangshan, lardin Guangdong.',
    '1894년': 'Shekara ta 1894',
    '청나라 타도를 위해 호놀룰루에서 흥중회를 조직함.': 'Ya kafa kungiyar Xingzhonghui a Honolulu domin hambarar da daular Qing.',
    '1911년': 'Shekara ta 1911',
    '우창 봉기가 성공하여 제국 청나라의 붕괴로 이어짐.': 'Tawayen Wuchang ya yi nasara wanda ya haifar da rushewar daular Qing ta sarakuna.',
    '1912년': 'Shekara ta 1912',
    '새로 선포된 중화민국의 초대 임시 대총통으로 잠시 재임함.': 'Ya yi aiki a taƙaice a matsayin shugaban wucin gadi na farko na Jamhuriyar Sin da aka kafa sabo.',
    '1925년': 'Shekara ta 1925',
    "미완의 '삼민주의'를 남기고 베이징에서 간암으로 사망함.": "Ya mutu sakamakon cutar sankarar hanta a Beijing, ya bar siyasarsa ta 'Ka'idojin Jama'a Uku' ba tare da an kammala ba.",

    '1543년': 'Shekara ta 1543',
    '미카와국에서 마쓰다이라 다케치요로 출생.': 'An haife shi a matsayin Matsudaira Takechiyo a lardin Mikawa.',
    '1560년': 'Shekara ta 1560',
    '오케하자마에서 이마가와 요시모토가 전사한 후 가문의 독립을 쟁취함.': "Ya sami 'yancin gidan bayan mutuwar Imagawa Yoshimoto a yakin Okehazama.",
    '1600년': 'Shekara ta 1600',
    '세키가하라 전투에서 동군을 승리로 이끌며 일본의 패권을 장악함.': 'Ya jagoranci rundunar Gabas zuwa nasara a yakin Sekigahara, inda ya kwace ikon Japan.',
    '1603년': 'Shekara ta 1603',
    '천황으로부터 쇼군으로 임명되어 공식적으로 도쿠가와 막부를 창건함.': 'Sarki ya nada shi Shogun, wanda ya kafa daular Tokugawa a hukumance.',
    '1615년': 'Shekara ta 1615',
    '오사카 전투에서 도요토미 가문을 멸망시키고 일본에 대한 절대적인 지배를 확정지음.': 'Ya lalata gidan Toyotomi a yakin Osaka kuma ya tabbatar da cikakken iko a kan Japan.',

    '1537': '1537',
    '오와리국 아이치군 나카무라에서 빈농 아들로 태어남 (덴분 6년 음력 2월 6일).': 'An haife shi a matsayin ɗan wani matalaucin manomi a Nakamura, gundumar Aichi, lardin Owari (Rana ta 6 ta watan 2 na shekara ta 6 ta zamanin Tenbun).',
    '1554': '1554',
    '오다 노부나가의 고모노로 일하기 시작함.': 'Ya fara aiki a matsayin bawan Oda Nobunaga.',
    '1561': '1561',
    '아사노 나가카쓰의 양녀 네네와 결혼함 (에이로쿠 4년).': "Ya auri Nene, 'yar riko ta Asano Nagakatsu (Shekara ta 4 ta Eiroku).",
    '1568': '1568',
    '오미 미쓰쿠리 성 공략에 활약했으며, 오다 노부나가가 아시카가 요시아키를 쇼군에 옹립하자 아케치 미쓰히데, 니와 나가히데와 함께 교토에서 정무를 봄 (에이로쿠 11년 음력 9월).': 'Ya taka rawar gani a harin da aka kai kan sansanin Omimitsukuri, kuma lokacin da Oda Nobunaga ya sanya Ashikaga Yoshiaki a matsayin shogun, ya tafiyar da lamuran siyasa a Kyoto tare da Akechi Mitsuhide da Niwa Nagahide (Watan 9 na shekara ta 11 ta Eiroku).',
    '1570': '1570',
    '에치젠국의 아사쿠라 요시카게 토벌에 종군하였고, 가나가사키에서 후위부대를 맡아 공을 세움 (겐키 원년).': 'Ya shiga yakin yaki da Asakura Yoshikage a lardin Echizen kuma ya nuna bajinta wajen jagorantar masu gadin baya a Kanegasaki (Shekarar farko ta Genki).',
    '1573': '1573',
    '아자이 가문 멸문 후 오미 3개군을 하사받아 나가하마성주로 부임했으며, 성을 하시바로 개명함 (덴쇼 원년).': 'Bayan halakar da gidan Azai, an ba shi yankuna uku a Omi, ya zama ubangijin gidan kurkukun Nagahama, kuma ya canza sunansa na karshe zuwa Hashiba (Shekarar farko ta Tensho).',
    '1576': '1576',
    '시바타 가쓰이에 구원 파견 중 무단 귀환했으며, 야마토국 마쓰나가 히사히데를 토벌함 (시기 산성 전투) (덴쇼 4년).': 'Ya dawo ba tare da izini ba yayin da aka tura shi domin taimakon Shibata Katsuie, kuma ya ci Matsunaga Hisahide na lardin Yamato (Yakin Shigisan) (Shekara ta 4 ta Tensho).',
    '1579': '1579',
    '비젠국, 미마사카국 다이묘 우키타 나오이에를 복속시킴 (덴쇼 7년).': 'Ya karkashin daimyo Ukita Naoie na lardin Bizen da Mimasaka (Shekara ta 7 ta Tensho).',
    '1580': '1580',
    '하리마 미키 성 성주 벳쇼 나가하루를 공격하여 항복받음 (미키 전투). 다지마국 야마나 아키히로의 아리코 산성을 공략함 (덴쇼 8년).': 'Ya kai hari ya kuma sa Bessho Nagaharu, shugaban sansanin Miki a lardin Harima, ya mika wuya (Yakin Miki). Ya kai hari a sansanin Arikoyama na Yamana Akihiro a lardin Tajima (Shekara ta 8 ta Tensho).',
    '1581': '1581',
    '돗토리 성을 함락함 (돗토리 성 전투). 이와야 성을 공략해 아와지국을 세력하에 둠 (덴쇼 9년).': 'Ya kama sansanin Tottori (Yakin Tottori). Ya kai hari a sansanin Iwaya kuma ya kawo lardin Awaji karkashin ikonsa (Shekara ta 9 ta Tensho).',
    '1582': '1582',
    '빗추 다카마쓰 성 수공 공략 중 오다 노부나가에게 원군을 요청함 (덴쇼 10년).': 'Ya nemi karin karfi daga Oda Nobunaga a lokacin harin ruwa kan sansanin Takamatsu a Bitchu (Shekara ta 10 ta Tensho).',
    '주군 오다 노부나가가 혼노지의 변으로 자결했다는 소식을 접함 (덴쇼 10년 음력 6월 2일).': 'Ya sami labarin cewa ubangidansa Oda Nobunaga ya kashe kansa a yakin Honno-ji (Rana ta 2 ta watan 6 na shekara ta 10 ta Tensho).',
    '야마자키 전투에서 아케치 미쓰히데를 격파함 (덴쇼 10년 음력 6월 13일).': 'Ya doke Akechi Mitsuhide a yakin Yamazaki (Rana ta 13 ta watan 6 na shekara ta 10 ta Tensho).',
    '기요스 회의에서 오다 노부나가의 후계자로 적손 산보시가 결정됨 (덴쇼 10년 음력 6월 27일).': 'A taron Kiyosu, an yanke shawarar zaben jikan Oda Nobunaga, Sanboushi, a matsayin magajinsa (Rana ta 27 ta watan 6 na shekara ta 10 ta Tensho).',
    '양자 하시바 히데카쓰를 상주로 오다 노부나가의 장례를 치름 (덴쇼 10년 음력 10월 15일).': "Ya gudanar da jana'izar Oda Nobunaga tare da dan rikonsa Hashiba Hidekatsu a matsayin babban mai zaman juyayi (Rana ta 15 ta watan 10 na shekara ta 10 ta Tensho).",
    '1583': '1583',
    '시바타 가쓰이에와의 대립이 격화되어 나가하마 성을 포위하고, 가지키 성을 함락시켰으며, 오다 노부타카로부터 산보시를 넘겨받음 (덴쇼 11년).': 'Rigimarsa da Shibata Katsuie ta kara kamari, ya kewaye sansanin Nagahama, ya kama sansanin Kameyama, kuma ya karbi Sanboushi daga Oda Nobutaka (Shekara ta 11 ta Tensho).',
    '시즈가타케 전투에서 시바타 가쓰이에를 격파함 (덴쇼 11년 음력 4월 21일).': 'Ya doke Shibata Katsuie a yakin Shizugatake (Rana ta 21 ta watan 4 na shekara ta 11 ta Tensho).',
    '이시야마 혼간지 터에 오사카성을 축조하기 시작함 (덴쇼 11년).': 'Ya fara gina gidan sarautar Osaka a filin Ishiyama Hongan-ji (Shekara ta 11 ta Tensho).',
    '1584': '1584',
    '오다 노부카쓰와 대립했으며, 도쿠가와 이에야스가 노부카쓰에 가담함 (고마키·나가쿠테 전투) (덴쇼 12년).': 'Ya yi rigima da Oda Nobukatsu, wanda Tokugawa Ieyasu ya mara wa baya (Yakin Komaki da Nagakute) (Shekara ta 12 ta Tensho).',
    '나가쿠테 전투에서 이케다 쓰네오키, 모토스케 부자와 모리 나가요시 등이 전사함 (덴쇼 12년 음력 4월 9일).': 'Uba da dan Ikeda Tsuneoki da Motosuke, da Mori Nagayoshi an kashe su a yakin Nagakute (Rana ta 9 ta watan 4 na shekara ta 12 ta Tensho).',
    '오다 노부카쓰와 강화 맺음 (덴쇼 12년 음력 11월 11일).': 'Ya kulla yarjejeniyar zaman lafiya da Oda Nobukatsu (Rana ta 11 ta watan 11 na shekara ta 12 ta Tensho).',
    '1585': '1585',
    '정2위 내대신에 위계 임관됨 (덴쇼 13년 음력 3월 10일).': 'An nada shi a matsayin Ministan Cikin Gida na matsayin koli na biyu (Rana ta 10 ta watan 3 na shekara ta 13 ta Tensho).',
    '기슈 정벌을 단행함 (덴쇼 13년 음력 3월 21일).': 'Ya kaddamar da yakin neman zabe a Kishu (Rana ta 21 ta watan 3 na shekara ta 13 ta Tensho).',
    '시코쿠 정벌을 단행함 (덴쇼 13년 음력 7월 25일).': 'Ya kaddamar da yakin Shikoku (Rana ta 25 ta watan 7 na shekara ta 13 ta Tensho).',
    '관백직에 오름 (덴쇼 13년 음력 7월 11일).': 'An nada shi matsayin Kampaku (Rana ta 11 ta watan 7 na shekara ta 13 ta Tensho).',
    '엣추의 삿사 나리마사가 히데요시에 항복함 (덴쇼 13년 음력 8월 25일).': 'Sassa Narimasa na Etchu ya mika wuya ga Hideyoshi (Rana ta 25 ta watan 8 na shekara ta 13 ta Tensho).',
    '1586': '1586',
    '여동생 아사히를 강제로 이혼시킨 뒤 이에야스에 시집 보냈으며, 어머니 오만도코로를 인질로 이에야스에게 보냄 (덴쇼 14년).': 'Ya tilastawa kanwarsa Asahi raba aure, ya aurar da ita ga Ieyasu, kuma ya tura mahaifiyarsa Omandokoro a matsayin garkuwa zuwa ga Ieyasu (Shekara ta 14 ta Tensho).',
    '조정으로부터 도요토미 성을 하사받음 (덴쇼 14년 음력 9월 9일).': 'Kotun sarki ta ba shi sunan gidan Toyotomi (Rana ta 9 ta watan 9 na shekara ta 14 ta Tensho).',
    '태정대신에 올라 정권을 확립함 (덴쇼 14년 음력 12월 25일).': 'Ya karfafa ikonsa ta hanyar zama Daijo-daijin (Rana ta 25 ta watan 12 na shekara ta 14 ta Tensho).',
    '분고 헤쓰기 강에서 시마즈 이에히사가 이끄는 시마즈 군과 싸워 패배함 (헤쓰기가와 전투) (덴쇼 14년).': 'Ya sha kashi a hannun sojojin Shimazu karkashin jagorancin Shimazu Iehisa a kogin Hetsugi a Bungo (Yakin Hetsugigawa) (Shekara ta 14 ta Tensho).',
    '1587': '1587',
    '20만 대군을 이끌고 규슈를 공략하여 시마즈 가문이 항복함 (규슈 정벌) (덴쇼 15년).': 'Ya jagoranci sojoji 200,000 don mamaye Kyushu, lamarin da ya sa gidan Shimazu mika wuya (Yakin Kyushu) (Shekara ta 15 ta Tensho).',
    '바테렌 추방령을 내림 (덴쇼 15년 6월).': 'Ya ba da umarnin korar Bateren (kiristoci) (Watan 6 na shekara ta 15 ta Tensho).',
    '1588': '1588',
    '가타나가리를 실시함 (덴쇼 16년).': 'Ya aiwatar da dokar farautar takuba ta Katanagari (Shekara ta 16 ta Tensho).',
    '1589': '1589',
    '측실 요도도노 사이에서 쓰루마쓰가 태어나 후계자로 지명함 (덴쇼 17년).': 'An haifi dansa Tsurumatsu daga matarsa Yododono kuma ya nada shi magaji (Shekara ta 17 ta Tensho).',
    '1590': '1590',
    '고호조 가문을 제압하기 위해 21만 대군을 이끌고 간토로 출병, 오다와라성을 포위함 (오다와라 정벌) (덴쇼 18년).': 'Ya tura sojoji 210,000 zuwa Kanto don kayar da gidan Hojo, ya kewaye gidan sarautar Odawara (Yakin Odawara) (Shekara ta 18 ta Tensho).',
    '1591': '1591',
    '후계자로 지명했던 쓰루마쓰가 병사하자, 조카 히데쓰구를 양자로 맞이해 관백직을 양도했으며, 자신은 태합으로 불림 (덴쇼 19년).': 'Lokacin da magajinsa Tsurumatsu ya mutu sakamakon rashin lafiya, ya karbi wansa Hidetsugu a matsayin dan riko kuma ya ba shi matsayin Kampaku, inda ya dauki lakabin Taiko ga kansa (Shekara ta 19 ta Tensho).',
    '다도인 센노 리큐에 할복을 명함 (덴쇼 19년).': 'Ya umurci masanin shan shayi Sen no Rikyu da ya yi seppuku (kashe kansa) (Shekara ta 19 ta Tensho).',
    '도호쿠 지방의 구노헤 마사자네가 일으킨 난을 진압함 (덴쇼 19년).': 'Ya murkushe tawayen da Kunohe Masazane ya tayar a yankin Tohoku (Shekara ta 19 ta Tensho).',
    '1592': '1592',
    '임진왜란이 시작됨 (분로쿠 원년).': 'An fara yakin mamayewar Japan a kan Koriya (Shekarar farko ta Bunroku).',
    '1593': '1593',
    '명과의 강화 교섭이 시작됨. 측실 요도도노가 히데요리를 낳음 (분로쿠 2년).': 'An fara tattaunawar zaman lafiya da daular Ming. Matarsa Yododono ta haifi Hideyori (Shekara ta 2 ta Bunroku).',
    '1595': '1595',
    '관백 도요토미 히데쓰구를 폐적시키고 고야산으로 추방했으며, 후에 모반 혐의로 할복시킴 (분로쿠 4년).': 'Ya cire Kampaku Toyotomi Hidetsugu, ya kore shi zuwa Dutsen Koya, sannan daga baya ya sa shi yin seppuku saboda zargin cin amana (Shekara ta 4 ta Bunroku).',
    '1596': '1596',
    '명과의 강화 교섭이 결렬됨 (분로쿠 5년).': 'Tattaunawar zaman lafiya da Ming ta ruguje (Shekara ta 5 ta Bunroku).',
    '1597': '1597',
    '14만 군으로 조선을 재침략함 (정유재란) (게이초 2년).': 'Ya sake kai hari kan Koriya da sojoji 140,000 (Mamayewar Japan na biyu akan Koriya) (Shekara ta 2 ta Keicho).',
    '1598': '1598',
    '후시미성에서 사망함 (게이초 3년 음력 8월 18일).': 'Ya mutu a gidan sarautar Fushimi (Rana ta 18 ta watan 8 na shekara ta 3 ta Keicho).',

    '전국 3영걸': 'Manyan Jarumai 3 na Sengoku',
    '오다 노부나가, 도쿠가와 이에야스와 함께 전국 3영걸로 불린다.': 'Ana kiran sa ɗaya daga cikin manyan jarumai guda uku na zamanin Sengoku, tare da Oda Nobunaga da Tokugawa Ieyasu.',
    '오다 노부나가 사업 계승': 'Magajin Ayyukan Oda Nobunaga',
    '혼노지의 변 후 아케치 미쓰히데를 격파하고 오다 노부나가의 사업을 계승하였다.': 'Bayan rikicin Honno-ji, ya kayar da Akechi Mitsuhide kuma ya gaji ayyukan Oda Nobunaga.',
    '일본 통일': 'Hada Kan Japan',
    '고호조 가문을 굴복시켜 일본을 통일하고 오랫동안 계속된 전국시대를 마감시켰다.': 'Ya tilasta wa gidan Hojo mika wuya don hada kan Japan sannan kuma ya kawo karshen yakin Sengoku wanda ya dauki lokaci mai tsawo ana yi.',
    '관백 및 태정대신 임명': 'Nadi a Matsayin Kampaku da Daijo-daijin',
    '관백과 태정대신에 임명되어 정권을 확립하고 조정으로부터 도요토미 성을 하사받았다.': 'An nada shi a matsayin Kampaku (Mai bawa sarki shawara) da Daijo-daijin (Babban Minista), ya kafa iko sannan kotun sarki ta ba shi sunan Toyotomi.',
    '태합검지 및 가타나가리': 'Taiko Kenchi da Katanagari',
    '태합검지와 가타나가리 정책을 펴 일본 국내를 안정시켰다.': 'Ya aiwatar da tsare-tsaren Taiko Kenchi (kimanta filaye) da Katanagari (ƙwace takuba) don tabbatar da kwanciyar hankali a cikin kasar Japan.',
    '최하층 신분에서 지배자 등극': 'Hawa Karagar Mulki Daga Karamin Matsayi',
    '일본에서 가장 낮은 신분이었던 자가 일본의 지배자로 등극했다.': 'Mutumin da ke da matsayi mafi kaskanci a kasar Japan ya zama babban mai mulkin kasar.',
    '오사카성 축조': 'Ginin Gidan Sarautar Osaka',
    '이시야마 혼간지 터에 오사카성을 축조하였다.': 'Ya gina Gidan Sarautar Osaka a kan filin da Ishiyama Hongan-ji ya kasance.',
    '임진왜란 주도': 'Jagorancin Mamaye Koriya',
    '분로쿠 원년(1592년) 임진왜란을 주도하여 조선을 침략한 장본인이다.': 'Shi ne babban mutumin da ya jagoranci farmakin da aka kai wa Koriya a shekarar farko ta Bunroku (1592).',
    '도요토미 히데요시의 출신은 어떠했나요?': 'Yaya asalin Toyotomi Hideyoshi yake?',
    '오와리국 아이치군 나카무라에서 빈농의 아들로 태어났다고 알려져 있으며, 매우 낮은 신분이었기 때문에 천출임을 의식하여 당대나 후대에 기록이 왜곡되거나 미화된 경우가 많다는 의심을 받습니다.': 'An ce an haife shi ne a matsayin ɗan wani matalaucin manomi a Nakamura, gundumar Aichi, lardin Owari. Saboda kaskancin matsayinsa, ana zargin cewa rubuce-rubucen tarihi game da asalin nasa an gurbata su ko kuma an kawata su a zamanin nasa da kuma na baya saboda jin kunyar kaskancinsa.',
    '도요토미 히데요시가 쇼군이 되지 못한 이유는 무엇인가요?': 'Me ya sa Toyotomi Hideyoshi bai zama Shogun ba?',
    "평민 출신으로 겐지 혈통이 아니었기 때문에 '쇼군은 반드시 겐지(源氏)만이 될 수 있다'는 규정으로 인해 쇼군이 될 수 없었습니다. 대신 관백과 태정대신에 올랐습니다.": "Domin kuwa an haife shi daga gidan talakawa, ba daga tsatson jinin Minamoto (Genji) ba ne, bai samu damar zama Shogun ba saboda ka'idar cewa 'Genji ne kawai ka iya zama Shogun'. A maimakon haka, ya hau matsayin Kampaku da Daijo-daijin.",
    '도요토미 히데요시가 임진왜란을 일으킨 주요 원인은 무엇인가요?': 'Menene babban dalilin da ya sa Toyotomi Hideyoshi ya kaddamar da yakin mamaye Koriya?',
    '일반적인 분석으로는 쇼군이 될 명분을 얻기 위해 과거 영토라고 주장하는 조선 남부를 회복하고 명나라 군대를 섬멸하려 했으며, 새로운 영지를 무사들에게 하사하여 불안했던 가신 관계를 굳건히 만들고자 했다는 설이 있습니다.': "Gabaɗaya ana fassara cewa ya nemi ne ya kwato yankin kudancin Koriya, wanda yake ikirarin cewa yankin su ne a da, kuma ya fatattaki sojojin daular Ming don samun dalilin da zai sa ya zama Shogun. Kuma ya yi hakan ne don ya kyautata dangantakar da ke tsakanin su ta hanyar ba da sabbin filaye ga mayakansa masu biyayya don ƙarfafa su.",
    '도요토미 히데요시의 신체적 특징은 무엇이었나요?': 'Mene ne yanayin jikin Toyotomi Hideyoshi?',
    "모습이 원숭이를 닮아 '작은 원숭이'로 불렸고, 키가 작고 추한 얼굴이었으며, 오른손 손가락이 6개인 다지증이었다는 선교사 루이스 프로이스의 기록이 있습니다.": "An kira shi 'Karamin Biri' saboda kamaninsa da biri, gajere ne kuma mai mummuna fuska. Fasto Luís Fróis ya rubuta cewa yana da yatsun hannu 6 a hannunsa na dama (polydactyly).",
    '도요토미 히데요시의 죽음은 어떻게 처리되었나요?': 'Yaya aka tafiyar da labarin mutuwar Toyotomi Hideyoshi?',
    '게이초 3년(1598년) 후시미성에서 사망했으며, 병력의 사기 문제로 인해 장례는 치러지지 않고 그의 죽음은 비밀로 부쳐졌습니다. 그의 무덤은 세키가하라 전투 이후 폭파되어 소멸되었습니다.': "Ya mutu a gidan sarautar Fushimi a shekara ta 3 ta Keicho (1598). Saboda gudun kar kwarin gwiwar sojojinsa ya fadi, ba a gudanar da jana'iza ba, an rufa asirin mutuwarsa. Kabarinsa ya lalace ta hanyar fashewa bayan yakin Sekigahara.",

    '1853년': 'Shekara ta 1853',
    '시암의 몽꿋 왕의 아들인 쭐랄롱꼰 왕자로 출생.': 'An haife shi a matsayin Yarima Chulalongkorn, ɗan Sarki Mongkut na ƙasar Siam.',
    '1868년': 'Shekara ta 1868',
    '아버지의 서거 이후 15세의 나이로 라마 5세로서 왕위에 오름.': 'Bayan mutuwar mahaifinsa, ya hau karagar mulki yana da shekaru 15 a matsayin Sarki Rama V.',
    '1874년': 'Shekara ta 1874',
    '시암에서 노예제와 부역 제도의 점진적인 폐지를 시작함.': 'Ya kaddamar da tsarin dakatar da bauta da aikin karfi a hankali a Siam.',
    '1893년': 'Shekara ta 1893',
    '위험했던 프랑스-시암 전쟁을 겪으며 시암의 독립을 보존하기 위해 영토를 양보함.': 'Bayan Yakin Faransa da Siam mai hatsari, ya sallama wasu yankuna domin kiyaye yancin kai na Siam.',
    '1910년': 'Shekara ta 1910',
    '10월 23일에 서거하였으며, 시암을 식민지화에서 지켜낸 위대한 근대화 군주로 기억됨.': 'Ya mutu a ranar 23 ga watan Oktoba, kuma ana tuna da shi a matsayin babban sarkin da ya kawo ci gaba kuma ya kiyaye Siam daga mulkin mallaka.',

    '기원전 247년': 'Karni na 247 K.Z.',
    '카르타고(현 튀니지)의 저명한 군사 가문에서 태어남.': 'An haife shi a wani fitaccen gidan sojoji a Carthage (Tunisia ta yau).',
    '기원전 218년': 'Karni na 218 K.Z.',
    '제2차 포에니 전쟁을 촉발하고 전투 코끼리를 이끌고 알프스를 넘어 이탈리아를 침공함.': 'Ya kunna Yakin Punic na Biyu kuma ya mamaye kasar Italiya ta hanyar tsallaka tsaunin Alps da giwayen yaki.',
    '기원전 216년': 'Karni na 216 K.Z.',
    '칸나에 전투에서 로마를 상대로 역사상 가장 위대한 전술적 승리 중 하나를 거둠.': 'Ya sami ɗaya daga cikin manyan nasarorin fasahar yaƙi a tarihi a kanta Roma a Yaƙin Cannae.',
    '기원전 202년': 'Karni na 202 K.Z.',
    '결정적인 자마 전투에서 로마 장군 스키피오 아프리카누스에게 패배함.': 'Ya sha kashi a hannun Janar na Roma Scipio Africanus a gagarumin Yakin Zama.',
    '기원전 183년경': 'Wajen Karni na 183 K.Z.',
    '로마로 체포되어 인도되는 것을 피하기 위해 비티니아에서 독약으로 자결함.': 'Ya kashe kansa da guba a Bithynia domin kaucewa a kama shi a mika shi ga Roma.',

    '1304년 2월 24일': '24 ga Fabrairu, 1304',
    '모로코 탕헤르의 울라마(법학자) 집안에서 태어났습니다.': 'An haife shi a gidan Malaman Addini (Ulama) a birnin Tangier, na ƙasar Maroko.',
    '1325년 6월': 'Yuni 1325',
    '21세의 나이로 고향을 떠나 메카를 순례하는 하즈 길에 올랐습니다.': 'Yana da shekaru 21, ya bar garinsu domin yin aikin Hajji a ƙasar Makka.',
    '1326년 이른 봄': 'Farkon bazara ta shekarar 1326',
    '알렉산드리아에 도착했습니다.': 'Ya isa birnin Alexandria.',
    '1326년 11월 17일': '17 ga Nuwamba, 1326',
    '메카에서 한 달을 지낸 후 이라크로 귀환하는 대상단에 합류했습니다.': 'Bayan ya shafe wata guda a Makka, ya bi sahun ayarin da ke komawa kasar Iraqi.',
    '1327년 6월': 'Yuni 1327',
    '바그다드에 도착했습니다.': 'Ya isa birnin Baghdad.',
    '1327년 7월 무렵': 'Wajen Yuli 1327',
    '바그다드를 떠나 티그리스강을 끼고 북쪽으로 향했습니다.': 'Ya bar Baghdad ya nufi arewa ta gabar kogin Tigris.',
    '1329년 또는 1331년 즈음': 'Wajen shekara ta 1329 ko 1331',
    '아덴에 도착했습니다.': 'Ya isa birnin Aden.',
    '1330년': 'Shekara ta 1330',
    '킬와의 술탄 알 하산 이븐 술레이만을 방문했습니다.': 'Ya ziyarci Sultan na Kilwa, Al-Hasan ibn Sulaiman.',
    '1331년': 'Shekara ta 1331',
    '모가디슈를 방문했습니다.': 'Ya ziyarci birnin Mogadishu.',
    '1330년 또는 1332년': 'Shekara ta 1330 ko 1332',
    '델리 술탄 왕조의 국왕 무함마드 빈 투그루크의 궁전에서 일자리를 찾아보기로 하고 아나톨리아를 출발하여 델리로 향하는 대상단에 합류했습니다.': 'Ya yanke shawarar neman aiki a fadar Sarkin Delhi Muhammad bin Tughluq, inda ya tashi daga Anatolia ya koma cikin ayarin dake tafiya zuwa Delhi.',
    '1332년 또는 1334년': 'Shekara ta 1332 ko 1334',
    '콘스탄티노폴리스에 도착하여 안드로니코스 3세 팔라이오로고스를 알현했습니다.': 'Ya isa Constantinople inda ya gana da Andronikos III Palaiologos.',
    '1345년': 'Shekara ta 1345',
    '수마트라섬 북부 아체 지방에 있던 사무데라 파사이 술탄국에 도착했습니다.': 'Ya isa masarautar Samudera Pasai dake yankin Aceh a arewacin tsibirin Sumatra.',
    '1346년': 'Shekara ta 1346',
    '광저우를 떠나 귀향길에 올랐습니다.': 'Ya bar Guangzhou ya fara tafiyarsa na komawa gida.',
    '1348년': 'Shekara ta 1348',
    '다마스커스에 도착하여 아버지가 15년 전에 사망했다는 소식을 들었습니다.': 'Ya isa Damascus inda ya sami labarin cewa mahaifinsa ya mutu shekaru 15 da suka gabata.',
    '1350년': 'Shekara ta 1350',
    '카스티야의 알폰소 11세가 탕헤르 지역을 공격하자 다른 무슬림들과 함께 항구를 지키기 위해 결집했습니다.': 'Lokacin da Alfonso na 11 na Castile ya farma yankin Tangier, ya hada kai da sauran Musulmai don kare tashar jiragen ruwa.',
    '1351년 가을': 'Lokacin kaka na shekarar 1351',
    '페스를 떠나 시질마사로 향했습니다.': 'Ya bar Fez ya nufi Sijilmasa.',
    '1352년 2월': 'Fabrairu 1352',
    '대상 대열과 함께 타가자에 도착했습니다.': 'Ya isa Taghaza tare da ayarin fatake.',
    '1353년 2월': 'Fabrairu 1353',
    '말리를 떠나는 대상단에 합류하여 팀북투로 향했습니다.': 'Ya koma cikin ayarin da ya bar Mali ya nufi Timbuktu.',
    '1353년 9월': 'Satumba 1353',
    '시질마사로 귀환했습니다.': 'Ya koma Sijilmasa.',
    '1354년 초': 'Farkon shekarar 1354',
    '모로코로 돌아갔습니다.': 'Ya koma Maroko.',
    '1354년': 'Shekara ta 1354',
    '술탄의 명에 따라 이븐 주자이에게 자신의 여행담을 구술하였고, 이븐 주자이가 이를 정리하여 《이븐 바투타 여행기》를 집필했습니다.': "Bisa umarnin Sarki, ya ba Ibn Juzayy labarin tafiye-tafiyensa, wanda Ibn Juzayy ya tattara ya rubuta a matsayin 'Rihla na Ibn Battuta'.",
    '1368년 또는 1369년': 'Shekara ta 1368 ko 1369',
    '사망했습니다.': 'Ya riga mu gidan gaskiya.',
    '유명한 여행기(리흘라) 저술': 'Rubuta Fitaccen Littafin Tafiye-Tafiye (Rihla)',
    "중세 이슬람 세계와 그 너머의 광범위한 지역을 기록한 유명한 여행기 '리흘라'를 저술했습니다.": "Ya rubuta sanannen littafin tafiye-tafiye 'Rihla' da ke rubuta tarihin duniyar Musulunci a tsakiyar karnoni da kuma fadi da dama fiye da hakan.",
    '광범위한 여행': 'Tafiye-Tafiye masu Faɗi',
    '당대 이슬람 국가, 중국, 수마트라 등 12만km에 달하는 광범위한 지역을 여행하며 문화 인류학적 가치가 큰 기록을 남겼습니다.': "Ya yi balaguro mai nisan kilomita 120,000 wanda ya hada da kasashen Musulmi na wancan lokacin, da kuma ƙasar Sin, da tsibirin Sumatra, inda ya bar muhimman bayanai akan al'adu da dabi'u.",
    '델리 술탄 왕조의 판관 임명': 'Naɗi a Matsayin Alƙali a Daular Delhi',
    '델리 술탄 왕조의 술탄 무함마드 빈 투그루크에 의해 판관(카디)으로 임명되어 활동했습니다.': 'Sarkin Delhi, Muhammad bin Tughluq, ya nada shi a matsayin alkali (Qadi) sannan kuma ya yi aiki a wurin.',
    '이븐 바투타는 언제 어디서 태어났나요?': 'Yaushe kuma a ina aka haifi Ibn Battuta?',
    '이븐 바투타는 1304년 2월 24일 모로코 탕헤르의 울라마(법학자) 집안에서 태어났습니다.': 'An haifi Ibn Battuta a ranar 24 ga Fabrairu, 1304, a gidan Malaman Addini (Ulama) a garin Tangier, dake kasar Maroko.',
    '이븐 바투타의 여행기는 어떤 가치를 가지고 있나요?': 'Wane kima littafin tafiye-tafiyen Ibn Battuta yake da shi?',
    '그의 여행기는 당대 거의 대부분 이슬람 국가와 중국, 수마트라에 이르기까지 12만km에 달하는 광범위한 여정을 묘사한 것으로 문화 인류학적 가치가 큽니다.': "Littafinsa na tafiye-tafiye ya ba da labarin tafiye-tafiye da ya kai kimanin kilomita 120,000 wanda ya hada da kusan duk kasashen Musulunci na wancan lokaci, kasar Sin, da Sumatra, kuma yana da babbar kima wajen nazarin al'adun dan adam.",
    '이븐 바투타는 어떤 직업을 가졌었나요?': 'Wane aiki ne Ibn Battuta ya yi?',
    '그는 여행가, 탐험가이자 유명한 여행기(리흘라)의 저자이며, 델리 술탄 왕조에서는 판관(카디)으로 임명되어 활동했고, 말년에는 모로코의 법관으로 생활했습니다.': 'Matafiyi ne, mai bincike, kuma marubucin fitaccen littafin tafiye-tafiye (Rihla). An nada shi a matsayin alkali (Qadi) a zamanin Daular Delhi, kuma ya shafe karshen rayuwarsa a matsayin alkali a Maroko.',
    '이븐 바투타의 여행기는 누가 집필했나요?': 'Wane ne ya rubuta littafin tafiye-tafiyen Ibn Battuta?',
    '이븐 바투타가 술탄의 명에 따라 이븐 주자이에게 자신의 여행담을 구술하였고, 이븐 주자이가 이를 정리하여 《이븐 바투타 여행기》를 집필했습니다.': "Ibn Battuta ya gaya wa Ibn Juzayy labarin tafiye-tafiyensa bisa umarnin Sarki, sai Ibn Juzayy ya tattara su ya rubuta a matsayin littafin 'Rihla na Ibn Battuta'.",

    '1122년경': 'Wajen shekarar 1122',
    '크메르 제국의 왕족 가문에서 태어남.': 'An haife shi a gidan sarautar daular Khmer.',
    '1177년': 'Shekara ta 1177',
    '이웃 참파 왕국에 의해 크메르의 수도 앙코르가 파괴되는 것을 목격함.': 'Ya shaida yadda masarautar Champa makwabciyarsu ta lalata Angkor, babban birnin Khmer.',
    '1181년': 'Shekara ta 1181',
    '참파 침략자들을 성공적으로 몰아내고 크메르 제국의 왕으로 즉위함.': 'Ya yi nasarar fatattakar masu mamaye Champa kuma aka nada shi a matsayin sarkin daular Khmer.',
    '1186년': 'Shekara ta 1186',
    '어머니를 기리기 위해 타 프롬 사원의 건설을 지시함.': 'Ya ba da umarnin gina gidan ibada na Ta Prohm don karrama mahaifiyarsa.',
    '1218년경': 'Wajen shekarar 1218',
    '앙코르 톰과 바욘 사원을 비롯한 대규모 건축 프로젝트를 완성한 후 사망함.': 'Ya rasu bayan ya kammala manyan gine-gine kamar Angkor Thom da kuma gidan ibada na Bayon.',

    '780년': 'Shekara ta 780',
    '바그다드에서 출생 (추정)': 'An haife shi a Baghdad (Kiyasi)',
    '825년': 'Shekara ta 825',
    "저서 '인도 수학에 의한 계산법' 저술": "Ya rubuta littafin 'Lissafi da Lambobin Indiya'",
    '830년': 'Shekara ta 830',
    "대표 저서 'al-Kitab al-mukhtasar fi hisab al-jabr wa'l-muqabala' (복원과 대비의 계산) 저술": "Ya rubuta sanannen littafinsa 'al-Kitab al-mukhtasar fi hisab al-jabr wa'l-muqabala' (Takaitaccen Littafi kan Lissafi ta Hanyar Kammalawa da Daidaitawa)",
    '850년': 'Shekara ta 850',
    '사망 (추정)': 'Mutuwa (Kiyasi)',
    '12세기': 'Karni na 12',
    '산술에 관한 저서가 라틴어로 번역됨': 'An fassara littafinsa kan lissafi zuwa harshen Latin',
    '그의 업적이 라틴어 번역을 통해 유럽으로 전파됨': 'Ayyukansa sun watsu zuwa Turai ta hanyar fassarar Latin',
    '12세기 중반': 'Tsakiyar karni na 12',
    "저서 '복원과 대비의 계산'이 라틴어로 번역됨": "An fassara littafinsa na 'Lissafi ta Hanyar Kammalawa da Daidaitawa' zuwa Latin",
    "대수학 저서 '복원과 대비의 계산'": "Littafin Aljebra 'Lissafi ta Hanyar Kammalawa da Daidaitawa'",
    '일차방정식과 이차방정식의 일반적인 해법을 소개하여 현대 대수학의 시초로 여겨지는 책을 저술했습니다.': 'Ya rubuta littafin da aka dauka a matsayin farkon lissafin Aljebra na zamani, inda ya gabatar da hanyoyin magance daidaito na digiri na daya da na biyu (linear da quadratic equations).',
    "산술 저서 '인도 수학에 의한 계산법'": "Littafin Lissafi 'Lissafi da Lambobin Indiya'",
    '인도-아라비아 숫자와 계산법을 서양에 전파하는 데 주요한 역할을 한 책을 저술했습니다.': 'Ya rubuta littafin da ya taka muhimmiyar rawa wajen gabatar da lambobin Indiya-Larabawa da hanyoyin lissafi zuwa kasashen yamma.',
    "천문표 '신드와 힌드에 기반한 천문표'": "Jadawalin Ilimin Taurari 'Zij al-Sindhind'",
    '달력과 천문학적 계산, 사인과 코사인 삼각 함수 표를 포함한 천문표를 만들었습니다.': 'Ya yi jadawalin lissafin taurari wanda ya ƙunshi kalanda, lissafin ilimin taurari, da kuma jadawalin lissafin sine da cosine a fannin ilimin lissafin triangles.',
    "지리학 저서 '지구의 표면'": "Littafin Ilimin Kasa 'Siffar Duniya'",
    '프톨레마이오스의 지리학을 수정하고 2402개 도시의 좌표 및 지리적 특징을 포함한 책을 저술했습니다.': 'Ya gyara ilimin yanayin kasa na Ptolemy sannan ya rubuta littafi wanda ya hada da inda garuruwa 2,402 suke, tare da siffofin kasa.',
    '기계 장치 연구': 'Nazarin Injinan Aiki',
    '아스트롤라베와 해시계 같은 기계적인 장치에 대해 연구했습니다.': "Ya yi nazari kan injinan aiki kamar astrolabe (na'urar duba taurari) da na'urar gane lokaci ta rana (sundial).",
    '지도 제작 및 지구 둘레 측정 프로젝트 참여': 'Kasancewa cikin Aikin Zana Taswira da Auna fadin Duniya',
    '칼리프 알마문을 위한 지도 제작을 돕고 지구의 둘레를 재는 프로젝트에 참여했습니다.': "Ya taimaka wajen yin taswira ga Khalifa Al-Ma'mun sannan ya kasance a cikin aikin auna kewayen duniya.",
    '알콰리즈미는 어떤 인물로 알려져 있나요?': 'A wane matsayi aka fi sanin Al-Khwarizmi?',
    "그는 페르시아의 수학자로, 인도에서 도입된 아라비아 숫자를 이용하여 사칙연산을 만들고 0과 위치값을 사용했으며, '대수학의 아버지'로 불립니다.": "Shi masanin lissafi ne na farisa wanda ya kirkiro ka'idojin lissafi na asali (sawa, ragi, rabawa, da rarrabawa) ta amfani da lambobin Larabawa daga Indiya, ya yi amfani da lamba 0 da ka'idar sanya lambobi, kuma ana kiransa 'Uban Aljebra'.",
    "'알고리즘'과 '앨지브라'라는 용어는 어떻게 유래했나요?": "Ta yaya kalmomin 'algorithm' da 'algebra' suka samo asali?",
    "'알고리즘'은 그의 이름에서 유래했고, '앨지브라'는 그의 저서 <al-jabr wa al-muqabala>에서 기원합니다.": "Kalmar 'algorithm' ta samo asali ne daga sunansa, sannan 'algebra' ta samo asali daga littafinsa <al-jabr wa al-muqabala>.",
    '알콰리즈미의 주요 저서는 무엇이며, 어떤 내용을 담고 있나요?': 'Wadanne ne manyan littattafan Al-Khwarizmi, kuma mene ne ke cikinsu?',
    "그의 대표 저서로는 일차 및 이차방정식 해법을 다룬 '복원과 대비의 계산'과 인도-아라비아 숫자를 서양에 전파한 '인도 수학에 의한 계산법', 그리고 프톨레마이오스 지리학을 수정한 '지구의 표면' 등이 있습니다.": "A cikin manyan littattafansa akwai 'Lissafi ta Hanyar Kammalawa da Daidaitawa', wanda ya gabatar da hanyoyin warware matsalolin daidaito na digiri na daya da na biyu, 'Lissafi da Lambobin Indiya' wanda ya yada lambobin Indiya-Larabawa a yamma, da kuma 'Siffar Duniya' wanda ya yi gyara ga ilimin kasa na Ptolemy.",

    '1891년': 'Shekara ta 1891',
    '4월 14일 영국령 인도 모우의 달리트(불가촉천민) 가문에서 출생.': "An haife shi a ranar 14 ga Afrilu, a dangin Dalit ('wadanda ba a tabawa') a Mhow, a lokacin da Indiya take karkashin mulkin Birtaniya.",
    '1923년': 'Shekara ta 1923',
    '런던에서 변호사 자격을 취득하고 인도 내 사회적 차별에 맞서는 평생의 캠페인을 시작함.': "Ya cancanci zama lauya a London kuma ya fara kamfen na tsawon rayuwa na yaki da wariyar al'umma a Indiya.",
    '1947년': 'Shekara ta 1947',
    '독립 인도의 초대 법무부 장관으로 임명됨.': "An nada shi a matsayin Ministan Shari'a na farko a Indiya mai cin gashin kanta.",
    '1949년': 'Shekara ta 1949',
    '불가촉천민 제도를 공식적으로 폐지한 인도 헌법 초안 작성을 성공적으로 주도함.': "Ya sami nasarar jagorantar tsara kundin tsarin mulkin Indiya wanda a hukumance ya soke tsarin rashin taba al'ummar Dalit.",
    '1956년': 'Shekara ta 1956',
    '사망 직전 수십만 명의 추종자들과 함께 불교로 개종함.': 'Ana gab da mutuwarsa, ya shiga addinin Buddah tare da dubban daruruwan mabiyansa.',

    '기원전 340년경': 'Wajen Karni na 340 K.Z.',
    '고대 인도에서 태어났으나 정확한 기원은 역사적 논쟁의 대상으로 남아 있음.': 'An haife shi a tsohuwar Indiya, amma ainihin asalin inda ya fito ya kasance batun muhawara a tarihi.',
    '기원전 321년경': 'Wajen Karni na 321 K.Z.',
    '스승 차나키야의 도움을 받아 난다 왕조를 무너뜨리고 마우리아 제국을 세움.': 'Tare da taimakon malaminsa Chanakya, ya hambarar da daular Nanda ya kuma kafa daular Maurya.',
    '기원전 305년경': 'Wajen Karni na 305 K.Z.',
    '알렉산드로스 대왕의 장군이었던 셀레우코스 1세 니카토르를 물리치고 서쪽으로 제국을 확장함.': 'Ya fadada daular zuwa yamma bayan da ya doke Seleucus I Nicator, daya daga cikin manyan janar-janar din Alexander the Great.',
    '기원전 297년경': 'Wajen Karni na 297 K.Z.',
    '아들 빈두사라에게 왕위를 물려주고 자이나교 고행자가 됨.': "Ya sauka daga kan karagar mulki domin dansa Bindusara kuma ya zama mai tsatsauran ra'ayin addinin Jainism.",
    '자이나교의 영적 수행에 따라 슈라바나벨라골라에서 단식(살레카나)으로 생을 마감함.': 'Ya kawo karshen rayuwarsa ta hanyar azumi (sallekhana) a Shravanabelagola kamar yadda addinin Jainism ya tanadar na samun ci gaban ruhi.',

    '1048년': 'Shekara ta 1048',
    '5월 18일 페르시아 니샤푸르(현 이란)에서 출생.': 'An haife shi a ranar 18 ga Mayu a Nishapur, na farisa (Iran ta yau).',
    '1070년': 'Shekara ta 1070',
    "영향력 있는 대수학 논문 '대수학 문제 증명에 관한 논고'를 저술함.": "Ya rubuta takarda mai tasiri game da lissafin Aljebra mai taken 'Rubuce-rubuce kan Nuna Tabbacin Matsalolin Aljebra'.",
    '1073년': 'Shekara ta 1073',
    '셀주크 술탄 말리크 샤 1세의 초청을 받아 이스파한에 천문대를 건설함.': 'Sarkin Seljuk Malik-Shah na Farko ya gayyato shi don kafa dakin lura da taurari a birnin Isfahan.',
    '1079년': 'Shekara ta 1079',
    '매우 정확한 태양력인 잘랄리 달력을 완성함.': 'Ya kammala Kalanda na Jalali, wanda kalanda ce mai cikakken inganci da ake bi da rana.',
    '1131년': 'Shekara ta 1131',
    '수학, 천문학, 시(루바이야트) 분야에 깊은 유산을 남기고 니샤푸르에서 사망함.': 'Ya rasu a Nishapur, inda ya bar babban tasiri a fannin lissafi, ilimin taurari, da rubutun wakoki (Rubaiyat).',

    '1137년': 'Shekara ta 1137',
    '현대 이라크인 티크리트의 저명한 쿠르드족 가문에서 출생.': 'An haife shi a wani sanannen gidan Kurdawa a Tikrit, dake kasar Iraqi a yau.',
    '1169년': 'Shekara ta 1169',
    '이집트 파티마 왕조의 와지르로 임명되어 정치적 권력을 공고히 함.': 'An nada shi wazir na daular Fatimid a Masar kuma ya karfafa ikonsa a siyasance.',
    '1174년': 'Shekara ta 1174',
    '아이유브 왕조를 세우고 이집트와 시리아에 걸쳐 영토 지배력을 확장하기 시작함.': 'Ya kafa Daular Ayyubid sannan ya fara faɗaɗa ikonsa a filayen Masar da Siriya.',
    '1187년': 'Shekara ta 1187',
    '하틴 전투에서 십자군을 결정적으로 격파하고 예루살렘을 탈환함.': 'Ya yi nasarar fatattakar mayakan Kurisiyya (Crusaders) a Yaƙin Hattin kuma ya kwato birnin Kudus.',
    '1193년': 'Shekara ta 1193',
    "다마스쿠스에서 열병으로 사망하였으며, 임종 전 자신의 개인 재산을 백성들에게 나누어 줌.": "Ya rasu sakamakon zazzabi a birnin Damascus, inda ya raba dukkan dukiyarsa ga jama'arsa kafin rasuwarsa.",

    '1887년': 'Shekara ta 1887',
    '12월 22일 영국령 인도 마드라스 관구의 에로드에서 출생.': 'An haife shi a ranar 22 ga Disamba a Erode dake lardin Madras, Indiya karkashin mulkin Birtaniya.',
    '1903년': 'Shekara ta 1903',
    'G. S. 카의 수학 요약집을 입수하여 심오한 수학적 천재성에 눈을 뜸.': 'Ya samo wani littafin takaitaccen lissafin ilimi na G. S. Carr, wanda ya zaburar da tsananin basirarsa ta fannin lissafi.',
    '1913년': 'Shekara ta 1913',
    '영국의 저명한 수학자 G. H. 하디와 역사적인 서신 교환을 시작함.': 'Ya fara aika wasiku na tarihi da G. H. Hardy, wani shahararren masanin lissafi na Birtaniya.',
    '1918년': 'Shekara ta 1918',
    '왕립학회 회원으로 선출되어 최연소 회원 중 한 명이 됨.': 'An zabe shi a matsayin memba na Royal Society, inda ya zama daya daga cikin mafi karancin shekaru a cikinsu.',
    '1920년': 'Shekara ta 1920',
    '수천 개의 증명되지 않은 정리를 남기고 32세의 젊은 나이로 인도에서 사망함.': "Ya rasu a Indiya yana da karancin shekaru 32, ya bar dubban ra'ayoyi da ba a tabbatar da su ba na fannin lissafi.",

    '1494년': 'Shekara ta 1494',
    '11월 6일 오스만 제국의 트라브존에서 출생.': 'An haife shi a ranar 6 ga Nuwamba a Trabzon dake cikin Daular Usmaniyya.',
    '1520년': 'Shekara ta 1520',
    '제국의 제10대 술탄으로 오스만 왕위에 오름.': 'Ya hau kan karagar mulkin Daular Usmaniyya a matsayin Sultan na 10 na daular.',
    '1526년': 'Shekara ta 1526',
    '중요한 모하치 전투에서 헝가리 왕국을 물리침.': 'Ya kayar da Masarautar Hungary a gagarumin Yaƙin Mohács.',
    '1529년': 'Shekara ta 1529',
    '오스만 제국의 제1차 빈 포위전을 이끌며 유럽 진출의 정점을 찍음.': 'Ya jagoranci kewaye Vienna a karon farko da Daular Usmaniyya ta yi, inda ya kai gagarumar kololuwa ta fadada daular a Turai.',
    '1566년': 'Shekara ta 1566',
    '시게트바르 포위전 도중 사망하여 오스만 역사상 가장 긴 통치를 마감함.': 'Ya rasu yayin kewaye Szigetvár, inda ya kawo karshen mulkin da yafi kowane tsawo a tarihin Daular Usmaniyya.',

    '1863년': 'Shekara ta 1863',
    '1월 12일 영국령 인도 캘커타에서 나렌드라나트 다타로 출생.': 'An haife shi a matsayin Narendranath Datta a ranar 12 ga Janairu a Calcutta dake Indiya karkashin Birtaniya.',
    '1881년': 'Shekara ta 1881',
    '자신의 구루인 스리 라마크리슈나를 만나 영적인 길에 깊은 변화를 겪음.': 'Ya haɗu da malaminsa Sri Ramakrishna, inda ya fuskanci babban sauyi a rayuwarsa ta ruhaniya.',
    '1893년': 'Shekara ta 1893',
    '시카고에서 열린 세계 종교 의회에서 유명한 연설을 하며 서양에 힌두교를 소개함.': 'Ya gabatar da shahararren jawabi a Majalisar Addinai ta Duniya a birnin Chicago, inda ya gabatar da addinin Hindu ga Yamma.',
    '1897년': 'Shekara ta 1897',
    '광범위한 사회 및 영적 봉사를 제공하기 위해 라마크리슈나 미션을 설립함.': 'Ya kafa Ofishin Ramakrishna Mission don bayar da taimakon zamantakewa da na ruhaniya mai fadi.',
    '1902년': 'Shekara ta 1902',
    '7월 4일 벨루르 마트에서 명상하던 중 세상을 떠남.': 'Ya rasu a ranar 4 ga Yuli yayin da yake yin zuzzurfan tunani a Belur Math.',
    '크메르 제국의 왕족 가문에서 태어났음.': 'An haife shi a gidan sarautar daular Khmer.',
    '크메르 제국의 왕족 가문에서 태어남.': 'An haife shi a gidan sarautar daular Khmer.',
}

for giant, info in data.items():
    if 'timeline' in info:
        for item in info['timeline']:
            if item['year'] in translations:
                item['year'] = translations[item['year']]
            else:
                print(f"Missing year trans: {item['year']}")
            if item['event'] in translations:
                item['event'] = translations[item['event']]
            else:
                print(f"Missing event trans: {item['event']}")
    if 'keyAchievements' in info:
        for item in info['keyAchievements']:
            if item['title'] in translations:
                item['title'] = translations[item['title']]
            else:
                print(f"Missing ach title trans: {item['title']}")
            if item['description'] in translations:
                item['description'] = translations[item['description']]
            else:
                print(f"Missing ach desc trans: {item['description']}")
    if 'faq' in info:
        for item in info['faq']:
            if item['question'] in translations:
                item['question'] = translations[item['question']]
            else:
                print(f"Missing faq q trans: {item['question']}")
            if item['answer'] in translations:
                item['answer'] = translations[item['answer']]
            else:
                print(f"Missing faq a trans: {item['answer']}")

with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print('Translation completed successfully.')
